### ISSUE TITLE
Server Query

### ISSUE THREAD

**Issue by IchSagDanke** [TeaSpeak/TeaSpeak#1]
When logging into the server query, it states: "The connection was lost or disconnected from the server."

**Comment by WolverinDEV** [comment]
What does the server log says?
I guess it would not disconnect you without any reason :)

**Comment by WolverinDEV** [comment]
Clicked the wrong button :(

**Comment by IchSagDanke** [comment]
ok ich glaube deutsch ist einfacher :D 
ich verbinde mich mit dem Port 30303 wie im log Geschrieben und dann steht dort einfach nur die Die Verbindung ging verloren oder wurde vom Server getrennt

Mehr steht da auch Nicht :(

**Comment by WolverinDEV** [comment]
... bitte lese...
30303 ist der ***FileServer*** Port.
10101 Ist der query port :)

**Comment by IchSagDanke** [comment]
Danke

**Comment by MrDj200** [comment]
Hey,
wie kann ich denn den Port ändern?

**Comment by WolverinDEV** [comment]
Dies kannst du in der config tun :)

**Comment by MrDj200** [comment]
Hmm, ich denke mal in der config.yml?
Aber da finde ich nur die Ports für Query und File hosting.
Was müsste ich denn dann da reinschreiben?

**Comment by WolverinDEV** [comment]
Du musst in YatQA schon den richtigen port angeben :=)
Ansich sollte alles gehn

**Comment by MrDj200** [comment]
Hab das so eingegeben:
![Image](https://puu.sh/yZ9IX/1e31495640.png)
Hier die config.yml:
query:
    #The default host for the query server
    host: 176.57.142.145
    #The default port for the query server
    port: 10101

Hab in YatQa auch schon direkte IP versucht

**Comment by WolverinDEV** [comment]
schonmal versucht auf 0.0.0.0 zu binden? Ansich sollte dies gehen.
Ansonnsten hast du schonmal deine Firewall getestet?

**Comment by MrDj200** [comment]
funktioniert auch nicht.
Da ich da noch nie was umstellen musste mit Firewall, denke ich nicht, dass es daran liegt.
Und ich weiß auch nicht wie ich das über SSH machen würde..

**Comment by WolverinDEV** [comment]
Hmm das erscheint mir irgendwie komisch.
Ich weiß das der Query eigendlich gehen sollte, und YatQA connecten sollte

**Comment by MrDj200** [comment]
also über putty komme ich auch rein, aber yatqa will nicht

**Comment by WolverinDEV** [comment]
Hmm okey?
Dann schreibe mal am besten den support von YatQA an :)

**Comment by Bluscream** [comment]
@MrDj200 starte mal yatqa mit `-debug` und guck nach dem log

**Comment by Bluscream** [comment]
Und stell sicher das du auf 1.0.16 beta bist

**Comment by MrDj200** [comment]
Also Teaspeak grade frisch runtergeladen: Check
YatQa ist ne neue Version: Check
Komme mit YatQa auf meinen normalen TS3 server drauf: Check
Frage: Ich hab noch den normalen TS3 Server auf dem gleichen Server wie Teaspeak, und will nur über den Serverquery den Serverport ändern, kann es am normalen TS3 server liegen?

P.S.: log von Yatqa kommt gleich

**Comment by MrDj200** [comment]
hmm, das ist komisch.
Hier der log:

`TeaSpeak
Welcome on the TeaSpeak ServerQuery interface.
login client_login_name=serveradmin client_login_password=nope

error id=0 msg=ok
quit

`

**Comment by Bluscream** [comment]
Was kommt den fürn fehler bei yatqa?

**Comment by MrDj200** [comment]
Hier im bild zu sehen: https://puu.sh/yZ9IX/1e31495640.png

**Comment by Bluscream** [comment]
Denke mak yatqa wartet auf teamspeaks standard motd und nicht "welcome on the teaspeak serverquery interface"

**Comment by WolverinDEV** [comment]
Du kannst mal versuchen den MOTD zu ändern :)

**Comment by MrDj200** [comment]
Ich bekomms nicht hin die MOTD zu ändern.
Hier sieht man, dass ich das in der config.yml geändert habe, es aber nicht übernommen wurde:
https://puu.sh/yZdKb/1774e1a43d.png

**Comment by Bluscream** [comment]
Entfern mal das !<!> überall

**Comment by WolverinDEV** [comment]
Du hast auch \r\n vergessen :)

**Comment by Bluscream** [comment]
Und TS3

**Comment by Bluscream** [comment]
Ne aber schau dir mal im yatqa log das an und vergleich mit dem yatqa log auf nem normalen ts

**Comment by MrDj200** [comment]
Hab ich schon. sieht exakt gleich aus

**Comment by Bluscream** [comment]
Hmm

**Comment by Bluscream** [comment]
Ich guck morgen früh/mittag gern mal per teamviewer oder so drauf

**Comment by MrDj200** [comment]
Ich setze den mal eben ganz frisch auf

**Comment by MrDj200** [comment]
Alles klar, ich bekomme es nicht hin.
Würde mich freuen, wenn du mir da helfen würdest.
Adde mich einfach auf [Steam](http://steamcommunity.com/id/MrDj200/), da bin ich immer on ^^.

**Comment by WolverinDEV** [comment]
Kannst auch gerne einfach TS kommen?

**Comment by MrDj200** [comment]
Geht natürlich auch. Wie ist denn die IP?

**Comment by Bluscream** [comment]
Teaspeak.de

**Comment by WolverinDEV** [comment]
jo :)

**Comment by MrDj200** [comment]
Danke für die TS Hilfe!

**Comment by Bluscream** [comment]
Was wars?

**Comment by MrDj200** [comment]
brauchte die beta build von YaTQA
