### ISSUE TITLE
Setting more messages in the config

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#10]
I'd like to see more settings to change some predefined messages like

- [x] `￼ <16:02:03> "Bluscream" disconnected (Application stopped)`
- [x] Default client description
- [x] Default channel topic

**Comment by WolverinDEV** [comment]
I already had this point on my todo list ;)

**Comment by WolverinDEV** [comment]
Implemented in TeaSpeak 1.0.11-Beta

**Comment by Bluscream** [comment]
I have more for you:

- [ ] `Invalid hardware id! Maybe spoofed?`
- [ ] `Invalid badges`
- [ ] `Invalid command. Protocol hacked?`
