### ISSUE TITLE
channelcreation

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#100]
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.17-beta-1

## Issue
***Reason for reporting this issue***:
crash : Disconnected from server (invalid channelID)

***Detailed Description***:
If you create a high channel ID it's working the first time , 
If you create another high channelID crash : Disconnected from server (invalid channelID)
can't reconnect server , need to delete the channel from yatqa or so to be able to reconnect again . 

I noticed the second created channel take the same ID of the first channel ID created . 
Maybe related to high channelID or high order ID ? also ? 

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
... Well same issue again.
A long time ago i used uint16_t (a 16 bit number). So the max channel id was 65565
Now im using uint64_t (a 64 bit number
