### ISSUE TITLE
Server Admin query issue

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#101]
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.17-beta3

## Issue
***Reason for reporting this issue***:

/*
Since the fix of channel creation ( working now ) can't create a channel without a password
*/
Read comment.

***Detailed Description***:
/*
When you create a channel you have a message you are forced to enter a password , and i can't make a channel without enter a password , same after the channel creation can't remove the password ?
*/
Read comment.

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by lemignon** [comment]
i have group Server Admin Query .

**Comment by lemignon** [comment]
it seems my server Query is useless i don't have any right anymore , so the problem seems to be a server group issue at all. 

Any explain ? also it's asking me a token now on enter server but i have already used it . the upgrade fucked something in database ? 

Should i resinstall everything ? 

Cordialy,

**Comment by Bluscream** [comment]
Try to remove `b_channel_create_modify_with_force_password` if you have it somewhere assigned to yourself.

**Comment by lemignon** [comment]
hum , another friend have problem also it's related to server admin query , it's no working at all ( no rights ) if you have this server group on teaspeak .

**Comment by lemignon** [comment]
also it's asking for a token on enter server ... and  we just updated our server nothing else

**Comment by Bluscream** [comment]
Can you give me the IP of the server?

**Comment by Bluscream** [comment]
One second have to finish something :)

**Comment by lemignon** [comment]
it's related to Server Admin Query since last update the Server Admin Query have no effect on teamspeak ( no right at all )

**Comment by lemignon** [comment]
but it seems few right are working with Server Admin Query like the right to create permanent channel ( need enter a password like without any group ) but can create permanent channel , by default only temp channel are allowed.

**Comment by WolverinDEV** [comment]
Hmm sounds like the query group messed up.
Well I have a few questions:
Do you have the b_channel_create_modify_with_force_password set?
Do you set the b_group_is_permanent on server admin query?
Does all work with the server admin group?

Well I may just fucked up the channel create system :)
(that's the only stuff I changed within the last update)

**Comment by lemignon** [comment]
channelcreate channel_name=?\sDiscussion\s2 channel_description=Discussion channel_topic=Discussion channel_order=15986 channel_codec=4 channel_codec_quality=10 channel_flag_permanent=1


but not working

**Comment by lemignon** [comment]
b_channel_create_modify_with_force_password is not enable on server admin query  group
b_group_is_permanent = yes enable on server admin query

**Comment by WolverinDEV** [comment]
fixed in the 4th build
