### ISSUE TITLE
#Problem GroupServer AdminQuery Big-Bug

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#102]
## System Information
***Operating System***: Debian 9
***Operating System Type*** (x86|x64): 64x
***TeaSpeak Version***: 1.1.17-Beta-3

## Issue
***Reason for reporting this issue***:
Problem GroupServer AdminQuery

***Detailed Description***:
hello new problem packet no sending requested + problem Permission_GroupeServer

[23:25:28] [ERROR]   3 | Command handling of command servergrouppermlist sgid='3' return_code='1:3s' needs 24ms
[23:25:28] [ERROR]   3 | Packet handing of Command needs more than 10ms. (24)

EDIT : and no view Groupe AdminQuery in the list on TeamSpeak  [ Servers Groups ] + bug permissions view 

EDIT : [00:20:15] [ERROR] Query invalid read. Code: 0 errno: 0 msg: Success

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by Home-Network** [comment]
all permissions on the groups AdminQuery do not work on this version on version 1.1.16 it worked but they did not have all the permissions please.

if you can please fix this bug before tomorrow if possible because I have a TelnetBotPhp bot and I test often on your moded version and I see what's wrong with my bot, so I can easily share the most important bug

**Comment by WolverinDEV** [comment]
Fixed in the 4th build
