### ISSUE TITLE
channelcreate

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#103]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64):
***TeaSpeak Version***:

## Issue
***Reason for reporting this issue***:

I am experimenting issue with my channelcreate fonction with Query :

command = "channelcreate channel_name=" + encodeTS3String(name) + " channel_description=" + encodeTS3String(description)+ " channel_topic=" + encodeTS3String(topic) + " channel_order=" + encodeTS3String(order)+" channel_codec=" + codec+ " channel_codec_quality=" + codecquality + " channel_flag_permanent=" + permanent;

***Detailed Description***:

Any idea how channelcreate works with query ? 

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by Bluscream** [comment]
@lemignon https://github.com/TeamspeakDocs/Server/blob/master/serverquerydocs/channelcreate.txt

Do you have any problems with it?

**Comment by lemignon** [comment]
i only switched my bot from teamspeak to teaspeak . it was working great on teamspeak with the query lline command i sent in ticket , but with teaspeak nothing create ?

**Comment by Bluscream** [comment]
Can you let your bot print the full command it would send and post that here?

**Comment by lemignon** [comment]
yes : 


channelcreate channel_name=?\sDiscussion\s2 channel_description=Discussion channel_topic=Discussion channel_order=15986 channel_codec=4 channel_codec_quality=10 channel_flag_permanent=1

but not working

work fine on teamspeak

**Comment by WolverinDEV** [comment]
Whats the error?

**Comment by Bluscream** [comment]
I can think of two culprits. Either the order or your non-ascii char in the name. Bet yeah whats the error?

**Comment by WolverinDEV** [comment]
Hmm just try to remove one of the properties and see if the error still occurs.
May you get the property which results this error

**Comment by lemignon** [comment]
i removed the first char of channel name ( wich is working in ts3 ) and result is : 

channelcreate channel_name=Discussion\s2 channel_description=Discussion channel_
topic=Discussion channel_order=15986 channel_codec=4 channel_codec_quality=10 ch
annel_flag_permanent=1
error id=2 msg=not\simplemented

**Comment by Bluscream** [comment]
why would it say not\simplemented :thinking:

**Comment by lemignon** [comment]
i removed \s2 : 

channelcreate channel_name=Discussion2 channel_description=Discussion channel_to
pic=Discussion channel_order=15986 channel_codec=4 channel_codec_quality=10 chan
nel_flag_permanent=1
error id=1540 msg=convert\serror extra_msg=Invalid\sargument so lemme me do more test to know what argument is the problem

**Comment by lemignon** [comment]
i can't figure what's wrong , maybe you can try urself ?

**Comment by WolverinDEV** [comment]
Found the problem :D
You forget to set the parent channel parm (`pcid`)
I fixed it (its not required anymore)
