### ISSUE TITLE
repro.teaspeak.de/server/ etc. no longer accessible

### ISSUE THREAD

**Issue by essemX** [TeaSpeak/TeaSpeak#105]
## Issue
https://repro.teaspeak.de/server/linux/x64/ results since today in a 404, same for /latest and /buildIndex.txt which breaks the update-script.
https://repro.teaspeak.de/ results in "Nothink here!".

Tried it a few times today to make sure its not just temporary.

Also it seems like the tls cert got mixed up with web.teaspeak.de (browsers will mark it as insecure)

**Comment by WolverinDEV** [comment]
I just fixed My English fail xD
It's now repo.teaspeak.de

I already changed it everywhere
