### ISSUE TITLE
Option for serveradmins to allow chatting with yourself

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#106]
teaspeak returns `error id=512 msg=invalid\sclientID extra_msg=you\scant\schat\swith\syourself!` when you try to message yourself which makes sense in some cases but people actually use the own chat for notes and stuff which is a pretty neat usecase. Also some plugins use that chat instead of printing to a chattab because teamspeak saves the chat content which some plugins use to provide something like a "log"

I don't request to remove this "security feature" but instead to add an option to the config to allow it.

**Comment by WolverinDEV** [comment]
Implemented.
Permission: `b_client_even_textmessage_send`
