### ISSUE TITLE
Implement ts3init_linux_netfilter_module

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#108]
Teamspeak has published https://github.com/TeamSpeak-Systems/ts3init_linux_netfilter_module
I have a few questions about that;
- Is this compatible with TeaSpeak?
- If yes, does it even add some extra security or is TeaSpeak's handshake already as secure as Teamspeak with the netfilter?
- Does it make sense to include this into TeaSpeak and if not does it make sense to create a fork that works with TeaSpeak?

**Comment by WolverinDEV** [comment]
Yes it should work, and is a good layer before TeaSpeak.
I've never tested it, but the way how it acts should be compatible with Teaspeak
