### ISSUE TITLE
Global Bans

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#11]
A new parameter for `banadd` / `banclient` called `sid` to specify either the serverid or `0` for a ban that issues to all virtual servers if the client/query has `b_client_ban_create_global` and shows on each server's `banlist` and can only be deleted with `b_client_ban_delete_global`
  
Examples:

- `banclient clid=1 bantime=0 reasonmsg=fag` (Client only needs `b_client_ban_create` because he's on it's handled like a normal server ban)
- `banclient clid=1 sid=2 bantime=0 reasonmsg=fag` (Client only needs `b_client_ban_create` because he's on sid=2)
- `banclient clid=1 sid=2 bantime=0 reasonmsg=fag` (Client needs `b_client_ban_create_global` because he's on sid=1)
- `banclient clid=1 sid=0 bantime=0 reasonmsg=fag` (Client needs `b_client_ban_create_global` because it's a global ban)
- `bandel banid=1` (Client needs `b_client_ban_delete_global` because the ban's sid=0)
- `bandel banid=2` (Client only needs `b_client_ban_delete` because the ban's sid is the same as the current server's)

**Comment by WolverinDEV** [comment]
Implemented in 1.0.11-Beta
+ New permission `b_client_ban_create_global`
+ New permission `b_client_ban_list_global`
+ New permission `b_client_ban_delete_own_global`
+ New permission `b_client_ban_delete_global`
+ Optional parameter at `banadd` `sid` = [0 = Global | <sid>]
+ Optional parameter at `banlist` `sid` = [0 = Global | <sid>]
+ Added variable `sid` on `banlist` result
+ Optional parameter at `bandel` `sid` = [0 = Global | <sid>]

**Comment by Bluscream** [comment]
Awesome !

**Comment by Bluscream** [comment]
Do you think the own_global perm makes a lot of sense?

**Comment by WolverinDEV** [comment]
Well not realy, but teamspeak already have this permission for "local" bans so why not add these in global as well :)

**Comment by Bluscream** [comment]
well, as long as it works as intended it should be fine. Gonna add it to the changes.md and the r4p3 post when im back home

**Comment by WolverinDEV** [comment]
jo thanks :) I think every perm and the sid parm is self explainable right?

**Comment by Bluscream** [comment]
Yeah, gonna explain them in the changes.md tho

**Comment by Bluscream** [comment]
@WolverinDEV since you used a completely different implementation, please explain it a little bit further here? Does the global banlist have other commands(`globalbanlist`/`banlistglobal`)/etc?

**Comment by WolverinDEV** [comment]
No they don't have own specific commands.
The old commands `banlist` `banadd` `bandel` have a new option. The `sid` (short for `serverId`) option.
If you set this to zero `sid=0` than you're managing/accessing the global ban list :)

**Comment by Bluscream** [comment]
So
- `banlist` gets the normal banlist
- `banlist sid=0` gets the global banlist
?

**Comment by WolverinDEV** [comment]
Yup :)
