### ISSUE TITLE
Kick common clients on banclient

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#111]
It would be neat if users with an IP that was banned just now could also get a notifyclientbanned so they can't stay. This is already a thing on Teamspeak servers but only with UIDs so if a user is online two times with the same uid if he gets a banclient which includes his uid he gets kicked out telling him he's banned
concept:
1. client was banned with `banclient` so two banrules are created (uid and ip [and hwid])
2. server iterates over all online clients and checks their uid and ip [and maybe hwid]
3. server kicks (that kick that you get when you're banned but without actually adding an additional ban) those that are affected by the ban

**Comment by WolverinDEV** [comment]
Implemented :)

**Comment by WolverinDEV** [comment]
Check out 1.1.19-beta-1
There's the hwid implemented too :)
