### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#112]
- [x] Channels created by guests are always permanent even if they don't have the permissions to create those
- [x] When the server deletes a channel it uses `TeaSpeak-Server` as the invokername instead of the virtualserver_name (This actually happens a couple of times i just dont remember where else)
- [x] The Server doesnt kick clients that are affected when a new banrule is added via `banadd`
- [x] When a client gets banned for antiflood it shows that the client banned himself
- [x] `channeledit cid=2128 channel_flag_permanent=0` results in `<05:13:20> Disconnected from server (invalid channel flags)`

**Comment by WolverinDEV** [comment]
Hey,
i cant recreate your last issue (`channeledit cid=2128 channel_flag_permanent=0`)
Everything works fine for me (may caused that i already fixed all issues above)

Please retest it when i uploaded the fix

**Comment by WolverinDEV** [comment]
Note: `banadd` on global also checks every server for the entry effect.

**Comment by Bluscream** [comment]
It only happened once so i'll reopen this if it happens again

**Comment by Bluscream** [comment]
- [ ] `virtualserver_min_clients_in_channel_before_forced_silence` stays at `5` even after editing. IMO 5 is too low as default value!

**Comment by WolverinDEV** [comment]
Fixed all issues in 1.1.20-beta
