### ISSUE TITLE
clan: ServerQuery Error 1538 @ addEventNotify(): invalid parameter - invalid group/specifier

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#114]
## System Information
***Operating System***: Debian 
***Operating System Type*** (x86|x64):  x64
***TeaSpeak Version***: 1.1.19-beta5

## Issue
***Reason for reporting this issue***:
Query bots don't works anymore after update from 1.1.18

***Detailed Description***:
clan: ServerQuery Error 1538 @ addEventNotify(): invalid parameter - invalid group/specifier

or phpframework : 

PHP Fatal error:  Uncaught exception 'TeamSpeak3_Adapter_ServerQuery_Exception' with message 'invalid parameter (invalid group/specifier)' in /xxx/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php:319
Stack trace:
#0 /xxx/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php(91): TeamSpeak3_Adapter_ServerQuery_Reply->fetchError(Object(TeamSpeak3_Helper_String))
#1 /xxx/libraries/TeamSpeak3/Adapter/ServerQuery.php(141): TeamSpeak3_Adapter_ServerQuery_Reply->__construct(Array, 'servernotifyreg...', Object(TeamSpeak3_Node_Host), true)
#2 /xxx/libraries/TeamSpeak3/Node/Abstract.php(73): TeamSpeak3_Adapter_ServerQuery->request('servernotifyreg...', true)

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by Bluscream** [comment]
servernotifyregister was changed from teamspeak to teaspeak, please look at

**Comment by WolverinDEV** [comment]
Hmm if you're using the TeamSpeak servernotifyrrgister right it should work too

**Comment by lemignon** [comment]
i don't see any change ? the changes seems to be related to the musicbot only ?

**Comment by lemignon** [comment]
of course , and it was working before ....

**Comment by lemignon** [comment]
Well it's pretty useless . Need again to rewrite some things  due of the lost of compatibility with teamspeak bots 100%.

I don't see any point of your idea since this should be handle like teamspeak. like it was before and we ( users will do conditions ( if ) ) to handle this . It's only complexify your query system + lost compatibility a little more for nothing at my point of view . )

**Comment by WolverinDEV** [comment]
Please give me the exact command you use

**Comment by lemignon** [comment]
all i know is that the ts3 php framework ... , java bots don't works anymore since 1.1.19 ... you should add a default value of subscribe all to not lost compatibility ...

**Comment by lemignon** [comment]
* Activate a Teamspeak event notify.<br>
	 * <br>
	 * <b>Notice:</b><br>
	 * You have to use setTeamspeakActionListener() first!
	 * 
	 * @param eventMode
	 *            Use an EVENT_MODE constant
	 * @param channelID
	 *            A channel ID, only needed for EVENT_MODE_CHANNEL. Use any
	 *            number for any other EVENT_MODE.
	 * @return <code>true</code> if the event notify could be activated
	 *         successfully, <code>false</code> if not (check error with
	 *         getLastError()).
	 * @since 0.7
	 * @see JTS3ServerQuery#EVENT_MODE_CHANNEL
	 * @see JTS3ServerQuery#EVENT_MODE_SERVER
	 * @see JTS3ServerQuery#EVENT_MODE_TEXTCHANNEL
	 * @see JTS3ServerQuery#EVENT_MODE_TEXTPRIVATE
	 * @see JTS3ServerQuery#EVENT_MODE_TEXTSERVER
	 * @see JTS3ServerQuery#getLastError()
	 */
	public boolean addEventNotify(int eventMode, int channelID) {

**Comment by lemignon** [comment]
for JTS3ServerMod java bot for example ...

**Comment by lemignon** [comment]
Well i think your new parameter should be optionnal then . and keep the default system of subscribe for everything and keep the parameters order ... ?

**Comment by lemignon** [comment]
your idea is not bad for the next guys who want make framework ... or new bot , but you should keep the compatibilty with actuals bots i think ^^

**Comment by WolverinDEV** [comment]
Fixed within build 6
