### ISSUE TITLE
ServerSnapshotDeploy: suggestion

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#115]
## System Information
***Operating System***: Linux
***Operating System Type*** (x86|x64): any
***TeaSpeak Version***: 1.1.19

## Issue
Now: After ServerSnapshotDeploy virtual server get new ID.  Also,  new directory "files/server_{new_id}"  is created, but old directory "files/server_{old_id}" remain at the same place.

Suggestions: Do not change a server ID, or rename  the old directory according to the new ID

**Comment by WolverinDEV** [comment]
fixed/implemented
