### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#117]
## System Information
***Operating System***: Debian 9
***Operating System Type*** (x86|x64):x64 
***TeaSpeak Version***: 1.1.20

## Issue
[dumps.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/1966815/dumps.tar.gz)

**Comment by lexesv** [comment]
> Are you adding and/or removing some virtual server very often?

No.

++ After 3 days, when connecting to the any virt.server gives an error: Action currently not possible due to spam protection. Please wait a few seconds and try again.

**Comment by WolverinDEV** [comment]
Hmm seems like the server instance hang up.

**Comment by lexesv** [comment]
crash dump
[dump.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/1987248/dump.tar.gz)

Also, users complain that the icons disappear after the server reboots.

![2018-05-09_12-46-48](https://user-images.githubusercontent.com/15149258/39808250-190d9444-5387-11e8-96eb-8aa5bd3d7e72.png)

**Comment by WolverinDEV** [comment]
Hey,
yes im testing for all icon, when the server restarts.
I also noticed that kind of bug. I'll look at this.

**Comment by WolverinDEV** [comment]
The crashes may fixed now :)
