### ISSUE TITLE
TS3Video compatibility

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#118]
## System Information
***Operating System***: Ubuntu 16.04.4 LTS (Xenial Xerus) 
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: TeaSpeak-1.1.21-beta-5

On normal Teamspeak Servers when rightclicking on a channel; "TS3Video" -> "Join now" or "Join via public server" the TS3Video client starts and connects to the session
On TeaSpeak Servers nothing happens after clicking either of the menuItems

TS3Video: https://mfreiholz.de/ts3video/

**Comment by WolverinDEV** [comment]
May look at the protocol which action failes

**Comment by Bluscream** [comment]
Fixed
