### ISSUE TITLE
Permissionsystem

### ISSUE THREAD

**Issue by NextPrex** [TeaSpeak/TeaSpeak#119]
## System Information
***Operating System***:Linux
***Operating System Type*** (x86|x64): Linux 1.1.24-beta-1 x64
***TeaSpeak Version***:

## Issue
***Reason for reporting this issue***:
There are some bugs at the permission system of teaspeak

***Detailed Description***:
There are some problems with the permission system. I cant show my rank (Admin) before my name. Not all permissions can be placed and the permission isn´t set.

**Comment by essemX** [comment]
can't conform this bug, works fine for me with showing the Rank. Can you please write in detail which permissions don't work? also show us error-messages if present.
![teaspeakworksfine](https://user-images.githubusercontent.com/12894598/39771073-403c8890-52f1-11e8-9613-3a409e227200.png)
