### ISSUE TITLE
Permissionsystem i_client_talk_power ...

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#120]
## System Information
***Operating System***: Linux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***:

## Issue
***Reason for reporting this issue***:
i_client_talk_power is not working properly and some others also related to the same bugs . 

***Detailed Description***:
When you set a client permission like : i_client_talk_power it should take the client permission on top of group permission , Client Permission > Server group permission . 

Also note that if you push a negative value it's not working at all . and if you put -1 in client permission i_client_talk_power it's like you have 999999999999 it put you on top of channel . 

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Hey,
i already saw that there's may something wrong with the client rights (they seem to disappear after a server restart).

To your second "bug". The reason is that -1 is something liken "infinity" and the highest level of permission you could grant.

**Comment by lemignon** [comment]
hum , ok . 

In teamspeak you can set high negative value and works like you said :. 
client channel permission -> client permission -> channel group permission -> server group permission

But let's imagine you want to make a group for mute people you can't if it's always take the top value of everything . 

in my teaspeak a new player joining the server have the talk power to talk in channel But if i want mute him how can i do ? 

I don't see any way then . the only way should be set more talk power needed in channel and then voice all people exept the one you want mute . it's a little crappy .

**Comment by lemignon** [comment]
if i make default group talk power 50 and all channels talk power needed to 50 . 

If i make a group with talk power 10 and give to one user , then he don't care and take the highest value at all ( 50 ) so he will always have talk power . 

There is some miss i guess .

**Comment by WolverinDEV** [comment]
client channel permission -> client permission -> channel group permission -> server group permission
Implemented within the next build
