### ISSUE TITLE
[BUG] : Client_TotalConnections

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#121]
## System Information
***Operating System***:  Linux
***Operating System Type*** (x86|x64):
***TeaSpeak Version***: 1.1.24-beta-1

## Issue
***Reason for reporting this issue***:
CLIENT_TOTALCONNECTIONS not valide value

***Detailed Description***:
<21:40:25> "[PHP]TelnetBotQuery_V6.5": [Noυvelle-Coɴɴeхιoɴ] =>[NιcĸNαмe: motards pro] [oѕ: Android]  [Pαyѕ: FR ] [ClιeɴтVerѕιoɴ: 3.1.8 [Build: 1516865456]]  [ToтαlCoɴɴecтιoɴ: 1]

<20:57:02> "[PHP]TelnetBotQuery_V6.4": [Noυvelle-Coɴɴeхιoɴ] =>[NιcĸNαмe: LeXium1] [oѕ: iOS]  [Pαyѕ: FR ] [ClιeɴтVerѕιoɴ: 3.1.8 [Build: 1516887927]]  [ToтαlCoɴɴecтιoɴ: 1]

<19:52:55> "[PHP]TelnetBotQuery_V6.4": [Noυvelle-Coɴɴeхιoɴ] =>[NιcĸNαмe: slayerkris] [oѕ: Windows]  [Pαyѕ: FR ] [ClιeɴтVerѕιoɴ: 3.1.9 [Build: 1525442084]]  [ToтαlCoɴɴecтιoɴ: 1]

<19:49:00> "[PHP]TelnetBotQuery_V6.4": [Noυvelle-Coɴɴeхιoɴ] =>[NιcĸNαмe: ♦ Kobunix ♦] [oѕ: Windows]  [Pαyѕ: FR ] [ClιeɴтVerѕιoɴ: 3.1.9 [Build: 1525442084]]  [ToтαlCoɴɴecтιoɴ: 1]

<21:38:52> "[PHP]TelnetBotQuery_V6.5": [Noυvelle-Coɴɴeхιoɴ] =>[NιcĸNαмe: Mιcĸα@Hoмe-Neтworĸ] [oѕ: BlooServ]  [Pαyѕ: FR ] [ClιeɴтVerѕιoɴ: PHP5 Hacked_By_BlooServ]  [ToтαlCoɴɴecтιoɴ: 1]

<16:14:00> "[PHP]TelnetBotQuery_V6.4": [Noυvelle-Coɴɴeхιoɴ] =>[NιcĸNαмe: luckyPGM] [oѕ: Windows]  [Pαyѕ: FR ] [ClιeɴтVerѕιoɴ: 3.1.9 [Build: 1525442084]]  [ToтαlCoɴɴecтιoɴ: 1]

the value TotalConnection and not correct you fix the bug TotalConnections client 

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Fixed within the next build (will be released this evening (im fixing some other bugs too))
