### ISSUE TITLE
Console spam and people randomly kicked out

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#123]
## System Information
***Operating System***: ArchLinux
***Operating System Type*** (x86|x64): x86_64
***TeaSpeak Version***: 1.1.25 beta 3 and some versions before too

## Issue
***Reason for reporting this issue***:
Bug

***Detailed Description***:

Console spam:

- "Found delay while ticking server"
- "Packet handing of Voice needs more than XXms"
- "Packet handing of Ping needs more than XXms"

I think **but I'm not sure** that this problem causes people be randomly kicked out for "no ping response" very frequently.

Logs here: [logs.log](https://github.com/TeaSpeak/TeaSpeak/files/1997796/logs.log)

**Comment by Bluscream** [comment]
Hey its #123 🎉

**Comment by WolverinDEV** [comment]
Hey,
does this bug still happen?

**Comment by xRedFox** [comment]
The kick problem seems solved.
I still have the console spam problem even without the server being overloaded but as you said, this is not a real problem.
