### ISSUE TITLE
Request Windows Build

### ISSUE THREAD

**Issue by d0narnbl1tz** [TeaSpeak/TeaSpeak#129]
Hallo mal wieder,

Teaspeak läuft derzeit bei mir auf einem günstigen Linux VPS, doch ich bin dabei auf einen Rootserver zu migrieren, auf diesem hab ich mir eine meiner Windows Server 2016 Lizenzen aktiviert und wäre froh wenn es einen windows build geben würde und ich mich nicht mit Hyper-V rumschlagen muss um ein kleines Linux zu Virtualisieren 😄

**Comment by WolverinDEV** [comment]
Wird definitiv dauern

**Comment by d0narnbl1tz** [comment]
Gib mir ne Verschwiegenheitserklärung und ich werd schauen ob ich ne Portierung hinbekomme ^^

**Comment by WolverinDEV** [comment]
Haha ansich hatte ich TeaSpeak sogar mal für Windows cross compiled (mingw) aber das hat einfach nur gebuggt

**Comment by d0narnbl1tz** [comment]
Naja ich würde es nativ probieren wollen ^^

**Comment by essemX** [comment]
offtopic frage: warum überhaupt einen Windows Server über Linux bevorzugen? Linux eignet sich wesendlich mehr für Server-anwendungen und läuft meistens noch effizienter. Ausserdem ist Linux kostenlos von haus aus.

**Comment by Bluscream** [comment]
Manche gameserver (bspw: CoD MW2) gibt es nur für windows

**Comment by d0narnbl1tz** [comment]
Weil z. B. Bei manchen games (hust Arma3) der windows Server weiter entwickelt ist und nunmal die meisten serverseitigen mods die als Bibliothek geliefert werden, nur für windoof gebaut werden ^^

Zum Thema Eignung, mein Server mit 8 Kernen und (leider nur) 8gb ram läuft auf der SSd mit Windows Server 2016 data enter, ist zwar umständlich zu installieren wenn du nur ipmi hast um eigene isos einzubinden, aber geht.
Jetzt hast du halt nen Server mit Windows, der läuft stabil, updatet sich selbstständig und hat ein geiles verwaltungsinterface, welches sobald du mehrere Server betreibst ALLE Server konfiguriert die du hast :)

**Comment by schoerg** [comment]
Dann ist doch eine Linux-VM auf der Kiste eh kein Problem.

**Comment by d0narnbl1tz** [comment]
ja das stimmt, doch wer will den leistung abzweigen für sowas ^^ vor allem dann müsste ich damit ich das (meiner ansicht nach gescheit) hab, eher auf esxi setzen...
ich bin mal am schauen ob ich windows server nicht vllt das linuxsubsystem beibringen kann

**Comment by d0narnbl1tz** [comment]
@schoerg windows subsystem wurde es jetzt, war irgendwie das beste, nachdem ich auf windows server 2019 umgestiegen bin 😄 
https://forum.teaspeak.de/index.php?threads/installation-on-windows-via-wsl.239/

**Comment by WolverinDEV** [comment]
Merged to https://github.com/TeaSpeak/TeaSpeak/issues/252
