### ISSUE TITLE
Allow dblist without ips

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#13]
It would be cool if i could allow clients to use `clientdblist` and `clientdbfind` with `b_virtualserver_client_dblist` but omit the IP's if the client/query doesn't have `b_client_remoteaddress_view` at the same time.
  
PS: Maybe send the `client_lastip=` empty instead of omitting to be more failsave with tools like YaTQA

- [X] Fix ServerQuery being able to `clientdblist` without permissions.
- [x] `b_client_remoteaddress_view` in clientdbfind

**Comment by WolverinDEV** [comment]
Fixed required permission and implemented the `b_client_remoteaddress_view` permission
