### ISSUE TITLE
More snapshot compatibilty

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#132]
Because TeaSpeak has a lot more permissions than TeamSpeak which results in a lot of errors.
Please add a `-legacy` switch to the `serversnapshotcreate` so the snapshot gets stripped from the snapshot.

**Comment by Bluscream** [comment]
Also remove Query and template groups from snapshots

**Comment by WolverinDEV** [comment]
Implemented within 1.1.31b (`version=<0|1>`)
