### ISSUE TITLE
Crash dumps

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#137]
## System Information
***Operating System***: Linux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.26-beta-5

## Issue
[dumps.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2034981/dumps.tar.gz)

**Comment by WolverinDEV** [comment]
Hmm okey seems that all crashes have the same source.
I will look at this, but it seems to be a littlebit more complicated

**Comment by WolverinDEV** [comment]
Could you please try out build 7?
