### ISSUE TITLE
Avatars do not appear after upload/set

### ISSUE THREAD

**Issue by WolverinDEV** [TeaSpeak/TeaSpeak#139]

**Comment by xRedFox** [comment]
Uhm, I don't have this problem (1.1.27 beta 6)
![lol](https://user-images.githubusercontent.com/19707386/40530362-c1a26b8e-5ff8-11e8-983c-f30810060b7a.PNG)

**Comment by WolverinDEV** [comment]
Hmm Okey?
A user reported it to me and I still not test it I planned to do that today. 
But thanks for your proof :)

**Comment by WolverinDEV** [comment]
I tested it locally and all worked well:
[](https://img.teaspeak.de/Peek 2018-05-25 19-17.gif)
