### ISSUE TITLE
[CRITICAL]=> MusicBot Could not get metadata tag

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#140]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.27-beta-6

## Issue
***Reason for reporting this issue***:

error while playing music with the bot

***Detailed Description***:

<23:03:12> "Im a music bot!": An error occurrent while trying to replay the next song! (Failed to initialize player. (Could not spawn new ffmpeg process.
  Message: Could not get metadata tag ()))

Link youtube music : https://www.youtube.com/watch?v=aQYn3YGLod0

**Comment by WolverinDEV** [comment]
Hey,
Could you please enable the trace log and give me the output of the music bot within the log?
There must be also the reason for this fail

**Comment by Home-Network** [comment]
ok no problem man i activate the log on my server and I give you that as soon as I can ok ...

**Comment by WolverinDEV** [comment]
Yes,
You have time. I can't work in Teaspeak this work week (I'm on class vacation)

**Comment by WolverinDEV** [comment]
For me everything works :)
(Tested with TeaSpeak-1.1.30b-3)
