### ISSUE TITLE
Add b_group_show_for_voice_clients

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#143]
So you can hide certain groups from the "Change Server Groups" dialog without using Query groups

**Comment by WolverinDEV** [comment]
No it's impossible.
If the groupa should not be visible there then I can't assign anyone to that group.

**Comment by Bluscream** [comment]
> If the groupa should not be visible there then I can't assign anyone to that group.

Sure, query groups are not visible and bots can still assign people to them (but query groups have dis-atvantages [for example to set an icon for a query group you have to first create a regular group for it then set the icon then copy it to a query group with query and then you have icons on a query group)

**Comment by WolverinDEV** [comment]
Yes,
but than these groups must be a query group as well (the visibility is determined by TeamSpeak's client!)

**Comment by Bluscream** [comment]
Damnit, okay thanks :)

**Comment by WolverinDEV** [comment]
Thats a general structure behaviour.
Query groups are server instance wide groups, which are equal on each server!

**Comment by Bluscream** [comment]
Will there be a way in the future to upload "global" icons via query?
