### ISSUE TITLE
"The identity of this server has changed" dialog

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#147]
Whenever i connect to a TeaSpeak server through my bookmarks i get
![grafik](https://user-images.githubusercontent.com/3318223/40587008-3703372a-61b9-11e8-98a4-3e55ed679474.png)
but i have no idea why because the serveruid (which i thought was the only thing to cause this dialog) was the same on every connect :confused: 
```
initserver virtualserver_unique_identifier=PgfyC8L6OZcu6AMXkaY3UcggZ18= ...
```
What feels strange to me is that in `%appdata%\TS3Client\settings.db/ProtobufItems`
![grafik](https://user-images.githubusercontent.com/3318223/40587103-7c26463e-61ba-11e8-84ae-6ecacc9ac11a.png)
![grafik](https://user-images.githubusercontent.com/3318223/40587070-0e7c6320-61ba-11e8-9a9e-2357eec4e088.png)

**Comment by WolverinDEV** [comment]
Never happens to me.
If I connect to a TeaSpeak via bookmark every think works (my test is ts.TEASPEAK.de)

**Comment by Bluscream** [comment]
Same thing with your teaspeak

```
initserver virtualserver_unique_identifier=SZ7Qowb5lYqbnG5wv0FR6InQkk0= virtualserver_name=Official\sTeaSpeak\sTest-Server virtualserver_welcomemessage=Welcome\son\sanother\sTeaSpeak\sserver.\s(Download\snow\sand\sa\slicence\sfee\sis\snot\syour\scup\sof\stea!\s[URL]www.teaspeak.de[\/URL]) virtualserver_platform=Linux virtualserver_version=TeaSpeak\s1.1.28-beta virtualserver_maxclients=120 virtualserver_created=0 virtualserver_codec_encryption_mode=0 virtualserver_hostmessage=Welcome virtualserver_hostmessage_mode=1 virtualserver_default_server_group=11 virtualserver_default_channel_group=14 virtualserver_default_channel_admin_group=12 virtualserver_hostbanner_url virtualserver_hostbanner_gfx_url virtualserver_hostbanner_gfx_interval=0 virtualserver_priority_speaker_dimm_modificator=-18 virtualserver_id=1 virtualserver_hostbutton_tooltip virtualserver_hostbutton_url virtualserver_hostbutton_gfx_url virtualserver_name_phonetic virtualserver_icon_id=3882675430 virtualserver_weblist_enabled=1 virtualserver_ask_for_privilegekey=0 virtualserver_hostbanner_mode=0 virtualserver_channel_temp_delete_delay_default=60 client_talk_power=0 client_needed_serverquery_view_power=0 lt=2 pv=6 acn=blu aclid=7
```
![grafik](https://user-images.githubusercontent.com/3318223/40587685-2dade5b8-61c2-11e8-9f98-063a9d80aac6.png)
![grafik](https://user-images.githubusercontent.com/3318223/40587689-3e03304e-61c2-11e8-90dd-0e7cc03875c9.png)

**Comment by WolverinDEV** [comment]
What's you client version?

**Comment by Bluscream** [comment]
`clientinit client_nickname=blu client_version=3.1.9\s[Build:\s1525442084] client_platform=Windows client_input_hardware=1 client_output_hardware=1 client_default_channel client_default_channel_password client_server_password client_meta_data client_version_sign=2SLjPTFXM9hQyNkeEGYIzs0fkBffyhsh5z+ZuaCcZdDfM8vgRM5lrAU6KNspFjLddcvw8cXw6gxRY73ZHsRVBg== client_key_offset=209531558492 client_nickname_phonetic client_default_token client_badges=Overwolf=0 hwid=1f0f10b8672abda01532fb607f280ff6,e51505ada1b056bd4d927fc30434dadc`

**Comment by Bluscream** [comment]
This is still happening to me

**Comment by WolverinDEV** [comment]
Should be fixed within the next build

**Comment by Bluscream** [comment]
What was the culprit? Just out of curiosity? :]
