### ISSUE TITLE
spam lock ban can be enforced by guests

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#148]
On Teamspeak if guests have permissions to create channels and create them fast (about 1 per second is enough) they can cause others to get antiflood-locked (because the other clients have to subscribe each channel manually) [it's an old "bug" that just hasn't been adressed by teamspeak "yet":tm:] https://www.youtube.com/watch?v=_hPCt-3auks

On teamspeak it's annoying enough because everyone has to wait for their spam points to reach 0 after the malicous clients have been banned but on TeaSpeak a "automatic" ban is created for all client's that are not protected by `b_client_ignore_antiflood`.
![grafik](https://user-images.githubusercontent.com/3318223/40588250-235c9b1a-61ca-11e8-9626-827ad12a0223.png)

Possible solutions:
- Send all clients a `notifychannelsubscribed` after a channel was created so they don't need to subscribe them theirselves
- Don't raise antiflood points on `channelsubscribe` (still raise them on `channelsubscribeall`)

**P.S. Also why is the same ban rule created 3 times?**
![grafik](https://user-images.githubusercontent.com/3318223/40588209-6329ab94-61c9-11e8-8ffb-19082282521a.png)

**Comment by WolverinDEV** [comment]
Well basically the flood points for create a channel are less than creating a channel, but i think if you're connect twice you could trigger that.
Ill change there something

**Comment by WolverinDEV** [comment]
Fixed within build 2 :)

**Comment by Bluscream** [comment]
Awesome, which solution did you choose?

**Comment by WolverinDEV** [comment]
Easy solution.
Im logging the channel create time stamp and if the channel's age under 5 seconds its free to subscribe

**Comment by Bluscream** [comment]
Can you check why the ban gets created 3 times tho?

**Comment by Bluscream** [comment]
Also expired tempbans seem to not get deleted from the database

**Comment by Bluscream** [comment]
Ahh okay, it could make the database very large tho. Let's see after some uptime

**Comment by essemX** [comment]
I don't think size is a real problem here because of the small footprint of one ban-entry. Anyway. You could implement a config option for this or a command to remove old bans if its really a problem.

**Comment by Bluscream** [comment]
You have to remember that a normal ban consists of two entries

**Comment by WolverinDEV** [comment]
ban option implemented
