### ISSUE TITLE
Apply virtualserver's guest group to Server Query Guests

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#149]
Expected behaviour:
1. Query connects to the instance and has "Server Query Guest" permissions
2. Query uses `use` command to join a server
3. Query has now "Server Query Guest" + "Guest" permissions

Actual behaviour:
1. Query connects to the instance and has "Server Query Guest" permissions
2. Query uses `use` command to join a server
3. Query has now "Server Query Guest" permissions

**Comment by WolverinDEV** [comment]
Sorry,
but i cant recreate this issue :)

**Comment by Bluscream** [comment]
I edited my text to make it more clear

**Comment by WolverinDEV** [comment]
Hmm?
It's new fow me that queries also get the normal groups :) 
And it even does not really make sense

**Comment by Bluscream** [comment]
![](https://i.imgur.com/M7HBMqm.png) Try it yourself and you will see

**Comment by WolverinDEV** [comment]
![http://img.mcgalaxy.de/Screenshot-12-56-15.png](http://img.mcgalaxy.de/Screenshot-12-56-15.png)
Sorry, but i cant confirm this

**Comment by Bluscream** [comment]
Of course you can't confirm this. It only applies to Guest Queries.

![](https://i.imgur.com/4KQuxQz.gif)

**Comment by WolverinDEV** [comment]
:relieved:

**Comment by WolverinDEV** [comment]
fixed/implemented within the next build
