### ISSUE TITLE
HWID validation

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#151]
Currently it's very easy to just use an empty hwid string it would be neat if there was atleast some validation like
```cpp
if (clientinit["hwid"].isEmptyOrWhiteSpace()) {
    returnPermBanResponse("HWID can't be empty");
}
``` 

but checking against existing patterns would be even more awesome:

- `Windows`: `^[a-z0-9]{32},[a-z0-9]{32}$` hwid=6466592562cbdbd99c421e6d9f87be63,c769c54ce6a61166e2b07cbf5411eed2
- `OS X`, `Linux`: `^[a-z0-9]{32}$` hwid=13f40e9066f264d267f49d2e0a40a7bb
- `Android`: `^[a-z0-9]{16}$` hwid=8f949c4de599aa3d
- `iOS`: `^[A-Z0-9]{8}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{12}$` hwid=0292BCDC-28B1-4B6B-A7E3-976852C3AE7B

For bypassing i would suggest a new permission, `b_client_allow_invalid_hwid`

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WolverinDEV** [comment]
Can you please provide any information how the hwid is build on linux, mac, android and ios?
I dont want to use that pattern if it does not fit to everyone

**Comment by Bluscream** [comment]
I added Android for now and am going to add more soon.

**Comment by Bluscream** [comment]
To temporary enforce a ban on empty hwids:
```
banadd sid=0 hwid= time=0 banreason=HWID\scan't\sbe\sempty!
```

**Comment by Bluscream** [comment]
Okay i added everything, can you recheck linux? thats the only one where i didn't have 2 people to verify

**Comment by WolverinDEV** [comment]
I'll look for Linux later

**Comment by WolverinDEV** [comment]
implemented
