### ISSUE TITLE
Client count is wrong

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#153]
![grafik](https://user-images.githubusercontent.com/3318223/40592432-e2d6f438-620e-11e8-9da4-804327e8ab9e.png)
![grafik](https://user-images.githubusercontent.com/3318223/40592435-ec11615a-620e-11e8-9886-fdd4bdeb4b18.png)

I think we should find a solution that everyone is okay with.

AFAIK TeamSpeak counts everything together but only counts queries as clients if there is more then 1

In my opinion queries should never count as clients but rather have their own property `virtualservers_total_queryclients_online` but should always count for the `clients <= slots` comparison

**Comment by Bluscream** [comment]
Dann ist es immernoch falsch weil es sind 2 musicbots auf dem server

**Comment by WolverinDEV** [comment]
Ja +query
