### ISSUE TITLE
Use build timestamps

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#154]
Just for the sake of completion i'd like to ask you to implement the build timestamp whereever required (either do it manually via https://www.epochconverter.com/clock or adjust your makefile accordingly to do it for you)
You can keep your general naming scheme, just append it. In the following list i use `1.1.30-beta6 [Build: 1527468306]` as example

- [x] query->server: `version` param: `build=1527468306`
- [x] query->server: `serverinfo` param: `virtualserver_version=TeaSpeak\s1.1.30-beta6\s[Build:\s1527468306]` (only when config value is not set or no license)
- [x] server->client: `initserver` param: `virtualserver_version=TeaSpeak\s1.1.30-beta6\s[Build:\s1527468306]` (only when config value is not set or no license)
- [x] server->client: `notifyserverupdated` param: `virtualserver_version=TeaSpeak\s1.1.30-beta6\s[Build:\s1527468306]` (only when config value is not set or no license)

PS. I would suggesting renaming the `Linux C++` "platform" to `Linux` for compatibility with styles and tools that show OS icons and because it's pretty obvious that it's C++

**Comment by Bluscream** [comment]
On the other hand you could use `TeaSpeak` as the platform at all times so styles/tools have something that stays consistent (not such a great idea if you plan to use ARM for Py devices)

**Comment by WolverinDEV** [comment]
Implemented

**Comment by Bluscream** [comment]
`Version:TeaSpeak 1.1.30-beta [1528039076] on Linux ` seems like you missed the `Build: ` part @WolverinDEV!

**Comment by WolverinDEV** [comment]
Implemented

**Comment by essemX** [comment]
1. zeigt immernoch nur den unix-timestamp an anstatt wie bei teamspeak das umgerechnete datum
2. zeigt version 1.1.31 an obwohl ich eben auf 1.1.32 geupdated hab
![teaspeakbug](https://user-images.githubusercontent.com/12894598/41236294-0e709f44-6d91-11e8-8abc-bef01db787c4.png)

**Comment by WolverinDEV** [comment]
Ja :D Have das `Build:` vergessen.
Ist jetzt implementiert
