### ISSUE TITLE
Block virtualserver_maxclients modification through db

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#155]
Let TeaSpeak check if `virtualservers_total_maxclients <= license_slots` on startup and if thats false refuse starting any more virtualservers

Also increase slot count with licenses for now lets say `2147483647` as thats the max int32 val or `65535` as thats the max int16

**Comment by Bluscream** [comment]
Why do we have `max slot limit reached` then at all?` just remove that error

**Comment by WolverinDEV** [comment]
Cause it's not really needed to have more that 1024 slots
