### ISSUE TITLE
[CRITICAL]: iphone imcompatibility => IOS 10.3.3 and Other bug

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#156]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***:  1.1.29-beta-2

## Issue
***Reason for reporting this issue***:
version of smartphone iphone IOS 10.3.3 on the version client teamspeak on iphone and the 3.1.28...
and other bug in the files log my friends is not talk voice on the server problem protocole just audio input request transmission audio

***Detailed Description***:
[01:06:38] [CRITICAL] GEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails!

[02:02:53] [ERROR]   4 | ype::0x4:0x8) => INVALID_PACKETftgetfileinfo'

EDIT Issue other bug : 

> ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib control.c:953:(snd_ctl_open_noupdate) Invalid CTL
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM

[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft
[08:05:46] [ERROR]   4 | Invalid channel property lastLeft

Line 17309: [19:23:57] [ERROR] GEN | !(reasonMessage.empty() && (reasonId != VREASON_SYSTEM && reasonId != VREASON_USER_ACTION)) at /home/wolverindev/TeamSpeak/server/src/client/ConnectedClient.cpp226
Line 49280: [01:58:37] [ERROR]   2 | Command handling of command clientchatclosed clid='2' cluid='oPCm4ciEb/+xzDRI9f+FgCt3gtI=' return_code='1:n' needs 10ms
	Line 180064: [03:31:51] [ERROR]   2 | Missing command '+.c>"co��ct/��"z@%t1{spea�б�d�C�Ѕge��p�+:���a%s��\sc>R
	Line 180065: [03:31:51] [ERROR] tA��ġ@%9:�qB��de:��p�+��:��]#1�q�mut
	Line 180066: [03:31:51] [ERROR] droi�\����sparô�
	Line 180067: [03:31:51] [ERROR] A�un
	Line 180068: [03:31:51] [ERROR] 0Ip$;�q(�����xUts)�o��Bre/U%��������꠾mtsAxner����p�"Q�n$�JBann�$�"
	Line 180069: [03:31:51] [ERROR] v
	Line 180071: [03:31:52] [ERROR]   2 | Missing command 'I'faiB�Js�82b811^ElD��v����z@3dwelQ�
	Line 180072: [03:31:52] [ERROR] �'
	Line 180073: [03:31:52] [ERROR]   2 | Missing command 'botinfo��"j�rma"��Q�A��\sDâte'
	Line 180074: [03:31:52] [ERROR]   2 | Missing command '+.c>"co��ct/��"z@%t1{spea�б�d�C�Ѕge��p�+:���a%s��\sc>R
	Line 180075: [03:31:52] [ERROR] tA��ġ@%9:�qB��de:��p�+��:��]#1�q�mut
	Line 180076: [03:31:52] [ERROR] droi�\����sparô�
	Line 180077: [03:31:52] [ERROR] A�un
	Line 180078: [03:31:52] [ERROR] 0Ip$;�q(�����xUts)�o��Bre/U%��������꠾mtsAxner����p�"Q�n$�JBann�$�"
	Line 180079: [03:31:52] [ERROR] v
	Line 20697: [00:45:30] [ERROR] [Music] Got error message from FFMpeg:
	Line 20697: [00:45:30] [ERROR] [Music] Got error message from FFMpeg:
	Line 20698: [00:45:30] [ERROR] [Music] size=  712336kB time=01:03:19.12 bitrate=1536.0kbits/s    
	Line 20699: [00:45:30] [ERROR] video:0kB audio:712336kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
	Line 20700: [00:45:30] [ERROR] [Music] size=  712336kB time=01:03:19.12 bitrate=1536.0kbits/s    
	Line 20701: [00:45:30] [ERROR] video:0kB audio:712336kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

	Line 38255: [02:36:35] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Failed to execute sql command: 1/database disk image is malformed[0m
	Line 125484: [20:56:06] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Failed to execute sql command: 1/database disk image is malformed[0m
	Line 132024: [21:00:30] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | The server crashed![0m
	Line 45973: [15:54:52] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 46154: [15:59:07] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 46567: [16:06:23] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 47309: [16:18:28] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 48743: [16:41:07] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 48844: [16:46:09] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 48948: [16:51:11] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49049: [16:56:13] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49152: [17:01:15] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49253: [17:06:18] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49357: [17:11:21] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49458: [17:16:23] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49565: [17:21:25] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49666: [17:26:27] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49769: [17:31:29] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49870: [17:36:31] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 49973: [17:41:33] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50074: [17:46:35] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50306: [17:52:34] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50429: [17:57:36] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50532: [18:02:38] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50633: [18:07:40] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50736: [18:12:42] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50838: [18:17:44] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 50940: [18:22:46] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 51055: [18:27:48] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 51197: [18:32:51] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 51302: [18:37:53] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 51403: [18:42:55] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 51506: [18:47:57] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getExternalType() == ClientType::CLIENT_VOICE' failed! This could cause fatal fails![0m
	Line 51622: [18:52:59] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31mGEN | Soft assertiation 'cl->state == ConnectionState::DISCONNECTED && cl->getE
	Line 160103: [23:36:00] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31m  4 | readQueue->peekNext(index++) => nullptr_t![0m
	Line 172477: [02:25:10] [ERROR] GEN | !(reasonMessage.empty() && (reasonId != VREASON_SYSTEM && reasonId != VREASON_USER_ACTION)) at /home/wolverindev/TeamSpeak/server/src/client/ConnectedClient.cpp228
	Line 172506: [02:25:11] [ERROR]   4 | Client id: 4 @ 0x7faeb0acddd0 thread 140191021664000
	Line 172543: [02:25:13] [ERROR]   4 | Client id: 6 @ 0x7faed402a8d0 thread 140389134944000
	Line 172653: [02:25:14] [ERROR]   4 | Client id: 6 @ 0x7faed402a8d0 thread 140389134944000
	Line 172788: [02:25:48] [ERROR]   4 | [Voice] Could not close v4 socket!
	Line 171987: [02:17:56] [ERROR] GEN | [WebList] Invalid web manager key response (-1) Error Resource temporarily unavailable
	Line 171987: [02:17:56] [ERROR] GEN | [WebList] Invalid web manager key response (-1) Error Resource temporarily unavailable
	Line 160217: [23:41:21] [ERROR] Timer statistics tick needs more than 22 milliseconds. Max allowed was 5 milliseconds.
	Line 160218: [23:41:21] [ERROR] Timer statistics tick needs more than 38 milliseconds. Max allowed was 5 milliseconds.
	Line 160219: [23:41:22] [ERROR] Timer statistics tick needs more than 8587 microseconds. Max allowed was 5000 microseconds.
	Line 160220: [23:41:22] [ERROR] Timer statistics tick needs more than 25 milliseconds. Max allowed was 5 milliseconds.
	Line 160221: [23:41:23] [ERROR] Timer flush needs more than 106 milliseconds. Max allowed was 5 milliseconds.
	Line 160222: [23:41:23] [ERROR] Timer statistics tick needs more than 6226 microseconds. Max allowed was 5000 microseconds.
	Line 160223: [23:41:23] [ERROR] Timer statistics tick needs more than 5167 microseconds. Max allowed was 5000 microseconds.
	Line 160224: [23:41:24] [ERROR] Timer statistics tick needs more than 6257 microseconds. Max allowed was 5000 microseconds.

**Comment by WolverinDEV** [comment]
Hmm I see the soft assert comes more often than I expected it :)
I'll look at this at the next weekend

**Comment by WolverinDEV** [comment]
Hey,
i already fixed the soft assert. This should work again now.
I also fixed several bugs. Could you may try it again?

**Comment by Home-Network** [comment]
ok no problem i will test this right now and i'll let you know if there are major bug ok

**Comment by Home-Network** [comment]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***:  1.1.30-beta-2

## Issue
***Reason for reporting this issue***:
news problem on the botmusic + crash_server for the version 

***Detailed Description***:
<06:45:04> "Music Manager": - 3165 | Im a music bot!
<06:45:10> "Music Manager": You successfully select the bot 3165 | Im a music bot!
<06:45:12> "Im a music bot!": Queueing video https://www.youtube.com/watch?v=LhU5OB64HWM
<06:45:42> "Im a music bot!": An error occurrent while trying to replay the next song! (Loader load timeout!)

+ crash_server 
http://home-network.ovh/[03-06-2018_06h54]CrashDump.rar

**Comment by WolverinDEV** [comment]
Hey,
the music bot bug (and crash) is already fixed as you see here #160.
`[07:16:51] [ERROR] 4 | Invalid channel property lastLeft` this has nothink to days really.
It just came from one of the past updates where i changed the property system (to decrease the memory usage).

**Comment by Home-Network** [comment]
no problem with my server big latency problems comes from your software I checked it's 100% on the actual version of the server teamspeak official there is no problem of slowness and on those since I uses the server version TeaSpeak Software and very slow because all the instructions running every 2 to 3 seconds of latency, it becomes really boring

**Comment by WolverinDEV** [comment]
Hmm Okey I trust you that it isn't your server.
I may think the maximum of 500 microseconds is way to small (remember 1000000 microseconds are one millisecond)
And yes I know that 27 is the most stable currently and I'm still try to find the bug. 
And when I found the bug why the server crashes sometimes random than the 30 should be better (the memory bug is already fixed)
But remember I'm still in beta so I can't garabtee that all version are stable. But I hope I can release a stable build soon.

**Comment by Home-Network** [comment]
I just stay on the version 1.1.27-beta-6 for the moment because it is the version for me the most stable but always with the problem of slowness but I am sure you will find the problems your project and very interested continued how does it make me know when you find the problem ok

**Comment by WolverinDEV** [comment]
Should be fixed :)
