### ISSUE TITLE
Musicbot "Online since" glitch

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#158]
## System Information
***Operating System***: ArchLinux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.27 beta 6 _(The 1.1.29 version is unstable)_

## Issue
***Reason for reporting this issue***:
Glitch (low priority bug 🌵)

***Detailed Description***:

No musicbot **flag** and wrong "online since" **time**.

![c1](https://user-images.githubusercontent.com/19707386/40801145-81b42c46-6512-11e8-9a6e-df4e02593deb.PNG)

**Comment by Bluscream** [comment]
It has no flag because it's connecting from your local server

**Comment by xRedFox** [comment]
My fallback_country is set to DE like in the default configuration file but the German flag does not appear...
My config here: [config.zip](https://github.com/TeaSpeak/TeaSpeak/files/2059688/config.zip)

**Comment by Bluscream** [comment]
Seems like that doesn't apply to musicbot, @WolverinDEV please add that.

**Comment by WolverinDEV** [comment]
I'll fix this as soon im at home and the unstable version which is currently 5he newest

**Comment by WolverinDEV** [comment]
Both bugs are fixed within the next build

**Comment by Bluscream** [comment]
voice client online time is also glitched out (refreshed the infoframe 1 second before moving the connection info dialog to foreground
![grafik](https://user-images.githubusercontent.com/3318223/41074794-47e0b44e-69f9-11e8-8999-6e706f27d79c.png)

**Comment by WolverinDEV** [comment]
It's a TeamSpeak glitch. It just updated when you're refreshing the client data and the ui

**Comment by Bluscream** [comment]
On Teamspeak however these two are in sync
