### ISSUE TITLE
slotinfo not correct

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#16]
`hostinfo` returns `virtualservers_total_maxclients=254 virtualservers_running_total=1` but `serverinfo` on that virtualserver returns `virtualserver_maxclients=120` which makes not really a lot of sense :)

**Comment by WolverinDEV** [comment]
virtualservers_total_maxclients -> Max slots set (Instance based)
virtualserver_maxclients            -> Max users (Server based)

**Comment by WolverinDEV** [comment]
Fixed in 1.0.11-Beta
