### ISSUE TITLE
Musicbot "stream" crash

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#160]
## System Information
***Operating System***: ArchLinux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.30 beta 2

## Issue
***Reason for reporting this issue***:
Bug

***Detailed Description***:
The server crashes when `.mbot stream https://www.youtube.com/watch?v=U3gbINiRbYk` is executed

**Crash dump**: [crash_dump_83b6493b-b090-4d11-b6469594-e7b9bf56.zip](https://github.com/TeaSpeak/TeaSpeak/files/2065716/crash_dump_83b6493b-b090-4d11-b6469594-e7b9bf56.zip)
**Logs**: [log_2018-06-03_08_40_27_general.zip](https://github.com/TeaSpeak/TeaSpeak/files/2065717/log_2018-06-03_08_40_27_general.zip)

**Comment by WolverinDEV** [comment]
Oh i forgot to update the music bot providers....
Its using a old version of a internal library.

**Comment by WolverinDEV** [comment]
Fixed within build 3
