### ISSUE TITLE
Refuse to add ban if already exists

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#161]
- [ ] When a ban gets added through `banadd` make sure that this (exact) ban entry does not exist already and if it does return `ERROR_database_duplicate_entry`.
- [ ] When a banrule that already exists would be added thorugh `banclient` just omit that rule silently and let the others get added.

Also maybe as an idea for the future:
- [ ] If a ban already exists in the banlist but it's duration is smaller then the duration of the ban that would have been added, let the server edit the old ban rule to match the duration of the "new" one.

**Comment by WolverinDEV** [comment]
Implemented within the next version
