### ISSUE TITLE
Version Sign validation

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#163]
- [ ] Now it's time to add stuff like validating the version signs like Teamspeak
Maybe https://puu.sh/Ayz2s/d109269338.zip helps you with it.
- [ ] New permission: `b_client_allow_invalid_sign`
- [ ] Also treat versions as invalid when their unix timestamp is higher than the current time

**Comment by WolverinDEV** [comment]
Version sign wird nicht überprüft, da z. B. der web client keine signierte Version besitzt und ich es ziemlich unnötig finde das nur für TeamSpeak clients zu enforcen

**Comment by Bluscream** [comment]
Sollte das selbe system nicht für den webclient möglich sein?

Falls nicht, naja dann muss ich wohl nen query bot dafür machen

**Comment by WolverinDEV** [comment]
Nunja ich habe nochmal drüber nachgedacht und denke das dieses System doch unnötig ist.

**Comment by Bluscream** [comment]
Ja stimmt warum auch den Trolls einheit gebieten, bitte bau den banclient command aus. Ist auch unnötig

**Comment by Bluscream** [comment]
So, ich würde mittlerweile sagen das es implementiert werden sollte, hier ist die Methode zum überprüfen: https://github.com/ReSpeak/TsVersionChecker/blob/master/Program.cs#L115-L117

Leute setzen sich da nämlich behinderte [Zalgo](https://stackoverflow.com/questions/6579844/how-does-zalgo-text-work) zeichen rein damit man viele sachen in dem Infodingsbums nicht mehr lesen kann.

**Comment by WolverinDEV** [comment]
Nein, eine überprüfung wir nicht eingebaut da, wie schon oben gesagt dies schwachsinnig ist.
Begrenze aber die characters auf ASCII.

**Comment by Bluscream** [comment]
Dann begrenz auch bitte die length auf 120 chars oder so damit die leute da keine romane reinschreiben

**Comment by Bluscream** [comment]
Dafür gibts ja die beschreibung

**Comment by Bluscream** [comment]
In which version will it be fixed?

**Comment by WolverinDEV** [comment]
1.3.5 :)
