### ISSUE TITLE
preprocessNextWritePacket() double triggered!

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#164]
## System Information
***Operating System***: ArchLinux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.30 beta 5

## Issue
***Reason for reporting this issue***:
Low priority bug

***Detailed Description***:
Spam in console
```
preprocessNextWritePacket() double triggered!
```
Logs: [log_2018-06-06_17:56:23_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2077097/log_2018-06-06_17.56.23_general.log)

**Comment by WolverinDEV** [comment]
This message isn't really an error.
Should be dropped to debug (or kicked out totally).
Its more something like a debug for me. (I just worked on the core connection system again)

**Comment by WolverinDEV** [comment]
Message got removed within the next build
