### ISSUE TITLE
Crash and autorestart script unable to restart the server

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#165]
## System Information
***Operating System***: ArchLinux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.30 beta 5

## Issue
***Reason for reporting this issue***:
Crash

***Detailed Description***:
Crash dump: [crash_dump_50afb436-b1b7-497c-656c7eb6-134ed6d1.zip](https://github.com/TeaSpeak/TeaSpeak/files/2077938/crash_dump_50afb436-b1b7-497c-656c7eb6-134ed6d1.zip)
Logs: [log_2018-06-06_17_56_23_general.zip](https://github.com/TeaSpeak/TeaSpeak/files/2077939/log_2018-06-06_17_56_23_general.zip)

**Comment by WolverinDEV** [comment]
Hey,
I already saw your issue and I already know that bug. It's the last known bug and it's hiding very well. It also may caused the hangup some times. I already try to fix it,but I still not got hin 'till two weeks :/

**Comment by WolverinDEV** [comment]
Should be fixed(nearly)
I heard it may already happen, but never saw that
