### ISSUE TITLE
Flood ban for Admin Server Query

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#167]
Even though i have full permissions and basically disabled the query antiflood i still get a floodban after creating or deleting too many channels!

![yatqa_2018-06-06_23-30-56](https://user-images.githubusercontent.com/3318223/41069920-87f724f6-69df-11e8-9450-02b608b91c2c.png)
![yatqa_2018-06-06_23-31-58](https://user-images.githubusercontent.com/3318223/41069922-895e6bba-69df-11e8-95f2-2ed90eb62e16.png)
![yatqa_2018-06-06_23-32-14](https://user-images.githubusercontent.com/3318223/41069926-8b08f14c-69df-11e8-80af-c50adb8239bf.png)

**Comment by WolverinDEV** [comment]
Version?
I think you're using a "old" version. I fit get to add a ! at some point

**Comment by Bluscream** [comment]
@WolverinDEV 1.0.30-5

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WolverinDEV** [comment]
Are you sure the permission does not get overridden by any other stuff?

**Comment by Bluscream** [comment]
What other stuff?

**Comment by Bluscream** [comment]
Even when using banlist too often i get flood locked ...

![](https://i.imgur.com/L0e4jIN.png)

**Comment by WolverinDEV** [comment]
Queries aren't invisibly to everyone. You first have to "join" with the command `join? .
And yes are you sure that you have ignore anti flood?
(BTW: Im not 100% sure i may not update the flag if you're just switching the server. But i'll definitely update it when you switch the channel)

**Comment by WolverinDEV** [comment]
Of causes there's also a leave command :)
BTW: Ill add that later to your pr request :)

**Comment by WolverinDEV** [comment]
BTW Flood stuff is fixed within the next version :)
