### ISSUE TITLE
Ability to kick Server Queries...

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#169]
... which would just close their connection.

**Comment by WolverinDEV** [comment]
You should already be able to kick them then they're bound to a server

**Comment by Bluscream** [comment]
Will that close their telnet connection or send them a notifyclientleftview for themselve?

**Comment by WolverinDEV** [comment]
no i dont think so?
Buit why should this be required?
And btw the serverquery woun't get a `notifyclientleftview`

**Comment by Bluscream** [comment]
So the request is still a thing. Otherwise `Ability to kick Server Queries...` wouldn't be fullfilled.

**Comment by WolverinDEV** [comment]
Well I was wrong if you kick a server query from the server it gets disconnected completely
