### ISSUE TITLE
Implement all commands

### ISSUE THREAD

**Issue by WolverinDEV** [TeaSpeak/TeaSpeak#17]
- [x] banadd
- [x] banclient
- [x] bandel
- [x] bandelall
- [x] banlist
- [x] bindinglist
- [x] channeladdperm
- [x] channelclientaddperm
- [x] channelclientdelperm
- [x] channelclientlist
- [x] channelclientpermlist
- [x] channelcreate
- [x] channeldelete
- [x] channeldelperm
- [x] channeledit
- [X] channelfind
- [x] channelgetdescription
- [x] channelgroupadd
- [x] channelgroupaddperm
- [x] channelgroupclientlist
- [x] channelgroupcopy
- [x] channelgroupdel
- [x] channelgroupdelperm
- [x] channelgrouplist
- [x] channelgrouppermlist
- [x] channelgrouprename
- [x] channelinfo
- [x] channellist
- [x] channelmove
- [x] channelpermlist
- [x] channelsubscribe
- [x] channelsubscribeall
- [x] channelunsubscribe
- [x] channelunsubscribeall
- [x] clientaddperm
- [x] clientchatclosed
- [x] clientchatcomposing
- [x] clientdbdelete
- [x] clientdbedit
- [x] clientdbfind
- [x] clientdbinfo
- [x] clientdblist
- [x] clientdelperm
- [x] clientdisconnect
- [x] clientedit
- [x] clientfind
- [x] clientgetdbidfromuid
- [x] clientgetids
- [x] clientgetnamefromdbid
- [x] clientgetnamefromuid
- [x] clientgetuidfromclid
- [x] clientgetvariables
- [x] clientinfo
- [x] clientinit
- [x] clientinitiv
- [x] clientkick
- [x] clientlist
- [x] clientmove
- [x] clientmute
- [X] ~~clientnotifyregister~~ (Client side only)
- [X] ~~clientnotifyunregister~~ (Client side only)
- [x] clientpermlist
- [x] clientpoke
- [x] clientsetserverquerylogin
- [x] clientunmute
- [x] clientupdate
- [x] complainadd
- [x] complaindel
- [x] complaindelall
- [x] complainlist
- [x] connectioninfoautoupdate
- [ ] custominfo
- [ ] customsearch
- [x] ~~dummy_connectfailed~~ (Dummy commands are not supported because they are for internal TeamSpeak interactions)
- [x] ~~dummy_connectionlost~~ (Dummy commands are not supported because they are for internal TeamSpeak interactions)
- [x] ~~dummy_newip~~ (Dummy commands are not supported because they are for internal TeamSpeak interactions)
- [x] ftcreatedir
- [x] ftdeletefile
- [ ] ftgetfileinfo
- [x] ftgetfilelist
- [x] ftinitdownload
- [x] ftinitupload
- [ ] ftlist
- [ ] ftrenamefile
- [ ] ftstop
- [x] getconnectioninfo
- [x] gm
- [x] help
- [x] instanceedit
- [x] instanceinfo
- [ ] logadd
- [X] login
- [X] logout
- [x] logview
- [x] messageadd
- [x] messagedel
- [x] messageget
- [x] messagelist
- [x] messageupdateflag
- [x] permfind
- [x] permget
- [x] permidgetbyname
- [x] permissionlist
- [x] permoverview
- [x] permreset
- [x] plugincmd
- [x] privilegekeyadd
- [x] privilegekeydelete
- [x] privilegekeylist
- [x] privilegekeyuse
- [x] quit
- [x] serverconnectinfo => serverrequestconnectioninfo
- [x] servercreate
- [x] serverdelete
- [x] serveredit
- [x] servergetvariables
- [x] servergroupadd
- [x] servergroupaddclient
- [x] servergroupaddperm
- [x] servergroupautoaddperm
- [x] servergroupautodelperm
- [x] servergroupclientlist
- [x] servergroupcopy
- [x] servergroupdel
- [x] servergroupdelclient
- [x] servergroupdelperm
- [x] servergrouplist
- [x] servergrouppermlist
- [x] servergrouprename
- [x] servergroupsbyclientid
- [x] serveridgetbyport
- [x] serverinfo
- [x] serverlist
- [x] servernotifyregister
- [x] servernotifyunregister
- [x] serverprocessstop
- [ ] serverquerycmd (?)
- [x] serverrequestconnectioninfo 
- [x] serversnapshotcreate (half/require valid data (no check!))
- [x] serversnapshotdeploy
- [x] serverstart
- [x] serverstop
- [ ] servertemppasswordadd
- [ ] servertemppassworddel
- [ ] servertemppasswordlist
- [x] setclientchannelgroup
- [x] setconnectioninfo
- [x] setwhisperlist (Unused and never explained system)
- [x] textmessagesend
- [x] tokenadd
- [x] tokendelete
- [x] tokenlist
- [x] tokenuse
- [x] use
- [x] verifychannelpassword
- [x] verifyserverpassword
- [x] version
- [x] whoami

**Comment by Bluscream** [comment]
I added some more commands for you to check :)

**Comment by WolverinDEV** [comment]
Not all commands are actually query/voice commands. (e.g. `setwhisperlist` or `servervariable` etc.)

**Comment by lexesv** [comment]
command **serveridgetbyport** implemented

**Comment by WolverinDEV** [comment]
Already implemented => Checked now :)

**Comment by ts3cloud** [comment]
Not implemented or not work corectly: 
*client*
 - connection_client_ip
 - connection_bytes_received_total
 - connection_bytes_sent_total
 - totalconnections

+
 - serversnapshotcreate
 - serversnapshotdeploy

**Comment by WolverinDEV** [comment]
These are 100% not TeamSpeak queries :)
- `connection_client_ip`
- `connection_bytes_received_total`
- `connection_bytes_sent_total`
- `totalconnections`

And the `serversnapshotcreate` sould work basicly (still not transfaring Channel client perms)
And `serversnapshotdeploy` not working

**Comment by ts3cloud** [comment]
@WolverinDEV
I gave you a PHP query from TeamSpeak 3 PHP Framework (modified to work with TeaSpeak).
When I find some moments of free time, i give an example from Query's pure serverquery.

**Comment by lexesv** [comment]
_TeaSpeak-1.1.0-beta-11_

serversnapshotcreate
error id=2 msg=not\simplemented

serversnapshotdeploy working )
I transferred  200+ virtual servers out of ts3 to Teaspeak.

**Comment by WolverinDEV** [comment]
@lexesv yes I mixed that up deploy and snapshot xD

@ts3cloud yes I know but to your post above. I guess you mixed up properties and commands

**Comment by ts3cloud** [comment]
Example for *client*

TS3 server: 

> clientinfo clid=31
> cid=146296 client_idle_time=51801 client_unique_identifier=JHazMrrd8xxxxxxxs= client_nickname=CLIENT client_version=3.1.8\s[Build:\s1516614607] client_platform=Windows client_input_muted=0 client_output_muted=0 client_outputonly_muted=0 client_input_hardware=1 client_output_hardware=1 client_default_channel client_meta_data client_is_recording=0 client_version_sign=gDEgQf\/BiOQZdAheKccM1XWcMUj2OUQqt75oFuvF2c0MQMXyv88cZQdUuckKbcBRp7RpmLInto4PIgd7mPO7BQ== client_security_hash client_login_name client_database_id=308315 client_channel_group_id=12654 client_servergroups=55555 client_created=1503861134 client_lastconnected=1519639305 client_totalconnections=232 client_away=0 client_away_message client_type=0 client_flag_avatar client_talk_power=75 client_talk_request=0 client_talk_request_msg client_description client_is_talker=0 client_month_bytes_uploaded=7946147 client_month_bytes_downloaded=280541 client_total_bytes_uploaded=8028827 client_total_bytes_downloaded=40054151 client_is_priority_speaker=0 client_nickname_phonetic client_needed_serverquery_view_power=75 client_default_token client_icon_id=0 client_is_channel_commander=0 client_country=IT client_channel_group_inherited_channel_id=146296 client_badges=overwolf=0 client_base64HashClientUID=cehglddclknnpaammmkpanbjfffaeemggelmljal connection_filetransfer_bandwidth_sent=0 connection_filetransfer_bandwidth_received=0 connection_packets_sent_total=15088 connection_bytes_sent_total=748914 connection_packets_received_total=16180 connection_bytes_received_total=801199 connection_bandwidth_sent_last_second_total=79 connection_bandwidth_sent_last_minute_total=213 connection_bandwidth_received_last_second_total=81 connection_bandwidth_received_last_minute_total=508 connection_connected_time=7173500 connection_client_ip=8.8.8.8
> error id=0 msg=ok

From TeaSpeak

> clientinfi clid=2
> client_type=0 clid=1 client_database_id=3 client_unique_identifier=pHZElqV2bOrSw3hup4A9CDLGQsA= client_nickname=ts3.cloud client_nickname_phonetic client_input_muted=0 client_output_muted=0 client_outputonly_muted=0 client_input_hardware=1 client_output_hardware=1 client_is_recording=0 client_meta_data client_channel_group_id=14 client_servergroups=11 client_away=0 client_away_message client_flag_avatar client_description=I\sdon't\shave\sa\sdescription client_talk_power=25 client_talk_request=0 client_talk_request_msg client_is_talker=0 client_is_priority_speaker=0 client_is_channel_commander=0 client_unread_messages=0 client_needed_serverquery_view_power=0 client_icon_id=0 client_country=JP client_channel_group_inherited_channel_id=0 client_badges=overwolf=0
> error id=0 msg=ok

**Comment by Bluscream** [comment]
`clientgetids` seems to working, right @WolverinDEV?
```
[OUT] clientgetids cluid=xxjnc14LmvTk+Lyrm8OOeo4tOqw=
[IN ] notifyclientids name=┬╗\sWolverinDEV\s[OFFLINE] clid=4 cluid=xxjnc14LmvTk+Lyrm8OOeo4tOqw=
```

**Comment by Bluscream** [comment]
Also i think the `help` stuff should be implemented i know it's not required but it helps new people getting into query and gives a quick syntax on how stuff can be used. it can work the same as in Teamspeak so just giving out the content of the `docs/` subdir. Example:
`help` = `teaspeak/docs/help.txt`
`help clientinfo` = `teaspeak/docs/clientinfo.txt`

**Comment by Bluscream** [comment]
Also maybe you could use the timestamp of build in `version` so yatqa doesn't show teaspeak as an outdated server if the teaspeak version is recent.
```
[OUT] version
[IN ] version=3.1.1 build=1519643644 platform=Linux
[OUT] version
[IN ] version=1.1.17-beta build=0 platform=Linux
```

**Comment by WolverinDEV** [comment]
Updated some commands (u2d now)

**Comment by Bluscream** [comment]
Can you check and update the list?

**Comment by daffyyyy** [comment]
Can u provide connection_connected_time?

**Comment by LordManzana** [comment]
Usefull commands, don't know why still not implemented. Maybe no one asked for?

servertemppasswordadd
servertemppassworddel
servertemppasswordlist
