### ISSUE TITLE
Parameter not found

### ISSUE THREAD

**Issue by Dominik28111** [TeaSpeak/TeaSpeak#171]
## System Information
***Operating System***: Debian 8.10
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.30-beta | Packed version: 5

## Issue
***Reason for reporting this issue***: Enhancement

***Detailed Description***: When we tried to move our root query connected via YaTQA all clients loses their connection. Reason: parameter not found

**Comment by Bluscream** [comment]
![grafik](https://user-images.githubusercontent.com/3318223/41120400-f08a58bc-6a84-11e8-9d42-4e0268d9d86b.png)

Works fine here

**Comment by WolverinDEV** [comment]
![https://img.teaspeak.de/Peek%202018-06-07%2021-04.gif](https://img.teaspeak.de/Peek%202018-06-07%2021-04.gif)

**Comment by WolverinDEV** [comment]
Fixed within the next version
