### ISSUE TITLE
[NOT A BUG!] Able to get TeaSpeak Server Running on Anniversary Version With Debian Installed

### ISSUE THREAD

**Issue by skokkk** [TeaSpeak/TeaSpeak#172]
## System Information
***Operating System***: Windows (Latest Anniversary)
***Operating System Type*** x64
***TeaSpeak Version***: 1.1.30-beta-6

## Issue
***Reason for reporting this issue***:
To show that windows support is actually possible, on Linux on Windows.

***Detailed Description***:
I ran TeaSpeak inside bash for my installed version of Debian on my Windows 10 Anniversary update. Here's a summary:
cd <the directory>
run the minimal for first run WITHOUT sudo
apt-get update
apt-get upgrade (is this still even needed?? was just by habit)
apt-get install youtube-dl (brought all this stuff with it: https://i.imgur.com/oYz9Wva.png)
It installed a bunch of packages including youtube-dl

***Client logs after doing basic stuff***:
6/9/2018 16:25:50	ClientUI	Info	Autoreconnecting	
6/9/2018 16:25:50	ClientUI	Info	Connect to server: localhost	
6/9/2018 16:25:50	ClientUI	Info	Trying to resolve localhost	
6/9/2018 16:25:50	TSDNS	Info	A/AAAA DNS resolve successful, "localhost" =(h: ::1 p:0), (h: 127.0.0.1 p:0)	
6/9/2018 16:25:50	ClientUI	Info	Lookup finished: ip=::1 port=9987 query=localhost error=0	
6/9/2018 16:25:50	ClientUI	Info	Resolve successful: [::1]:9987127.0.0.1:9987	
6/9/2018 16:25:50	ClientUI	Info	Initiating connection: [::1]:9987	
6/9/2018 16:25:50	UDPClient	Error	No connection could be made because the target machine actively refused it	
6/9/2018 16:25:50	UDPClient	Error	An existing connection was forcibly closed by the remote host	
6/9/2018 16:25:50	ClientUI	Info	Connect status: Connecting	
6/9/2018 16:25:50	UDPClient	Error	No connection could be made because the target machine actively refused it	
6/9/2018 16:25:50	UDPClient	Error	An existing connection was forcibly closed by the remote host	
6/9/2018 16:25:51	UDPClient	Error	No connection could be made because the target machine actively refused it	
6/9/2018 16:25:51	UDPClient	Error	An existing connection was forcibly closed by the remote host	
6/9/2018 16:25:52	UDPClient	Error	No connection could be made because the target machine actively refused it	
6/9/2018 16:25:52	UDPClient	Error	No connection could be made because the target machine actively refused it	
6/9/2018 16:25:53	UDPClient	Error	No connection could be made because the target machine actively refused it	
6/9/2018 16:25:53	UDPClient	Error	No connection could be made because the target machine actively refused it	
6/9/2018 16:25:55	ClientUI	Info	Connect status: Disconnected	
6/9/2018 16:25:55	ClientUI	Info	Initiating connection: 127.0.0.1:9987	
6/9/2018 16:25:55	ClientUI	Info	Connect status: Connecting	
6/9/2018 16:25:55	PktHandler	Devel	Puzzle solve time: 1	
6/9/2018 16:25:55	ClientUI	Info	Connect status: Connected	
6/9/2018 16:25:55	ClientUI	Info	Connect status: Establishing connection	
6/9/2018 16:25:55	ClientUI	Info	Connect status: Connection established	
6/9/2018 16:25:55	PermManager	Info	Requesting permissions from server	
6/9/2018 16:25:55	ClientUI	Info	Removed 0 non-existant channels from autosubscribe list	
6/9/2018 16:27:05	PermissionsTree	Info	Is new permID server: 1	
6/9/2018 16:27:05	PermissionsTree	Info	Is new permID server: 1	
6/9/2018 16:27:05	PermissionsTree	Info	Is new permID server: 1	
6/9/2018 16:27:05	PermissionsTree	Info	Is new permID server: 1	
6/9/2018 16:27:05	PermissionsTree	Info	Is new permID server: 1	

***Only Issue I can see out of anything (compared to linux)***:
https://i.imgur.com/SnL7YrI.png

*Delete me: If you don't follow this issue template, you may not get a response or the issue get instantly closed.*

Just something I came accross whilke testing Windows' stuff. Teaspeak could let a lot of users know about this and report issues, for one day for /proper/ windows support :).

<3
a cup of tea for you,
shock

**Comment by skokkk** [comment]
Ps. You would like to install screen in there as well.

**Comment by Bluscream** [comment]
Does lsfw even work on windows server? And if yes how would one autorun it on startup etc?
