### ISSUE TITLE
Crashing TS3 srvs.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#177]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.32-beta

## Issue
***Reason for reporting this issue***:
Crashing - Dunno about it can be issue with:
15:06:17] [DEBUG]  64 | [Permission] Value test result for test type 1.
[15:06:17] [DEBUG]  64 | [Permission] Permission: i_channel_description_view_power Required value: -2 Gained value: 50 Force required: 0

***Detailed Description***:
Crash dump: [crash_dump_360f5b6a-7f6b-4062-06e5c788-af8fc7b4.zip](https://github.com/TeaSpeak/TeaSpeak/files/2090328/crash_dump_360f5b6a-7f6b-4062-06e5c788-af8fc7b4.zip)
Logs: [log_2018-06-11_150131_general.log.zip](https://github.com/TeaSpeak/TeaSpeak/files/2090367/log_2018-06-11_150131_general.log.zip)

**Comment by WolverinDEV** [comment]
No the crash append while you created a server snapshot :)

**Comment by MikkelDK** [comment]
I got new crash. - can i upload it?

I saw this text:
[14:54:11] [ERROR]  51 | Packet handing of Voice needs more than 10ms. (128)
[14:54:11] [CRITICAL] GEN | The server crashed!

**Comment by WolverinDEV** [comment]
No its just a random fault. 
I dont think its a reproduce able bug. 
Its happed when you created a snapshot from a TeaSpeak server.
(`serversnapshotcreate`)
But ill test it locally later

**Comment by MikkelDK** [comment]
[17:25:19] [INFO]   6 | [FILE] Missing group icon (4294967294).
[17:25:19] [INFO]   6 | [FILE] Missing group icon (4294967294).
[17:25:19] [INFO]   6 | [FILE] Missing group icon (4294967294).
[17:25:19] [ERROR]   6 | Missing servers default group!
[17:25:19] [ERROR]   6 | Missing servers default channel group!

Do you think, there is some fix (for that as example)

**Comment by WolverinDEV** [comment]
Already fixed the errors. Should not be shown anymore.

**Comment by MikkelDK** [comment]
Nice @WolverinDEV - when will next build be updated?

**Comment by WolverinDEV** [comment]
As soon i finalized my work with permreset and some restructuring within my permission system

**Comment by MikkelDK** [comment]
Cool enough! ;)

**Comment by MikkelDK** [comment]
@WolverinDEV Seems i have found new error. is it OK, i create new issue for that?

**Comment by WolverinDEV** [comment]
Of cause
