### ISSUE TITLE
New TS3 Crash

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#178]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.32b

## Issue
***Reason for reporting this issue***:
Server crashing - so soon you are login serveradmin on YaTQA > So soon you are clicking on 1 TS Server. the server has been crashed.

***Detailed Description***:
Crash Dump: [crash_dump_953ef625-e946-4acb-33d7b4ad-cc67bd72.dmp.zip](https://github.com/TeaSpeak/TeaSpeak/files/2091317/crash_dump_953ef625-e946-4acb-33d7b4ad-cc67bd72.dmp.zip)
Logs: [log_2018-06-11_201557_general.log.zip.zip](https://github.com/TeaSpeak/TeaSpeak/files/2091359/log_2018-06-11_201557_general.log.zip.zip)

**Comment by WolverinDEV** [comment]
Upps :D Fixed :)
