### ISSUE TITLE
Problems with ServerQuery, or is it YaTQA update?

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#179]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.32b2

## Issue
***Reason for reporting this issue***:
After updating > making server via YaTQA. so soon i wanna to check serverlist again, not possible.. does it mean the YaTQA problem?

***Detailed Description***:
Command: serverlist
Error message: insufficient manager permissions
Error code 2568
Missing permission: (b_serverinstance_virtualserver_list?)

**Comment by MikkelDK** [comment]
@WolverinDEV i did found some extra error (after update) - Does it have anything to do with YatQA?

**Comment by WolverinDEV** [comment]
One second i think theres something strange. Your query group get lost on server switch

**Comment by WolverinDEV** [comment]
Beta 4 fixed it! Was just a little bug within the group system
