### ISSUE TITLE
Editing bans

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#18]
```
banedit banid ip name uid time banreason
```

The client has an "Edit Ban" contextmenu entry but it only executes
```
[OUT] banadd ip=def name uid=sRbhRdbz3cXcWHhVnkGETj8YBMI= banreason return_code=1:d return_code=__1:d_1:d
[ IN] error id=0 msg=ok return_code=1:d
[OUT] bandel banid=1 return_code=1:e return_code=__1:e_1:e
[ IN] error id=0 msg=ok return_code=1:e
```

**Comment by WolverinDEV** [comment]
I dont realy understand what you mean with this issue :D

**Comment by Bluscream** [comment]
Well id like to see a new command to edit bans directly rather than removing/adding

**Comment by WolverinDEV** [comment]
Added in TeaSpeak 1.0.11-beta
+ New permission `b_client_ban_edit_global`
+ New permission `b_client_ban_edit`
+ New command:
  `banedit`
  * `banid`    [IN] [REQ]
  * `sid`        [IN] [OPT]
  * `ip`          [OUT] [OPT]
  * `name`    [OUT] [OPT]
  * `uid`        [OUT] [OPT]
  * `reason`  [OUT] [OPT]
  * `time`      [OUT] [OPT]

**Comment by Bluscream** [comment]
Awesome, thanks. Just think of the time Teamspeak Systems GmbH would have needed for that xD

**Comment by WolverinDEV** [comment]
haha yeah
