### ISSUE TITLE
crash after update.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#184]
## System Information
***Operating System***: Debian 9.2
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.33-beta0

## Issue
***Reason for reporting this issue***:
Server did crashed after few minutes.

***Detailed Description***:
Dump: [crash_dump_f15e16b9-0ada-4185-47197483-2a86d3d5.dmp.zip](https://github.com/TeaSpeak/TeaSpeak/files/2104029/crash_dump_f15e16b9-0ada-4185-47197483-2a86d3d5.dmp.zip)
Logs: [logs.zip](https://github.com/TeaSpeak/TeaSpeak/files/2104030/logs.zip)

**Comment by MikkelDK** [comment]
@Bluscream possible for you can assign @WolverinDEV 👍

**Comment by WolverinDEV** [comment]
duplicated of #182 
(Crashes are equal caused)

I'll try to fix this
