### ISSUE TITLE
Crash_Dump

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#185]
## System Information
***Operating System***: Linux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.33-beta-2 

## Issue

https://transfer.sh/uuQqT/crash_dump_606842d0-9fcc-4297-0c216ca0-930718fd.dmp.tar.gz

**Comment by MikkelDK** [comment]
Which error are you getting. - If you are running (behind screen). - are you getting this crash: "Illegal instruction" ?

**Comment by WolverinDEV** [comment]
Its euqal again to #182 :)
