### ISSUE TITLE
Channel permissions not saving

### ISSUE THREAD

**Issue by M0V3** [TeaSpeak/TeaSpeak#187]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.33-beta

## Issue
Channel permissions (join, subscribe, change, delete, browse, upload, download, rename and create directory) don't seem to save when shutting the server down and starting it again.
They always get reset to 0.

**Comment by WolverinDEV** [comment]
Fixed, sorry for the little bug :)
