### ISSUE TITLE
Can't use sendtextmessage with targetmode 2

### ISSUE THREAD

**Issue by M0V3** [TeaSpeak/TeaSpeak#193]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.35-beta-3

## Issue
It's not possible to use sendtextmessage to send a message to a channel.
Example command:
`sendtextmessage targetmode=2 target=17 msg=test`
Will return `error id=768 msg=invalid\schannelID extra_msg=invalid\sbounded\schannel`
target is the channel ID, I've tried multiple channels, none worked.

**Comment by WolverinDEV** [comment]
Hmm? I never know that you're able to send text messages to channels where are you not in.
BTW to join a channel via query you first have to join via the command `join`

**Comment by M0V3** [comment]
Thanks, I thought there could be a command to join a channel, but I couldn't find it in any documentation i checked and didn't think of trying a simple "join" haha.  
It works with using join before.  
I don't know if TeamSpeak supports sendtextmessage without joining the channel, but in the Documentation they seem to use it without joining a channel beforhand:
Just one example from the doc (http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf)
`serverlist
clientlist –uid –away –groups
clientdbfind pattern=ScP
clientdbfind pattern=FPMPSC6MXqXq751dX7BKV0JniSo= –uid
clientkick reasonid=5 reasonmsg=Go\saway! clid=1|clid=2|clid=3
channelmove cid=16 cpid=1 order=0
sendtextmessage targetmode=2 target=12 msg=Hello\sWorld!`

**Comment by WolverinDEV** [comment]
Hmm okey?
I think its a little bit creepy when you're getting text messages from unknown clients, which are not even within your channel :)
