### ISSUE TITLE
Problems with starting TS srv, on new server.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#195]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.35-b4

## Issue
***Reason for reporting this issue***:
Problems with launching/starting TS3 server.

***Detailed Description***:
`./TeaSpeakServer: error while loading shared libraries: libasan.so.2: cannot open shared object file: No such file or directory`

**Comment by xRedFox** [comment]
I only know that this library refers to
https://github.com/google/sanitizers/wiki/AddressSanitizer
Probably @WolverinDEV did something wrong after last #182 issue xD

**Comment by xRedFox** [comment]
Try: sudo apt install libasan3

**Comment by MikkelDK** [comment]
It was installed...but didnt still helped.. so i did moved the TS files to new IP address (cuz problems with hoster..of wrongly setup network.. each 10 minutes disconnected/(server fake crash) :D

**Comment by WolverinDEV** [comment]
Oh fuck :D I forgot to put that out again.
But stay posivive. With this library i got nearly zero crashes. Without I'll had some crashes within my stress test :)

**Comment by MikkelDK** [comment]
@WolverinDEV  - No crash on the new server! :D (only small crash with mySQL about: Can't create more than max_prepared_stmt_count statements. but i did fixed it. :D

**Comment by WolverinDEV** [comment]
Fixed as well :)
