### ISSUE TITLE
Problem with starting TeaSpeakServer after reinstall.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#196]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.35b4

## Issue
***Reason for reporting this issue***:
Can't starting TeaSpeakServer.

***Detailed Description***:
Failed to determinate address type for "[::]" teaspeak
Could not stop server tick task!

How do i fix that? :D

**Comment by MikkelDK** [comment]
@WolverinDEV - Maybe you have some idea? 👍

**Comment by WolverinDEV** [comment]
Yes that's my fault.
I probably failed the default host setting. 
It's `0.0.0.0,[::]` for virtualserver host, but it should be `0.0.0.0,::`

**Comment by MikkelDK** [comment]
@WolverinDEV - is there a temporary fix. for could set virtualserver host to be: 0.0.0.0,:: via serverquery?

**Comment by WolverinDEV** [comment]
Fixed within the next build (Old (may set) properties would not change back)
