### ISSUE TITLE
Possible memory leak? | 1.1.35-beta-4 using much more RAM/CPU than 1.1.35-beta-3

### ISSUE THREAD

**Issue by M0V3** [TeaSpeak/TeaSpeak#197]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.35-beta-4

## Issue
On version 1.1.35-beta-3 TeaSpeak used about 300MB RAM and about 20% of 4 CPU Cores. (Maybe more, maybe less, it's just about what I remember)  
With version 1.1.35-beta-4 TeaSpeak is using about 1GB RAM and up to 65% of 8 CPU Cores. I had to upgrade the Container from 4 Cores and 512MB RAM to 8 Cores and 2GB RAM, since the Server would become unresponsive for Clients.  
I'm running 10 MusicBots, the ffmpeg processes are using about 0.7% CPU and 1.4% RAM each, which is perfectly fine.

For me it's not a problem to provide these resources but other users may have problems with that, especially when using a hosting service.
If you need more informations I'm happy to provide them.

**Comment by M0V3** [comment]
tbh it looks like there could be a memory leak.
After ~3h uptime the server uses about 1.8GB RAM, CPU usage didn't rise.

**Comment by MikkelDK** [comment]
I agree (now i'm running on dedicated server...which is not worth for me for run TS only) using 4GB out of 32GB. ^^

**Comment by WolverinDEV** [comment]
Yes one thing that causes that is the Debug library which was my fault that I did not excluded that. That's properly the cause

**Comment by WolverinDEV** [comment]
Fixed (removed the debugging library (Can may causes crashes, or better the current crash happen more often (im still researching the reason => still no result))
