### ISSUE TITLE
virtualserver_default_channel_group buggy?

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#199]
## System Information
***Operating System***: Linux 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
***TeaSpeak Version***: v1.1.35-beta-4 [Build: 1529242094]

## Issue
For some reason on all servers the virtualserver_default_channel_group is the same as virtualserver_default_channel_admin_group. I have to change each one to the real channel guest group manually

**Comment by WolverinDEV** [comment]
Is it after an update or does it also applies when you're creating a new server

**Comment by Bluscream** [comment]
I have no non-imported servers so i can only confirm it for snapshotdeploy

**Comment by WolverinDEV** [comment]
Just create a new server for testing (I mean virtualserver)

**Comment by Bluscream** [comment]
It works fine for created servers

**Comment by WolverinDEV** [comment]
Okey well this properly causes by the fact that on serversnapshotdeploy the group does not get mapped right

**Comment by WolverinDEV** [comment]
Fixed within the next build :)

**Comment by Bluscream** [comment]
Awesome >(
