### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#2]
Do you think in the future it would be possible to host a TeaSpeak server for free on Heroku (maybe in connection with a free mysql/maria-db)

**Comment by WolverinDEV** [comment]
Hello,
well i never heard about "Heroku". But i already planned mysql/maria-db support.

**Comment by Bluscream** [comment]
>Heroku is a cloud platform as a service (PaaS) supporting several programming languages that is used as a web application deployment model. Heroku, one of the first cloud platforms, has been in development since June 2007, when it supported only the Ruby programming language, but now supports Java, Node.js, Scala, Clojure, Python, PHP, and Go.[1][2] For this reason, Heroku is said to be a polyglot platform as it lets the developer build, run and scale applications in a similar manner across all the languages. Heroku was acquired by Salesforce.com in 2010 for $212 million.[3]

source: https://en.wikipedia.org/wiki/Heroku

**Comment by WolverinDEV** [comment]
Hmm interisiting project, but not compatible with TeaSpeak.
The TeaSpeak-Server was/is written in C++ :)
TeaSpeak is also not a open source project so i think a release/compatibility with Haroku would never happen.

**Comment by Bluscream** [comment]
Thanks for your opinion :)
