### ISSUE TITLE
Crash again?

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#200]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.35-b6

## Issue
***Reason for reporting this issue***:
Seems it crash after update has been installed. and run few hours.

***Detailed Description***:
Dump: [dump.zip](https://github.com/TeaSpeak/TeaSpeak/files/2114347/dump.zip)
Log: [log.zip](https://github.com/TeaSpeak/TeaSpeak/files/2114349/log.zip)

**Comment by MikkelDK** [comment]
@WolverinDEV (assigned) ^^

**Comment by WolverinDEV** [comment]
Hey,
this is the same crash as you already reported before.
Its because somewhere the program enters a undefined behavior which causes them to crash a few seconds/minutes or even hours later.
Im already searching for that (the last two weeks)

**Comment by MikkelDK** [comment]
Noted @WolverinDEV - lets hope it can be fixed! :D

**Comment by WolverinDEV** [comment]
I'll close this issue and referee to #194
