### ISSUE TITLE
TS Server - CPULeak 1core 100%.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#201]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.35b6

## Issue
***Reason for reporting this issue***:
Seems there is a CPU leak on 100% using (1core)
only 7 users is on the TS server.

***Detailed Description***:
![](https://i.gyazo.com/fb7b728a519641bb2b404ff9e98b00bb.png)
CPU Leak?

**Comment by MikkelDK** [comment]
A reboot of ./teaspeakserver did helped! :-) but it was odd, since it did used 100% CPU anytime. :)

**Comment by WolverinDEV** [comment]
Hmm shit i cant recover which thread caused the fail.
Next time could you may activate Thread names?

**Comment by WolverinDEV** [comment]
Okey i got the error.
Someone tried properly to upload a snapshot (there was a little bug)
