### ISSUE TITLE
virtualserver_uptime wrong in serverlist

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#203]
The `virtualserver_uptime` property seems to be wrong for stopped servers in the response of the `serverlist` command.

![grafik](https://user-images.githubusercontent.com/3318223/41654018-9274d4d0-7477-11e8-9f6d-1ab8c66f0bfe.png)

- [ ] Stop and reset the `virtualserver_uptime` when a virtualserver was stopped.

**Comment by WolverinDEV** [comment]
Fixed within the next build. 
And please stop using checkboxes for only one item
