### ISSUE TITLE
Server management (create | delete) crashes server

### ISSUE THREAD

**Issue by WolverinDEV** [TeaSpeak/TeaSpeak#204]
## System Information
***Operating System***: any
***Operating System Type*** (x86|x64): 64
***TeaSpeak Version***: any

## Issue
***Detailed Description***:
Any management can cause a undefined behaver. 
Its not tested if its still in use etc.

**Comment by WolverinDEV** [comment]
Should be fixed within 1.1.36 :)

**Comment by MikkelDK** [comment]
Nice! i will test tomorrow. :_D
