### ISSUE TITLE
crash? or is it same crash from before?

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#205]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.36-b5

## Issue
***Reason for reporting this issue***:
The server did crash until 18:xx something, and didnt noted the srv was crashed (first checked now 20:25) - my question is, about the "crash" is same issue from the old issues on github. and crashed again after few minutes.

***Detailed Description***:
Dumpfiles: 
[63531471-52d5-46b0-10e3e4b1-5036b4d8.dmp.zip](https://github.com/TeaSpeak/TeaSpeak/files/2131089/63531471-52d5-46b0-10e3e4b1-5036b4d8.dmp.zip)
[crash_dump_18743efc-29de-48a3-3e8f1a8c-484f4709.dmp.zip](https://github.com/TeaSpeak/TeaSpeak/files/2131090/crash_dump_18743efc-29de-48a3-3e8f1a8c-484f4709.dmp.zip)

**Comment by MikkelDK** [comment]
@WolverinDEV

**Comment by WolverinDEV** [comment]
Hmm seems to be a similar crash, but its properly caused by another bug.
Well did it took longer until it crashed or is it just the same thing like before?

**Comment by MikkelDK** [comment]
Seems. since 12:21 and until now. :)

**Comment by MikkelDK** [comment]
I know we can not give a guarantee of being able to run a stable server. // It just not everyone who understands it. (not even those who have got a free TS of me lol)

**Comment by WolverinDEV** [comment]
Yes i know that feeling.
A lot of guys thinks thats really easy to do something high performance and still really stable.

Well i think it may again the same error as i fixed (but just in another point/case)

**Comment by MikkelDK** [comment]
Yeah. people "thinking: Oh this server is TeamSpeak" emm.. Nope. it's (called: TeaSpeak) and i can't give guarantee for stable... (as what i said to teams and private m8s: Just find a another provider.. i'm just running THIS service free)..and of course...i just wanna to support TeaSpeak project! :-)

**Comment by xRedFox** [comment]
@MikkelDK same here :D

**Comment by WolverinDEV** [comment]
Hey does it may be fixed within beta 37?
I found a possible bug which could cause this crash.

**Comment by MikkelDK** [comment]
Hi.

Not tested yet. But will update it pretty soon. Since i have vacation, so
easy free test. :D

I will update it about few minutes, and keep you Update, if it crash after
few days. :)

ons. 27. jun. 2018 07.53 skrev WolverinDEV <notifications@github.com>:

**Comment by WolverinDEV** [comment]
Take your time.I'm also running a bigger server and since I updated it jester day it's still online. I also improved a lot of things (forget to upload the ChangeLog.md) but trust me there a lot of improvements also within performance.And I hope it will be stable before I'm on a tree week vacation.

**Comment by MikkelDK** [comment]
I did updated it. seems running smooth, but i will still keep update, if i find something crash again! :-) - More so we can be sure, before we can "call it 'maybe stable' :-)"

**Comment by MikkelDK** [comment]
Seems it did stuck/crashed for me. i have uploaded dmp file.
dump: [dump.zip](https://github.com/TeaSpeak/TeaSpeak/files/2140669/dump.zip)

**Comment by WolverinDEV** [comment]
Hmm shit :)
Well  do you delete server frequently and does it happens when you delete server or is it a general issue?

**Comment by MikkelDK** [comment]
it was just general issue.

Now i need to find new provider, cuz network issue (disconnecting on TS srv+SSH) and the network is dropped.. (i wont think it's does has todo with TS server.. but just sad.. support wont will fix lol!)

`RX errors 0  dropped 10680  overruns 0  frame 0` (as example)

**Comment by xRedFox** [comment]
-- **Off-Topic** --
@MikkelDK https://contabo.com/?show=vps

**Comment by MikkelDK** [comment]
**-- Off-Topic --**
@xRedFox Do you use them? - My (old provider) was livingbots.

**Comment by xRedFox** [comment]
-- **Off-Topic** --
Yep, I've been with them for more or less 2 months. I've never had problems like service interruption, DDOS attack or things related to the system. They have a wide range of operating systems available and the important thing is that they offer possibility to change your vps ip (in case teamspeak decide to blacklist your ass). Very low prices for the quality they offer. Efficient, effective and kind support. Among all the services I've tried this is definitely the best.

**Comment by MikkelDK** [comment]
**-- Off-Topic --** @xRedFox 
Is there someway, i can contact you? - since i have few small question, about the Contabo. 👍

**Comment by xRedFox** [comment]
-- **Off-Topic** --
Uhm, actually I'm really busy with work n stuff (I also want to get into the Italian Air Force so I'm studying and working a lot) so I'm never at home.
if you want to find me somewhere else I'm available on telegram with tag @redrainbow or you can email me at blurio90@gmail.com.
Otherwise ask me here and hope that @WolverinDEV will not put an end to us and our Off-Topic ahahahaha.

PS: I received your email, I'll answer you as soon as I can

**Comment by WolverinDEV** [comment]
Guys come one.
Please move this off topic to a private platform.
You also could use the pm function within the Teaspeak forum. 

:)

**Comment by MikkelDK** [comment]
I will close this. Since it seems fixed. :) Sorry @WolverinDEV

**Comment by WolverinDEV** [comment]
Uhh that sounds incredible. May it's now nearly stable

**Comment by MikkelDK** [comment]
@WolverinDEV no crash at all. 10/10 for the new update. 👍
