### ISSUE TITLE
bug? server just stuck.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#206]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.37-b1

## Issue
***Reason for reporting this issue***:
malloc(): smallbin double linked list corrupted

***Detailed Description***:
What does the issue means. the malloc?

**Comment by WolverinDEV** [comment]
Haha server crash again... I already found one. In this case within the query system.
If you flood it the server crashes. But for the voice clients it seems stable :)

**Comment by MikkelDK** [comment]
Oh. i see.. weird. :-D so it does nothing to have with networkloss..where all will be disconnected?

**Comment by WolverinDEV** [comment]
When you see that message it means that the heap memory i corrupt and the server is fucked up ;(

**Comment by WolverinDEV** [comment]
Could you test again?
I'm not getting crashed anymore when im testing it on my local pc (basically i just tested the query, but that was (i guess) the trigger for the crash)

**Comment by MikkelDK** [comment]
I did shutdown the TS server since 08 > but i have updated it, and boot it up.. So i will see, about it works. :-)

Since it's nothing has to-do with TeaSpeak. but i think i has some "network loss issues" with DCs. so i can first move to new DC, once sunday. :-)

**Comment by WolverinDEV** [comment]
Oh thats really wired with you're network loss issue, but good luck

**Comment by MikkelDK** [comment]
new bug found! @WolverinDEV - so soon you connect to query via YATQA = crash.

**Comment by WolverinDEV** [comment]
Do you have a crashlog for me?
It doesnt happen for me

**Comment by MikkelDK** [comment]
Fun. Now it works and no crash. :)
