### ISSUE TITLE
server version is too old for command

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#207]
## System Information
***Operating System***: ArchLinux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.37 beta 1

## Issue
***Reason for reporting this issue***:
Critical

***Detailed Description***:
Cannot connect to server with **3.2.0 client** version
```
<14:25:29> Trying to resolve hostname support.thebunny.eu
<14:25:29> Trying to connect to server on support.thebunny.eu
<14:25:29> Disconnected from server (server version is too old for command)
```

**Comment by WolverinDEV** [comment]
Yes TeamSpeak dropped the support for the old protocol.
We have to wait untill the patch is up again.

**Comment by WolverinDEV** [comment]
Moved out to here: [click me](https://forum.teaspeak.de/index.php?threads/teaspeak-update.199/page-3#post-1290)
