### ISSUE TITLE
Disconnected Client (server version is too old for command)

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#209]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.37-beta-2

## Issue
***Reason for reporting this issue***:
Client version TeamSpeak 3.2.0[Beta]

***Detailed Description***:
Client version TeamSpeak 3.2.0[Beta] 

disconnected Client (server version is too old for command)

**Comment by M0V3** [comment]
https://github.com/TeaSpeak/TeaSpeak/issues/207

**Comment by MikkelDK** [comment]
duplicated of #207
