### ISSUE TITLE
Add server side plugin engine | Feature Request 

### ISSUE THREAD

**Issue by VerHext** [TeaSpeak/TeaSpeak#21]
## Feature
- add server side plugin engine.

***Detailed Description***:
A plugin engine, thats allow to developed plugins for the server. Example a "Afk Mover".
that move clients into a channel. In the moment it is only avaibel with a bot. But server side is mutch better.

**Comment by WolverinDEV** [comment]
Hey,
i already thought about a pretty cool API, but i think that would take a long time.
I think the earliest implementation would take over 6 Months

**Comment by Newcomer1989** [comment]
The idea is good, cause it should be much faster to give the server directly the things to run as to give an API (ServerQuery) commands and that will interpret an run the thing.

But is it really needed?

I think the profit is to small and so the amount of work which is required is disproportionate.

**Comment by Chazotu** [comment]
Cause of the server query complexity it will not be implemented in the next future.
