### ISSUE TITLE
[INFO] voice.protocol.experimental  ?

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#212]
## System Information
***Operating System***: Debian 9.4
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.38-beta1

## Issue
***Reason for reporting this issue***:
what is the purpose of this feature add voice.protocol.experimental it's for the new voice.protocol for the client version 3.2.0

**Comment by WolverinDEV** [comment]
Well this feature isn't new.
It's for the 3.1 protocol with the new crypto handshake. 
The new thig is that I added support to define own keychains fore more flexibility.

**Comment by Home-Network** [comment]
ok but that does not change anything because we still can not connect to the server with 3.2.0 client version it does not work, we tested me and LuckyPGM do not understand how it works.

how to connect to the server with client version 3.2.0 with the new protocol ? ........

**Comment by xRedFox** [comment]
@Home-Network #207
