### ISSUE TITLE
disconnect bug? [Question]

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#213]
## System Information
***Operating System***: Any
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: Any

## Issue
***Reason for reporting this issue***:
People disconnecting from TeaSpeak Server (and i wont disconnect?)

***Detailed Description***:
Few friends reporting, they has been disconnected from the server(timeout) where the server hasn't been crashed and there hasn't been problems with network. (I have tested from my laptop. and has been online 2 days without crash or disconnect.)

is there someway i can prevent that can be happened again?

**Comment by WolverinDEV** [comment]
Close this because of the duplicated (other thread is more detailed)
