### ISSUE TITLE
[INFO]: TS3 Reverse URL Binary Client

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#215]
## System Information
***Client Version***: TeamSpeak-3.2.0
***Operating System Type*** (x86|x64):  x64

## this can be used for the experts^^

***versions LINK***
http://versions.teamspeak.com/ts3-client-2

***ts3services LINK***
https://ts3services.teamspeak.com/revocation-myteamspeakid
https://ts3services.teamspeak.com/revocation-certificates
https://ts3services.teamspeak.com/static_integration_info

***clientapi LINK***
https://clientapi.myteamspeak.com/synchronization
https://clientapi.myteamspeak.com/authentication
https://clientapi.myteamspeak.com/session
https://clientapi.myteamspeak.com/addon
https://clientapi.myteamspeak.com/user
https://clientapi.myteamspeak.com/integration

***Other LINK***
https://blacklist2.teamspeak.com/check
https://named.myteamspeak.com/
https://badges-content.teamspeak.com/list
http://news.teamspeak.com
http://statistics.teamspeak.com
https://weblist.teamspeak.com

**Comment by WolverinDEV** [comment]
Uhh some links looks interesting.
Specifically the https://ts3services.teamspeak.com/static_integration_info, i have never heard about that.
May create a thread within the forum with all URL's which TeamSpeak calls and e.g. with the result and a little explanation

**Comment by Chazotu** [comment]
Moved to https://forum.teaspeak.de/index.php?threads/ts3-reverse-url-binary-client.282/
