### ISSUE TITLE
[INFORMATION]: experimental_31 :1 

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#216]
## System Information
***Operating System***:  Debian 9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.38 beta 5

## Issue
***Reason for reporting this issue***:

when i set experimental31 to 1 , nothing works anymore.

***Detailed Description***:
Why when i set experimental31 to 1 , no  one can connect anymore ? 
i received message : 

Failed to connect server for everyone who try to join the server ?

I seen it's write ( require a plugin ) in the config.yml comment . 

How to enable experimental31 to 1 and allow players to join my teaspeak ? 

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Hey,
I thing the discussion within the forum about 3.1 and the new 3.2.0 client is more detailed
