### ISSUE TITLE
b_client_ignore_antiflood

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#218]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.38 

## Issue
***Reason for reporting this issue***:

I got ban even with the permission b_client_ignore_antiflood enabled. 

***Detailed Description***:
I got banned some times and i have the permission ignore antiflood . reason of ban : You're flooding too much. 

How to whitelist IP ? or people ? 

Cordialy

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Hmm okey?
Are your sure that no other permission negated or skiped that permission?

**Comment by WolverinDEV** [comment]
Hmm that sound really Strange. 
I'll test it as soon I have the possibilities for that.

**Comment by WolverinDEV** [comment]
Fixed within the next build I release soon (Notice I build that build from another pc and I don't have webrtc installed so the web client would not work!)
