### ISSUE TITLE
<01:56:53> insufficient client permissions (failed on b_client_use_bbcode_image)

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#219]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.38 beta 5

## Issue
***Reason for reporting this issue***:
I can't edit a channel with bbcode in decription i have the good right ( b_client_use_bbcode_image checked , grant 100. ) 

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Well which bb codes are you using?
This permission just allows you to use the `[img]` tag, but not all others

**Comment by lemignon** [comment]
the problem is : i have removed the description of the channel , so now i don't have bug anymore , but for sure a bug occur  lemme check if i can found the bbcode . i will update here .

**Comment by lemignon** [comment]
OK i found :)

**Comment by lemignon** [comment]
can you check on your support teaspeak plz
