### ISSUE TITLE
Add more infos to channelinfo

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#22]
- `created_at` which contains a unix timestamp of the creation time.
- `created_by` which contains either the invokers dbid or uid

**Comment by WolverinDEV** [comment]
Implemented in TeaSpeak 1.0.11-Beta
+ `created_by` -> Client db id (Visible in channel list & channel info)
+ `created_at` -> Unix timestamp (Milliseconds) (Visible in channel list & channel info)

**Comment by Bluscream** [comment]
Awesome, thanks :)
