### ISSUE TITLE
ServerQuery liefert nur "null" zurück anstatt der ID und "channel_icon_id" kann nicht geändert werden

### ISSUE THREAD

**Issue by dwwe2017** [TeaSpeak/TeaSpeak#224]
## System Information
***Operating System***: Ubuntu 14.04.5 LTS‬
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.38b

## Issue
Die folgenden Befehle via ServerQuery liefern lediglich "null" zurück anstatt der erwarteten id (int):
- channelgroupcopy
- servergroupcopy
- channelcreate

Des Weiteren wird eine Änderung der Channel-Eigenschaft "channel_icon_id" mittels "channeledit" via ServerQuery nicht übernommen.

**Comment by WolverinDEV** [comment]
Fixed within the next build
