### ISSUE TITLE
bbcode issue

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#226]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.39

## Issue
***Reason for reporting this issue***:

Can't modify description with bbcode in . even with all rights  ( you can create  a channel with the following bbcode ) but once created can't modify the description if you keep the current description ( add a character or a new string ... ) .

***Detailed Description***:

[center][b]test.com[/b][/center]

[color=#ff0000]the only [/color][color=#3399ff]way ![/color]

[url]test.com[/url]

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by MikkelDK** [comment]
@lemignon - Try check > #219

**Comment by WolverinDEV** [comment]
You have the permission i_client_bbcode_any?

**Comment by lemignon** [comment]
of course . You can come my teaspeak to check and see yourself . try to modify a channel permission on the bottom of the teaspeak by adding character and check your group permission and other you will see everything is correct .

**Comment by lemignon** [comment]
since last update , the Query bot's don't works anymore ?

**Comment by WolverinDEV** [comment]
Should work again.
I'll test it with the bb codes

**Comment by WolverinDEV** [comment]
Well for me the bbcode stuff works.
I changed the channel description to the given above.
I was server admin and had the permission `b_client_use_bbcode_url` (nothing else)
Without `b_client_use_bbcode_url` or `b_client_use_bbcode_any` the edit would fail.
I use the last version

**Comment by daffyyyy** [comment]
Same problem, i  have problem with save description with  [/url]

**Comment by daffyyyy** [comment]
> Please describe a detailed way how to reproduce it.
> Try it with a fresh and new TeaSpeak setup.
w8 im uplading vid

**Comment by WolverinDEV** [comment]
Mad you hadn't added the permission because you haven't granted permission.
You probably imported that server. Its already fixed, but you still have to grant the permission.

**Comment by daffyyyy** [comment]
> Mad you hadn't added the permission because you haven't granted permission.
> You probably imported that server. Its already fixed, but you still have to grant the permission.

Second server on has all permissions from bbcode and nothing can be save with [/url]
First server installed yesterday

**Comment by WolverinDEV** [comment]
Oh i just saw that the permissions missing within my permission mapping file o.O
Youst give yourself server admin and try it again

**Comment by daffyyyy** [comment]
How can I fix it on a server where I have the required permissions but I can not use [/ url]?
My group have 100 grant permissions on alll perms, but i can't use ]/url] when channel edit

**Comment by WolverinDEV** [comment]
If you checked `b_client_use_bbcode_url` you can!

**Comment by daffyyyy** [comment]
Yes, when i unmark and mark again, it works
