### ISSUE TITLE
can't connect anymore

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#227]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.39-beta

## Issue
***Reason for reporting this issue***:

clients can't connect anymore : error message : Unknown property client_active_integrations_info
this happened just after i did an new client update for teamspeak client 3.2.0 .

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Well seems like you activated something within your client.
In general it's possible

**Comment by lemignon** [comment]
it was working well , then i updated my teamspeak client to latest update from beta channel ( released yesterday ) and since i did update i can't connect anymore i have the error : Unknown property client_active_integrations_info that's all i did .

I also tryed to come back 38 beta 5 but result is the same. so it's because of the latest client update or so

**Comment by WolverinDEV** [comment]
Fixed within the next build
