### ISSUE TITLE
Bekahm durch TokenUse die Server Admin Vorlagen gruppe??

### ISSUE THREAD

**Issue by MypowerHD** [TeaSpeak/TeaSpeak#229]
## System Information
***Operating System***: Debian 9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.40-beta

## Issue
***Reason for reporting this issue***:
Kann die gruppe mir nicht über ServerQuery entferenen da ich angeblich nicht in der Gruppe bin.
![93ba99b3122369b864eb9734d3b57422](https://user-images.githubusercontent.com/10728025/42756507-b39597dc-88fc-11e8-91f7-e1f600a2e83d.png)

![7669edb23414192937c31658eddefb3d](https://user-images.githubusercontent.com/10728025/42756535-db9de50e-88fc-11e8-8e54-7f2e29e0f00f.png)

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
You may assigned the group globally and try to remove it just locally or vise versa

**Comment by WolverinDEV** [comment]
Fixed within the next build
