### ISSUE TITLE
Crashed when adding ban

### ISSUE THREAD

**Issue by daffyyyy** [TeaSpeak/TeaSpeak#230]
## System Information
***Operating System***: debian9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***:
1.1.39-beta
Packed version: 4
## Issue
***Reason for reporting this issue***:
Application crashed

***Detailed Description***:
When I tried to add a ban by admin server query, the server was crashed.
Log: https://pastebin.com/erHifyyT
.dmp: https://www89.zippyshare.com/v/C6TviMHO/file.html

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Fixed within the next build
