### ISSUE TITLE
Cannot ban client via admin server query

### ISSUE THREAD

**Issue by daffyyyy** [TeaSpeak/TeaSpeak#231]
## System Information
***Operating System***: debian9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: last

## Issue
***Reason for reporting this issue***:
The fix does not fulfill its role

***Detailed Description***:

> [2018-07-17 01:19:01] [TRACE] QUERY | [167.114.227.107:43678] Got query command banclient clid=1 time=60 banreason=1dsad
> [2018-07-17 01:19:01] [TRACE]     1 | [167.114.227.107:43678/daffyy - WWW][Command][Client -> Server] Processing command: banclient clid='1' time='60' banreason='1dsad'
> [2018-07-17 01:19:01] [DEBUG]     1 | [Permission] Value test result for test type 1.
> [2018-07-17 01:19:01] [DEBUG]     1 | [Permission]    Permission: i_client_ban_power Required value: 1 Gained value: 100 Force required: 1 Channel: none Result: 1
> [2018-07-17 01:19:01] [TRACE]     1 | [167.114.227.107:43678/daffyy - WWW][Command] Command banclient with return code <undefined> fails and returns error code 0x0200. Properties: {extra_msg = Could not find target client}

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Well was the client online or not?

**Comment by WolverinDEV** [comment]
Sorry my fault I forgot a '!'
Should be fixed :)
