### ISSUE TITLE
Clientinfo additional property

### ISSUE THREAD

**Issue by daffyyyy** [TeaSpeak/TeaSpeak#235]
## System Information
***Operating System***: Debian9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: last

## Issue
***Reason for reporting this issue***:
Im working on web statistics for clients. 

***Detailed Description***:
User connection Time assigned to clientinfo. 
Teamspeak3 has  [connection_connected_time] 
*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Implemented within the last version :)
