### ISSUE TITLE
First start error: bbcode_img

### ISSUE THREAD

**Issue by Sporesirius** [TeaSpeak/TeaSpeak#237]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64):
***TeaSpeak Version***: v1.1.40-beta

## Issue
***Reason for reporting this issue***:
If you start the server for the first time with teastart_minimal.sh you get this error:
[CRITICAL] Could not resolve permission id for b_client_use_bbcode_img

***Detailed Description***:
Reproduce:
Start TeaSpeak with teastart_minimal.sh the first time.

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Uh seems to be a invalid setup permission.
I'll fix that

**Comment by WolverinDEV** [comment]
Fixed :)
