### ISSUE TITLE
.help doesn't work and neither does .mbot yt <anything>

### ISSUE THREAD

**Issue by ike2117** [TeaSpeak/TeaSpeak#238]
## System Information
***Operating System***: Linux 16.04 LTS
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: TeaSpeak 1.1.40-beta

## Issue
***Reason for reporting this issue***: Whenever I do .help, I get "invalid manager id" and when I try playing a song with .mbot yt it says that youtube-dl isn't the default search

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by xRedFox** [comment]
can you please provide us your logs file?

**Comment by WolverinDEV** [comment]
Any updates?

**Comment by WolverinDEV** [comment]
Closed because of inactivity
