### ISSUE TITLE
Crash on serversnapshotdeploy

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#239]
## System Information
***Operating System***: Debian 9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.40-beta-9 

## Issue

[crash_dump_432abcd1-99b1-435f-8c3b3f86-c527fbdd.dmp.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2214717/crash_dump_432abcd1-99b1-435f-8c3b3f86-c527fbdd.dmp.tar.gz)

**Comment by WolverinDEV** [comment]
Important point:
This just happens when you override a server with a snapshot!

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
