### ISSUE TITLE
Unable to Download from teaspeak.de:443

### ISSUE THREAD

**Issue by Newcomer1989** [TeaSpeak/TeaSpeak#24]
Your download link seems to be wrong or webserver is wrong configurated!

https://repro.teaspeak.de/server/linux/x64/TeaSpeak-1.0.11-beta.tar.gz

Got your IP address resolved -> 87.106.252.164 but no connection to download that stuff from port 443.

**Comment by WolverinDEV** [comment]
i got fucked up :D
I fixed that, forgot that i changed to https :)
