### ISSUE TITLE
Crash on permreset

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#240]
Operating System: Debian 9
Operating System Type (x86|x64): x64
TeaSpeak Version: 1.1.40-beta-9

## Issue
[dump.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2214894/dump.tar.gz)

**Comment by WolverinDEV** [comment]
Hmm this error seems really strange.
I'll test it later. It may take some time because of I'm still in holiday :=)

**Comment by WolverinDEV** [comment]
Should be fixed but not 100% sure
