### ISSUE TITLE
Channel permissions are buggy/dont functionally

### ISSUE THREAD

**Issue by EnderPixel** [TeaSpeak/TeaSpeak#241]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64):
***TeaSpeak Version***:

## Issue
***Reason for reporting this issue***:
The channel permissions are buggy/dont functionally

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by MikkelDK** [comment]
You need to give us more details. :)

tir. 24. jul. 2018 13.08 skrev EnderPixel <notifications@github.com>:

**Comment by EnderPixel** [comment]
When i change the poke permissions on 200 then it dont work. I can poke the client still.

**Comment by xRedFox** [comment]
https://github.com/TeaSpeak/TeaSpeak/blob/master/documentation/dataflow_calculate_permissions.png

**Comment by EnderPixel** [comment]
ok thanks

**Comment by WolverinDEV** [comment]
I thing its quite stupid to implement channel permissions.
For example: The client icon id is just a calculation of permission.
Now thing that youre in a channel wher's an icon id set so you would get that icon as well

**Comment by EnderPixel** [comment]
its not stupid when you make a afk not poke channel

**Comment by EnderPixel** [comment]
but its not working when i set the needet poke permission on 200

**Comment by WolverinDEV** [comment]
Isn't it the *only* one application for that?

**Comment by EnderPixel** [comment]
for me yes i dont need it for anything else

**Comment by EnderPixel** [comment]
*for me it is the only application

**Comment by WolverinDEV** [comment]
Implemented within the next version :)
