### ISSUE TITLE
Several Bugs

### ISSUE THREAD

**Issue by capsload** [TeaSpeak/TeaSpeak#244]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
3. Setting to apply '....'

**Expected behaviour**

**Screenshots**

**Logs**

**Environment information:**
 Operating system: 3.13.0-147-generic #196-Ubuntu SMP Wed May 2 15:51:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.1.40-beta-2]

**Additional context**

If you use the default Token created when you make a new Server, you'll receive "Server Admin" as Group.
After that, you can give yourself "Server Admin" Group (the same) again. You are in the group twice, you cant remove the Second Group by yourself.

<15:36:36> "-Nikoladiv" wurde von "Nikoladiv beTa" zur Server Gruppe "Server Admin" zugewiesen.
<15:36:40> "-Nikoladiv" wurde von "-Nikoladiv" zur Server Gruppe "Server Admin" zugewiesen.

I started two musicbots at the same time with permanent music playing:

- on the fresh created teaspeak server, music still plays
- on the yatqa-restored 3.0.18 server, bot is not playing anymore > but in the webcontrol everything is ok and "playing". Sound is just not coming through somehow

**Comment by WolverinDEV** [comment]
If cause.
You can remove the group by yourself (You have to do that twice :))

**Comment by capsload** [comment]
I can only remove "Server Admin", but then i still have the first Server Admin, but its already unchecked when i right click on the Name > Groups.

**Comment by WolverinDEV** [comment]
Well idk why YatQA does not show that, but telnet terminal its possible :)

**Comment by WolverinDEV** [comment]
A smal update: I had a little issue.
I gave the serveradmin template group and not the actual server admin.
Is fixed within the next version :)
