### ISSUE TITLE
No sound after some time

### ISSUE THREAD

**Issue by WolverinDEV** [TeaSpeak/TeaSpeak#245]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new VS and one VS from snapshot
2. Start two music bots. The VS from snapshot will be silent after some time

**Expected behaviour**
Music bot plays a cerain time, and the VS snapshot music bot will be silent after some time

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: debian
 TeaSpeak version: Newest (Not 1.2.0)

**Additional context**

**Comment by capsload** [comment]
1.2.0 still has that bug!

**Comment by WolverinDEV** [comment]
Yes i know.
Here is nowhere the message that its fixed :)

**Comment by WolverinDEV** [comment]
Fixed in 1.2.1 :)
