### ISSUE TITLE
Permission limiting the amount of temporary channels existing, created by the same user

### ISSUE THREAD

**Issue by Ghostium** [TeaSpeak/TeaSpeak#247]
**Is your feature request related to a problem? Please describe.**
Problem: I allow my Teamspeak users to create temporary channels. Making them permanent increases the engagement of the user and makes it more likely that he sticks to my server. However, this is a manual task which I wish to automate. An alternative I tried to make use of the delayed deletion of temporary channels feature. Unfortunately this was abused heavily by a single user, who filled the channel tree with spam channels. 

Feature: Adding a permission limiting the max amount of temporary channels which can exist at the same time created by the same user will alleviate this problem.

**Describe the solution you'd like**
A new client permission like ```i_channel_create_temporary_maxamount```.

**Describe alternatives you've considered**
I don't know any alternatives besides permanent channels which require a heavy administrative burden.

**Additional context**
None.

**Comment by WolverinDEV** [comment]
Implemented within the next version :)
