### ISSUE TITLE
Log views terrible

### ISSUE THREAD

**Issue by Newcomer1989** [TeaSpeak/TeaSpeak#25]
## System Information
Ubuntu 17.10 x64
TeaSpeak-Server v1.0.11-beta

## Issue
There seems to be signs inside the log, which are not needed.
A colored view is a good thing for an online view to a log, but a real log file has to be clear (IMHO)!

The following view is a screenshot of a default configurated vi editor.
![image](https://user-images.githubusercontent.com/11364569/34650140-21184560-f3bc-11e7-915f-b1293951bc3d.png)

**Comment by WolverinDEV** [comment]
Please read/view the last 2 options in the config.yml :)

**Comment by Newcomer1989** [comment]
Ok, my bad.. Perhaps it should be at default without color things to prefer new reports.

**Comment by WolverinDEV** [comment]
Hmm maybe. You view the log with putty right?
Under ubuntu the log (if you `cat` it)  file is still colored :)

~ Edit ~
Changed the default value to false

**Comment by Newcomer1989** [comment]
How to disable it inside the config.yml?
If I remember right it were on default `1`
I changed it to 0, now no logs will be written!
What value is valid?   `disabled`, `0`, `false`, `no`, `off`
Is there a check for valid values?

**Comment by WolverinDEV** [comment]
Probably 0 ist the right way
And are you sure? That's one of the parts where I'm sure that they works stable

**Comment by Newcomer1989** [comment]
I changed at the same moment the Debug Level to `level: 2` and this was the problem.
Now I changed the Debug Level to default `level: 1` a log will be written and with `colored: 0` there are not signs to color the things.

So colored function is working, but your debug level seems to be buggy.

**Comment by WolverinDEV** [comment]
Are you shure that you changed the log file debug and not the Terminal Message debug?

**Comment by Newcomer1989** [comment]
Yes, I am sure.. That mistake I did only once^^

It is definite the level under the log: area.

**Comment by WolverinDEV** [comment]
A little question: What you mean with signs to color thinks? May that you're able to re colorize the log with ascii colors or what?

**Comment by Newcomer1989** [comment]
With the signs I am meaning the ASCII Codes, which you are using to color the Debug-Level inside the logfile.

**Comment by WolverinDEV** [comment]
Yep but when you disable the colorization the log file should be plain and without ascii codes.
And as far as i know is that functional already

**Comment by Newcomer1989** [comment]
Yes, and as I already wrote:

So colorization of the log is working, but the debug level seems to be buggy.
Changing debug level -> no logging any more
