### ISSUE TITLE
Max ping and packetloss

### ISSUE THREAD

**Issue by Sporesirius** [TeaSpeak/TeaSpeak#251]
The possibility to change the max ping and packetloss value?
if the value is reached, a kick occurs, for example.

Example:
i_client_max_ping
i_client_max_packetloss <0-100%>?

**Comment by WolverinDEV** [comment]
Why should this be possible?

**Comment by Sporesirius** [comment]
it can happen that people have a too high ping and you don't want them on the server or the exact opposite is the case.

**Comment by WolverinDEV** [comment]
I think it does not really matter how high/or low a client's ping is.
Specially not then they have the possibility to get kicked for stuff they cant influence

**Comment by xRedFox** [comment]
@Sporesirius just ban them 🗡

**Comment by Bluscream** [comment]
Thats actually a great idea, but more for a bot not integrated

**Comment by xRedFox** [comment]
hahah this thread has been closed so brutally XD

**Comment by Sporesirius** [comment]
:D
