### ISSUE TITLE
Music Bot Error

### ISSUE THREAD

**Issue by Chazotu** [TeaSpeak/TeaSpeak#253]
**Describe the bug**
When running the .mbot yt <video url> the Song is not Playing

**Expected behaviour**
The Music Bot Should Play the Song

**Error Mesage**
https://pastebin.com/xYjxEy7r

**Environment information:**
 Operating system: (`Debian 9.5.0)
 TeaSpeak version: [TeaSpeak 1.2.1-beta]

**Comment by WolverinDEV** [comment]
This is a youtubedl error
