### ISSUE TITLE
2 servers 1 port (quote)

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#255]
**Describe the bug**
Remove the possibility to create more servers on the same port

**Expected behaviour**
You know :)

**Screenshots**
![nice](https://user-images.githubusercontent.com/19707386/43687729-cbaf9726-98da-11e8-956f-9fcbe450cd23.PNG)

**Environment information:**
 Operating system: (`uname -a`)
 TeaSpeak version: [TeaSpeak-1.1.40-beta-1]

**Comment by WolverinDEV** [comment]
Fixed within the next version
