### ISSUE TITLE
Turning Push-To-Talk on, "force-push-to-talk" permission was assigned. (?)

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#258]
**Describe the bug**
Turning Push-To-Talk on, "force-push-to-talk" permission was assigned. (All TS3 Servers) is now force-push-to-talk after updating.

**Expected behaviour**
Updated the TS3Server to new version > and all TS virtualserver has now the issue with: Turning Push-To-Talk on, "force-push-to-talk" permission was assigned.

**Environment information:**
 Operating system: Debian 9.5
 TeaSpeak version: [TeaSpeak-1.2.2-beta-2]

**Additional context**
Is there someway to fix the "Turning Push-To-Talk on, "force-push-to-talk" permission was assigned." to all servers...seems i need to edit on each virtualserver manually.

**Comment by Chazotu** [comment]
Please Clear you Cache Folder of your Teamspeak Client

**Comment by MikkelDK** [comment]
Works! ;) i will tell my friends about it! ;)

**Comment by MikkelDK** [comment]
A little update: I have tryed on my client-side.. it works. but for others it wont works ;/

**Comment by Chazotu** [comment]
They also have to all clear their cache.

**Comment by MikkelDK** [comment]
Update:

Clear Cache wont helps...the issue is only on Windows. OSX/Android don't have the issue.. what can i do so? ;)

**Comment by WolverinDEV** [comment]
1. Close TeamSpeak
2. Open explorer and browse to the TeamSpeak cache folder (`%APPDATA%\TS3Client\`)
3. Delete the `cache` folder (or the `perm.dat` from the specific TeaSpeak server)
4. Start TeamSpeak again and try it :)

**Comment by MikkelDK** [comment]
//Fixed from WolverinDEV.. - Closed ;)
