### ISSUE TITLE
Error - Log-Level

### ISSUE THREAD

**Issue by Newcomer1989** [TeaSpeak/TeaSpeak#26]
## System Information
Ubuntu 17.10 x64
TeaSpeak-Server v1.0.11-beta

## Issue
The log-level is default configurated inside the `config.yml` to level 2.
But inside the log-file, there will be shown all logs. Also debug entries.

And something like the following is surely a trace, not a debug ;-)

> [15:27:26] [DEBUG] [10.0.2.2:62970/Newcomer1989][Server -> Client][Command] Id '0/0' Command: notifyconnectioninfo clid=1 connection_client_ip=10.0.2.2 connection_client_port=64245 connection_client2server_packetloss_speech=0.000000 connection_client2server_packetloss_keepalive=0.000000 connection_client2server_packetloss_control=0.000000 connection_client2server_packetloss_total=0.000000 connection_idle_time=3847
> [15:27:26] [DEBUG] [10.0.2.2:62970/Newcomer1989][Server -> Client][Command] Id '0/0' Command: error id=0 msg=ok return_code=1:n

**Comment by WolverinDEV** [comment]
#25 
Please read/view the last 2 options in the config.yml

**Comment by Newcomer1989** [comment]
And all TCP packets are DEBUG, really?

**Comment by WolverinDEV** [comment]
Currently all Telnet|TCP and Voice|Udp are written in debug mode. You can disable the debug mode by changing the log setting in the config.yml. (I may change the protocoll logging to trace)

**Comment by Newcomer1989** [comment]
That's what I am thinking.. It should be TRACE. Only an error occured you could log the last few packets before.

**Comment by WolverinDEV** [comment]
Moved the protocoll to Trace :)
