### ISSUE TITLE
I don't have a description [remove via config?] [Idea]

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#261]
**Is your feature request related to a problem? Please describe.**
Remove "I don't have a description" on each new creating rooms.

**Describe the solution you'd like**
Possible for remove "I don't have a description" under creating rooms on virtualserver. maybe via config?

**Additional context**
![](https://i.gyazo.com/564e75356481f8b4543fc1d245931323.png)

**Comment by WolverinDEV** [comment]
Hey,
there are new server properties:
- `virtualserver_default_client_description`
- `virtualserver_default_channel_description`
- `virtualserver_default_channel_topic`

**Comment by MikkelDK** [comment]
Will i need to edit on the sqlite.. for forced remove the textversion? - since it's not possible insert that on query/yatqa. ;o

**Comment by MikkelDK** [comment]
@WolverinDEV -- where can i paste tehse properties? ;) 

```
virtualserver_default_client_description
virtualserver_default_channel_description
virtualserver_default_channel_topic
```

**Comment by MikkelDK** [comment]
@WolverinDEV seems it didnt works for me.

I did typed use port=9987 >> serveredit virtualserver_default_channel_description=lol > and it still force to: "I don't have a description" - i did too try and "set it blank" ;/

What can i do?

**Comment by WolverinDEV** [comment]
Its just changes for new channels not for all already created :)
(It may changes after a instance restart, but not sure)

**Comment by MikkelDK** [comment]
hmm.. nah didnt helped ;/

**Comment by MikkelDK** [comment]
@Bluscream I will try that! ;)

**Comment by batizisanya** [comment]
Hi, I tried to change but I failed. 

> TeaSpeak
> Welcome on the TeaSpeak ServerQuery interface.
> login "serveradmin" "***"
> error id=0 msg=ok
> use port=9987
> error id=0 msg=ok
> serveredit virtualserver_default_client_description=""
> error id=2568 msg=insufficient\sclient\spermissions failed_permid=66
 
In yatqa I just didn't find that perm.

**Comment by WolverinDEV** [comment]
In YatQA you have to use the server permission list :)

**Comment by batizisanya** [comment]
Well, I tried to find it, but I failed. Can you write the menu option, where can I find this?

**Comment by WolverinDEV** [comment]
goto web.teaspeak.de
connect to you server
right click on the server
click on edit
select the messages tab

**Comment by Bluscream** [comment]
> Well, I tried to find it, but I failed. Can you write the menu option, where can I find this?

![grafik](https://user-images.githubusercontent.com/3318223/44223592-8f2be980-a177-11e8-92d3-b6ec1f3fca30.png)

**Comment by batizisanya** [comment]
I could change it from web.teaspeak.de (Thx WolverinDEV)
@Bluscream In yatqa I pressed that (Use server's permission list) and than I tried to edit from the console, but the same response. 
![image](https://user-images.githubusercontent.com/16525148/44227262-75e46680-a192-11e8-9e43-3f78168ef228.png)
![image](https://user-images.githubusercontent.com/16525148/44227313-901e4480-a192-11e8-9059-36aa94a9d1f0.png)

**Comment by Bluscream** [comment]
You can always use the permgrant command in your server's teaspeak console to give yourself missing permissions from the lowest level possible

**Comment by batizisanya** [comment]
@Bluscream Huge thanks!

**Comment by MikkelDK** [comment]
Hey. 

How can i give meself permgrant?

[2018-08-18 23:35:54] [INFO]    GEN | Arguments: <ServerId> <GroupId> <Permission Name> <Grant>
[2018-08-18 23:36:17] [ERROR]   GEN | Could not parse given numbers
[2018-08-18 23:36:21] [ERROR]   GEN | Could not resolve server!

Do i need to type: permgrant 90 (serverid) groupid 918 admin and what do i need to type on <Grant> ?

@WolverinDEV

**Comment by WolverinDEV** [comment]
pergrant <server id> <group id> <permission name> <value>

**Comment by Bluscream** [comment]
what the fuck did you try to do?

**Comment by MikkelDK** [comment]
@Bluscream i try getting permission, so i can remove description

**Comment by Bluscream** [comment]
`b_virtualserver_modify_default_messages` is the permission not `admin`

**Comment by MikkelDK** [comment]
Lol. sorry.. (drunk) for much beeerrrr ;)))

2018-08-19 22:56 GMT+02:00 Bluscream <notifications@github.com>:

**Comment by MikkelDK** [comment]
ok Seems i can't get permission.

@Bluscream 
`Failed on permission b_virtualserver_modify_default_messages `
What do i wrongly?

I did try with: permgrant 1 9 b_virtualserver_modify_default_messages 100
serverid: 1
group (9) permission name and grant (100)

**Comment by MikkelDK** [comment]
Something must be done wrong. :/

` permgrant 1 9 b_virtualserver_modify_default_messages 1`
> login on web client 
insufficient client permissions. Failed on permission b_virtualserver_modify_default_messages
;/

**Comment by WolverinDEV** [comment]
Yeah you have the granted permission that means you can give now the right to yourself :) you still have to enable the right for you

**Comment by MikkelDK** [comment]
Hey @WolverinDEV - is it possible to edit it. so it's "applied" on new creating servers?

As example i'm creating new virtualserver >> the description has been removed on the new virtualserver.
