### ISSUE TITLE
remake template group (permissions)

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#267]
**Describe the bug**
If i'm trying to setting new permissions on "Guest [T]" of template. (so it should update/applied on all virtualserver correct? - Since i did from 9987 port (so it should update/apply to all virtualservers.

**Expected behaviour**
Trying adding to be enabled/activated via Guest [T]
```
b_virtualserver_info_view
b_virtualserver_client_list
b_virtualserver_channel_list
```

**Screenshots**
![](https://i.gyazo.com/1ecf35815201dc0417e52728511e2bf7.png)

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: Debian 9.5
 TeaSpeak version: [TeaSpeak-1.2.4-beta-0]

**Additional context**
I'm trying make a "highcharts" for show "totally clients online on all virtualserver" -- The issue is: it take from serverinstance (serverIP) but seems it taking only from port 9987, and not all virtualservers 
(As example below screenshot):
![](https://i.gyazo.com/38106cda331b5c2216397b7e3b3387ed.png) 

-- If i change the myTS3ServerIP to another RandomserverIP (it will show like this!):
![](https://i.gyazo.com/55fdced4ea2a783d6919ca6ae40730e7.png)

**Comment by WolverinDEV** [comment]
Hey,
if you edit the guest template you just edit the permission for **new** servers.
Only a change within the query groups has a global effect. 
The Template groups are just there to get copied.

**Comment by MikkelDK** [comment]
So i can't set the template to be edited for (exist) servers? :(

**Comment by WolverinDEV** [comment]
No thats impossible :)

**Comment by MikkelDK** [comment]
Damnit ;/ so there is only one way.. to edit manually. :D
