### ISSUE TITLE
Problems with restarting teastart.sh

### ISSUE THREAD

**Issue by Newcomer1989** [TeaSpeak/TeaSpeak#27]
## System Information
Ubuntu 17.10 x64
TeaSpeak-Server v1.0.11-beta

## Issue
On restarting ( `./teastart.sh restart` ) the TeaServer it has everytime problems. It needs a long time and seems to be kill the process hard at the end.

I got also an error on shell and there seems to be also special signs, why the lines will be broken at shell.
The logfile says nothing to the restarting. It only ends.. and a new logfile will be created. There the start process could be seen.

![image](https://user-images.githubusercontent.com/11364569/34650447-c60be194-f3c1-11e7-8c10-8b1d6a03618d.png)

**Comment by WolverinDEV** [comment]
Hello,
i know the reason for that is that somethimes the TeaSpeak-Server hangs up while closing the query server. But after 20/30 sec. the teastart.sh scipt kills the server. Thats why it takes so long :)

**Comment by WolverinDEV** [comment]
Should be fixed in 1.0.12-Beta
