### ISSUE TITLE
[CRITICAL]: Some Query events don't works anymore 

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#270]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
The event server don't works anymore . ( servernotifyregister event=server => is never called ). It was working on preview versions.
Also the bot don't see any channel event ( servernotifyregister event=textchannel ) ( if you type help into the bot channel , this one should answer as he is in the current channel ) . Now he don't see any cmd . it was working also in oldest versions. 
so you can subscibe to server event and channel , with response OK , but don't works anymore. 

**Environment information:**
 Operating system: (`uname -a`) Debian 9 x64
 TeaSpeak version: [TeaSpeak-1.2.5]

**Comment by WolverinDEV** [comment]
Hmm Okey?
That sound critical for me. 
I'll check this in a few minutes :)

**Comment by WolverinDEV** [comment]
Okey will be fixed within the next build (In a hour or something like that)

**Comment by WolverinDEV** [comment]
Fixed in build 1 :)

**Comment by Home-Network** [comment]
error leak memory CPU man no fixed please you verify your code source man ^^

**Comment by MikkelDK** [comment]
I agree! there is CPU leak ;/ 104-100% CPU using.

`Found varianzes within the server tick! (Supposed: 500ms Hold: 489ms` < dunno about this can be issue.


![](https://i.gyazo.com/62b590eb30aa9c2c53f4dba2bd3a4e39.png)

@WolverinDEV ^^

**Comment by WolverinDEV** [comment]
Pleas what? Can you describe the issue a littlebit closer?
