### ISSUE TITLE
Server crash if used web client

### ISSUE THREAD

**Issue by SossenSystems** [TeaSpeak/TeaSpeak#272]
I tried to connect to the TeaSpeak server version 1.2.3 beta via Google Chrome (web browser).
Thereupon the server has crashed ...
Error:
```
<01:57:40> Connecting to 54.36.135.226:9987
<01:57:40> Logging in ...
<01:57:40> invalid ecc key state!
```

**Comment by Sporesirius** [comment]
Please always check if there is a new version, if so test your problem with the new version and if it still does not work, create an issue.

**Comment by WolverinDEV** [comment]
Hey,
Well that's a general problem. 
There are still several problems with the web client an I may guess my server (the web part) hanged up again. I'll of cause fix this soon :)

**Comment by WolverinDEV** [comment]
BTW I still need the crash dump :)

**Comment by WolverinDEV** [comment]
Fixed (Well im not 100% sure about the crash, but the second one)

**Comment by WolverinDEV** [comment]
Both crashes are fixed now.
Resolved the first one
