### ISSUE TITLE
i_client_max_idletime on client. [bug]

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#273]
**Describe the bug**
i_client_max_idletime.
A user has been set (1second for be kicked for idle!) - the issue is: If i'm trying delete the permission (and refresh) it forces back to normal with 1second kick for idle.

**Expected behaviour**
I'm trying to delete the permission. but it coming forced back.

**Screenshots**
Here you see: it's automatic enabled (Dunno how it happened!)
![](https://i.gyazo.com/af2f66bc8e6ba1a8f26e8d9cbc776723.png)

This is.. after i have removed it. but it (forced back) from the first picture!
![](https://i.gyazo.com/b68bf23fdffa860acd77eb2e5bcd4e50.png)

**Logs**
[2018-08-12 17:06:49] [ERROR]    80 | Command handling of command clientdblist needs 87ms
[2018-08-12 17:07:03] [ERROR]    80 | Command handling of command clientpermlist needs 11ms
[2018-08-12 17:07:25] [ERROR]    80 | Command handling of command clientdelperm needs 15ms

Seems it wont remove it. :( 

**Environment information:**
 Operating system: Debian 9.5
 TeaSpeak version: [TeaSpeak-1.2.5-beta2]

**Comment by MikkelDK** [comment]
@WolverinDEV - Do you have see this before? 
And i did asked the client to reinstall TS. but it did still happened.. **(regardless of having deleted permission.)**

**Comment by WolverinDEV** [comment]
Hmm okey? Thats quite funny.
I'll take a look

**Comment by WolverinDEV** [comment]
Cant confirm this issue either
