### ISSUE TITLE
Cannot connect to server from php framework

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#274]
**Describe the bug**
Cannot connect to server from php framework

**Screenshots**
![aq](https://user-images.githubusercontent.com/19707386/44015967-4c70bdd8-9ed3-11e8-982d-0c8f2eb58eba.PNG)

**Logs**
```
TeamSpeak3_Transport_Exception: connection to server 'localhost:10101' lost in /usr/share/nginx/panel/core/TeamSpeak3/Transport/TCP.php:131 Stack trace: #0 /usr/share/nginx/panel/core/TeamSpeak3/Adapter/ServerQuery.php(73): TeamSpeak3_Transport_TCP->readLine() #1 /usr/share/nginx/panel/core/TeamSpeak3/Adapter/Abstract.php(57): TeamSpeak3_Adapter_ServerQuery->syn() #2 /usr/share/nginx/panel/core/TeamSpeak3/TeamSpeak3.php(327): TeamSpeak3_Adapter_Abstract->__construct(Array) #3 /usr/share/nginx/panel/core/TsQuery.php(33): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri)) #4 /usr/share/nginx/panel/panel.php(31): TsQuery->connectToServer() #5 {main}
```

**Environment information:**
 Operating system: ArchLinux
 TeaSpeak version: TeaSpeak-1.2.5-beta-11

**Comment by xRedFox** [comment]
**Nope, still here**

![qq](https://user-images.githubusercontent.com/19707386/44032135-9099e2cc-9f06-11e8-9570-3380ff5d5f01.PNG)

**Comment by xRedFox** [comment]
I updated my php framework today (https://github.com/planetteamspeak/ts3phpframework)

```
TeamSpeak3_Transport_Exception: connection to server '127.0.0.1:10101' lost in /usr/share/nginx/panel/core/TeamSpeak3/Transport/TCP.php:161 Stack trace: #0 /usr/share/nginx/panel/core/TeamSpeak3/Adapter/ServerQuery.php(134): TeamSpeak3_Transport_TCP->readLine() #1 /usr/share/nginx/panel/core/TeamSpeak3/Node/Abstract.php(70): TeamSpeak3_Adapter_ServerQuery->request('login client_lo...', true) #2 /usr/share/nginx/panel/core/TeamSpeak3/Node/Abstract.php(94): TeamSpeak3_Node_Abstract->request('login client_lo...') #3 /usr/share/nginx/panel/core/TeamSpeak3/Node/Host.php(804): TeamSpeak3_Node_Abstract->execute('login', Array) #4 /usr/share/nginx/panel/core/TeamSpeak3/TeamSpeak3.php(341): TeamSpeak3_Node_Host->login(Object(TeamSpeak3_Helper_String), Object(TeamSpeak3_Helper_String)) #5 /usr/share/nginx/panel/core/TsQuery.php(33): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri)) #6 /usr/share/nginx/panel/panel.php(31): TsQuery->connectToServer() #7 {main}
```

TeaSpeak query hangs totally after connection from php framework

```
[2018-08-15 10:08:50] [ERROR] QUERY | [127.0.0.1:41378/ServerQuery#127.0.0.1/41378] Failed to read! Code: 0 errno: 0 message: Success
[2018-08-15 10:09:06] [INFO]  QUERY | Got new client from 127.0.0.1:41384
[2018-08-15 10:09:16] [ERROR] QUERY | [127.0.0.1:41384/ServerQuery#127.0.0.1/41384] Failed to read! Code: 0 errno: 0 message: Success
[2018-08-15 10:09:36] [INFO]  QUERY | Got new client from 127.0.0.1:41406
[2018-08-15 10:09:47] [ERROR] QUERY | [127.0.0.1:41406/ServerQuery#127.0.0.1/41406] Failed to read! Code: 0 errno: 0 message: Success
[2018-08-15 10:10:28] [INFO]  QUERY | Got new client from 127.0.0.1:41412
[2018-08-15 10:10:59] [ERROR] QUERY | [127.0.0.1:41412/ServerQuery#127.0.0.1/41412] Failed to read! Code: 0 errno: 0 message: Success
[2018-08-15 10:11:31] [INFO]  QUERY | Got new client from 37.162.109.165:21524
[2018-08-15 10:12:52] [ERROR] QUERY | [37.162.109.165:21524/ServerQuery#37.162.109.165/21524] Failed to read! Code: -1 errno: 104 message: Connection reset by peer
[2018-08-15 10:12:52] [CRITICAL] QUERY | Could not shutdown query client socket! 107 (Transport endpoint is not connected)
```

**Comment by xRedFox** [comment]
It works well more or less before the 1.2 update. Doesn't teaspeak use https for these things?

![aaa](https://user-images.githubusercontent.com/19707386/44193185-4ef64800-a132-11e8-999e-4ee6317d00cf.PNG)
![ad](https://user-images.githubusercontent.com/19707386/44193419-11de8580-a133-11e8-9bc4-6ccdf9cff431.PNG)

**Comment by xRedFox** [comment]
Maybe the framework is not compatible anymore with the old protocol...  btw exp31 doesn't work

**Comment by xRedFox** [comment]
I can confirm, this is a teaspeak problem. Sometimes it connects sometimes not.

```
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number in /usr/share/nginx/panel/core/TeamSpeak3/Transport/TCP.php on line 60
TeamSpeak3_Adapter_Exception: invalid reply from the server (eak) in /usr/share/nginx/panel/core/TeamSpeak3/Adapter/ServerQuery.php:77 Stack trace: #0 /usr/share/nginx/panel/core/TeamSpeak3/Adapter/Abstract.php(57): TeamSpeak3_Adapter_ServerQuery->syn() #1 /usr/share/nginx/panel/core/TeamSpeak3/TeamSpeak3.php(333): TeamSpeak3_Adapter_Abstract->__construct(Array) #2 /usr/share/nginx/panel/core/TsQuery.php(33): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri)) #3 /usr/share/nginx/panel/panel.php(31): TsQuery->connectToServer() #4 {main}
```

**Comment by MikkelDK** [comment]
@xRedFox I think I had seen someone had made it possible, so it worked ... but do not know where I found it.

**Comment by WolverinDEV** [comment]
I dont use https. I just use ssl.
Well it seems trange an is only a ssl issue :)
I'll look at this. I dont really know which side (server or client) cause the error or trigger the error

**Comment by WolverinDEV** [comment]
Uhh seems like an hang up thats not good.
Could you may enter dummy_crash within the terminal and send me the crash dump?
Because so its easier to find the deadlock :)

**Comment by xRedFox** [comment]
Sure! Here it is:
[7d54ed19-3caa-4b48-c5d4aab5-6e2ccd73.zip](https://github.com/TeaSpeak/TeaSpeak/files/2294934/7d54ed19-3caa-4b48-c5d4aab5-6e2ccd73.zip)

**Comment by WolverinDEV** [comment]
For 221 you can't use that.
That's not a hangup/deadlock bug :)

**Comment by xRedFox** [comment]
duplicate of #315 and fixed

**Comment by xRedFox** [comment]
jk the problem is still here

**Comment by WolverinDEV** [comment]
Can you provide a log without ssl?

**Comment by xRedFox** [comment]
I restarted and it is working both with and without ssl. I wait for it to hang again and I'll send you logs... For now I'll send you what I have from the previous session (unfortunately without trace)
[log_2018-08-19_13_56_30_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2300302/log_2018-08-19_13_56_30_general.log)

**Comment by xRedFox** [comment]
I was working on my panel using localhost and my ip (whitelisted) and everything was fine. As soon as I tried to connect from android to the panel (localhost with teaspeak) everything exploded...
In localhost I used all the time tls and it worked without problems, at this point I don't think it's the fault of that. If you think the opposite I can always try without, which I have already done in the past and the result was exactly the same as the one with tls

[log_2018-08-19_14_19_37_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2300419/log_2018-08-19_14_19_37_general.log)

**Comment by xRedFox** [comment]
fixed, is not a framework problem anymore... Probably something's wrong elsewhere. I'll open another issue tonight or tomorrow.
