### ISSUE TITLE
issue with groups. + serveradmin

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#276]
**Describe the bug**
Issue with servergroups + serveradmin permissions is bugged/or changed after update.

**Expected behaviour**
I did updated the TeaSpeakServer to 1.2.6-b1 and i can't "assign" group or edit serveradmin.

**Screenshots**
I can't assigned the other group (but only xD but it's limited as serveradmin!):

![](https://i.gyazo.com/c6a4403d439cdf2435a2a5bf7908d589.png)

Here i can't set "serveradmin" as serveradmin on the group. (where it too show unknown, and i can't set it to serveradmin as normal again!):

![](https://i.gyazo.com/539f4fd0d4186ab14122cf42fbfdfd3c.png)

Here where i trying to "apply" the group (serveradmin) to be serveradmin. but it denied to be updated:

![](https://i.gyazo.com/73b3a333787edb991807d443da3e85c3.png)

**Environment information:**
 Operating system: Debian 9.5
 TeaSpeak version: [TeaSpeak-1.2.6-beta-1]

**Additional context**
It only happened after I got updated teaspeak server.  
Is there something I must have overlooked since it "tears" with the groups?

**Comment by Chazotu** [comment]
Please clear your Cache and try again

**Comment by MikkelDK** [comment]
works. - I have coded a small .exe file to launch the .bat file and unpack to desktop! :D
