### ISSUE TITLE
Deleting future handle, but still having some entries which waits task!

### ISSUE THREAD

**Issue by fedecingo** [TeaSpeak/TeaSpeak#277]
I started TeaSpeak, everything is regular, but the console is continually invaded by this kind of problem, I do not know what it is

![asd](https://user-images.githubusercontent.com/32389206/44092130-d413e75e-9fcf-11e8-8a01-c8f5bf4cef58.png)

**Environment information:**
 Operating system: (`Linux Admin 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux`)
 TeaSpeak version: [1.2.6-beta-2]

**Comment by MikkelDK** [comment]
Are you using teaspeak 1.1.40? ;) we have new version > 1.2.6-beta-2

**Comment by fedecingo** [comment]
@MikkelDK I correct myself, I'm using 1.2.6-beta-2

**Comment by MikkelDK** [comment]
Seems the "kernel version" is pretty old. are you using Debian 8? - Maybe @WolverinDEV can come with a idea. ^^

**Comment by fedecingo** [comment]
Maybe my OS is too old...

`Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02)`

**Comment by fedecingo** [comment]
What type of message is this? Because sometimes the server on the port 9987 lost connection with me...

`[2018-08-14 15:12:52] [ERROR] Timer InstanceHandler::tickInstance -> flush needs more than 6706 microseconds. Max allowed was 5000 microseconds.
`

**Comment by MikkelDK** [comment]
@fedecingo You are not alone. ;) i getting it too.

and too this: ` Found varianzes within the server tick!`

**Comment by WolverinDEV** [comment]
Well in general its not a that big deal.
Its just comes when a client connects, but times out at a specific handshake state.
The second error isnt that critical as well.
It just indicates that may something is slower than expected.

**Comment by fedecingo** [comment]
@WolverinDEV but it is normal that the message going in loop for the same left message?

**Comment by WolverinDEV** [comment]
No not really but this client held 4 connections so :)
And all 4 were still in handshake mode. There was something crazy going on :)

**Comment by WolverinDEV** [comment]
Well this isnt a big issue so i'll close this
