### ISSUE TITLE
Issue starting server

### ISSUE THREAD

**Issue by tzmst** [TeaSpeak/TeaSpeak#278]
./TeaSpeakServer: error while loading shared libraries: libnice.so.10: cannot open shared object file: No such file or directory

This is a help, i don't think this is a bug. Trying to install teaspeak 1.2.6-beta

**Comment by MikkelDK** [comment]
What OS are you using? ;)

**Comment by tzmst** [comment]
Its a hosting server, unfortunately i only have access with FTP client on it, no console. I guess i need to apt get the lib ?

**Comment by tzmst** [comment]
@MikkelDK Thx, thought so.
