### ISSUE TITLE
Query-Commandline - line breaks

### ISSUE THREAD

**Issue by Newcomer1989** [TeaSpeak/TeaSpeak#28]
## System Information
Ubuntu 17.10 x64
TeaSpeak-Server v1.0.11-beta

## Issue
The query-command line seems to respond also bad line breaks
![image](https://user-images.githubusercontent.com/11364569/34650547-2f57e232-f3c3-11e7-9039-fface3e32c93.png)

So at first I need to press Enter to get a new line and I will directly get the following error.

> error id=2 msg=not\simplemented

**Comment by WolverinDEV** [comment]
Hello,
this problem results by the not fixed newline policy.
I guess your shell requires '\n\r', but TeaSpeak sends by default only '\n' in the welcome MOTD.
You should be able to change this in the config as well.

(I may change the default setting here)

**Comment by Newcomer1989** [comment]
Sorry, I missed to give the information -> I am using Putty for the query connection

**Comment by Newcomer1989** [comment]
> (I may change the default setting here)

And yes, you should or you will get much more error reports ;-)

**Comment by WolverinDEV** [comment]
Did you changed the default query motd in the config? And does it works?

**Comment by Newcomer1989** [comment]
At this moment I didn't changed anything in the config file. So it were a default config.

The command line does work. I was able to get the admin privileges on the server over this.

**Comment by WolverinDEV** [comment]
Changed the default value at 1.0.12
