### ISSUE TITLE
Will TeamSpeak Allow This?!

### ISSUE THREAD

**Issue by iJosephY** [TeaSpeak/TeaSpeak#280]
I Have a NPL License 
i know it's not the good place to ask this

but if i use my license with teaspeak
teamspeak will not mind it?!
i mean ... they will not revoke my license or black list my server?!

thanks

**Comment by jonipin** [comment]
Short Answer : Yes they Will

Long Answer: If u buy a premium from teaspeak and disguise Teaspeak to make it look like TeamSpeak the only way you're getting banned or revoked is if someone reports you for using too many Slots on a TS License that only allows 512(NPL)

Post here on how to make TeaSpeak look like TeamSpeak: https://forum.teaspeak.de/index.php?threads/make-teaspeak-look-like-teamspeak.174
