### ISSUE TITLE
Starting problem : libnice.so.10: cannot open shared object file

### ISSUE THREAD

**Issue by 007basaran** [TeaSpeak/TeaSpeak#281]
**Describe the bug**
During installation, the script fails to start.

**Logs**
./teastart_minimal.sh: line 49: packageManagersList: bad array subscript
./teastart_minimal.sh: line 49: packageManagersList: bad array subscript
./teastart_minimal.sh: line 49: packageManagersList: bad array subscript
./TeaSpeakServer: error while loading shared libraries: libnice.so.10: cannot open shared object file: No such file or directory

**Environment information:**
 Operating system: Linux hostname 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 TeaSpeak version: TeaSpeak 1.1.32-beta [Build: 1528736451]

**Comment by Chazotu** [comment]
Please use current version 1.2.6-beta-3.Which Linux OS are you using ?

**Comment by Sporesirius** [comment]
Which centos version exactly? 7, 6 or older?

**Comment by Mavrios** [comment]
i have the same problem in debian-7.0-amd64-minimal.tar.gz

**Comment by 007basaran** [comment]
Is there anything you can do to help solve this problem?

**Comment by WolverinDEV** [comment]
I thing the issue is resolved in general :)

**Comment by 007basaran** [comment]
The problem is not solved, how can we solve it ??

**Comment by WolverinDEV** [comment]
There is a instruction set within the forum.
I think it's within the tutorial for the installer

**Comment by MrTramp** [comment]
Have you tried to install/reinstall the libnice package? Or by chance libnice-dev ?

**Comment by MrTramp** [comment]
I'm not sure why it asks for this library but will it be fixed with installing libnice?
yum install libnice

And for debian installing libnice-dev?
apt-get install libnice-dev

**Comment by MikkelDK** [comment]
apt-get install libnice10 for Debian 9.5

You can try with apt-get install libnice-dev ;)
