### ISSUE TITLE
Cannot create channel before the first room of the server

### ISSUE THREAD

**Issue by fedecingo** [TeaSpeak/TeaSpeak#284]
When I edit or create a room, it's impossible to place it as the first server room, and then I end up in the back of the rooms of the whole server, I attach the screens.

When creating channel... ![screen1](https://user-images.githubusercontent.com/32389206/44149525-c5e92e82-a09c-11e8-84db-bca3d084fac6.png)

As soon as the channel is created, it goes to the end... ![screen2](https://user-images.githubusercontent.com/32389206/44149526-c60c682a-a09c-11e8-84b0-f0635e377975.png)

**Comment by WolverinDEV** [comment]
Fixed within the next version :)
