### ISSUE TITLE
Impossible start teastart_minimal.sh on Debian 9 : Syntax error: "(" unexpected on file teastart_minimal.sh

### ISSUE THREAD

**Issue by FleuryK** [TeaSpeak/TeaSpeak#285]
Hello,

**Describe the bug**
After execution shell script teastart_minimal.sh, a error syntax appear. This error : `teastart_minimal.sh: 4: teastart_minimal.sh: Syntax error: "(" unexpected`

**To Reproduce**
After downloading, untar and put in a folder (so that it is clean in my `home/user` folder), run teastart_minimal.sh and a syntax error appears immediately.

**Environment information**
 Operating system: Debian Stretch (Debian 9 (9.5))
 TeaSpeak version: TeaSpeak-1.2.7-beta-1

Can you fix this bug ?

Thank You.

**Comment by WolverinDEV** [comment]
Hey,
which shell are you using?
`/bin/bash` or `/bin/sh`

**Comment by FleuryK** [comment]
Hello,
I use `/bin/bash`.
I tape this command: `sh teastart_minimal.sh start` (with or without `start`) and I have this syntax error.

**Comment by WolverinDEV** [comment]
ahh can you please use bash or just `./`?

**Comment by FleuryK** [comment]
I have used `./teastart_minimal.sh` and it works but i have another problem once launched. Once I log in to TeamSpeak, I am immediately disconnected and have the message `(server version is too old for command)`.

**Comment by MikkelDK** [comment]
Edit config.yml and set exp31 to 1 and save. And try again.

**Comment by FleuryK** [comment]
In config.yml, did not you talk about this? `experimental_31`.

**Comment by FleuryK** [comment]
Ok. So it does not work. It shows me "Failed to connect to the server".

**Comment by MikkelDK** [comment]
You need to update the protocol_key.txt ;)

**Comment by FleuryK** [comment]
I deleted and retaped command `./teastart.sh` for recreate protocol_key.txt and ... failed. I still have "Failed to connect to the server".

**Comment by Bluscream** [comment]
You did **what**?

**Comment by FleuryK** [comment]
I have changed on config.yml `experimental_31` to `1`.
I deleted protocol_key.txt for recreate automatically via the command `./teastart.sh` for update.

And fail mon my PC (I still have "Failed to connect to the server") but i have no problem with my phone (Android 6.0.1 with TS 3.1.9).

It's weird that it makes me on my PC and not on my phone...

**Comment by WolverinDEV** [comment]
I thing the actual issue is resolved :)
