### ISSUE TITLE
ipv6 Support

### ISSUE THREAD

**Issue by GoRiLliAz** [TeaSpeak/TeaSpeak#288]
**Describe the bug**
if you use ipv6 on teaspeak hi is impossible to connect

**To Reproduce**
Steps to reproduce the behaviour:
1. you connect
2. you are disconnected

**Expected behaviour**
possible to connect with ipv6

**Screenshots**

**Logs**

[2018-08-15 16:58:47] [[1m[7m[0;31mCRITICAL] [1m[7m[0;31m    2 | Failed to write datagram packet for client **IPV6:53421** (errno: 97 message: Address family not supported by protocol). Closing connection[0m

**Environment information:**
 Operating system: Linux machine 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.7-beta-2]

**Additional context**

**Comment by WolverinDEV** [comment]
IPv6 is implemented. It seems that your server does not support ipv6

**Comment by GoRiLliAz** [comment]
my server support ipv6 with teamspeak i have no problem !
If i desactivate ipv6 in my server player connect if i active player ipv6 cant connect

**Comment by GoRiLliAz** [comment]
give me ip ts3 and i you proof
