### ISSUE TITLE
Logfile - paused?

### ISSUE THREAD

**Issue by Newcomer1989** [TeaSpeak/TeaSpeak#29]
## System Information
Ubuntu 17.10 x64
TeaSpeak-Server v1.0.11-beta

## Issue
If there is an action, which will be logged, the last row will not be written full. It gets halted in the middle of the line.
It seems with the next action which enters a new row, the last missing part will be written at this moment. So the information is not lost, but it's still a bit crazy.

I also tried it with tail, so it is definitly not a problem, that I entered the file on half ended writing process.

Here an tail output. The line breaks was me, I did that at the point, the log breaks.
![image](https://user-images.githubusercontent.com/11364569/34650687-6cad477e-f3c5-11e7-9e48-646a050df0c5.png)

**Comment by WolverinDEV** [comment]
Hello,
Im using spdlog (https://github.com/gabime/spdlog) in async caching mode.
I recommand if you want a clear Terminal use the TeaStart_minimal script. You also have a little command promt there as well :)

**Comment by Newcomer1989** [comment]
Hmm, for testing the minimal script could be a nice thing. But in an production environment the most ppl will use the startscript to bind it to the background.
The datablock writing should be no bad thing, but you can configurate it, that it will do that 1) faster and 2) only break on end of a line?

**Comment by WolverinDEV** [comment]
Well I think a break at a new line would be probably a better way.
And yes you're completely right with your point that the most would use the normal start script. 
May I should improve that a little bit. 
I personally using the minimal with screen.

**Comment by WolverinDEV** [comment]
Fixed in 1.0.24-Beta (Log directly (Max. 500ms delay))
