### ISSUE TITLE
Negative values on permissions not working properly in some cases

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#296]
Just gonna throw a chatlog in here, this happens on the latest version, 1.2.7 beta-4

Acnologia Today at 4:19 AM
if u can find out how to exactly reproduce those permission bugs i'll report it and it'll probably get fixed

Stusse Today at 4:45 AM
I'll check
if they persist
Yeah the rank stuff still exist
At least, before I could add the "talk power -1" to anyone and they couldnt speak
Now, when added it to someone, they get above me, talk power 90, in the channel
so seems like it consideres negative value as infinite

Acnologia Today at 4:58 AM
well rip

Stusse Today at 4:58 AM
in some considerations, -1 should be infinite
For example

Acnologia Today at 4:59 AM
gotta work around it temporarily by using 0/1 i guess

Stusse Today at 4:59 AM
"maximum qouta for  download"
-1 = infinite
but in some sense
it should be < 0
for example
talk power
poke power
view power/subscribe to channel power
It is possible to work around it
By setting values for everything
but is not convenient
at all
Would have to cross-check all other server groups to align them to get the same result
for example
if I want ppl that enter first time to not be able to do SHIT at all
Instead of just put -1 on stuff
I need to put 1
and then _needed for other groups to 2
or similar
a lot of work
To not say updating/moderate all the channels
Seems like it also persist the issue where you are required to relog in order to get server groups in effect
Sometimes it works sometimes it doesnt, either have to move them to a channel or kick reconnect for certain talk powers for example to get in use
Proabbly whoever made this new server client just put infinte on -1, as it aplies to certain permissions
Instead of, as normally, each individual permission -1 has different meaning
So how to reproduce  would be to just play around with talk power -1 trying to talk in a channel with 0 required, or to assign poke power -1 and try to poke someone with needed_poke 50 <- they can still do these things
Same with text message in priv
not to channel however seems like
Would have to check each and every permission individually
Just having 2 clients, one with -1 on each permission and one on _needed on each permission would probably troubleshoot most of them
As well as in relation to channels, have channels with certain required permissions (view, subcscribe, view description, download) etc and try them in relation to -1 permission clients

**Comment by MikkelDK** [comment]
About the maximum quota for transfers has been requested.... look here: #264 .. And no it DONT needed to be 0... ;) -1 is for unlimited!

**Comment by MikkelDK** [comment]
Why are you talking about "talk power" since i'm walking about the "maximum quota for transfers" ? ;) 

Stusse Today at 4:59 AM

> "maximum qouta for download" < Look.. maximum quota for download is under "Edit virtualserver > Transfers"

-1 = infinite
but in some sense
it should be (not need)< 0

**Comment by Sickness-chan** [comment]
Ignore what he said about the quotas, those are supposed to work like -1 being infinite.

**Comment by MikkelDK** [comment]
I do not want to ignore what he has written to you. :) - just you know it. it has been requested! > #264 :-)

We're all here for help! ;) - i did tell you.. (about the quote transfers is under edit virtualserver!) ;)

**Comment by Bluscream** [comment]
I can indeed comfirm that talk power -1 should be under 0 npt infinite

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
