### ISSUE TITLE
Send message to clients via serverquery not working properly

### ISSUE THREAD

**Issue by lbenicio** [TeaSpeak/TeaSpeak#297]
**Describe the bug**
I have a bot for TeamSpeak which sends a private message to all users when they log in to TeamSpeak client when I switched to TeaSpeak it stopped working, even all the code seems to be processed.

For example: if I put a notify.cleintenterview, do some coding, console.log some output, all execute, except to send the private message. But the strange part is: if I manually open the chat with the bot and send command, it works normally.

Unfortunately, I could figure out how to reproduce the bug, posting here is you guys could give some advice.

how do I know that is was working, its been working on TeamSpeak server for over a year, the issue started after I migrate to TeaSpeak

**Logs**
maybe my Bot logs? I think it is not needed the teaspeak log
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: Ubuntu x64
 TeaSpeak version: [TeaSpeak-1.1.40-beta-1]

**Comment by Chazotu** [comment]
Please update to the latest version

**Comment by lbenicio** [comment]
I installed teaspeak yesterday, just downloaded it yesterday, how could I am not be on the latest version?

**Comment by Chazotu** [comment]
Cause we are maintaning the project and are curently making more updates over the day as we are still in beta an listen to the feedback of our community

**Comment by lbenicio** [comment]
I will make a script to download the project as soon as a version change to keep all up to date! Just to make sure I'm always on latest version. 

Just to make sure, to update is just replace the files except for the db and the config.yml?

**Comment by WolverinDEV** [comment]
What commands does your bot recives/executes?

**Comment by lbenicio** [comment]
Update channel with information crawled from websites, kick clients, move clients, poke everyone on the server, this kind of stuff, apparently, everything works fine, just sending the welcome_message when a new client enters the server appear the problem.

As Chazotu said, I was on 1.2.7-beta4, as I can't turn off the server while users using then I will update in a while and report back

**Comment by lbenicio** [comment]
on latest version seens to have closed the issue, the message take a few second to arrive but the successfully manage to send menssages when a user connect to server! Thank you guys for the hard work =)

**Comment by lbenicio** [comment]
yes, just ran the update script, sometimes it sends the message with a little delay, sometimes it does not. Which logs do you want ? print what? just the client list?

**Comment by lbenicio** [comment]
look my bot logs:

`Bot started.
start drawing videos channel.
subscribe all events
error:
null
resp
{ status: 'ok', raw: 'error id=0 msg=ok' }
sent welcome_msg to 1| Nico Frota
sent welcome_msg to 9| Daannzin
sent welcome_msg to 12| Blackbat - Guilherme
sent welcome_msg to 15| Karnaque
sent welcome_msg to 16| Bud Amassado
sent welcome_msg to 21| Kamelo - Kausz Bloker
sent welcome_msg to 25| Gui
sent welcome_msg to 26| Boderas
sent welcome_msg to 23| Valerio
sent welcome_msg to 20| Old Kamicase
sent welcome_msg to 3| Padre Beato

channel update error: { status: 'error',
message: 'channel name is already in use',
error_id: 771 }
{ cid: 40, channel_name: '╠● Videos (0)' }
draw video channel error 2 { status: 'error',
message: 'channel name is already in use',
error_id: 771 }
client enter view --
3 | Padre Beato
sent welcome_msg to 3| Padre Beato
seted new client
client enter view --
3 | Padre Beato
sent welcome_msg to 3| Padre Beato
seted new client`

it executes the code when the cliententertview event is fired but the client could not receive the message.

if i restart my bot, it queries all clients connected and sends a message to all of then greeting, this part works well. the strange part is, the event is triggered but the send message isn't. i'm starting to think it not with the TeaSpeak but with the node library i'm using? (which is: https://github.com/macpie/node-teamspeak-api)

**Comment by lbenicio** [comment]
i managed to make it work putting a 3seconds delay to send the welcome message, but it strange the fact it needs a delay to work

**Comment by WolverinDEV** [comment]
Ahh it seems like you're sending the message may too fast.
I guess the bot is running on the same server as the TS server so the client is may not ready initialized and could not receive any messages.
