### ISSUE TITLE
Cannot change channels (only when creating one)

### ISSUE THREAD

**Issue by Pdani001** [TeaSpeak/TeaSpeak#298]
**Describe the bug**
I (and my friends) cannot change channels, only when creating one.
I always get the missing permission error "i_client_move_power".

**To Reproduce**
Steps to reproduce the behaviour:
1. (Create new server)
2. Try to change channels

**Expected behaviour**
Changing channels should work without problems.

**Environment information:**
 Operating system: Ubuntu 14.04 x64
 TeaSpeak version: [TeaSpeak-1.2.8-beta]

**Additional context**
I just updated from 1.2.6-beta, before that, the only problems was with the "Stop Channel Group Inharitance" permission, i didn't tested that one out yet. (Because of this problem)

**Comment by WolverinDEV** [comment]
Fucking shit oh my god!
Its fixed withion the next build i made a mistake at the latest fix

**Comment by WolverinDEV** [comment]
Fixed in build 1

**Comment by Pdani001** [comment]
@WolverinDEV Thanks, and when this build will be up?

**Comment by WolverinDEV** [comment]
Already :) repo.teaspeak.de
