### ISSUE TITLE
Open/Create Multiple Servers  on Same Machine

### ISSUE THREAD

**Issue by ChrysUk** [TeaSpeak/TeaSpeak#299]
Hello,

Is there a way to make somehow to be able to set/bind ip on the config file or on the start command and the server to start on the ip specified ?

In this way we ar able to create multiple servers on the same  vps/dedicated server.
Like is on the teamspeak  with the start name.ini file voice_ip=...

Thank you

**Comment by MikkelDK** [comment]
Do you think about the multiple IP address? (as example: 5 IP address is assigned on the VPS or dedicatedserver?)

**Comment by ChrysUk** [comment]
Yes, at the moment even if i got more ips on the vps/dedicatedserver the server will start on 0.0.0.0 not able to set ip

**Comment by MypowerHD** [comment]
You can find All settings on your Config file.!
@WolverinDEV Close pls

**Comment by ChrysUk** [comment]
@MypowerHD yea true but not what i say :)  why do you jump ? Did you test it ?

**Comment by WolverinDEV** [comment]
`virtualserver_host` the property for each virtual server.

When you bind your server on 0.0.0.0 you bind to *any* address and cant use that port anymore even on "another" address

**Comment by WolverinDEV** [comment]
Yeah these are the default settings once applied to the server you'll find it within the server property...

**Comment by ChrysUk** [comment]
Can you tell me where exactly ? i searched since  yerstaday all day to do this

**Comment by WolverinDEV** [comment]
`serveredit virtualserver_host=8.8.8.8`

As an alternative you could configure the virtual server via the web client :)

**Comment by GoRiLliAz** [comment]
its the same thing for teaspeak and teamspeak use that in telnet 
```

servercreate virtualserver_name=My\sSecond\sServer virtualserver_port=1337 virtualserver_maxclients=128
sid=3 virtualserver_port=1337 token=baJXf04IjoBXUphgxM3Y
```

**Comment by GoRiLliAz** [comment]
in telnet say `use 1` or `use 2` for select your virtual server you try change ip
