### ISSUE TITLE
Binaries on Github

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#3]
Could you (also) provide the binaries as github releases? That would allow 3rd parties to easily create cool stuff like auto-updaters ^^

**Comment by WolverinDEV** [comment]
Hey,
well i already have a verry well (planed :D) structured repro (repro.teaspeak.de).
You could always get the last ***Release*** at http://repro.teaspeak.de/server/linux/x64/.
Im currently not saving the beta binaries, but i will ssave the Release binaries and build up a versions history.

**Comment by Bluscream** [comment]
Is there any way to get stuff as json for example?

**Comment by WolverinDEV** [comment]
Currently not but I would probably add it :)I think I would look like the updater of my project BungeeUtil

**Comment by Bluscream** [comment]
Well, github ships the api and is way more reliable against ddos and pentested/secured against vulnerabilities than anything you could come up with. I mean if you want you can still use your solution as main download etc. but mirror the releases on github. I would gladly do that job if i had the permissions on your github repo. (i think i can be kind of trusted as i'm honored to have partial push access to the yatqa website)

**Comment by Bluscream** [comment]
Well, github ships the api and is way more reliable against ddos and pentested/secured against vulnerabilities than anything you could come up with. I mean if you want you can still use your solution as main download etc. but mirror the releases on github. I would gladly do that job if i had the permissions on your github repo. (i think i can be kind of trusted as i'm honored to have partial push access to the yatqa website)

**Comment by WolverinDEV** [comment]
You got your own project/repro where you do this stuff :)
