### ISSUE TITLE
Deleting channel currently in makes the server crash

### ISSUE THREAD

**Issue by joaonl** [TeaSpeak/TeaSpeak#30]
## System Information
***Operating System***: Ubuntu Server 16.04
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: [21:41:12] [INFO] Starting TeaSpeak-Server v1.0.12-beta

## Issue
***Reason for reporting this issue***:
Server crash
Automatically channels deleted

***Detailed Description***:
1. Go into a random sub-channel
2. While in the sub-channel, delete the sub-channel
3. Server will crash

Second issue.

<21:49:39> Channel "efferwfewefw" was deleted by "Another TeaSpeak server software user"
When creating a channel, the server seems to be removing it.

**Comment by WolverinDEV** [comment]
I guess you mean temporary sub channels right?

**Comment by WolverinDEV** [comment]
~ Fixed in 1.0.13-Beta
* This issue triggered me so much to create a new version just fixing this really important issue
