### ISSUE TITLE
People dissapearing

### ISSUE THREAD

**Issue by h1rule** [TeaSpeak/TeaSpeak#305]
**Describe the bug**
Wenn man aufm TeaSpeak verbunden ist, sieht man irgendwann seine anderen Leute nicht mehr, die sind aber im gleichen Channel, können dir schreiben, hören dich, aber du siehst/hörst sie nicht, kannst aber mit ihnen chatten. Bis man sich neu verbindet, dann sind sie wieder da. Leider keine Bugs/Logs vorhanden, die ich reporten könnte.

**To Reproduce**
Steps to reproduce the behaviour:
3. Setting to apply '....'

**Expected behaviour**

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: (`uname -a`)
 TeaSpeak version: [TeaSpeak 1.2.7-beta-1]

**Additional context**

**Comment by MikkelDK** [comment]
Do you have try to update the server to 1.2.8-beta-1? ;)

**Comment by jonipin** [comment]
Happens in 1.2.8 too just happened in my server aswell

**Comment by WolverinDEV** [comment]
Hmm?
Sounds strange are they just disappearing or are they never appeared? 
And when they are disappearing which message comes within the client servet log?

**Comment by Sickness-chan** [comment]
I also experience this, all I did was start & stop the server, the clients reconnected on their own as they should, but not all users show up for all of the clients. https://i.killuminati.eu/67951196Q.webm

If you leave & rejoin the channel, they'll start showing up again.

**Comment by WolverinDEV** [comment]
Ahh yeah Okey that's a kind of known issue.
Well it a comprehension between speed and safety. I'll may improve that as well because it could crash the client :)

**Comment by WolverinDEV** [comment]
Should be fixed within the next version :)

**Comment by Sickness-chan** [comment]
Users aren't yet appearing properly on reconnect, same problem as I described above https://i.killuminati.eu/6802p316d.webm

**Comment by MrTramp** [comment]
Noticed this on v1.2.9-beta [Build: 1534531853] while I was fooling around with a cpl sinusbots that suddenly didn't appear for neither me nor another client. Not even after reconnecting the bots but only after reconnecting myself.

However I just updated to v1.2.10-beta [Build: 1534624226] so will have to check if it does the same sometime tomorrow.

**Comment by WolverinDEV** [comment]
Should be fixed (and i tested it several times (20 i guess)) within the next build :)
