### ISSUE TITLE
PHP Framework (planetteamspeak): channel_password - doesn't work

### ISSUE THREAD

**Issue by Fastmancz** [TeaSpeak/TeaSpeak#307]
**Describe the bug**
Hello, I'm trying to change the password of the room via PHP framework. It's not working.
https://docs.planetteamspeak.com/ts3/php/framework/

`$ts_ch_password_new = generateRandomString2();

					$ts3_VirtualServer = TeamSpeak3::factory("serverquery://myteaspeak:10101/?server_port=9987");
					$ts3_VirtualServer->login('mylogin', 'mypassword');

					$ts3_VirtualServer->execute("channeledit", array(
						"cid"	=> $db_ts_id_room,
						"channel_password"	=> $ts_ch_password_new
					));`
The password will not change (or is not working). I tried change password for the room via YaTQA, the problem is the same.

**Logs**
PHP, Teaspeak log doesn't display any errors.

**Environment information:**
 Operating system: Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
 TeaSpeak version: TeaSpeak-Server v1.2.8-beta [Build: 1534430952] (16.08.2018 - 16:49:12)

Thanks for help and answer.

**Comment by Fastmancz** [comment]
channeledit cid=24830 channel_password=test
error id=0 msg=ok
<10:48:42> Channel "xxyy" was edited by "myquery"

The channel room doesn't have a password set.

**Comment by WolverinDEV** [comment]
Yeah,
There are two things. 
The first is that you have to enable the channel_flag_password property :) and you have to hash the password I guess I know it's a special Teaspeak thing and it will may improve within the future

**Comment by WolverinDEV** [comment]
`sha1(<password>)`

**Comment by WolverinDEV** [comment]
Should fixed within the next version

**Comment by xRedFox** [comment]
@WolverinDEV 
![c7imi-_xqaa8wd9](https://user-images.githubusercontent.com/19707386/44312779-b98ed880-a3fd-11e8-91e2-93d32531d69e.jpg)

**Comment by WolverinDEV** [comment]
Yeah please tell that TeamSpeak, but I thing sha1 is still strong enough just for a channel password. :)

**Comment by batizisanya** [comment]
@WolverinDEV Its not working. `$top_cid = $ts3_VirtualServer->channelCreate(array(
    "channel_name" => "teszt",
    "channel_order" => $chan_order,
    "channel_password" => sha1('asd'),
    "channel_description" => "asdasdda",
    "channel_flag_permanent" => true,
	"channel_flag_password" => true
));`

And when I try to join to the channel, i get invalid password error...

**Comment by WolverinDEV** [comment]
Yeah :D You dont have to hash the password anymore :)

**Comment by Fastmancz** [comment]
Yeah, it's a bug, I must use this solution. You must create a channel and use "channeledit" for change password.

$sub_cid = $ts3_VirtualServer->channelCreate(array(
.....
));

$ts3_VirtualServer->execute("channeledit", array(
                            "cid"   => "Your channel ID",
                            "channel_password"  => "Your password"
                            ));

**Comment by batizisanya** [comment]
@Fastmancz Can you reopen the case, until there is a bug, please?

**Comment by Fastmancz** [comment]
I can not open it.

**Comment by WolverinDEV** [comment]
Thats the right code to calculate the password:
```
cmd["channel_password"] = base64::decode(digest::sha1(cmd["channel_password"].string()));
```

But nevermind will be fixed when I build the next build (Not build 4!)
