### ISSUE TITLE
Crash the server after creating a channel on the server with sid 0

### ISSUE THREAD

**Issue by 07artem132** [TeaSpeak/TeaSpeak#308]
**Describe the bug**
I create a channel on the server with sid 0 and the server crashes

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'server sid 0'
2.  Create channel 
3. See error

**Expected behaviour**
The server does not crash

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: Linux ts02.tea.fr.service-voice.com 4.15.18-1-pve #1 SMP PVE 4.15.18-19 (Mon, 13 Aug 2018 07:50:59 +0200) x86_64 x86_64 x86_64 GNU/Linux
 TeaSpeak version: 1.2.8-beta

**Additional context**
[log_2018-08-17_16%3A55%3A55_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2298079/log_2018-08-17_16.3A55.3A55_general.log)
[0b3b3aad-796a-4be9-7e051689-612cb158.dump](https://github.com/TeaSpeak/TeaSpeak/files/2298080/0b3b3aad-796a-4be9-7e051689-612cb158.txt)

**Comment by WolverinDEV** [comment]
Fixed within the next build (1)
