### ISSUE TITLE
Permission b_virtualserver_client_dbinfo (And dropped v2?)

### ISSUE THREAD

**Issue by MrTramp** [TeaSpeak/TeaSpeak#310]
**Describe the bug**
While trying to change or add the permission "b_virtualserver_client_dbinfo" it doesn't keep the value after closing Permissions nor does it seem to write the value to database.
I tried adding the permission via terminal as well with: clientaddperm cldbid=X permid=31 permvalue=100 it responds "error id=0 msg=ok" but nothing happens.

Tried with two different servers with same results.

**To Reproduce**
Just try adding power b_virtualserver_client_dbinfo from permissions tab in TS-client or via Query command "clientaddperm cldbid=X permid=31 permvalue=100"

**Environment information:**
Operating system:
Linux 4.9.0-6-amd64 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux - Running server on MariaDB server
Linux 4.4.0-130-generic Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - Running on sqlite
TeaSpeak version:
TeaSpeak-Server v1.2.7-beta [Build: 1534360275]

**Additional context**
By a coincidence- it might be different issue but...seems after the Query console timed out and I reconnected the serveradmin account it had lost the permission to reuse the clientaddperm

**Follow ups:**
Unfortunately I had loglevel lowered so can't add logs for this.
Will try a clean TeaSpeak server if it's needed

**Comment by WolverinDEV** [comment]
Well if you're using YatQA does the permission appear there?
Because the client has a bug:
Every time when i edit a permission another top permission got not editable anymore within the client... TeamSpeak :D

**Comment by MrTramp** [comment]
I just tried with YaTQA as well.... This time on the new involvement with continued log from before. Can't remember if you got a log with trace from the connection problem but I managed to generate that this time lol

[log_2018-08-17_18%3A52%3A20_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2298390/log_2018-08-17_18.3A52.3A20_general.log)
