### ISSUE TITLE
Fail to connect to server

### ISSUE THREAD

**Issue by lbenicio** [TeaSpeak/TeaSpeak#311]
**Describe the bug**
Sometimes it not possible to connect to the server. The server is online, there are clients connected but some clients could not connect, some can after 3-5 tries, others don't. Nothing on log files

**To Reproduce**
can't reproduce the problem

**Logs**
Last teaSpeak log is over 7mb, should I post a ghostbin link? already searched there and found nothing interesting...

**Environment information:**
 Operating system: ubuntu x64
 TeaSpeak version: TeaSpeak-1.1.40-beta-1
Client system: Windows / macOS

**Comment by lbenicio** [comment]
Log link: https://codeshare.io/2WzwNl

**Comment by MikkelDK** [comment]
I think you has same issue.. >> the "title" is same on this: #232

**Comment by lbenicio** [comment]
sorry for double post, will close issue
