### ISSUE TITLE
Badges of the music bot standard id

### ISSUE THREAD

**Issue by 07artem132** [TeaSpeak/TeaSpeak#312]
It would be great if the music bot automatically received an icon on the server if it was loaded. id icons can be specified in the configuration file

**Comment by WolverinDEV** [comment]
What do you mean?
The `i_icon_id` permission?
I thing its kind of useless because you could easily give the bot a group.
But may I'll allow to setup a specific default group for music bots.

**Comment by 07artem132** [comment]
The default group seems even really better.

**Comment by WolverinDEV** [comment]
Implemented at version 1.2.10-beta!
