### ISSUE TITLE
Transfer config locked?

### ISSUE THREAD

**Issue by fedecingo** [TeaSpeak/TeaSpeak#313]
I have the transfer config locked in this value? If i edit this it comes anyway (i am running TeaSpeak 1.2.9-beta)

![locked](https://user-images.githubusercontent.com/32389206/44297064-f4dcba80-a2ca-11e8-8d79-dfea07f4ed2f.png)

**Comment by MikkelDK** [comment]
Duplicted. #264

**Comment by WolverinDEV** [comment]
Duplicate of #264
