### ISSUE TITLE
View power and channel behaviour

### ISSUE THREAD

**Issue by Najsr** [TeaSpeak/TeaSpeak#314]
**Describe the bug**
When you get a new permission with i_channel_view_power channels, that you should be able to see are not visible until relog. Same goes for i_channel_needed_view_power (don't disappear until relog)

**Environment information:**
 TeaSpeak version: [TeaSpeak-1.2.8-beta1]

**Comment by WolverinDEV** [comment]
From the changelog:
```
Notes: The channel visibility states updates only on a channel permission change
That means if a client/or group changes the permission i_channel_view_power he has to rejoin This also applies to server/channel groups. The reason for this is simple: To reduce the server sided load
```

**Comment by Najsr** [comment]
Ah.. Would it be possible to force the change somehow? Maybe Giving them the channel list again? Iterate through the channel list and "create" the ones that I am able to see with the new permissions and "delete" the ones that are no longer visible? Ofc checking if the server group has the view_power assigned to not waste CPU cycles

**Comment by WolverinDEV** [comment]
Hmm well i already have a system like that.
I just disabled it for the view permission.
Imagine:
You have a server with 200 channels (sometimes normal) and you edit the permission of the guest group. I think its pretty CPU intensive there :)

**Comment by WolverinDEV** [comment]
Fixed/implemented within the next build

**Comment by Najsr** [comment]
I am using latest build (1.2.10-beta-4) and it does not seem to work. Is there any way to debug it?

**Comment by WolverinDEV** [comment]
Sure?
Just add or remove groups or change permission :)
