### ISSUE TITLE
TeaSpeak PHP Framework (Help)

### ISSUE THREAD

**Issue by ssg0b** [TeaSpeak/TeaSpeak#315]
I can not connect when I try with Teamspeak Framework.
How can I check the TeaSpeak Server with PHP?

I used connect code;
$ts3 = TeamSpeak3::factory("serverquery://serveradmin:querypassword@127.0.0.1:10101/?server_port=9987");

Please Help me.

**Comment by xRedFox** [comment]
duplicate #274

**Comment by Chazotu** [comment]
#274

**Comment by WolverinDEV** [comment]
It isn't because the other is a ssl issue I guess

**Comment by ssg0b** [comment]
Not relevant to SSL.

The web server shows this error;
`Error 0: invalid reply from the server`

That's what the console says on Linux;
```
[2018-08-18 16:52:23] [INFO]  QUERY | Got new client from 40.89.xx.xx:59806
[2018-08-18 16:52:24] [INFO]    GEN | [Query] 40.89.xx.xx:59806 disconnected. (Requested by manager)
```

**Comment by xRedFox** [comment]
@WolverinDEV #274 is not a ssl problem, I can not even connect without ssl. As soon as I try to connect with the framework all login attempts timeout (even those of YaTQA)

**Comment by batizisanya** [comment]
@ssg0b just download the newest release of the library and its gonna work.
