### ISSUE TITLE
User sorting bug

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#317]
**Describe the bug**
When assigning the channel admin group, it seems to send wrong information about the user order in channels to only 1 client.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect 3 clients to a server
2. Have 1 with the server admin group and assign the channel admin group to another
3. Re-enter the channel with both clients
4. Switch between the 3 clients and check the order of users
5. Seems to send a wrong order only to the server admin

**Expected behaviour**
Server admin should always be at the top, because it has 75 talk power, channel admin has 60

**Screenshots**
https://i.killuminati.eu/6801A062l.webm

**Environment information:**
 TeaSpeak version: [TeaSpeak-1.2.10-beta]

**Comment by WolverinDEV** [comment]
Fixed with the build 2 :)
Was a fail on my side.
