### ISSUE TITLE
Invalid Parameter Size

### ISSUE THREAD

**Issue by angelocerr** [TeaSpeak/TeaSpeak#320]
## System Information
***Operating System***: Debian 8
***Operating System Type*** (x86|x64): x86
***TeaSpeak Version***: 1.2.10 beta 2

## Issue
***Reason for reporting this issue***:  Invalid Parameter Size error

***Detailed Description***: i get Invalid Parameter Size error when sinusbot edit some channel with clockbot script. Users Can't connect to server

**Comment by WolverinDEV** [comment]
Should be fixed until version 1.2.10 :)
