### ISSUE TITLE
 Disconnected (Server version is too old to command)

### ISSUE THREAD

**Issue by r4son** [TeaSpeak/TeaSpeak#321]
## System Information
***Operating System***:
Fedora 28, Windows 10, Debian 9, MacOS
***Operating System Type*** (x86|x64):
x64, x64, x64,
***TeaSpeak Version***:
1.2.10 Beta [Build: 1534621808] on Linux

## Issue
***Reason for reporting this issue***:

Disconnected (Server version is too old to command)
Can't connect with TeamSpeak 3.2.0 or higher version to server

***Detailed Description***:

Yesterday I installed on my Debian 8 VPS TeaSpeak, I connected from my phone and it worked. My phone has a TS3 Client version of 3.1.8. 
On my notebook I'm using 3.2.1 and I'm not able to connect.
One of my friends is using 3.1.9 he was able to connect, but than he updates his client to 3.2.0 and 3.2.1 and both failed  to connect. 
Is a fix or an update coming? It would be great, if it would be compatible.

**Comment by MikkelDK** [comment]
Check forum. :) There is guide there.
