### ISSUE TITLE
clientdblist -count don't show all users, only 20

### ISSUE THREAD

**Issue by dennyb** [TeaSpeak/TeaSpeak#322]
**Describe the bug**
When using "clientdblist -count" or "clientdblist duration=1 -count" then normaly all users should be displayed, but unfortunately only 20 users will be displayed

**To Reproduce**
Steps to reproduce the behaviour:
clientdblist start=0 -count (only 20 displayed)
clientdblist duration=1 -count (only serverquery user displayed)

**Expected behaviour**
There is no way to know how many users in total are in the database

**Environment information:**
 Operating system: Debian Linux 9
 TeaSpeak version: v1.2.7-beta [Build: 1534356675]

**Comment by WolverinDEV** [comment]
Command: ```clientdblist duration=1 -count```
Response: 
```
cldbid=1 client_unique_identifier=serveradmin client_nickname=serveradmin client_created=1515698585 client_lastconnected=0 client_totalconnections=1 client_description=I\sdon't\shave\sa\sdescription client_lastip count=1384
error id=0 msg=ok```
