### ISSUE TITLE
Can't set serverpassword via telnet / yatqa

### ISSUE THREAD

**Issue by dennyb** [TeaSpeak/TeaSpeak#323]
**Describe the bug**
Setting new serverpassword via "serveredit virtualserver_password=" is not possible due "invalid password flag"

**To Reproduce**
use 10
error id=0 msg=ok
serveredit virtualserver_password=123
error id=1538 msg=invalid\sparameter extra_msg=Invalid\spassword\sflag
serveredit b_virtualserver_modify_password=123

**Expected behaviour**
Change or remove server password

**Logs**
serveredit b_virtualserver_modify_password=123
notifyserveredited invokerid=2 invokername=serveradmin1 invokeruid=serveradmin reasonid=10
error id=0 msg=ok
serveredit b_virtualserver_modify_password=
notifyserveredited invokerid=2 invokername=serveradmin1 invokeruid=serveradmin reasonid=10
error id=0 msg=ok

**Environment information:**
 Operating system: Debian Linux 9
 TeaSpeak version: Latest TeaSpeak

**Additional context**
Also removing password is not possible

**Comment by WolverinDEV** [comment]
Fixed within build 3 :)
