### ISSUE TITLE
Order by Talk power not working

### ISSUE THREAD

**Issue by menesakdeniz** [TeaSpeak/TeaSpeak#328]
Talk power permission not working properly. I get listed second when i need to get listed first(because i have the higher talk power)

**To Reproduce**
Steps to reproduce the behaviour:
1. Join server
2. Give your self a permission that has talk power
3. Reconnect the server
4. Go to a channel that has a low talk power from you
5. You are going to listing under the client that has lower talk power from you.

 TeaSpeak version: [TeaSpeak-1.2.10b-4]

**Comment by WolverinDEV** [comment]
Sure you're using the latest version?
I already improved / fixed that as well.
Do you may have a proof for example a video?
