### ISSUE TITLE
Disconnected from server (parameter not found)

### ISSUE THREAD

**Issue by SafariGaming** [TeaSpeak/TeaSpeak#329]
<00:32:43> Disconnected from server (parameter not found)

why I'm kicking this way from the server?

**Comment by xRedFox** [comment]
### Please use this template to report a problem:
### https://github.com/TeaSpeak/TeaSpeak/blob/master/.github/ISSUE_TEMPLATE/report-a-bug.md

**Comment by WolverinDEV** [comment]
Should be fixed within version 1.2.10-beta!
