### ISSUE TITLE
Client disconnected (disconnected)

### ISSUE THREAD

**Issue by menesakdeniz** [TeaSpeak/TeaSpeak#330]
**Describe the bug**
Clients get disconnected with "disconnected (disconnected)" message.

**Screenshots**
http://prntscr.com/kkju37

**Logs**
[2018-08-20 03:13:36] [DEBUG]   373 | [xxx.xx.248.233:49754/[Mia]* Tugce] Cant flush io!
[2018-08-20 03:13:36] [DEBUG]   373 | [xxx.xx.248.233:49754/[Mia]* Tugce] Could not get acknowledge for all commands before disconnecting. Acknowledges left: 15
[2018-08-20 03:13:36] [INFO]    373 | Voice client 15865/ZrK5puTW516eCEDNXeQ1+zYdiQA= ([Mia]* Tugce) from xxx.x.248.233:49754 left.

**Environment information:**
 Operating system: Linux localhost.localdomain 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.10b-4]

**Comment by WolverinDEV** [comment]
Ahh shit that meint packet resend failed.
I'll look at this :)

**Comment by WolverinDEV** [comment]
Should be fixed within version 1.2.10-beta!

**Comment by menesakdeniz** [comment]
This problem happened with newest client of 1.2.10-beta-5
did you fix this with 1.2.11 version or not ? cause i can't see anything in changelog about this issue.

**Comment by MikkelDK** [comment]
@menesakdeniz - Do you have try it out? ;) you can too try see on servergroup about `i_client_max_idletime` is enabled or disabled.

**Comment by lbenicio** [comment]
Is this timeout problem linked to `i_client_max_idletime` servergroup property? like, if I want to stop it to let then never timeout just set value 9999....9 to it?

**Comment by MikkelDK** [comment]
@lbenicio i'm pretty sure it will works, if you "delete permission/delete grant permission" on it. ;) i have tested. and no one of my friends/clients got disconnected.

**Comment by menesakdeniz** [comment]
@MikkelDK i checked i_client_max_idletime property, it is not enabled. But the problem still continues.

**Comment by MikkelDK** [comment]
Hmm.. weird. ;/ so dunno. lets hope..it will be fixed..(once) ;)
