### ISSUE TITLE
connect 

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#332]
**Describe the bug**
Mass disconnects & loss of users groups when they rejoin

**To Reproduce**
Happens very randomly and erratically

**Expected behaviour**
Not to DC

**Screenshots**
<15:02:31> "Tyurs" disconnected (disconnected)
<15:02:33> "Grizz1y" disconnected (disconnected)
<15:02:35> "k5o" disconnected (disconnected)
<15:02:36> "ZealousPure" disconnected (disconnected)

**Logs**
In the moment of getting logs.

Using: TeaSpeak-1.2.10-beta-5

**Comment by WolverinDEV** [comment]
Should be fixed at version 1.2.11-beta!
