### ISSUE TITLE
Clients permission is not ordering properly

### ISSUE THREAD

**Issue by menesakdeniz** [TeaSpeak/TeaSpeak#336]
**Describe the bug**
Client permissions is ordering by id asc
please change it to talkpower desc

**To Reproduce**
Steps to reproduce the behaviour:
1. Click someone
2. Look server group or channel group permissions you'll see the permissions ordered by id ascended

**Screenshots**
http://prntscr.com/kkxl0p

**Comment by WolverinDEV** [comment]
Hey,
I don't do anything with the order. 
It's within the TeamSpeak 3 client and it sorts it with the talk power already :)
