### ISSUE TITLE
Server query can't stay connected

### ISSUE THREAD

**Issue by lbenicio** [TeaSpeak/TeaSpeak#338]
**Describe the bug**
I have a Bot which uses the server query interface to do a lot of jobs on the server, the problem is that is cant stay connected 24/7 after like 18-20h it got timed out/socket lost

**To Reproduce**
1. Create a serverquery bot
2. Make it ping each minute to stay alive
3. after 20h it drops the connection

**Expected behaviour**
Serverquery client should stay connected no matter how long the connection is

**Screenshots**
no screenshots

**Logs**
No logs provided

**Environment information:**
 Operating system: ubuntu x64
 TeaSpeak version:  1.2.11-beta-1 

**Additional context**

**Comment by WolverinDEV** [comment]
Well are you sure that this is a TeaSpeak issue and not a general timeout?
May because of a network reboot?

**Comment by lbenicio** [comment]
i think the problem do not appear any more on newer versions
