### ISSUE TITLE
Channel permissions and Cyrillics channels

### ISSUE THREAD

**Issue by FREDisBad** [TeaSpeak/TeaSpeak#339]
The rights of the channel don't remain and channels in Russian aren't created!
Sorry google translate.
Video: https://www.youtube.com/watch?v=u0dMPpHM6Go
TeaSpeak version: [TeaSpeak-1.2.11-beta-1]
Ubuntu 18.04.1 LTS
Logs: https://pastebin.com/6hKjiTvM

**Comment by FREDisBad** [comment]
The problem only with the channels postponed through snapshot at new channels everything remains.
p.s. google translate(

**Comment by WolverinDEV** [comment]
Did you tried to convert the characters to UTF-8?

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
