### ISSUE TITLE
Subscribe and dropping bug

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#342]
**Describe the bug**
When someone joins the channel on being moved sometimes you can't hear or see this person and you have to unsubscribe and subscribe all channels to be able to see him. 

Very often people gets dropped and their teamspeak probably is being crashed.
`<13:07:09> "x" dropped (Packet resend failed)
<13:07:10> "x" dropped (Packet resend failed)
<13:07:10> "x" dropped (Packet resend failed)
<13:07:10> "x" dropped (Packet resend failed)
<13:07:10> "x" dropped (Packet resend failed)
<13:07:11> "x" dropped (Packet resend failed)
<13:07:12> "x" dropped (Packet resend failed)
<13:07:12> "x" dropped (Packet resend failed)
<13:07:13> "x" dropped (Packet resend failed)
<13:07:13> "x" dropped (Packet resend failed)
<13:07:13> "x" dropped (Packet resend failed)
<13:07:13> "x" dropped (Packet resend failed)
<13:07:14> "x" dropped (Packet resend failed)
<13:07:14> "x" dropped (Packet resend failed)`

It dropped me with:
Disconnected from server (parameter not found)

I can't join to the server:
Action currently not possible due to spam protection. Please wait a few seconds and try again.

When I delete the channel where there are 3 people for example it drops people massively.

**To Reproduce**
Steps to reproduce the behaviour:
3. Setting to apply '....'

**Expected behaviour**

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: (`uname -a`)
 TeaSpeak version: [TeaSpeak-1.1.40-beta-1]

**Additional context**

**Comment by WolverinDEV** [comment]
Fixed within the newest version :)

**Comment by DanielAlves123** [comment]
@WolverinDEV Disconnected from server (parameter not found)

**Comment by DanielAlves123** [comment]
Disconnected from server (invalid clientID)

**Comment by DanielAlves123** [comment]
Disconnected from server (channel name is already in use)

**Comment by DanielAlves123** [comment]
@WolverinDEV

**Comment by Denver3D** [comment]
I can confirm invisible people until I unsubscribe and subscribe all channels again :(
