### ISSUE TITLE
Channelgroup talk power. Not updating

### ISSUE THREAD

**Issue by SafariGaming** [TeaSpeak/TeaSpeak#343]
https://ibb.co/g5Vjvz
https://ibb.co/chbPvz
https://ibb.co/fZsa2e

My English is not good. I don't understand what you wrote on the form. I am already using last version "Linux x64 | 1.2.11-beta-1". Not fixed this !

**Comment by SafariGaming** [comment]
When a person gives a channel group, the speech authority is not updated.

**Comment by WolverinDEV** [comment]
Im sorry. I forget it. Fixed within the next build :)
