### ISSUE TITLE
Huge issue with ban  

### ISSUE THREAD

**Issue by NotYourMajesty** [TeaSpeak/TeaSpeak#344]
**Describe the bug**
This problem is important. When I ban a person on my server, one or more people on the server are also banned. I do not know where this problem comes from. People banned in addition to the target do not appear in the list of banned.

**To Reproduce**
Just ban a member and see

**Environment information:**
 Operating system: (`Debian 9`)
 TeaSpeak version: [TeaSpeak-1.2.10-beta-5]

**Comment by WolverinDEV** [comment]
Can you please provide debug or verbose logs?

**Comment by katrio022** [comment]
Same problem here, newest version 1.2.11 beta 2. List of bans is clear.

**Comment by Sickness-chan** [comment]
I can confirm this, heard about it twice already. Apparently when you ban someone, someone else will also get banned at the same time for whatever reason, and the bans list will not have an entry. Little chatlog snippet:

```Stusse Last Monday at 9:45 PM
Ok the strangest thing now happened
An admin banned one guy, but two got banned
Only one instance was found in Ban List though

Acnologia Last Monday at 9:45 PM
U got logs?

Stusse Last Monday at 9:45 PM
<21:41:57> "Khrosnickov" was banned permanently from the server by "Deec" (bye)
<21:41:57> "Cron Dham" was banned permanently from the server by "Deec" (bye)

Acnologia Last Monday at 9:45 PM
I heard of that before too

Stusse Last Monday at 9:45 PM
He was supposed to ban Khrosh
And I found no Ban List entry for Cron Dham

Acnologia Last Monday at 9:46 PM
Give me the ip of khros and ill shitlist him in firewall

Stusse Last Monday at 9:46 PM
I mean now both are unbanned
It was on joke
But I am not sure if Cron Dham was ever even banned
For safety I banned Dham and unbanned it
since I couldnt find an entry for it
But not sure he was even at one point banned as well as collateral
weird anyhow

Acnologia Last Monday at 9:49 PM
Cant u ask him if he got kicked when that first ban happened?

Stusse Last Monday at 9:49 PM
he did

Acnologia Last Monday at 9:49 PM
Prob was banned then

Stusse Last Monday at 9:49 PM
asking if he was banned at all
<21:44:38> "Cron Dham" connected to channel "Silent Lobby"
so yea he was kicked
but idk I couldnt find anything on yatqa for that guy being banned
```

**Comment by katrio022** [comment]
Problem still exists on newest version (1.2.12)

**Comment by Sickness-chan** [comment]
Did he ever say it wouldn't be in this version?

**Comment by WolverinDEV** [comment]
Well there isnt a fix actiually, you propely banned the other clients as well because the have the same IP | UUID | Hardware ID | name.
But there is within the next version more debug within the log (if debug is enabled) where you can see why they got banned.

**Comment by katrio022** [comment]
They don't have anything same, it's very strange and random.

**Comment by NotYourMajesty** [comment]
Yes, it's totally random, they have nothing in common. I checked their IP, their Teamspeak ID, their name (...) nothing similar.

**Comment by WolverinDEV** [comment]
May the HWID :)
As I said, there is a detailed message within the debug log :)

**Comment by WolverinDEV** [comment]
Probably fixed (Else you can watch information within the log)
