### ISSUE TITLE
Arabic Letters In Channel Name

### ISSUE THREAD

**Issue by iJosephY** [TeaSpeak/TeaSpeak#345]
**Describe the bug**
When i try to name a chennel in arabic i got an invalid channel name error
Creating spacers in arabic works fine, the issue is only in rooms

**Environment information:**
 Operating system: (`Ubuntu 16.04`)
 TeaSpeak version: [TeaSpeak-1.2.11b]

**Comment by WolverinDEV** [comment]
Yeah,
I know Cyrillic  characters doesn't work as well :)

**Comment by iJosephY** [comment]
Also when i create a temporary room .. then i change 
Max Users to Limited and Family Max Users 
the server crash

**Comment by WolverinDEV** [comment]
Duplicate of #339
