### ISSUE TITLE
Problem with client list

### ISSUE THREAD

**Issue by katrio022** [TeaSpeak/TeaSpeak#348]
**Describe the bug**
When I search for user by Permissions > List all clients I get "Disconnected from server (parameter not found)".
One more problem with client list - when I enter Server Groups, then I choose group with many users TeamSpeak hangs and turn off. On normal TeamSpeak there wasn't any problem with that.

**To Reproduce**
Just enter List all clients and search.

**Expected behaviour**
No problem, list of clients.

**Logs**
"Disconnected from server (parameter not found)".

**Environment information:**
 Operating system: Debian 8
 TeaSpeak version: [TeaSpeak-1.2.11-beta-2]

**Comment by Chazotu** [comment]
Pleae provide us as screenshot

**Comment by katrio022** [comment]
Screenshot of what? I'm getting disconnected with "Disconnected from server (parameter not found)", that's all.

**Comment by DrN00bish** [comment]
Confirmed though

**Comment by WolverinDEV** [comment]
Ahh seems like you search for something not existing and I missed to send you the database empty result error :)

**Comment by katrio022** [comment]
But second problem is a little different, looks like perfomance issue.

"One more problem with client list - when I enter Server Groups, then I choose group with many users TeamSpeak hangs and turn off. On normal TeamSpeak there wasn't any problem with that."

**Comment by DrN00bish** [comment]
https://github.com/TeaSpeak/TeaSpeak/issues/348#issuecomment-415016547

Firstly are you saying I don't exist? That would explain why people overlook me ever so often lol

And secondly. The search feature isn't working yet?

**Comment by WolverinDEV** [comment]
Hmm well I can't really tell you why TeamSpeak hangs up but you see if a command needs a long time to proceed there is a error :)

**Comment by WolverinDEV** [comment]
Cant reproduce that bug anymore.
May try the newest version which ill release within the next hours
