### ISSUE TITLE
Servery notify for servergroupadd and servergroupdel not work

### ISSUE THREAD

**Issue by lbenicio** [TeaSpeak/TeaSpeak#349]
**Describe the bug**
The server query events for `servergroupadd` and `servergroupdel` are not working properly. i just subscribed to all events and it only report back the normal teamspeak events.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login to serverquery
2. subscribe to all events

**Expected behaviour**
should send back information when a user add or delete a server group for other user

**Screenshots**
no screenshots.

**Logs**
no logs.

**Environment information:**
 Operating system: ubuntu x64
 TeaSpeak version: 1.2.11-beta-2

**Comment by WolverinDEV** [comment]
Do you use a specific framework?
Did you see the client?

**Comment by lbenicio** [comment]
I'm using a node-teamspeak-api. It was working fine with teamspeak for over 100 days without socket tomeout

**Comment by WolverinDEV** [comment]
May the node api filters this new events :)

**Comment by lbenicio** [comment]
i tried over serverquery using telnet directly from terminal and still wasn't seeing the triggers

**Comment by WolverinDEV** [comment]
Fixed within the next version
