### ISSUE TITLE
Add sender to plugincmd

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#35]
Please add a sender identifier to `notifyplugincmd`

Something like:
```
notifyplugincmd name=test data=test sender=1
```

**Comment by Bluscream** [comment]
Implemented in 1.0.14-beta

**Comment by Bluscream** [comment]
Maybe rename it to `invokerid=1` to stay with Teamspeak's naming conventions.

**Comment by WolverinDEV** [comment]
I would add this name converting later

**Comment by WolverinDEV** [comment]
Implemented in 1.0.17-Beta
