### ISSUE TITLE
Last Version Start Bug

### ISSUE THREAD

**Issue by SafariGaming** [TeaSpeak/TeaSpeak#351]
WARNING ! For security reasons we advise: DO NOT RUN THE SERVER AS ROOT
!!!!!!!!!!!
Starting the TeaSpeak server./teastart.sh: line 64: cat: command not found
./teastart.sh: line 73: cat: command not found

Could not start TeaSpeak server.
Last log entries:
./teastart.sh: line 80: cat: command not found

Linux x64 | 1.2.11-beta-2 

Linux virtual-machine 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SafariGaming** [comment]
I fixed.

`sudo apt-get install --reinstall core-utils`

**Comment by MikkelDK** [comment]
it's not recommended to run TeaSpeakServer as root user! :)
