### ISSUE TITLE
Query command channellist: -flags argument is not working since TeaSpeak version 1.2.11-beta2

### ISSUE THREAD

**Issue by Stefan1200-de** [TeaSpeak/TeaSpeak#353]
**Describe the bug**
Using the query command **channellist -flags -secondsempty** in my JTS3ServerMod, the **-flags** argument is not working since TeaSpeak version 1.2.11-beta2. In TeaSpeak version 1.2.10-beta2 the **-flags** argument was working, like in TeamSpeak 3.

TeaSpeak version 1.2.11-beta2:
> channellist -flags -secondsempty
cid=1 pid=0 channel_name=[cspacer01]┏╋━━━━━━◥◣◆◢◤━━━━━━╋┓ channel_order=0 total_clients=0|cid=2 pid=0 channel_name=[cspacer02]\sTeaSpeak\sServer channel_order=1 total_clients=0|cid=3 pid=0 channel_name=[cspacer03]┗╋━━━━━━◥◣◆◢◤━━━━━━╋┛ channel_order=2 total_clients=0|cid=4 pid=0 channel_name=[cspacer04]Default\sChannel channel_order=3 total_clients=0

TeaSpeak version 1.2.10-beta2:
> channellist -flags -secondsempty
cid=1 pid=0 channel_name=[cspacer01]┏╋━━━━━━◥◣◆◢◤━━━━━━╋┓ channel_order=0 total_clients=0 channel_flag_default=0 channel_flag_password=0 channel_flag_permanent=1 channel_flag_semi_permanent=0|cid=2 pid=0 channel_name=[cspacer02]\sTeaSpeak\sServer channel_order=1 total_clients=0 channel_flag_default=0 channel_flag_password=0 channel_flag_permanent=1 channel_flag_semi_permanent=0|cid=3 pid=0 channel_name=[cspacer03]┗╋━━━━━━◥◣◆◢◤━━━━━━╋┛ channel_order=2 total_clients=0 channel_flag_default=0 channel_flag_password=0 channel_flag_permanent=1 channel_flag_semi_permanent=0|cid=4 pid=0 channel_name=[cspacer04]Default\sChannel channel_order=3 total_clients=0 channel_flag_default=1 channel_flag_password=0 channel_flag_permanent=1 channel_flag_semi_permanent=0

**To Reproduce**
Using query interface and use the query command:
channellist -flags -secondsempty

**Environment information:**
 Operating system: Debian 8 (3.16.0-4-amd64)
 TeaSpeak version: [TeaSpeak-1.2.11-beta2]

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
