### ISSUE TITLE
Disconnect for no reason

### ISSUE THREAD

**Issue by katrio022** [TeaSpeak/TeaSpeak#354]
**Describe the bug**
I'm being disconnected with no reason.

**To Reproduce**
I'm just on TeamSpeak (muted) and pow! Disconnected with error.

**Expected behaviour**
No disconnect.

**Screenshots**
![image](https://user-images.githubusercontent.com/7473277/44483392-3e226680-a64b-11e8-98c3-28fc44561dff.png)

**Logs**
Above.

**Environment information:**
 Operating system: Debian 8
 TeaSpeak version: [TeaSpeak-1.2.11-beta-2]

**Comment by katrio022** [comment]
Other error:
![image](https://user-images.githubusercontent.com/7473277/44487706-3ff22700-a657-11e8-9c00-e146f92454b6.png)

**Comment by slushpuppy** [comment]
![image](https://user-images.githubusercontent.com/1729407/44564371-21924580-a795-11e8-8806-3ded8e7f9907.png)
Same issue for me

**Comment by WolverinDEV** [comment]
Should be improved within the next version :)

**Comment by WolverinDEV** [comment]
Need test if this still exists.

**Comment by KevinCaruZo** [comment]
http://prntscr.com/ks5bf1
