### ISSUE TITLE
Enabling 3.1 Protocol don't let 3.2.X clients connect

### ISSUE THREAD

**Issue by iJosephY** [TeaSpeak/TeaSpeak#356]
**Describe the bug**
in client 3.2.x they dropped support for pre-3.1 servers
enabling the protocol in config don't make a difference 
3.2 users can't connect
is this a bug or it's not implemented yet ?

 Operating system: (`Ubuntu 16.04`)
 TeaSpeak version: [TeaSpeak-1.2.11b]

**Comment by MikkelDK** [comment]
You need to update the protocol_key.txt :) so it's not a bug. Just the file needed to be updated.

**Comment by Sickness-chan** [comment]
https://gist.github.com/Bluscream/5531ceefd86fcf7efc0c5519072fb2d6

**Comment by iJosephY** [comment]
So i should just copy the lines in the link above
or delete my current one and it will regenerate?!

**Comment by MikkelDK** [comment]
Just copy from the link. And it will works.

**Comment by iJosephY** [comment]
Thanks ♥
