### ISSUE TITLE
Delete afk server by Default server token

### ISSUE THREAD

**Issue by DWKevinos** [TeaSpeak/TeaSpeak#358]
Hello,

Would it be possible for you to add a system that will delete the afk server with the token that is not used after x time? 

Table: tokens server id : Default server token for the server admin.

I already have a php script, but it would be nice if it would be in teaspeak config

**Comment by WolverinDEV** [comment]
You mean when nobody uses the default token to delete it, after a predefined amount of time?

**Comment by DWKevinos** [comment]
Yes delete the server

**Comment by WolverinDEV** [comment]
It's already implemented. There is a property where you see the last user join and leave so you can create a script which deletes server which are older that n days
