### ISSUE TITLE
Error accepting new clients / CPU usage through the roof

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#359]
**Describe the bug**
TeaSpeak is causing 100% CPU usage and my logs are being spammed with this error:
```2018-08-24 22:27:15] [ERROR]  FILE | Having an error while accepting a new client. (24/Too many open files)```

**To Reproduce**
No idea how to reproduce it

**Expected behaviour**
Shouldn't happen, the server is only up for about 1.5 hours

**Screenshots**
https://i.killuminati.eu/6845s865b.webm
https://i.killuminati.eu/68439862Q.png

**Logs**
Spams this error multiple thousand times per second
```2018-08-24 22:27:15] [ERROR]  FILE | Having an error while accepting a new client. (24/Too many open files)```

**Environment information:**
 Operating system: Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.12-beta]

**Comment by WolverinDEV** [comment]
Well it seems like there is/was a file Spam or there is a file issue.
In general there is a critical failure with opening and/or closing files.
I'll look at that later (currently trying to resolve the memory leak :))

**Comment by Sickness-chan** [comment]
Found a crash dump too, maybe contains something useful https://transfer.sh/M4vao/crash_dump_3dff614c-cf5c-480c-98c16fa1-f93dcc48.dmp

**Comment by Sickness-chan** [comment]
Seems to become a common issue for me now, happens very frequently that it starts spamming the logs with that error

**Comment by WolverinDEV** [comment]
Hmm well,
in general the error means that for some reason the file server cant accept new clients because already a lot of clients have been connected.

Well i know that the server sometimes crashes when you stop it, but that should not be that big issue :)

**Comment by Sickness-chan** [comment]
Weird that it ends up in this infinite loop tho, and spams as hard as it can https://i.killuminati.eu/6866J571n.webm

**Comment by WolverinDEV** [comment]
Yeah its just hanging up a restart is the only possibility.
You can count the open file descriptors by executing `ls -la /proc/<TeaSpeakServer pid>/fd/ | wc -l`
Can I ask you how many virtual server you have running?

**Comment by Sickness-chan** [comment]
teaspeak@debian:~$ ls -la /proc/101127/fd/ | wc -l
1027
teaspeak@debian:~$ ls -la /proc/101241/fd/ | wc -l
1027

Got a total of 60 virtual servers, 19 of which are running and 41 are just always shut down and don't have autostart enabled.

**Comment by WolverinDEV** [comment]
Well with just 1027 open file descriptors it should not be an issue to open another one.
Is it possible that you have really low system limits?

**Comment by Sickness-chan** [comment]
Dunno, it's a fresh Debian 9 VM with nothing touched except setting up TeaSpeak

After restarting they all seem to have 179 file descriptors

```teaspeak@debian:~$ ls -la /proc/19443/fd/ | wc -l
179
teaspeak@debian:~$ htop
teaspeak@debian:~$ ls -la /proc/19481/fd/ | wc -l
179
teaspeak@debian:~$ ls -la /proc/19453/fd/ | wc -l
179
```

**Comment by Sickness-chan** [comment]
Nevermind, it's all of the TeaSpeak processes that have 1027 open file descriptors when it happens, even tho not all of them have that high CPU usage.

**Comment by Sickness-chan** [comment]
```
teaspeak@debian:~$ cat /proc/sys/fs/file-max
811452
teaspeak@debian:~$ ulimit -Hn
1048576
teaspeak@debian:~$ ulimit -Sn
1024
```
So apparently the soft limit for the `teaspeak` user is 1024, I'll try increasing it and report back. I'll increase it to 16384.

**Comment by Sickness-chan** [comment]
It's been stable for longer now, but now after 21h~ it's got 2400 open file descriptors, maybe the problem is that it never closes some of them, hence they stack up and it runs into the limits? Even after starting the server it'll have 179 open file descriptors and that number won't change.

**Comment by WolverinDEV** [comment]
Hmm well i cant really understand why it dosnt close any of them (Or some of them).
179 is normal because each server uses a fd for a sockert where its listening on.
(E.g. for ipv4 and v6 binding each vs needs 2)

**Comment by Sickness-chan** [comment]
24h uptime, uploaded 13 files in a queue, it closed those descriptors as you can see below, but not sure where the other 4k come from. Those don't go away at all.

teaspeak@debian:~$ date
Sat Sep  1 11:24:41 CEST 2018
teaspeak@debian:~$ ls -la /proc/797/fd/ | wc -l
4119
teaspeak@debian:~$ ls -la /proc/797/fd/ | wc -l
4123
teaspeak@debian:~$ ls -la /proc/797/fd/ | wc -l
4119
teaspeak@debian:~$ ls -la /proc/797/fd/ | wc -l
4121
teaspeak@debian:~$ ls -la /proc/797/fd/ | wc -l
4119
teaspeak@debian:~$ ls -la /proc/797/fd/ | wc -l
4119

**Comment by WolverinDEV** [comment]
Haha they are like TeamSpeak's queries :D
I'll look at that :)

**Comment by WolverinDEV** [comment]
May be fixed within the newest version (Implemented a file transfare timeout)

**Comment by Sickness-chan** [comment]
Are you gonna publish a build that I can test tonight?

**Comment by WolverinDEV** [comment]
Well not sure may :)

**Comment by WolverinDEV** [comment]
Is the file "issue" fixed?

**Comment by Sickness-chan** [comment]
Probably, don't have alot of activity anymore so not sure. But there seems to be just 179 descriptors open as if the instance just started

**Comment by WolverinDEV** [comment]
top :) And sad to hear :/ Why not?
