### ISSUE TITLE
Channel delete power

### ISSUE THREAD

**Issue by batizisanya** [TeaSpeak/TeaSpeak#361]
**Describe the bug**
Now when example serveradmin create a channel, (serveradmin have channel_delete_power 75) channel create with needed delete power 0. On teamspeak, the channel created needed power. (At this example with 75)

**Expected behaviour**
When a group with channel_delete_power set, create a group, set the created channel needed_delete_power to creator's channel_delete power.

**Comment by WolverinDEV** [comment]
Fixed within the next version :)
