### ISSUE TITLE
[BUG] Permission is not saved after change

### ISSUE THREAD

**Issue by GoRiLliAz** [TeaSpeak/TeaSpeak#365]
**Describe the bug**
Since have passed me on teaspeak, have me viewer on me site no longer works.
So I decided to look at why I look so rights and permission is to me a big surprise in  "Guest " Any permissions that allows to see the server info Nothing is active, I activate them closes the authorization page but nothing works I Come back, I can't see anything checked. 
I do the same try but leaving the page open the It works as soon as I close the Permissions page this removes all 

**To Reproduce**
Steps to reproduce the behaviour:
3. Setting to apply '....'

**Expected behaviour**
The authorization must remain saved

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 TeaSpeak version: [TeaSpeak-1.2.3-beta-1]

**Additional context**

**Comment by Chazotu** [comment]
Use YATQA and use our Template corect please

**Comment by GoRiLliAz** [comment]
which template?

**Comment by Chazotu** [comment]
Use telnet

**Comment by GoRiLliAz** [comment]
i use telnet, i just report bug but ok bye.
