### ISSUE TITLE
iOS client mic/speak bugs

### ISSUE THREAD

**Issue by targaryen94** [TeaSpeak/TeaSpeak#367]
If i join to a teaspeak server as ios client, i can speak but others in the room can't hear me.

https://imgur.com/a/RrRoX04

Operating system: Linux admin 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
TeaSpeak version: 1.2.13-beta3

**Comment by WolverinDEV** [comment]
Is this error continuously?

**Comment by WolverinDEV** [comment]
Android as well?

**Comment by targaryen94** [comment]
In my experience no

**Comment by sorajate** [comment]
already face this problem ios cannot talk.

**Comment by WolverinDEV** [comment]
In general solved?

**Comment by SafariGaming** [comment]
the microphone and speak bugs have fixed. I have not tried everything in general.

**Comment by Chazotu** [comment]
Applying Again in latest version
