### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#368]
**Describe the bug**
Groups that do not have the `i_channel_join_power` permission set can not join channels that require 0 join power.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a group with no `i_channel_join_power` permission assigned, e.g. guest
2. Try to join a channel with 0 required join power needed
3. Join attempt will fail with `Unzureichende Client Rechte (gescheitert an i_channel_join_power)`

**Expected behaviour**
Join should work as the required value is 0

**Screenshots**
https://i.killuminati.eu/6869p652T.webm

**Environment information:**
 TeaSpeak version: [TeaSpeak-1.2.13-beta-3]

**Additional context**
Same thing should apply to all other scenarios where no permission is set and only a 0 value is required.

**Comment by batizisanya** [comment]
Same issue with channel's permission view power.

**Comment by Fastmancz** [comment]
Same.

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
