### ISSUE TITLE
Download anchor on website

### ISSUE THREAD

**Issue by exp111** [TeaSpeak/TeaSpeak#37]
Shouldn't the link in the about section point to [the download anchor](https://www.teaspeak.de/#download) instead of [the top anchor](https://www.teaspeak.de/#) ?

**Comment by WolverinDEV** [comment]
Hmm well i guass i forgot to change some tags :)
Thanks man i will fix it later

**Comment by exp111** [comment]
Btw the repo has as a tag ‚teamsepak‘.

**Comment by WolverinDEV** [comment]
Yeah i already regonice that :)

And the anchor is a problem with the size.
If you're using these anchros on a smaller display all works :)

**Comment by exp111** [comment]
Doesn‘t work on mobile or smaller size (desktop, chrome) for me. 
It gets fixed for me by linking it to #download. 
Maybe it‘s just a problem for me^^

**Comment by WolverinDEV** [comment]
Oh well than i already changed it localy :D
