### ISSUE TITLE
[Question] Memory and teaspeak

### ISSUE THREAD

**Issue by GoRiLliAz** [TeaSpeak/TeaSpeak#371]
Hello,
It's normal that teaspeak uses so much memory?
Here's a screenshot for 2 virtual server and 13 people connected

![teaspeak](https://user-images.githubusercontent.com/18401955/44672541-0b041c80-aa29-11e8-8275-34de9c533d25.PNG)

**Comment by WolverinDEV** [comment]
Whats wrong there?
58MB memory isn't that much?

**Comment by GoRiLliAz** [comment]
2.9% ( now 3% ) multiple by number of process is running it's too much after 2 heures 11 m open

**Comment by WolverinDEV** [comment]
There isnt a leak.
And 60MD is totally acceptable.

**Comment by GoRiLliAz** [comment]
Okay, thanks for the information.
