### ISSUE TITLE
Avatars of 3.0.x clients are not shown on other users.

### ISSUE THREAD

**Issue by Stitch626** [TeaSpeak/TeaSpeak#373]
**Describe the bug**
Its not possible to see avatars of users with version 3.0.x but users with such a old version can see avatars of newer clients.

**To Reproduce**
Steps to reproduce the behaviour:
Connect one or more clients with version 3.0.x (in my case 3.0.18.2) to a server, set/change your avatar and check if other users can see them. If you connect with a newer client, set your avatar, change back to old client version (with same identity) the avatar works as expected.

**Expected behaviour**
The avatar should be visible for both older and newer clients.

**Environment information:**
 Operating system: Debian 9, kernel 4.15.18
 TeaSpeak version: [TeaSpeak-1.2.13-beta4]

**Additional context**
None.

**Comment by Chazotu** [comment]
Update your Client ?

**Comment by Stitch626** [comment]
How about no? 

Bugfix ftw!

**Comment by MypowerHD** [comment]
It's not a Bugfix. Update your Client. it's a Teamspeak Client Bug.

**Comment by Chazotu** [comment]
That a TeamSpeak Bug Avatar IDs are new generated you have to update your client

**Comment by Stitch626** [comment]
But in the original ts3 server it worked even with those old clients. If I connect once with a newer client, change my avatar and switch back to the older one (with the same identity) it works...
But if I connect with the older one (and a new identity) I'm able to set a avatar but other clients (even on the same version) doesn't show my avatar.

There is no reason to close the issue with the reason "update your client" thats stupid.
If you don't understand the problem correctly I'll write it in german....

**Comment by MypowerHD** [comment]
Dude, update your TeamSpeak Client. Your Client is Outdated.

**Comment by Stitch626** [comment]
Dude, I don't care. I'm using TeaSpeak to use my old client... It seems the avatar/filetransfer has a bug somehow.. Avatar files of newer clients are readable but those made by 3.0.x ones arent.
