### ISSUE TITLE
server kick user with error nickname is already in use

### ISSUE THREAD

**Issue by ariaieboy** [TeaSpeak/TeaSpeak#374]
hello 
I have a problem with the teaspeak server, which is that the server automatically kicking random users out of the server with this error "Disconnected from server (nickname is already in use)"

I tried teaspeak version 1.2.10b and 1.2.13b on ubuntu 16.04 lts 

I have a sinusbot in my server If it relates to this problem

**Comment by MikkelDK** [comment]
Update to the newest version.

**Comment by ariaieboy** [comment]
i update it 30min ago to version 1.2.13b and still i have this issue

**Comment by WolverinDEV** [comment]
So its may an Issue with multi threading.
Thats a littlebit unbelievable but may possible. (Does is just kickouts some users or all?)

**Comment by WolverinDEV** [comment]
Should be fixed already :)

**Comment by ariaieboy** [comment]
same problem on teaspeak 1.2.15-beta8

**Comment by WolverinDEV** [comment]
Hmm any steps to reproduce or is it just randomly?
May can you think about a query related issue?

**Comment by ariaieboy** [comment]
its happened randomly again

**Comment by ariaieboy** [comment]
any progress ?
I realized that this happens when there are more members.
like 10 or more

**Comment by WolverinDEV** [comment]
Test out version 1.2.20-beta2

**Comment by WolverinDEV** [comment]
This bug should be fixed with version 1.2.22 :)
