### ISSUE TITLE
invalid channel name

### ISSUE THREAD

**Issue by ariaieboy** [TeaSpeak/TeaSpeak#375]
I am using teaspeak 1.2.13b on ubuntu 16.04 lts and when i want to create channel with UTF-8 characters like persian letters i get an error that says "Invalid channel name"

an example of what name i am saying is "┣❉تست"
"تست"
"©"
and etc

**Comment by WolverinDEV** [comment]
Please use the issue template!
Are you using the newest version?

**Comment by Chazotu** [comment]
Works in latest version just update

**Comment by ariaieboy** [comment]
I said in the first line that I use 1.2.13b on Ubuntu 16.04 lts and it's the latest version
