### ISSUE TITLE
insufficient client permissions (failed on b_client_use_bbcode_url)

### ISSUE THREAD

**Issue by Home-Network** [TeaSpeak/TeaSpeak#376]
**Describe the bug**
can't update the channel description

**To Reproduce**
Steps to reproduce the behaviour:
1. Edit a channel
2. Set the description to :

[center][b]url.com[/b][/center]

[color=#ff0000]Hello [/color][color=#3399ff]friends ![/color]

[url]www.url.com[/url]

failed on b_client_use_bbcode_url is checked with grant 100.

**Expected behaviour**
The server should modify the description of channel as well.

**Environment information:**
 Operating system: (`uname -a`) Debian 9 x64
 TeaSpeak version: TeaSpeak-1.2.13-beta-4

**Additional context**
it should be fixed since some days ...

**Comment by Chazotu** [comment]
Works fine seems like you have configured your permissions wrong
