### ISSUE TITLE
Channel Min Depth - Max Depth

### ISSUE THREAD

**Issue by Fastmancz** [TeaSpeak/TeaSpeak#377]
**Describe the bug**
You can create a sub-channel anywhere you want.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'your teamspeak server'
2. Click on 'some room'
3. Click right mouse on the room
4. Create Sub-Channel
5. Sub-Channel created regardless of the permissions

**Expected behaviour**
Rejection due to insufficient permissions.

**Screenshots**
-

**Logs**
-

**Environment information:**
 Operating system: (`Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux`)
 TeaSpeak version: [`TeaSpeak-1.2.13-beta-4`]

**Additional context**
-

**Comment by Chazotu** [comment]
Cant Reproduce

**Comment by Fastmancz** [comment]
Hello Chazotu, b_channel_create_child is allowed but i_channel_min_depth and i_channel_max_depth are set to 0. So they shouldn't be able to create a sub channels. Can you help me, where is the problem?

**Comment by Chazotu** [comment]
Just tested it again whit a clean group and clear cache cant Reproduce it whit just the perms from you abouth

**Comment by WolverinDEV** [comment]
`i_channel_min_depth` and `i_channel_max_depth` isnt supported :D

**Comment by WolverinDEV** [comment]
Implemented within the next build
