### ISSUE TITLE
please make for windows

### ISSUE THREAD

**Issue by ali6344** [TeaSpeak/TeaSpeak#378]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 07artem132** [comment]
Hi, this request was created earlier: https://github.com/TeaSpeak/TeaSpeak/issues/129

**Comment by Chazotu** [comment]
#252

**Comment by Chazotu** [comment]
#252
