### ISSUE TITLE
Invalid channel order

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#381]
**Describe the bug**
Can't connect to the server after updating from `1.2.13-beta-4` to `1.2.13-beta-6`, connection error is `<03:59:54> Von Server getrennt (invalid channel order)`

**To Reproduce**
Not sure, update between those 2 versions?

**Expected behaviour**
Channel order doesn't get messed with for no apparent reason

**Logs**
Log from when I started the server on `1.2.13-beta-6`, it seems to have modified some channel properties for whatever reason. https://transfer.sh/50GLk/log_2018-08-30_03-57-22_general.log

**Environment information:**
 Operating system: Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.13-beta-6]

**Comment by WolverinDEV** [comment]
Did it fixed after a restart or is it continuously?
Is it possible to provide the database to inspect it and see why there is an invalid order?

**Comment by Sickness-chan** [comment]
Idk, I just went back to 1.2.13-beta-4 and it was fine again. I'll check again tonight and provide the DB if it happens again.

**Comment by WolverinDEV** [comment]
Well is there any way to reproduce it maybe?

**Comment by Sickness-chan** [comment]
Sent you a PM with a log + the database on the forum, as I ran into some problems when trying to update to 1.2.15-beta again

**Comment by WolverinDEV** [comment]
Should be fixed within build 1

**Comment by Sickness-chan** [comment]
Getting invalid channel order again on beta-8, specifically on the server on port 9987

**Comment by WolverinDEV** [comment]
Shit...
Do you have a snapshot and or a database with this constantly error?

**Comment by Sickness-chan** [comment]
Sent the DB + some info on the forum

**Comment by WolverinDEV** [comment]
Hmm I could connect.
I just started the server and it worked fine :)

![http://img.mcgalaxy.de/Screenshot-10-53-08.png](http://img.mcgalaxy.de/Screenshot-10-53-08.png)

**Comment by Sickness-chan** [comment]
I see what you mean, I took the same DB and server version and tried to trigger it on another host, but I couldn't make it happen there for some reason, restarted about 10 times

**Comment by REDMONDS** [comment]
@WolverinDEV "invalid channel order" Maybe you should throw users into the default channel instead of this error? How's the idea?

**Comment by WolverinDEV** [comment]
@Sickness-chan 
According to the packet log its obvious why the client disconnects.
It was according to (I described it somewhere I dont know where anymore) the algorithm how users join and which channel they get.
I know that there was a update within the latest build, which should have fixed that.
