### ISSUE TITLE
Server Starting Problem

### ISSUE THREAD

**Issue by SafariGaming** [TeaSpeak/TeaSpeak#382]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
3. Setting to apply '....'

**Expected behaviour**

**Screenshots**

**Logs**

> userr@userr-virtual-machine:~/ts$ ./teastart.sh start
> -bash: ./teastart.sh: Permission denied
> userr@userr-virtual-machine:~/ts$ sudo ./teastart.sh start
> [sudo] password for userr:
> WARNING ! For security reasons we advise: DO NOT RUN THE SERVER AS ROOT
> !!!!!!!!!!!
> Starting the TeaSpeak serverERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> .ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> 
> Could not start TeaSpeak server.
> Last log entries:
> ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Environment information:**
 Operating system: Linux userr-virtual-machine 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 TeaSpeak version: TeaSpeak-1.2.13-beta-6.tar.gz

**Additional context**

**Comment by SafariGaming** [comment]
This Version Working : TeaSpeak-1.2.11-beta-2.tar.gz

**Comment by WolverinDEV** [comment]
Please ensure that you're starting the server within the server directory.

**Comment by PutoPT** [comment]
try chown 777 teastart.sh 
TeaSpeak can't run in root user

**Comment by SafariGaming** [comment]
-bash: ./teastart.sh: Permission denied
without ROOT!

**Comment by Najsr** [comment]
That's because you don't have the rights to execute it. Go and learn some of Linux basics :)

**Comment by SafariGaming** [comment]
ROOT is required to execute. You do not run it with root. What am I supposed to do then?

**Comment by SafariGaming** [comment]
```

userr@userr-virtual-machine:~/ts$ ./teastart_minimal.sh start
ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
./TeaSpeakServer: error while loading shared libraries: libjemalloc.so.2: cannot open shared object file: No such file or directory
ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
userr@userr-virtual-machine:~/ts$ ./teastart.sh start
Starting the TeaSpeak server
TeaSpeak server could not start (PID == 0)
userr@userr-virtual-machine:~/ts$

```

**Comment by SafariGaming** [comment]
I solved the problem of opening but this time TeamSpeak 3 does not enter. He was entering in the old version.

**<19:27:32> Disconnected from server (invalid channel order)**

**Comment by WolverinDEV** [comment]
Can you enable the verbose log? 
And my make a packet log with TS3Hook?

**Comment by WolverinDEV** [comment]
Seems like,
just saw that one im sorry for the delayed response (this actually fall over :D)

**Comment by SafariGaming** [comment]
> Can you enable the verbose log?

How?

**Comment by SafariGaming** [comment]
:D I was going to look at the channels from YatQA. I compared this image.

https://ibb.co/kuMdee

**Comment by SafariGaming** [comment]
you will not find a solution. I am trying to fix the channel order using the sqlite browser.

**Comment by SafariGaming** [comment]
I solved it by sacrificing 100 channels from 1200 channels :( I'll open it again.

**Comment by WolverinDEV** [comment]
Well thats actually bad to head.
I would be interested within the database and all its channel to reproduce your bug.
