### ISSUE TITLE
Crash during Startup

### ISSUE THREAD

**Issue by hardwii** [TeaSpeak/TeaSpeak#383]
Clean install 
crashes with this error:

[CRITICAL]   GEN | Missing default server guest template group!

doesnt matter if it first execute with root or with the .sh´s
same error every time

happens on current version 1.2.13-beta-6 
debian 9 64Bit

[log_2018-08-31_17_38_54_general.txt](https://github.com/TeaSpeak/TeaSpeak/files/2340716/log_2018-08-31_17_38_54_general.txt)
[crash_dump_be319ba0-64e9-483f-d04765a9-cac90636.zip](https://github.com/TeaSpeak/TeaSpeak/files/2340717/crash_dump_be319ba0-64e9-483f-d04765a9-cac90636.zip)

**Comment by hardwii** [comment]
ok i solved it by rebooting ?! :)

but new problem is now : 
server crashes after approx. 5 sec

changed exp. from 0 to 1
changed every port in config incl. IP
deleted protocol_key and/or pasted with new key

i have a normal ts3 running witha different user, might be that a problem?

[log_2018-08-31_18_31_36_general.txt](https://github.com/TeaSpeak/TeaSpeak/files/2340859/log_2018-08-31_18_31_36_general.txt)
[6d7e578a-77e0-4d22-d26f67b0-796eaaae.zip](https://github.com/TeaSpeak/TeaSpeak/files/2340861/6d7e578a-77e0-4d22-d26f67b0-796eaaae.zip)

**Comment by WolverinDEV** [comment]
Well seems like your database is fucked up.
May reinstall?

**Comment by hardwii** [comment]
did it 3 times already.
deleted all teaspeak realted files and the user
always the same

**Comment by WolverinDEV** [comment]
With a clear setup everything works :)

**Comment by hardwii** [comment]
Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz
4 GB RAM
HDD 300GB

**Comment by hardwii** [comment]
in debian 9 sql is handled by mariaSQL , i tried using mysql but its the same issue

**Comment by hardwii** [comment]
so i figured it out:
you cannot! have a running teamspeak und then at a teaspeak server "on-the-go"
u have to stop the other server to do this.

but the next thing is if u start the normal ts u get cockblocked from ts3 again, at least under debian.
BC ts3 and tea spawn a lot processes you have to manually set that limit per user up 
`|CRITICAL|              |   |Failure during pthread_create, error = EAGAIN`

**Comment by WolverinDEV** [comment]
Yeah but its not so much.
I thing TeaSpeak is running somewhere around 20-50 Threads (Depends on your settings)

**Comment by WolverinDEV** [comment]
Does this crash still applies?

**Comment by WolverinDEV** [comment]
Closed due to inactivity.
