### ISSUE TITLE
Latest update (1.2.15-beta) - SQL Syntax error

### ISSUE THREAD

**Issue by Fastmancz** [TeaSpeak/TeaSpeak#387]
**Describe the bug**
The server crashes after start.

**To Reproduce**
-

**Expected behaviour**
-

**Screenshots**
-

**Logs**
sql: SELECT * FROM `bannedClients` WHERE (`serverId` = 0 OR `serverId` = '1') AND (`name` = 'I'm like avokado, I'm special' OR `strType` = 3) AND (bannedClients.`until` > 1535875218678 OR bannedClients.`until` = 0) returned -> 1/near "m": syntax error

**Probably SQL injection in the section** - name - ' I **'** m... <<-- Wrong quotes.

**Environment information:**
 Operating system: (`Debian 3.16.39-1+deb8u2`)
 TeaSpeak version: [TeaSpeak-1.2.15-beta]

**Additional context**
The previous version works (TeaSpeak-1.2.14-beta).

**Comment by Sickness-chan** [comment]
Looks like the name is just not being escaped, technically an SQL injection right there @WolverinDEV

**Comment by Fastmancz** [comment]
I don't know, if it's same as in PHP, but I recommend use $mysqli->**prepare**, it's better, I think.

```
$result = $mysqli->prepare("SELECT * FROM my_table WHERE code LIKE ?");
$result->bind_param("s", $my_code);
$result->execute();
```

**Comment by WolverinDEV** [comment]
Haha well yes its the only one point where is was a littlebit fuzzy.
I implemented that system really far at the beginning where I hadn't my SQL class.
Will be fixed (BTW: Its the only one possibility to execute an (My)SQL injection)

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
