### ISSUE TITLE
channel sort option not working in 1.2.15-b

### ISSUE THREAD

**Issue by ariaieboy** [TeaSpeak/TeaSpeak#388]
**Describe the bug**
after updating teaspeak from 1.2.10b to 1.2.15b channel sort option not working

**To Reproduce**
create a clean new server
create a channel and then sort it after "[cspacer02] TeaSpeak Server"
create another and sort it after "[cspacer02] TeaSpeak Server" too
now restart the server u see that this channels going after "[cspacer04]Default Channel"

**Expected behaviour**
sorting option in channel settings must remain after restarting the server

**Environment information:**
 Operating system: Linux ubuntu 4.4.0-133-generic
 TeaSpeak version: 1.2.15-beta

**Additional context**
As I noticed, the channels are arranged according to the date and time of the build, and the sort in channel settings option does not work.

**Comment by ariaieboy** [comment]
I downgrade my Teaspeak from 1.2.15b to 1.2.14b and problem fixed

**Comment by WolverinDEV** [comment]
Yep this is fixed within the next build (Made a caching mistake)
