### ISSUE TITLE
Server crashed after typing use sid=0 via YatQA console?

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#389]
**Describe the bug**
The server did crashed, after i did entered use sid=0 on YatQA console.

**Expected behaviour**
Did just entered use sid=0 (and clicked enter on keyboard) and crash of server.

**Logs**
Dump file: [crash_dump_80ae232b-bfa1-474c-00b503b8-c45938b6.dmp.zip](https://github.com/TeaSpeak/TeaSpeak/files/2343119/crash_dump_80ae232b-bfa1-474c-00b503b8-c45938b6.dmp.zip)

**Environment information:**
 Operating system: Debian 9.5 
 TeaSpeak version: [TeaSpeak-1.2.15]

**Comment by MikkelDK** [comment]
@WolverinDEV

**Comment by WolverinDEV** [comment]
Fixed within the next build (2) :)
