### ISSUE TITLE
Problems with kick/invalid file permissions.. and invalid argument

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#390]
**Describe the bug**
Issues with kick/connect getting "disconnect from server" + invalid file permissions with avatar+icons.

**Expected behaviour**
Seems there is issue after update..kick from server (issues with disconnect from server) + invalid file permissions with avatar+icons.
**Screenshots**
![error](https://user-images.githubusercontent.com/5301047/44957321-5f981380-aed1-11e8-92b7-929520f76ee1.png)

**Environment information:**
 Operating system: Debian 9.5 
 TeaSpeak version: [TeaSpeak-1.2-15]

**Additional context**
<16:54:15> "Mikkel" disconnected (Invalid argument) < is that fixed on other updates?

**Comment by MikkelDK** [comment]
@WolverinDEV

**Comment by Chazotu** [comment]
Update to Build 4 its fixed their
