### ISSUE TITLE
use sid=0 for changes servertemplate (yatqa console)

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#392]
**Describe the bug**
error id=1024 msg=invalid\sserverID extra_msg=invalid\sbounded\sserver

**Expected behaviour**
Not possible to using: serveredit virtualserver_name=TeamSpeak ]|[ Server - since it will post the error. after using use sid=0 for edit servertemplate.

**Screenshots**
![error1337](https://user-images.githubusercontent.com/5301047/44959179-f1604a80-aeea-11e8-89e8-a4eab557d7c2.png)

**Environment information:**
 Operating system: (Debian 9.5)
 TeaSpeak version: [TeaSpeak-1.2.15-beta-5]

**Additional context**
I was hoped, the use sid=0 did works for edit servertemplate direct on yatqa console. for setup settings for creating new virtualservers.

**Comment by WolverinDEV** [comment]
Virtualserver properties aren't implemented yet.

**Comment by WolverinDEV** [comment]
Implemented within the next build :)
