### ISSUE TITLE
Weird file upload issue

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#393]
**Describe the bug**
Can't upload any sort of files (files in a channel / set an avatar), server will disconnect you and an error will show up: `Transfer "avatar" berichtet: (could not open file transfer connection)`
Weird part is, it works just fine on a completely fresh instance on another host, so you will probably have to use the DB again I sent you yesterday and see for yourself

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to upload a file to a channel or try to upload an avatar
2. See error

**Expected behaviour**
Files upload normally

**Screenshots**
https://i.killuminati.eu/6907h392K.webm

**Logs**
I don't even really get anything useful in the logs

**Environment information:**
 Operating system: Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.15-beta-6]

**Comment by WolverinDEV** [comment]
Well this bug is fixed in beta 6 but I don't recommend you to update now.

How you can fix your behavior:
Reset the bandwidth and quota setting within the virtual server dialog (you have to change any of them to apply another value)

**Comment by Sickness-chan** [comment]
I used beta 6, so not sure if your fix worked, but I did it the manual way by changing the values in each server through the client interface.
