### ISSUE TITLE
User got invisible

### ISSUE THREAD

**Issue by lbenicio** [TeaSpeak/TeaSpeak#396]
**Describe the bug**
If you have a channel with subscribe power, for example, 150 to make users inside it invisible to normal TeaSpeak users (with subscribe power 50), it an admin with subscribe power 150 join the protected channel and goes back to the normal channel, this user will get invisible for the other and they won't hear the user who changed channels

**To Reproduce**
Steps to reproduce the behaviour:
1. Set a subscribe power to channel to 150
2. join a channel with this subscribed power
3. go back to a normal channel
4. the other users won't be able to see you in the channel tree and won't hear you

**Expected behaviour**
The modified user should appear normally on the unmodded channel

**Screenshots**
No screenshots available, maybe a video if it nos clear yet/not understandable.

**Logs**
no logs applicable.

**Environment information:**
 Operating system: ubuntu x64
 TeaSpeak version: 1.2.15-beta-6 

**Additional context**
no additional context

**Comment by REDMONDS** [comment]
too, there is such a problem, today users complained :-(

**Comment by WolverinDEV** [comment]
Cant confirm the way you described....
Did this happens constantly?

**Comment by lbenicio** [comment]
it happens everytime user switch channels.

1. create a channel with subscribe power 150
2. create 2 servergroups, 1 with channel subscribe power 50 e the other 150
3. join the channel you previously create with client with 150 subscribe power and go back to the normal channel (both users were in and the subscribe power were 0)
4. the user with 50 subscribe power wont be able to see the user with 150 subscribe power

**Comment by WolverinDEV** [comment]
Uhh yeah thanks for that explanation!
I really missed there something <3

Fixed within build 8
