### ISSUE TITLE
Disconnect when viewing or uploading icons

### ISSUE THREAD

**Issue by dennyb** [TeaSpeak/TeaSpeak#398]
**Describe the bug**
Random disconnect when viewing or uploading some (server) icons

**To Reproduce**
Don't know, there are some icons which force the client to disconnect.
In the client log there is only something with "unsupported image found" (on join)
and directly disconnect when trying to upload an icon.

**Expected behaviour**
No disconnect

**Screenshots**

**Logs**
<19:27:02> Von Server getrennt
<19:27:17> Transfer "icon_536159088" berichtet: (invalid file permissions)
<19:27:17> Transfer "icon_2296336530" berichtet: (invalid file permissions)
<19:27:17> Transfer "icon_743095982" berichtet: (invalid file permissions)
<19:27:17> Transfer "icon_3468864332" berichtet: (invalid file permissions)

**Environment information:**
4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
{build_name: "1.2.15-beta-6", build_version: "1.2.15-beta", build_index: 6}

**Additional context**

**Comment by dennyb** [comment]
<19:40:06> Transfer "icon_3803792321" berichtet: (could not open file transfer connection)

**Comment by WolverinDEV** [comment]
Disconnect fixed within the newest version (Build 7!)
