### ISSUE TITLE
Tried to attempt to delete a not existing cached client.

### ISSUE THREAD

**Issue by fa5tkill3r** [TeaSpeak/TeaSpeak#40]
## System Information
***Operating System***: Ubuntu 16.04.3 LTS
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: Linux x64 | 1.0.19-beta

## Issue
***Reason for reporting this issue***: 
After i run teaspeak with minimal its start spamming this:

Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
^C
root@felix5:/home/xxx/teaspeak# Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Handschake timeout (Step 2)
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Handschake timeout (Step 2)
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Handschake timeout (Step 2)
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Handschake timeout (Step 2)
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02
Tried to attempt to delete a not existing cached client.
Tried to attempt to delete a not existing cached client.
Invalid handschake: Invalid handschake step. Got: 0 Expected: 0x02

***Detailed Description***:
I cant connect to server. I need to manualy stop teaspeak with htop.  BTW TeaSpeak running as a root. 

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Hey,
hmm well do you connect with the newest TS3 client? I guess TeamSpeak tries to connect like they connect to a 3.1 server :)

**Comment by WolverinDEV** [comment]
I will change this massages to debug mode

**Comment by fa5tkill3r** [comment]
yes i tried it with newest ts3 version.

**Comment by WolverinDEV** [comment]
Removed the message in 1.0.20-Beta.
May i fixed this in 1.0.20 too, but i'll keep this issue still open until the 'cant connect error' is resolved:)
