### ISSUE TITLE
Add passwd as starting, for queryadmin passwd. 

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#404]
**Is your feature request related to a problem? Please describe.**
Could being nice for adding possible for set querypassword on starting (for using TeaSpeak on controlpanel!)

**Describe the solution you'd like**
Could be nice. if it's possible to adding commandline for adding querypassword as starting.
As example:
`./teastart_minimal.sh --passwd somerandompasswordhere` for queryadmin(for login on YatQA)

**Describe alternatives you've considered**
Have long considered whether there will soon be a function where it is possible and could do this .. especially when using control panel to cough server. and the ability to grant people access to manage their own virtual server.

**Additional context**
Just as example with:
`./teastart_minimal.sh --passwd randompasswordhere`
`./teastart.sh --passwd randompasswordhere`

where the -passwd (is set of passwd for serverquery!)

**Comment by MikkelDK** [comment]
@WolverinDEV is there planned to-do this in the future? ;)

**Comment by WolverinDEV** [comment]
Well when I really implemented that (not sure yet) I'll just apply that for the minimal script.

**Comment by MikkelDK** [comment]
As example `(ts3server has like this: ./ts3server_minimal.sh --serveradmin_password=blablabla)`

**Comment by WolverinDEV** [comment]
Implemented within the next build/version
