### ISSUE TITLE
Add youtube-dl location on config.yml 

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#405]
**Is your feature request related to a problem? Please describe.**
Adding youtube-dl location on config.yml 
As example: `youtube-dl: /usr/local/sbin/youtube-dl` for getting works (if people wanna to use TeaSpeak as adding on controlpanel)

**Describe the solution you'd like**
Possibility to enable to set where the path should be, regarding youtube-dl

**Describe alternatives you've considered**
Adding a way for set youtube-dl as folder (e.g youtube=/usr/local/sbin/youtube-dl for works to controlpanel e.g (for virtualservers)

**Additional context**
N/A

**Comment by WolverinDEV** [comment]
https://github.com/TeaSpeak/TeaMusic/blob/master/providers/yt/YTProvider.cpp#L44
Its a simple sh command. You have to add youtubedl to /bin/sh :)

**Comment by MikkelDK** [comment]
Hmmm...it's because i'm working for getting "TeaSpeak" on a controlpanel.

Dunno about we can use that "proc.open" or need to use.
As example: /usr/local/bin/youtube-dl e.g

**Comment by WolverinDEV** [comment]
Fixed within the next packaging :)
