### ISSUE TITLE
WebList Not Working

### ISSUE THREAD

**Issue by METALG0D** [TeaSpeak/TeaSpeak#406]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64):
***TeaSpeak-1.2.15-beta-12***:

## Issue
***Fix***:

***Detailed Description***:
server list not work in TeaSpeak-1.2.15-beta-12, I have Install and Try Teamspeak 3 Server And My Server Showing In WebList But On TeaSpeak Server Not Showing In WebList

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Not tested yet, but another user said to me that the web list address changed.
May this is the reason for that. I'll take a look

**Comment by Chazotu** [comment]
Confirmed

**Comment by Chazotu** [comment]
Will be fixed in next version/build

**Comment by METALG0D** [comment]
Thanks......
