### ISSUE TITLE
Android Ts3 3.2.1 Connection Problem

### ISSUE THREAD

**Issue by SafariGaming** [TeaSpeak/TeaSpeak#407]
## System Information
***Operating System***: Android
***Operating System Type*** (x86|x64): 
***TeaSpeak Version***: Last Version
TeamSpeak3 Version: Android 3.2.1

## Issue
***Reason for reporting this issue***:
https://ibb.co/dMSC4e

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
There are several instructions on R4P3 or my forum :)
