### ISSUE TITLE
Download aus dem Dateibroser fehlgeschlagen

### ISSUE THREAD

**Issue by websat** [TeaSpeak/TeaSpeak#408]
ab der v. TeaSpeak-1.2.15-beta-6 ging der Download von Datein aus dem Datei-Broser
und nach der TeaSpeak-1.2.15-beta-7 ging es nicht mehr?

**Comment by WolverinDEV** [comment]
Errors?

**Comment by Chazotu** [comment]
Are your running the latest build ?

**Comment by Sickness-chan** [comment]
It's probably the same problem as https://github.com/TeaSpeak/TeaSpeak/issues/393#issuecomment-418029798

Do the manual method described there or update to the latest build.

**Comment by Chazotu** [comment]
Try Updating to latest build should not apear
