### ISSUE TITLE
opus Musik mit höherer qualität

### ISSUE THREAD

**Issue by preterive** [TeaSpeak/TeaSpeak#41]
Hi,
ich wünsche mir die möglichkeit opus musik mit Bitraten von 32 kib/s oder mehr übertragen zu können.

gruß

**Comment by WolverinDEV** [comment]
Hey,
Da der server momentan nicht dir Musik Bandbreite überprüft sind alle möglichen Opus Einstellungen möglich, und es gibt keine reelle Grenze. Des Weiteren ignoriert der music bot die Bandbreite limits sowieso
