### ISSUE TITLE
Force push to talk

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#412]
When you add force push to talk permission and remove it person still cant talk.

**Comment by Chazotu** [comment]
Confirmed Reconects solves it on PC for me / Also on Mobile Clients they just ignore the permission

**Comment by WolverinDEV** [comment]
Please clear your cache.
Because you moved your TeamSpeak to TeaSpeak the permission id's changed.
Because your server UID didnt the client still uses the old cache.
Should work when you clear that cache :)

**Comment by DanielAlves123** [comment]
@WolverinDEV I don't really know what you are talking about. 
1. Add user to group with b_client_force_push_to_talk permission.
2. Remove user from this group.
3. User still has to use push to talk function, without being in the group. After he reconnects he is able to speak normally again.

**Comment by DanielAlves123** [comment]
@WolverinDEV checked, still doesn't work. 
# Version: 1.2.16-beta-2
# TeaSpeak version: 1.2.16-beta
# Build version: 2

{build_name: "1.2.16-beta-2", build_version: "1.2.16-beta", build_index: 2}
