### ISSUE TITLE
No icons are loading

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#413]
**Describe the bug**
After the update TeaSpeak-1.2.16-beta-1 stopped loading icons

**To Reproduce**
Steps to reproduce the behaviour:
1. Tools -> Options -> Security -> Clear cache
2. Select everything.
3. Confirm and restart the client.
4. Connect to the server.
5. See Server log or screenshot below.

**Expected behaviour**
That icons of groups and channels are loaded and will start to be displayed.

**Screenshots**
1. https://prnt.sc/ks7tl8

**Logs**
1. https://redoss.ru/files/logs.log

**Environment information:**
 Operating system: Debian 9.3
 TeaSpeak version: TeaSpeak-1.2.16-beta-1
 I am using `experimental_31`: yes

**Comment by REDMONDS** [comment]
@slushpuppy and @WolverinDEV Most likely this is a bug and it is played on a clean server.

**Comment by Chazotu** [comment]
Cant Reproduce it tested on 1.2.16 Beta 1

**Comment by REDMONDS** [comment]
@Chazotu Did you clear the client cache?

**Comment by REDMONDS** [comment]
@Chazotu and @WolverinDEV Logs - https://redoss.ru/files/logs.log

**Comment by Chazotu** [comment]
Their is some how an bug currently we will have an closer look on it

**Comment by REDMONDS** [comment]
@Chazotu I decided not yet to use your versions, I will temporarily stay on 3.0.13.8

**Comment by REDMONDS** [comment]
@WolverinDEV Unfortunately, many problems: - (both with memory consumption, and with the presence of errors ... customers complain. I decided to test it on a separate server.

**Comment by REDMONDS** [comment]
Added: 
![ts](https://user-images.githubusercontent.com/6460267/45322567-4fc3a380-b551-11e8-9e88-f022150b9144.png)

[log_2018-09-10_23%3A24%3A29_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2368287/log_2018-09-10_23.3A24.3A29_general.log)

**Comment by REDMONDS** [comment]
@WolverinDEV and @Chazotu Download for you snapshot server and its icons in the archive?
Link: https://my.pcloud.com/publink/show?code=XZqVp17ZJYap6t3S1Abu583qASvCfpBm1h0k

**Comment by slushpuppy** [comment]
<11:47:45> Transfer "icon_2341513464" reports: (lost file transfer connection)
<11:47:45> Transfer "icon_1650176758" reports: (lost file transfer connection)
<11:47:45> Transfer "icon_248786194" reports: (lost file transfer connection)
<11:47:45> Transfer "icon_1753268879" reports: (lost file transfer connection)

Old icons are fine, but try deleting and reuploading new icons- that is where the problem starts

**Comment by slushpuppy** [comment]
11/9/2018 03:54:09		Warning	Unsupported image format for C:/Users/lukel/AppData/Roaming/TS3Client/cache/WUlXN0I4MnZyOVhlMEk4N0wxMTJ3WDhyZGhZPQ==/icons/icon_2341513464	
11/9/2018 03:54:10		Warning	Unsupported image format for C:/Users//AppData/Roaming/TS3Client/cache/WUlXN0I4MnZyOVhlMEk4N0wxMTJ3WDhyZGhZPQ==/icons/icon_191801430	
11/9/2018 03:54:10		Warning	Unsupported image format for C:/Users//AppData/Roaming/TS3Client/cache/WUlXN0I4MnZyOVhlMEk4N0wxMTJ3WDhyZGhZPQ==/icons/icon_3247455152

**Comment by WolverinDEV** [comment]
Fixed within the next version :)
