### ISSUE TITLE
Disconnected from server (parameter not found)

### ISSUE THREAD

**Issue by eucode** [TeaSpeak/TeaSpeak#421]
## System Information
***Operating System***: Linux
***Operating System Type*** (x86|x64): x86
***TeaSpeak Version***: 1.2.11

## Issue
***Reason for reporting this issue***: Disconnected from server (parameter not found)

***Detailed Description***: if i kick a user from the channel but it is not in my channel to crash TeaSpeak

**Comment by MikkelDK** [comment]
I wanna to hear. about you are using 1.2.11 ? ;)

**Comment by zafai** [comment]
Install the new version please Linux x64 | 1.2.16-beta-1 
https://teaspeak.de/
https://repo.teaspeak.de/server/linux/amd64/TeaSpeak-1.2.16-beta-1.tar.gz
