### ISSUE TITLE
CPU high using on TeaSpeak.

### ISSUE THREAD

**Issue by MikkelDK** [TeaSpeak/TeaSpeak#427]
**Describe the bug**
Is there some planned for optimization the CPU using?

**Expected behaviour**
TeaSpeak - using around 53% <-> up to 80% CPU. 
74 servers online <-> 68 users online.

**Screenshots**
![110a248073df2eebec5e9244a30f2f39](https://user-images.githubusercontent.com/5301047/45375765-3aed1b80-b5f6-11e8-8b1e-643bbabcb018.png)

**Logs**
Dunno, about you want a meminfo?

**Environment information:**
 Operating system: (`Debian9.5 - 4.9.0-6-amd64`)
 TeaSpeak version: [TeaSpeak-1.2.15-beta-12]
 I am using `experimental_31`: (yes)
 Using of `CPU Processor`: E5-2620 v2
 `Memory` on server: 30GB. (2.05GB out of 29.5GB!)

**Additional context**
Seems pretty strange/weird, since it's using to high CPU with: 67-68 users. and around 50% CPU <-> up to 80%.

**Comment by MikkelDK** [comment]
@WolverinDEV

**Comment by MikkelDK** [comment]
**Update**:
Now it's using more CPU of % with 83 users.

![f5d9bc000771d3bddf59aec68ec4ff10](https://user-images.githubusercontent.com/5301047/45377168-15faa780-b5fa-11e8-814e-438542e4a56b.png)

Hope there is  a chance for.. it can be optimization . 👍

**Comment by WolverinDEV** [comment]
Well there is a bug one and its when im switching from debug to release mode (Im currently building in debug without optimizations because with its its incredible hard to debug errors)
Ill progress that when I released the first stable version

**Comment by MikkelDK** [comment]
Is there some tricks, i can do for fix the issues? - or do i need to wait for a update? ;)

**Comment by WolverinDEV** [comment]
You cant do anything really.
Yust testing the release mode when I release it within that :;D

**Comment by MikkelDK** [comment]
Let me know, when it will be released <3
