### ISSUE TITLE
List of all new command

### ISSUE THREAD

**Issue by GoRiLliAz** [TeaSpeak/TeaSpeak#428]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
You should put a list of all new orders available.
As well as an order list imported from teamspeak.

**Describe alternatives you've considered**

**Additional context**

**Comment by WolverinDEV** [comment]
I don't really know what you mean

**Comment by chronicals** [comment]
I think he asks for a documentation, so that we can see what commands and permissions can be used, compared to TeamSpeak.

**Comment by WolverinDEV** [comment]
https://github.com/TeaSpeak/TeaSpeak/blob/master/Changes.md? :D
