### ISSUE TITLE
No Ping Response 

### ISSUE THREAD

**Issue by minatozinola** [TeaSpeak/TeaSpeak#429]
**Describe the bug**
No Ping Response to different clients , does not matter if there are 20 connected or 50 , they just get no ping response after certain time.

**Environment information:**
 Operating system: Debian 8 
 TeaSpeak version: 1.2.17-beta-5 
 I am using `experimental_31`: yes

This is my config,yml file : 

#The configuration version.
#Do NOT modify!
version: 10
log:
  #The log level
  #Available types:
  #  0: Trace
  #  1: Debug
  #  2: Info
  #  3: Warn
  #  4: Error
  #  5: Critical
  #  6: Off
  level: 1
  #Disable/enable ascii codes in log
  colored: 0
  #Virtualserver log chunk size
  #0 = Disable (Log all to one file)
  #1 = Individual (Create for each virtual server a new log)
  #>1 = Chunked (Use for each n virtual servers the same log file)
  #Do NOT TOUCH unless you're 100% sure!
  vs_size: 0
  #The log file path
  #Do NOT TOUCH unless you're 100% sure!
  path: logs/log_${time}(%Y-%m-%d_%H:%M:%S)_${group}.log
messages:
  #The terminal log level
  level: 2
  voice:
    #The server stopped message
    server_stop: Server stopped
  application:
    #The server stopped message
    stop: Application stopped
    #The application crashed message
    crash: Application crashed
  #The idle time kick message
  idle_time: Idle time exceeded
  mute:
    #The mute notify message
    mute_message: "Hey!\nI muted you!"
    #The unmute notify message
    unmute_message: "Hey!\nI unmuted you!"
    kick_invalid:
      #The message when a client get kicked caused by an invalid hardware id
      hardware_id: Invalid hardware id. Protocol hacked?
      #The message when a client get kicked caused by an invalid command
      command: Invalid command. Protocol hacked?
      #The message when a client get kicked caused by an invalid badges
      badges: Invalid badges. Protocol hacked?
  vpn:
    #This is the kick/ban message when a client tries to connect with a vpn
    #Variables are enabled. Available:
    # - provider.name => Contains the provider of the ip which has been flaged as vps
    # - provider.website => Contains the website provider of the ip which has been flaged as vps
    kick: "Please disable your VPN! (Provider: ${provider.name})"
general:
  #The database url
  #Available urls:
  #  sqlite://[file]
  #  mysql://[host][:port]/[database][?propertyName1=propertyValue1[&propertyName2=propertyValue2]...]
  #
  #More info about about the mysql url could be found here: https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html
  #There's also a new property called 'connections', which describes how many connections and queries could be executed synchronously
  #MySQL example: mysql://localhost:3306/teaspeak?userName=root&password=mysecretpassword&connections=4
  #Attention: If you're using MySQL you need at least 3 connections!
  database_url: sqlite://TeaData.sqlite
  #Insert here your license code (if you have one)
  license: none
  #The crashdump file path
  crash_path: crash_dumps/
binding:
  file:
    #The default host for the file server
    host: 0.0.0.0
    #The default port for the file server
    port: 30303
  query:
    #The default host for the query server
    host: 0.0.0.0
    #The default port for the query server
    port: 10101
server:
  #The displayed version to the client
  #This option is only for the premium version.
  version: "TeaSpeak 1.2.6-beta [Build: 1534195805]"
  #The displayed platform to the client
  #This option is only for the premium version.
  platform: Linux
  #The displayed licence type to every TeaSpeak 3 Client
  #Attention this option just work for non 3.2 clients!
  #Available types:
  #  0: No Licence
  #  1: Authorised TeaSpeak Host Provider License (ATHP)
  #  2: Offline/Lan Licence
  #  3: Non-Profit License (NPL)
  #  4: Unknown Licence
  #  5: ~placeholder~
  #  6: Auto-License (Server based)
  #  7: Auto-License (Instance based)
  #This option is only for the premium version.
  licence: 6
  #Enable/disable the deletion of old bans within the database
  delete_old_bans: 1
  #Enable/disable the deletion of invalid icon id permissions
  delete_missing_icon_permissions: 0
query:
  #Change the query newline character
  nl_char: "\r\n"
  #The query welcome message
  #Notice: If not like TeamSpeak then some applications may not recognize the Query
  #Default TeamSpeak 3 MOTD:
  #TS3\r\nWelcome to the TeamSpeak 3 ServerQuery interface, type \"help\" for a list of commands and \"help <command>\" for information on a specific command.\r\n\r\n
  motd: "TeamSpeak\r\nWelcome on the TeamSpeak ServerQuery interface.\r\n"
  #Enable/disable SSL for query
  #Available modes:
  #  0: Disabled
  #  1: Enabled (Enforced encryption)
  #  2: Hybrid (Prefer encryption but fallback when it isnt available)
  enableSSL: 2
  ssl:
    #The SSL certificate for the query manager
    #The SSL certificate for the query manager
    certificate: certs/query_certificate.pem
    #The SSL private key for the query manager (You have to export the key without a password!)
    privatekey: certs/query_privatekey.pem
voice:
  #Enable/disable the mute notify
  notifymute: 1
  rsa:
    #The amount of precomputed puzzles
    #Do NOT TOUCH unless you're 100% sure!
    puzzle_pool_size: 128
  handshake:
    #The puzzle level. (A higher number will result a longer calculation time for the manager RSA puzzle)
    #Do NOT TOUCH unless you're 100% sure!
    puzzle_level: 1000
    #Enforces the cookie exchange (Low level protection against distributed denial of service attacks (DDOS attacks))
    #This option is highly recommended!
    #Do NOT TOUCH unless you're 100% sure!
    enforce_cookie: 0
  #Maximum amount of join attempts per second.
  connect_limit: 10
  #Maximum amount of join attempts per second per ip.
  client_connect_limit: 3
  protocol:
    #Its just a test for the new TeamSpeak licensing system (you require a extra plugin!)
    experimental_31: 1
  #Change the default voice server port
  default_port: 9987
  #Supress the MyTS integration warnings
  suppress_myts_warnings: 1
web:
  #Disable/enable the possibility to connect via the TeaSpeak web manager
  enabled: 1
  ssl:
    #The SSL certificate for the web manager
    certificate: certs/default_certificate.pem
    #The SSL private key for the web manager (You have to export the key without a password!)
    privatekey: certs/default_privatekey.pem
threads:
  #Thread pool size for the ticking task of a VirtualServer
  #Do NOT TOUCH unless you're 100% sure!
  ticking: 100
  voice:
    #Max number of threads for command handling on the instance
    #Do NOT TOUCH unless you're 100% sure!
    execute_limit: 10
    #Threads per server for command executing
    #Do NOT TOUCH unless you're 100% sure!
    execute_per_server: 3
    #LibEvent events per server
    #Do NOT TOUCH unless you're 100% sure!
    events_per_server: 4
    #Minimum IO threads
    #Do NOT TOUCH unless you're 100% sure!
    io_min: 3
    #IO Thread increase per server
    #Do NOT TOUCH unless you're 100% sure!
    io_per_server: 4
    #Max IO threads
    #Do NOT TOUCH unless you're 100% sure!
    io_limit: 10
  music:
    #Max number of threads for command handling on the instance
    #Do NOT TOUCH unless you're 100% sure!
    execute_limit: 15
    #Threads per server for command executing
    #Do NOT TOUCH unless you're 100% sure!
    execute_per_bot: 1
geolocation:
  #The fallback country if lookup fails
  fallback_country: DE
  mapping:
    #The mapping file for the given provider
    #Default for IP2Location: geoloc/IP2Location.CSV
    #Default for Software77: geoloc/IpToCountry.csv
    file: geoloc/IP2Location.CSV
    #The IP 2 location resolver
    #0 = IP2Location
    #1 = Software77
    type: 0
  #Disable/enable the IP2Location lookup
  force_fallback_country: 0
  vpn:
    #The mapping file for vpn checker (https://github.com/client9/ipcat/blob/master/datacenters.csv)
    file: geoloc/ipcat.csv
    #Disable/enable the vpn test
    enabled: 0

**Comment by WolverinDEV** [comment]
Already heard about some strage instance hangup for several seconds.
Im already looking at this. Im also currently investigating an total instance hangup.

**Comment by WolverinDEV** [comment]
Should be fixed/be improved
