### ISSUE TITLE
Badgets

### ISSUE THREAD

**Issue by preterive** [TeaSpeak/TeaSpeak#43]
Hallo,
ist es evtl. möglich, eine Funktion einzubauen die das setzen von mehr als 3 Badgets unmöglich macht? dann würde pytson nicht mehr gehen.

gruß

**Comment by WolverinDEV** [comment]
~ Implemented in 1.0.20-Beta

**Comment by Bluscream** [comment]
Schade :^)

**Comment by WolverinDEV** [comment]
:P
