### ISSUE TITLE
1.2.17-beta-6 - crash every 15/20 minutes

### ISSUE THREAD

**Issue by ts3cloud** [TeaSpeak/TeaSpeak#432]
**Describe the bug**
Server crash

**To Reproduce**
Steps to reproduce the behaviour:
Run server. 

**Expected behaviour**
Server was crashed

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: (`Last Debian 8`)
 TeaSpeak version: [TeaSpeak-1.2.17-beta6]
 I am using `experimental_31`: (yes)

**Additional context**
Crashdumps
[crash.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2385565/crash.tar.gz)

**Comment by WolverinDEV** [comment]
Most of them results on the same issue.
Is there any way to reproduce?

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
