### ISSUE TITLE
Channel password issues

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#433]
**Describe the bug**
Old password protected channels aren't working with their previous passwords anymore and newly created channels seem to ignore their password. Note: I was on version 1.2.15-beta-12 when I was informed of this, then updated to the latest version but the problem persisted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new channel with a password
2. Try to join it with a guest user
3. Password is completely ignored

**Expected behaviour**
It should ask for the password and behave like normal

**Screenshots**
https://i.killuminati.eu/69522685M.webm

**Environment information:**
 Operating system: Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.17-beta-6]
 I am using `experimental_31`: yes

**Comment by Chazotu** [comment]
Cant confirm channel password works great on latest build seems like an permission problem


Check that the guest group does not have
- b_channel_join_ignore_password
- b_client_skip_channelgroup_permissions

**Comment by Sickness-chan** [comment]
Just checked, it has neither of the 2 permissions. I'll send the DB to Wolverin on the forum.

**Comment by REDMONDS** [comment]
@WolverinDEV fix?

**Comment by Sickness-chan** [comment]
Yeah it doesn't reproduce on 2 seperate clients. But there's still that other odd problem where people reported their old channel passwords not working anymore, although I can't really provide any more useful info on that, because I don't know a password to any channel, so I can't verify it myself

**Comment by WolverinDEV** [comment]
:) As I said :)

Yes I don't import passwords from snapshots.
