### ISSUE TITLE
Database migration TeamSpeak to TeaSpeak

### ISSUE THREAD

**Issue by Newcomer1989** [TeaSpeak/TeaSpeak#44]
Is there any plan to make it possible to migrate an existing TeamSpeak database to TeaSpeak?
I am meaning all stuff with that (Channel, User, Permissions and so on..)

For me this would be the most important thing, cause I do not want to recreate all again. ;-)

**Comment by WolverinDEV** [comment]
Hello,
basicly TeaSpeak supports the `serversnapshotdeploy` function, so you can create a server snapshot from your old server and upload it to the new :)

**Comment by Newcomer1989** [comment]
But with this all database IDs get changed, what is a very bad solution. That's what fucked up on the server snapshot function on TeamSpeak.

Today the most server have so much scripts, which are using the IDs of channels, servergroups...
Sure, also the user get a new database ID.

It would be very nice, to use the old ts3sqlite.db file. Is this still possible or possible to create a support for that?

**Comment by WolverinDEV** [comment]
Basically is everything possible, but the problem is that this would be take way too much time.
As a little reminder: and I know what you mean with the scripts,but keep in mind that you should base all scripts on the clientuid because that 8s on every server equal.

**Comment by Newcomer1989** [comment]
Its a pity, then I will never use your tool for the production environment. :(
Or TeaSpeak will need much more effort compared to TeamSpeak. And with effort I am not meaning the actual gimmicks. Sure they are nice, but the effort is minimal. I am meaning the big things like:
- default encryption for the query connection
- a communication with a web client, that users are available to use only their browser (like discord). Sure, the "expert mode" (permission system,...) could stay in classic client

**Comment by WolverinDEV** [comment]
Hey,
well we already thought already of both of your points, and we may add some parts of this in TeaSpeak soon :) But we all will see where TeaSpeak is going to in the future
