### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#440]
For the latest version of teaspeak 1.2.17-beta-7 , the android client reports "Server license not valid" when connecting. Any assistance would be appreciated!!

**Comment by Chazotu** [comment]
Thats Normal You have this 3 Options


1. Use 32 Slots 

2. Take a nother license from Teamspeak like NPL / AAL


3. Downgrade you mobile version

**Comment by slushpuppy** [comment]
Are there any plans to make it work for mobile clients?
