### ISSUE TITLE
Interviewer Bug

### ISSUE THREAD

**Issue by reduux** [TeaSpeak/TeaSpeak#442]
**Describe the bug**
The bug occurs randomly and could not be reproduced.
In some channels, normal users receive interviewers.
You can not take this away.  When the users leave the channel, the interviewer is gone again.

**Screenshots**
https://i.imgur.com/upqlgne.png
https://i.imgur.com/9lRowX2.png

**Environment information:**
 TeaSpeak version: [TeaSpeak 1.2.17-beta]
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Hmm does the client may have the permission on another way?
I've tried to reproduce that but for me everything worked.

**Comment by reduux** [comment]
Not that I know, it seems to be the server group and the channel.
But nothing else was set there.

https://i.imgur.com/ShXZQKa.gifv

**Comment by WolverinDEV** [comment]
Fixed within the next build (permission didn't updated when it was manually assigned or removed)
