### ISSUE TITLE
Connection lost because server license can not be validated

### ISSUE THREAD

**Issue by macaaaxc** [TeaSpeak/TeaSpeak#443]
ive used newest version of teaspeak beta 7
<18:12:31> Trying to connect to server on 82.208.17.191
<18:12:31> Connected to Server: "No server"
<18:12:31> Connection lost because server license can not be validated

**Comment by MikkelDK** [comment]
https://forum.teaspeak.de/index.php?threads/information-connection-lost-because-server-license-can-not-be-validated.944/#post-6240

Read this topic, i did created! ;)

**Comment by Chazotu** [comment]
Thats Normal You have this 3 Options


1. Use 32 Slots 

2. Take a nother license from Teamspeak like NPL / AAL


3. Downgrade you mobile version
