### ISSUE TITLE
Connection lost because server license can not be validated

### ISSUE THREAD

**Issue by NeoNCoding** [TeaSpeak/TeaSpeak#444]
**Describe the bug**
I can't connect to my server, anybody can't with TS3 3.2.2 client version..

**Expected behaviour**
Just want connect to server

**Screenshots**
![image](https://user-images.githubusercontent.com/40951993/45644819-f6aebf00-babe-11e8-825f-62d6e2862c84.png)

**Environment information:**
 Operating system: Linux
 TeaSpeak version: TeaSpeak-1.2.17-beta-7 
 I am using `experimental_31`: yes

**Comment by MikkelDK** [comment]
Duplicated....
#443 

Read here > https://forum.teaspeak.de/index.php?threads/information-connection-lost-because-server-license-can-not-be-validated.944/#post-6240

**Comment by Chazotu** [comment]
Thats Normal You have this 3 Options
Use 32 Slots
Take a nother license from Teamspeak like NPL / AAL
Downgrade you mobile version

**Comment by MikkelDK** [comment]
@Chazotu (can you close this) ^^
