### ISSUE TITLE
Connection lost because server license can not be validated

### ISSUE THREAD

**Issue by RealRunSpace** [TeaSpeak/TeaSpeak#445]
## System Information
***Operating System***; Ubuntu 16.04
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.2.17b

## Issue
***Reason for reporting this issue***:
Users can't log in with the latest TS3 CLIENT version due to: Connection lost because server license can not be validated

***Detailed Description***:

Just try to log into a server created with Tea and you'll get the message

**Comment by Chazotu** [comment]
Thats Normal You have this 3 Options
Use 32 Slots
Take a nother license from Teamspeak like NPL / AAL
Downgrade you mobile version

**Comment by RealRunSpace** [comment]
ok thanks and sorry! closing it!

**Comment by RealRunSpace** [comment]
@Chazotu it's not from mobile, it's from the new TS3 client! (3.2.2 I think)
