### ISSUE TITLE
Connection lost because server license can not be validated

### ISSUE THREAD

**Issue by i-Clyde** [TeaSpeak/TeaSpeak#446]
**Describe the bug**
New TS3 version

**To Reproduce**
Steps to reproduce the behaviour:
1. Run TS3 with experimental_31 
2. Connect with 3.2.2 client (newest)

**Expected behaviour**
Teamspeak will not allow you to connect.

**Screenshots**
https://i.imgur.com/vSxIqu8.png

**Environment information:**
 Operating system: Windows 10 - Ubuntu-server
 TeaSpeak version: 1.2.15b & 1.2.17b7
 I am using `experimental_31`: yes

**Comment by MikkelDK** [comment]
Duplicated ;) 

Because 3.2.2 clients checking the new license system from Tea**m**Speak. thats why 32 slots is max on "No License" server.

#443 
Read this: https://forum.teaspeak.de/index.php?threads/information-connection-lost-because-server-license-can-not-be-validated.944/#post-6240

**Comment by MikkelDK** [comment]
@Chazotu - can we get this closed.
