### ISSUE TITLE
suppress_myts_warnings: 1 doesn't work

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#448]
It still shows warnings even with this option enabled.

**Comment by WolverinDEV** [comment]
Hmm sad to hear, may TeamSpeak changed something.
I'll take a look :)

**Comment by DanielAlves123** [comment]
@WolverinDEV Happened on Version: 3.1.9 on Windows if it's important. :P

**Comment by WolverinDEV** [comment]
Hmm Okey?
I'm not sure but it must be something with active intigrations,because in general it works and it works for me too :)

**Comment by WolverinDEV** [comment]
Still happening?
