### ISSUE TITLE
permission force_push_to_talk auto assigns itself after being removed

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#449]
**Describe the bug**
permission force_push_to_talk auto assigns itself after being removed

**Screenshots**
![](https://i.imgur.com/YEIw1Im.gif)

**Environment information:**
 Operating system: Linux 4.14.70-v7+ #1144 SMP Tue Sep 18 17:34:46 BST 2018 armv7l GNU/Linux

 TeaSpeak version: version=1.2.18-beta build_count=0 build=1537273823
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Seems more to be a display bug and not an actual issue.

**Comment by Bluscream** [comment]
It is an actual issue as i can not talk

**Comment by WolverinDEV** [comment]
You have to wait 5 seconds before the client gets the update.

**Comment by Bluscream** [comment]
I did wait a lot longer than that. Still no way for me to speak

**Comment by WolverinDEV** [comment]
Do you have talk power?
Well even with ppt seems to be a client related issue :)
Btw can't reproduce that error

**Comment by WolverinDEV** [comment]
![](https://img.teaspeak.de/FPTT.gif)

**Comment by Bluscream** [comment]
I got that it's working for you, but that doesn't mean that it works for anyone else. Tell me when you have time then i'll invite you to the server in question

**Comment by Chazotu** [comment]
Still up ?

**Comment by Bluscream** [comment]
Oh lol completely forgot about my server hahaha :D
