### ISSUE TITLE
Connection lost because server license cannot be validated

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#450]
Have a valid working AAL license on the server.

1. Restart the server
2. User connects fine
3. 5-10 mins later, user reconnects and is unable to connect because license cannot be validated.

Error:
22/9/2018 04:59:38	PktHandler	Devel	Puzzle solve time: 1	
22/9/2018 04:59:39	ClientUI	Info	Connect status: Connected	
22/9/2018 04:59:39	SCHandler	Warning	Error while parsing packet: failed to validate server license	
22/9/2018 04:59:39	ClientUI	Error	Failed to get hostmessage mode	
22/9/2018 04:59:39	ClientUI	Info	Connect status: Establishing connection	
22/9/2018 04:59:39	ClientUI	Info	Connect status: Connection established	
22/9/2018 04:59:39	ChatTabWidget	Info	Prevented to set an empty chattab name in addNewTab	
22/9/2018 04:59:39	ClientUI	Info	Connect status: Disconnected

**Comment by MikkelDK** [comment]
Use forum please.
