### ISSUE TITLE
TeaSpeak | 1.2.19-beta-5 - Avatar upload crash server

### ISSUE THREAD

**Issue by csivca** [TeaSpeak/TeaSpeak#456]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'set avatar'
2. Click on 'search picture'
3. Setting to apply 'save.'
4. See error - server  shutdown - application error

**Expected behaviour**

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: (`uname -a`)
 TeaSpeak version: | 1.2.19-beta-5 
 I am using `experimental_31`: yes

**Additional context**
Helo TeaSpeak, i try set avatar sserver going down!
- Other client wanna set avatar avatar .. server again shutdown

**Comment by Chazotu** [comment]
cant repoduce

**Comment by WolverinDEV** [comment]
Crash dump?

**Comment by WolverinDEV** [comment]
Fixed already :)
