### ISSUE TITLE
Crash Dump

### ISSUE THREAD

**Issue by Davide550** [TeaSpeak/TeaSpeak#459]
Crash that happens randomly
[crash_dump_2cb3b1f2-cb45-4c7c-718c74a8-924fc48f.zip](https://github.com/TeaSpeak/TeaSpeak/files/2421542/crash_dump_2cb3b1f2-cb45-4c7c-718c74a8-924fc48f.zip)

**Comment by Davide550** [comment]
Another crash dump
[crash_dump_18be11d8-28cd-4e9e-305a709f-41c0da48.zip](https://github.com/TeaSpeak/TeaSpeak/files/2421692/crash_dump_18be11d8-28cd-4e9e-305a709f-41c0da48.zip)

**Comment by WolverinDEV** [comment]
Version?

**Comment by Davide550** [comment]
Latest
1.2.19-beta-5

**Comment by WolverinDEV** [comment]
Will be fixed within next build :)

**Comment by Davide550** [comment]
Not fixed.
[crash_dump_d4033755-0fd6-46a0-37ac9eba-20bddf23.zip](https://github.com/TeaSpeak/TeaSpeak/files/2425831/crash_dump_d4033755-0fd6-46a0-37ac9eba-20bddf23.zip)

**Comment by Davide550** [comment]
Version 1.2.19-beta-6
