### ISSUE TITLE
Wrong GEO Location

### ISSUE THREAD

**Issue by MrFunken** [TeaSpeak/TeaSpeak#46]
## System Information
***Operating System***: Linux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: Latest

## Issue
***Reason for reporting this issue***:
TS3 Client shows wrong IP Location

***Detailed Description***:
I'm connected to a TeaSpeak Server from 185.189.58.0/24. Not sure from where you get the geolocation information. But the IP should have a UK or EU flag, but TeaSpeak shows it as a German IP.

**Comment by WolverinDEV** [comment]
Hello,
i currently dont have a geo location lookup table, so im not lokking the remote's location up.
But you could change the flag globally for all users in the config :)

**Comment by WolverinDEV** [comment]
~ Fixed in 1.0.24-Beta
