### ISSUE TITLE
 Double ban (the second - in a random way)

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#460]
**Describe the bug**
After locking the user, two are blocked (the second one is random).

**Screenshots**
https://prnt.sc/kzgvqp

**Environment information:**
 Operating system: Debian 9.3
 TeaSpeak version: [TeaSpeak-1.2.19-beta-5]
 I am using `experimental_31`: yes

**Comment by Chazotu** [comment]
Please check if they shared IP/HWID/UUID

**Comment by WolverinDEV** [comment]
Also checkout the terminal.
There should be the reason why the second got banned too :)
