### ISSUE TITLE
Server license could not be validated[AAL] for 2nd or more server instances

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#462]
29/9/2018 05:07:54	SCHandler	Warning	Error while parsing packet: failed to validate server license	
29/9/2018 05:07:55	ClientUI	Error	Failed to get hostmessage mode	

First server instance is fine, the problem starts after the 2nd or 3rd

*Edit* it appears to occur randomly

**Comment by MikkelDK** [comment]
Do you have read the guide? > https://forum.teaspeak.de/index.php?threads/how-to-get-teaspeak-to-show-license-aal-license-from-teamspeak.702/

**Comment by slushpuppy** [comment]
Yes I have, I will keep testing, because it happens on either 1 of the 3 virtual servers i host, it happens randomly and the only way to fix it is to restart the server

**Comment by MikkelDK** [comment]
Hmm.. weird. i don't have any issues. and i'm running 70-80 virtualservers. ;)

**Comment by slushpuppy** [comment]
That's interesting, what is your setup? How many IPs are attached to your server?

**Comment by MikkelDK** [comment]
Only 1 IP ;)

**Comment by slushpuppy** [comment]
Ah ok I have multiple IPs attached to my server. Could that be a cause?

**Comment by MikkelDK** [comment]
That may be the problem. but dunno! ;) i'm only using 1 IP ;)

**Comment by slushpuppy** [comment]
Thanks alot for replying! I'll keep trying and feedback to this thread
