### ISSUE TITLE
Can't install teaspeak

### ISSUE THREAD

**Issue by vale1802** [TeaSpeak/TeaSpeak#464]
i'm trying to install teaspeak from 0 but after i download it and i insert this command "tar -xzf TeaSpeak-X.X.X.tar.gz
rm TeaSpeak-X.X.X.tar.gz" this happens ( http://prntscr.com/l06cj9) and i can't do anything.

**Comment by MikkelDK** [comment]
Why are you typing X.X.X??? ;)

Do this: wget https://repo.teaspeak.de/server/linux/amd64/TeaSpeak-1.2.19-beta-7.tar.gz && rm TeaSpeak-1.2.19-beta-7.tar.gz.2 ;) && tar -zxvf TeaSpeak-1.2.19-beta-7.tar.gz

**Comment by vale1802** [comment]
i did it but after this i've got some other problems... can you help me installing it trought team viewer ?

**Comment by vale1802** [comment]
@MikkelDK  I did it but my ts3 client is 3.2.2 and i can't join the server it is too old... Why ?

**Comment by MikkelDK** [comment]
Read on forum. ;) there is a guide > https://forum.teaspeak.de/index.php?threads/how-to-get-teaspeak-to-show-license-aal-license-from-teamspeak.702/ (because you need a valid license!)

**Comment by vale1802** [comment]
@MikkelDK  I need to buy a license because it says "server version is too old for command" ?

**Comment by Sporesirius** [comment]
Use max. 32 slots per server and it should also work for 3.2.2 clients
