### ISSUE TITLE
Music bot command

### ISSUE THREAD

**Issue by WolverinDEV** [TeaSpeak/TeaSpeak#467]
[ ] Configurable command prefix
[ ] Disable music bots

**Comment by WolverinDEV** [comment]
IUmplemented

**Comment by Fearitselfpt** [comment]
how to disable music bots?

**Comment by lexesv** [comment]
@WolverinDEV 

enabled: 0
but the command ***.help***  still runs

**Comment by WolverinDEV** [comment]
I've never sad that this disables the commands it just disabled the music bots (as requested :))

**Comment by lexesv** [comment]
OK) I was think that disable the music bots means disable the all music bots features
