### ISSUE TITLE
TSViewer error 0 (invalid reply from the server)

### ISSUE THREAD

**Issue by EndiaFR** [TeaSpeak/TeaSpeak#469]
**Describe the bug**
When i try to add my TeaSpeak server to the ts3viewer from www.tsviewer.com, they tell me the error code 0 invalid reply from the server. I see on the FAQ's this error can come from query ban but i add tsviewer ip in my query_ip_whitelist without effect.

**Screenshots**
![image](https://user-images.githubusercontent.com/26543072/46346183-7ef89c80-c647-11e8-835f-325ed4b02fd3.png)

**Logs**
[2018-10-02 11:37:02] [INFO]  QUERY | Got new client from 94.23.235.222:13340
[2018-10-02 11:37:03] [DEBUG] QUERY | Got new query client from 94.23.235.222. Whitelisted: true
[2018-10-02 11:37:03] [ERROR] QUERY | [94.23.235.222:13340/ServerQuery#94.23.235.222/13340] Failed to read! Code: 0 errno: 0 message: Success

**Environment information:**
 Operating system: Linux web1 4.15.18-3-pve #1 SMP PVE 4.15.18-22 (Fri, 24 Aug 2018 11:12:20 +0200) x86_64 GNU/Linux Debian
 TeaSpeak version: latest
 I am using `experimental_31`: no

**Comment by MikkelDK** [comment]
There will be a guide later today on forum! ;)

**Comment by EndiaFR** [comment]
Okay thank you :D

**Comment by MikkelDK** [comment]
> Can u notify me on this post when the tutorial is online ? :p

I'm already going to create it now! ;)

**Comment by EndiaFR** [comment]
Ah this is so nice :D

**Comment by MikkelDK** [comment]
it is online now on forum! ;) just close this ^^

**Comment by EndiaFR** [comment]
Ok that's work perfectly now ;) Thanks !

**Comment by MikkelDK** [comment]
Did it works for you?

**Comment by EndiaFR** [comment]
Yes ! I can got my teamspeak on a widget in my website :) Thanks from me and my community ;)
