### ISSUE TITLE
server does not start

### ISSUE THREAD

**Issue by cleronfx** [TeaSpeak/TeaSpeak#471]
## System Information
***Operating System***: Debian 9
***Operating System Type***: x64
***TeaSpeak Version***: Linux x64 | 1.2.20-beta 

## Issue
server does not start

***Detailed Description***:

root@srv50002:/home/gamer# ./teastart_minimal.sh start
Time 09:58:37 date Sep 15 2018
./TeaSpeakServer: symbol lookup error: ./TeaSpeakServer: undefined symbol: _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE
root@srv50002:/home/gamer# ./teastart_minimal.sh start
Time 09:58:37 date Sep 15 2018
./TeaSpeakServer: symbol lookup error: ./TeaSpeakServer: undefined symbol: _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE

or 

root@srv50002:/home/gamer# ./teastart_minimal.sh
Time 09:58:37 date Sep 15 2018
./TeaSpeakServer: symbol lookup error: ./TeaSpeakServer: undefined symbol: _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE
root@srv50002:/home/gamer#

**Comment by GoRiLliAz** [comment]
Hi
Not start server in root...

**Comment by cleronfx** [comment]
Hi,
the server does not start with other users either ...

**Comment by WolverinDEV** [comment]
Do you have a default setup (I mean your operating system)?
Did you may installed a custom compiled standard library?

**Comment by cleronfx** [comment]
my server is a clean Debian 9 system .... :-(

**Comment by WolverinDEV** [comment]
... How had you updated?

**Comment by WolverinDEV** [comment]
Any response?

**Comment by WolverinDEV** [comment]
I'll close that here due no response
