### ISSUE TITLE
protocol_key.txt

### ISSUE THREAD

**Issue by eucode** [TeaSpeak/TeaSpeak#472]
Give me a protocol_key.txt that work... If i set slot up to 32, 3.2.2 teamspeak users they can not enter :(

**Comment by eucode** [comment]
i use teaspeak 1.2.20

**Comment by MikkelDK** [comment]
This is not a issues!

@Chazotu or @WolverinDEV can u close this? ^^

**Comment by Chazotu** [comment]
closed
