### ISSUE TITLE
Missing command ''

### ISSUE THREAD

**Issue by Ondra3211** [TeaSpeak/TeaSpeak#474]
Server say every minute "error"

Log: https://haste.zerocz.eu/ugeximavad.cs
TeaSpeak chat: https://haste.zerocz.eu/izugudoxen.css

Version:TeaSpeak 1.2.19-beta
My client version: 3.2.3 [Beta]

**Comment by WolverinDEV** [comment]
Hey,
this is a error caused by TS3Hook and the blocking of commands.
This isnt a TeaSpeak error.
