### ISSUE TITLE
Adding the IP at the ban

### ISSUE THREAD

**Issue by GoRiLliAz** [TeaSpeak/TeaSpeak#475]
**Is your feature request related to a problem? Please describe.**
Hello
On TeamSpeak when a person was banned, it was by ID and IP.
This was useful, because there it just that the person re-installs are client to have a new ID is  come back.

**Describe the solution you'd like**
Automatically ban by ID and IP as under TeamSpeak

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by DanielAlves123** [comment]
Had this problem too.

**Comment by Chazotu** [comment]
TeaSpeak also ban by ID and IP on default if you have the permission (b_client_remoteaddress_view)

**Comment by GoRiLliAz** [comment]
It doesn't work, I have that permission.
In addition this permission is just to display the IP address when you do a right click  "Client login information "

**Comment by Chazotu** [comment]
Yeah,
In Tea**m**speak its like that.
With TeaSpeak its a little bit different.
This permission has more then just that one meaning :)

**Comment by GoRiLliAz** [comment]
Ok, but doesn't work 
![look](https://user-images.githubusercontent.com/18401955/46906959-af73ec80-cf0b-11e8-8a93-9cefa6a72cb4.PNG)

**Comment by WolverinDEV** [comment]
Well its relative easy.
If you right click on a client and click on ban TeaSpeak bans as following:
- add ban for unique id and client database id
- if client is online:
  - if permission `b_client_remoteaddress_view` is granted:
     - add ban for client ip and client hardware id
