### ISSUE TITLE
Packet resend failed/invalid channelID

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#479]
People get disconnected with invalid channelID, then they cant join for like 30 seconds.

**Comment by WolverinDEV** [comment]
Still with the newest version? (Build 1)

**Comment by DanielAlves123** [comment]
@WolverinDEV I will investigate that.

**Comment by DanielAlves123** [comment]
@WolverinDEV 
<16:07:18> "Morfina" dropped (No ping response)
<16:08:02> "Morfina" dropped (Packet resend failed)
<16:10:58> "Rays" dropped (Packet resend failed)
<16:10:59> "Morfina" dropped (Packet resend failed)
<16:12:00> "WaleWiadroo" dropped (No ping response)
<16:23:04> "teamspeak user" dropped (No ping response)
<16:25:09> "M A R C E L ϟ" dropped (Packet resend failed)
<16:31:47> "teamspeak user" dropped (No ping response)
<16:36:07> "ESZKERE" dropped (No ping response)
<16:36:30> "kopiaa" dropped (Packet resend failed)
<16:37:54> "Patrycja." dropped (No ping response)
<16:38:47> "McSebaPizi" dropped (Packet resend failed)

**Comment by WolverinDEV** [comment]
Doesnt help...
Version user log etc

**Comment by DanielAlves123** [comment]
@WolverinDEV join the server and check by yourself. How can i tell you these informations? Btw im banned on your teamspeak

**Comment by DanielAlves123** [comment]
You banned me for 1 hour with reason 'fuck off' then when i reconnected someone gave me permanent ban.

**Comment by WolverinDEV** [comment]
You haven't one anymore :)

**Comment by WolverinDEV** [comment]
And how is the newest version going?
I explicitly tested within 24 the channel switch and create system. Does these errors still appear?

**Comment by DanielAlves123** [comment]
@WolverinDEV I will test it today with multiple identities connected. :)

**Comment by DanielAlves123** [comment]
Still happening. Confirmed packet resend failed and Disconnected from server (already member of channel)

**Comment by DanielAlves123** [comment]
@WolverinDEV @Chazotu actually it dropped whole teamspeak, couple days befofe that it crashed whole server 2 times.

**Comment by WolverinDEV** [comment]
Crash dump?
Server version?
There were some fixes in 26 build 1 if I remember right :)

**Comment by DanielAlves123** [comment]
@WolverinDEV I sent you crash dumps on your teamspeak, I will investigate it more.

**Comment by WolverinDEV** [comment]
As a notification to all viewer:
I've looked at them and there Wil be a fix today :)

**Comment by Sickness-chan** [comment]
Nice, that issue has been plaguing TeaSpeak for a while, and is probably the only annoying one that is left

**Comment by hamidkag** [comment]
when i drop for no reason in my server
see the log:
`[2018-11-23 13:37:24] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:24] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:24] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:25] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:25] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:26] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:27] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:27] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Resend 1 packets (Expected response within 57.4644ms)
[2018-11-23 13:37:28] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Failed to receive disconnect acknowledge!
[2018-11-23 13:37:28] [DEBUG]     1 | [176.65.240.18:29484/TeamSpeakUser | 1] Closing voice client connection. (Flush: false)
`

**Comment by Sickness-chan** [comment]
@WolverinDEV did you only fix the crash that was mentioned or did you fix the resend issue too?

**Comment by Sickness-chan** [comment]
@WolverinDEV anything new about the packet resend problem? How can someone help in getting it fixed, what logs do you need?

**Comment by WolverinDEV** [comment]
Well in general this only happens when the internet is slow or "broken".
I'm currently working on the second significant update, focusing the reconnect after a timeout.
This allows then to directly rejoin without waiting 20 sec. I think then it might improve as well.

**Comment by WolverinDEV** [comment]
This should be in general fixed :)
Closing this issue here :)
