### ISSUE TITLE
serverinstance_pending_connections_per_ip as perm per server

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#48]
This is only set-able on the full instance but i think it would be awesome if each virtualserver admin could use a `i_client_max_clones_ip` permission to set a limit for their server (if it does exceed the instance limit i think the instance limit should have higher priority)

There's already `i_client_max_clones_uid` but i think the connections per IP should be settable via a permissions too and work the same way.

Got and spun the idea from https://r4p3.net/threads/script-multi-instance-on-single-ip.6051/post-53137

**Comment by WolverinDEV** [comment]
Implemented:
Permission name: `i_client_max_clones_ip`

BTW: `serverinstance_pending_connections_per_ip` isnt implemented :)

**Comment by Bluscream** [comment]
Thanks :3
