### ISSUE TITLE
CLIENT_DESCRIPTION property

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#480]
I cant get CLIENT_DESCRIPTION, it returns empty string.

**Comment by WolverinDEV** [comment]
Where do you expect this property

**Comment by REDMONDS** [comment]
@WolverinDEV How to delete user description? https://prnt.sc/l76ltn

**Comment by MikkelDK** [comment]
> @WolverinDEV How to delete user description? https://prnt.sc/l76ltn

Ask on forum! ;) it's not a issue here. ^^

**Comment by HAMMERxPL** [comment]
It should be client property too see and edit client's descripiton. Right now this option doesnt work with teamspeak api.

**Comment by WolverinDEV** [comment]
Yeah which command, where do you expect that

**Comment by HAMMERxPL** [comment]
@WolverinDEV https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/ClientProperty.java#L56

**Comment by WolverinDEV** [comment]
I still need the command...

**Comment by DanielAlves123** [comment]
@WolverinDEV https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/Wrapper.java#L209

**Comment by WolverinDEV** [comment]
With which command do you expect to be description in ?!

**Comment by DanielAlves123** [comment]
@WolverinDEV I have to get property CLIENT_DESCRIPTION and set description to the client. CLIENT_DESCRIPTION property returns empty string.

**Comment by WolverinDEV** [comment]
Yeah,
how are you doing that?
And where is the issue

**Comment by DanielAlves123** [comment]
@WolverinDEV com.github.theholywaffle.teamspeak3.api.wrapper.Client.get(ClientProperty.CLIENT_DESCRIPTION);

IT RETURNS EMPTY STRING.

**Comment by WolverinDEV** [comment]
... that tells me **nothing**

**Comment by DanielAlves123** [comment]
@WolverinDEV what the fuck am i supposed to tell you? You cant get and change client's description man.

**Comment by WolverinDEV** [comment]
Yeah,
Which command are you executing and where do you expect it

**Comment by DanielAlves123** [comment]
@WolverinDEV I don't know which command it uses, check this api for more informations.

**Comment by DanielAlves123** [comment]
@WolverinDEV fixed. Could you look at the ban issue? People without permission to see the address cant ban for ip and hwid, thats really annoying.
