### ISSUE TITLE
Server Group icon upload problem

### ISSUE THREAD

**Issue by okanozdemir** [TeaSpeak/TeaSpeak#482]
Unable to upload Server Group icon. It seems to be correctly uploaded first, but when check again, it doesn't seem. When you clear the cache, the icons disappear completely.

**Screenshots**
![](https://media.giphy.com/media/xAPuw7rHQ3zUUi97wC/giphy.gif)

[Server Log](https://github.com/TeaSpeak/TeaSpeak/files/2508685/log_2018-10-24_04_46_31_general.log)

**Environment information:**
 Operating system: Ubuntu 18.04 Server on AWS EC2
 TeaSpeak version: 1.2.23-beta-2
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Well please post a wider log view.
What also does the server log within the client says?

**Comment by okanozdemir** [comment]
Client says nothing. No error or anything else. This is my server log. I started the server, tried uploading an icon and stopped the server.

[Server Log](https://github.com/TeaSpeak/TeaSpeak/files/2508685/log_2018-10-24_04_46_31_general.log)

**Comment by WolverinDEV** [comment]
```
[2018-10-24 04:46:45] [INFO]   FILE | Got new client from 176.41.148.6:55363
[2018-10-24 04:46:45] [ERROR]  FILE | [0|176.41.148.6:55363|unconnected] Remote peer closed the connection
[2018-10-24 04:46:45] [DEBUG]  FILE | [0|176.41.148.6:55363|unconnected] Disconnecting client. Connection state: 0 Flush IO: true
```
Well it seems like the file transfer does not really writes the data because the client instantly disconnects.
Ill work on it :)

**Comment by WolverinDEV** [comment]
Should be fixed within the next build :)

**Comment by okanozdemir** [comment]
> Should be fixed within the next build :)

In version 1.2.25-beta or maybe .26 ? Sorry but still have same problem in:
```
Version: 1.2.25-beta
TeaSpeak version: 1.2.25-beta
```

**Comment by WolverinDEV** [comment]
Yeah I mean 1.2.25-1.
Will be out in a few minutes currently trouble with my build server :D
