### ISSUE TITLE
Bans

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#485]
Default bans are not for ip or hwid, just for uid and name, please fix that or add permission for this. Thanks

**Comment by WolverinDEV** [comment]
Default bans are for IP and hardware IP.
You just require the permission to see ip addresses.

**Comment by DanielAlves123** [comment]
@WolverinDEV People with permission to see ip ban for ip and people without this permission ban for uid. Thats how it looks in ban list.

**Comment by WolverinDEV** [comment]
Yes :)

**Comment by DanielAlves123** [comment]
@WolverinDEV yes, thats how it shouldnt work. All default bans should be on ip and hwid.

**Comment by DanielAlves123** [comment]
@WolverinDEV XDDD Why do you want to see someone's ip when you only want to ban him. XD And make people be aware of various ddos or something XD Thats why on teamspeak its done like im saying

**Comment by WolverinDEV** [comment]
Well look at release 25 :)

**Comment by DanielAlves123** [comment]
@WolverinDEV thank you <3
