### ISSUE TITLE
Could not connect to my teaspeak server

### ISSUE THREAD

**Issue by alsoGAMER** [TeaSpeak/TeaSpeak#490]
<14:56:39> Trying to connect to server on myip
<14:56:40> Disconnected from server (server version is too old for command)

**Environment information of the client:**
 Operating system: (`Linux alsoPC 4.18.16-200.fc28.x86_64 #1 SMP Sat Oct 20 23:53:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`)
 TS3 Client version: 3.2.3

**Environment information of the server:**
 Operating system: (`Linux myhost 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 GNU/Linux`)
 TeaSpeak version: {build_name: "1.2.26-beta-2", build_version: "1.2.26-beta", build_index: 2}
 I am using `experimental_31`: no

**Comment by MikkelDK** [comment]
This is not a issue.

Look on the forum >> experimental_31 needed to be 1 (AND you NEED VALID license before people can join the server!) ->>> https://forum.teaspeak.de/index.php?threads/how-to-get-teaspeak-to-show-license-aal-license-from-teamspeak.702/
