### ISSUE TITLE
Teamspeak bind IP

### ISSUE THREAD

**Issue by peylight** [TeaSpeak/TeaSpeak#492]
Hi
Teamspeak bind IP address not working.
I set host ip address for query and file but in the server list i see another ip address.

**Comment by WolverinDEV** [comment]
Yeah the TeamSpeak 3 server list would be requested from the main ip. But in general it works for each individual server.

**Comment by peylight** [comment]
What do you mean about the web list?
My server have multiple IP address and each one for something else.
In the original ts3 server when i set the IP address then i see that in the server list. but now for TeaSpeak i see another IP address.
Now people can't join to my server because i blocked my main IP address ports. 
How can i fix that?

**Comment by WolverinDEV** [comment]
Im sorry I ment the TeamSpeak server list.

**Comment by peylight** [comment]
Are you remove server list ability in the new version(1.2.27-beta-1)?
After i update to the new version i can't see my server in the server list.

**Comment by hamidkag** [comment]
> 
> 
> Are you remove server list ability in the new version(1.2.27-beta-1)?
> After i update to the new version i can't see my server in the server list.

yes dude... turn back your server to 1.2.26
1.2.27 is shit

**Comment by WolverinDEV** [comment]
use 1.2.29 :)
That seems more stable :)

**Comment by peylight** [comment]
I checking the by lsof ip binding seems not working..
```
COMMAND     PID      USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
TeaSpeakS  4294 teamspeak   18u  IPv4 291604      0t0  TCP 87.236.xxx.xxx:30033 (LISTEN)
TeaSpeakS  4294 teamspeak   23u  IPv4 291620      0t0  TCP 87.236.xxx.xxx:10011 (LISTEN)
TeaSpeakS  4294 teamspeak   44u  IPv4 292583      0t0  UDP *:9987 
TeaSpeakS  4294 teamspeak   45u  IPv6 292584      0t0  UDP *:9987 
TeaSpeakS  4294 teamspeak   54u  IPv4 292591      0t0  TCP *:9987 (LISTEN)
TeaSpeakS  4294 teamspeak   55u  IPv4 292630      0t0  UDP *:30567 

```
The qurey (9987) port is binding to all ip address.
I try to add host in the config.yml for quey option, But it's not working...

**Comment by WolverinDEV** [comment]
`serveredit virtualserver_host=...`

**Comment by peylight** [comment]
you should add this feature to the config.yml

**Comment by WolverinDEV** [comment]
Will be implemented within the next build :)

**Comment by xlenonz** [comment]
there is no workaround for that yet?

when i create new virtual server like 9999 port it bind 0.0.0.0 and 9999

i want to bind always same ip not 0.0.0.0

how can i do that?

**Comment by WolverinDEV** [comment]
You could specify the property `virtualserver_host` or change the default value within the config.yml :)
