### ISSUE TITLE
Youtube playlist to music bot

### ISSUE THREAD

**Issue by lbenicio** [TeaSpeak/TeaSpeak#493]
**Is your feature request related to a problem? Please describe.**
The need of keeping re-adding videos to the queue each 3-5 minutes is too annoying

**Describe the solution you'd like**
a music bot command to play youtube video accept playlist as well

**Describe alternatives you've considered**
a separate command for yt playlists

**Comment by WolverinDEV** [comment]
Playlist is a duplicate enchant of https://github.com/TeaSpeak/TeaMusic/issues/3

Auto repeat is a duplicate of
