### ISSUE TITLE
android clients cant view avatar in TeaSpeak Server!

### ISSUE THREAD

**Issue by hamidkag** [TeaSpeak/TeaSpeak#494]
hi
there is a problem [an error] on TeaSpeak Server
when i connect to my TeaSpeak server with android client i cant view the client avatars [in client info]
and there is an error: "not implemented"

i take an screenshot, link below:
http://s8.picofile.com/file/8342153300/photo_2018_11_08_14_43_17.jpg

check it and fix it
thanks

**Comment by WolverinDEV** [comment]
Fixed within the next build :)
