### ISSUE TITLE
CONNECTION_CONNECTED_TIME doesn't work

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#497]
I think client property CONNECTION_CONNECTED_TIME doesn't show anything and you can't check it.

**Comment by WolverinDEV** [comment]
Command again?

**Comment by DanielAlves123** [comment]
@WolverinDEV clientinfo or clientlist

**Comment by WolverinDEV** [comment]
Fixed be fixed within the next version (it was `clientinfo`)
(Not1.2.27-3!)
