### ISSUE TITLE
Getting kicked while having 2 connections to the same server on 2 different identities

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#499]
**Describe the bug**
After 1-2 minutes after connecting to the same server with 2 different identities, the second one gets kicked by the server for whatever reason.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to the server on 1 identity
2. Connect to the same server in a new tab with another identity
3. Wait 1-2 minutes
4. Get kicked by the server

**Expected behaviour**
Shouldn't be kicked

**Screenshots**
https://i.killuminati.eu/74722187b.webm
https://i.killuminati.eu/7470S7770.png
https://i.killuminati.eu/7471C033k.png

**Logs**
https://pastebin.com/7f1uAqYe

**Environment information:**
 Operating system: Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
 TeaSpeak version: TeaSpeak-1.2.26-beta-2
 I am using `experimental_31`: yes

**Comment by Zaword** [comment]
Check `i_client_max_clones_ip` and `i_client_max_clones_hwid`
Set them to -1 for no limits

**Comment by Sickness-chan** [comment]
Tried changing the limits for those permissions, it doesn't make a difference for this issue. It's actually this permission: `b_client_allow_invalid_packet`, although I don't know what the invalid packet would be if there's nothing happening. Should be looked into.

**Comment by Bluscream** [comment]
`[2018-11-15 17:10:28] [ERROR]     2 | Missing command ''`

That means your other ID is using ts3hook which denied by that pemission.

**Comment by Sickness-chan** [comment]
TS3Hook is disabled, it has to launch via a startup parameter as far as I know, which I don't have enabled.

**Comment by Bluscream** [comment]
@Sickness-chan nope, you dont have it as startup parameter and older versions of it won't care if you enabled it.

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bluscream** [comment]
If you want to know anything else you should maybe not let me wait on your server xd
