### ISSUE TITLE
Missing variable in ClientInfo Command Response

### ISSUE THREAD

**Issue by MypowerHD** [TeaSpeak/TeaSpeak#501]
Da fehlt mal wieder im ClientInfo Querry command Response eine Variabel.
"Can not cast null value of parameter 'connection_connected_time' to target type 'System.UInt32'."
währe sehr erfreulich wenn du sie für den nächsten build hinzufügen magst.

**Comment by WolverinDEV** [comment]
Any proof and or switch for teamspeak?
Actually client info just returns client variables

**Comment by MypowerHD** [comment]
![60ff522fba4bc4ae25efbe5ce16c18fe](https://user-images.githubusercontent.com/10728025/48984948-78941780-f102-11e8-9d23-318af0e9429a.png)

**Comment by WolverinDEV** [comment]
Fixed within next build :)
