### ISSUE TITLE
Server Crash on serverquery load.

### ISSUE THREAD

**Issue by ts3cloud** [TeaSpeak/TeaSpeak#504]
**Describe the bug**
When the query (php) robot starts performing cleaning of unused servers, the server crashes.

**To Reproduce**
Many query queries

**Environment information:**
 Operating system: Debian 8
 TeaSpeak version: 1.2.28-beta-1 
 I am using `experimental_31`: yes

**Additional context**
Crashdump
[crash_dump_5069fcc9-39b3-4447-b57ae280-128a210f.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2603399/crash_dump_5069fcc9-39b3-4447-b57ae280-128a210f.tar.gz)

**Comment by ts3cloud** [comment]
It is really bad..

`[2018-11-21 15:22:49] [CRITICAL]   GEN | The server crashed!
[2018-11-21 15:22:49] [CRITICAL]   GEN | Wrote crash dump to crash_dumps/crash_dump_415d93f1-3827-47e8-0922139c-aa697108.dmp
[2018-11-21 15:22:49] [CRITICAL]   GEN | Please report this crash to the TeaSpeak maintainer WolverinDEV
[2018-11-21 15:22:49] [CRITICAL]   GEN | Official issue and bug tracker url: https://github.com/TeaSpeak/TeaSpeak/issues
[2018-11-21 15:22:49] [CRITICAL]   GEN | Any reports of crashes are useless if you not provide the above generated crashlog!
[2018-11-21 15:22:49] [CRITICAL]   GEN | Stopping server
[2018-11-21 15:23:19] [CRITICAL]   GEN | Could not shutdown server within 30 seconds! (Hangup!)
[2018-11-21 15:23:19] [CRITICAL]   GEN | Killing server!
`
Crash every 2 hours ..

[crash_dump_415d93f1-3827-47e8-0922139c-aa697108.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2604578/crash_dump_415d93f1-3827-47e8-0922139c-aa697108.tar.gz)

**Comment by ts3cloud** [comment]
Create 2k+ servers and try to stop/delete it via query. 
example code: 
>             foreach ($tslist->serverList() as $serverID => $serverNAME) {
>                    if (strcasecmp($serverNAME->virtualserver_status, 'online') == 0) {
>                           $tslist->serverStop($serverID);
>                     }
>                       if (strcasecmp($serverNAME->virtualserver_status, 'offline') == 0) {
>                         $tslist->serverDelete($serverID);
>                     }
>               }

Now, i am downgraded all servers. Old version work OK (except tommorow and today night-crash  ) :( )

If you have any question, contact me, PM.

**Comment by wendellcosta** [comment]
> Yes,
> Its already a known problem, and I run out of ideas.
> Im already running a bot starting and stopping servers, no result.
> (Actually found another rare crash :D)

dont start/stop empty instance

**Comment by WolverinDEV** [comment]
Update server to beta 2 :)
(May fixed)

**Comment by wendellcosta** [comment]
It looks like this has been fixed, I have done few tests

**Comment by WolverinDEV** [comment]
Great to hear :)
I'll close that here for now
