### ISSUE TITLE
SQL Errors

### ISSUE THREAD

**Issue by Dad-Ju** [TeaSpeak/TeaSpeak#505]
## System Information
***Operating System***: Ubuntu 16.04-Latest
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: # Version: 1.2.28-beta-1 # TeaSpeak version: 1.2.28-beta # Build version: 1

{build_name: "1.2.28-beta-1", build_version: "1.2.28-beta", build_index: 1}

## Issue ##
SQL Errors & Some More

***Detailed Description***:

I think that says very much.
I don`t know from where it come or it beginns.
https://hastebin.com/alefadocul.sql

I also got 3 or 4 crashes in a row after Server Start
[crash_dump_f514180d-7846-47ec-37f9b08f-7ddbfcef.zip](https://github.com/TeaSpeak/TeaSpeak/files/2606079/crash_dump_f514180d-7846-47ec-37f9b08f-7ddbfcef.zip)

Can anyone Help me ?
Good Wishes Ju

**Comment by WolverinDEV** [comment]
Okey,
well these errors, except the crash dumps are not really critical.
I have to remove the message properly.

I'll look at the crash dumps as soon im back home

**Comment by WolverinDEV** [comment]
The SQLIte error shall be disappeared, crashes fixed
