### ISSUE TITLE
Can't Install TeaSpeak under Windows 10

### ISSUE THREAD

**Issue by Jonirulah** [TeaSpeak/TeaSpeak#507]
I can't install TeaSpeak client under Windows 17134.407

I open the installer and i suddenly get this error

![image](https://user-images.githubusercontent.com/25936173/48964477-9483a600-efa8-11e8-933c-17f6675da4f1.png)

I tried both the zip and the exe version.

**Comment by WolverinDEV** [comment]
Yeah,
I seems a littlebit for me that a library or something is missing.
My guess is that it works for me because I've install the node libraries, and on all my test devices as well.
I'll try to use a VM :)

**Comment by WolverinDEV** [comment]
Update:
Event within a VM I dont get that error

**Comment by C4KMASTER** [comment]
I have the same error.

**Comment by Jonirulah** [comment]
I installed nodejs
I found that it says that the module that is supposed to not be found is indeed in the Temp Folder
![image](https://user-images.githubusercontent.com/25936173/48973171-82057d00-f039-11e8-94e5-6d3dd338e633.png)

**Comment by WolverinDEV** [comment]
Snd did it worked?

**Comment by Jonirulah** [comment]
It didn't, it keeps happening

**Comment by WolverinDEV** [comment]
What the hell, Okey? That's somehow crazy because it seems like the file exists. Ever tried to run the Programm as admin? (may it can't read that directory for some reason)

**Comment by sysworx** [comment]
Same here too...

**Comment by WolverinDEV** [comment]
Well its not hardcoded  by me.
It must be something from electron itself, I'm already searching around, but I dont really find anything.

**Comment by WolverinDEV** [comment]
Fixed: https://forum.teaspeak.de/index.php?threads/teaclient-1-1-0-a-critical-error-happened.1441/page-3#post-9721
