### ISSUE TITLE
In client generated serverquery cant use comannd line

### ISSUE THREAD

**Issue by lbenicio** [TeaSpeak/TeaSpeak#508]
**Describe the bug**
If you create a new serverquery login and password via TeamSpeak client and try to login to serverquery interface it fails to select the server.

For example, I have a server which server id (sid) = 1.

If I log in with the new generated login and password and try to select a server with the command "use <server id>" (in this case, it would "use 1"). it fails with that error: 

error id=2568 msg=insufficient\sclient\spermissions failed_permid=22

**To Reproduce**
1. Create a new serverquery login and password via TeamSpeak Client
2. Login via telnet interface with your new credentials
3. use command "use" <server id> (with proper server id)

**Expected behaviour**
You should be able to create serverqueyr credentials capable of managing your server

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: Ubuntu x64
 TeaSpeak version: 1.2.28-beta-1
 I am using `experimental_31`: yes

**Additional context**

**Comment by WolverinDEV** [comment]
Ahh well you have to give the client the permission `b_virtualserver_select` on your server.
This is also a way to control on which server the client is allowed to loging :)

**Comment by lbenicio** [comment]
let me ask a stupid question.

Menu Tools - > Serverquery Login (generate a new login), how do I change that permissions for that newly generated login? @WolverinDEV

**Comment by Bluscream** [comment]
You change the permissions for the client you made the login with.

**Comment by lbenicio** [comment]
that is my question, i did a little search and could not find how to change it. If i open the client permissions i have to have the client uniq id to change a permission for a specific client and it generate only the name and the password

**Comment by Bluscream** [comment]
You can change any permissions that apply to the client, either one of his server groups, or client permission or if you want to be real restrictive you just change the client-channel permissions for the default channel for that client.

**Comment by Bluscream** [comment]
Either you rightclick him->permissions->client permissions or change the perms of one of his servergroups

**Comment by lbenicio** [comment]
that is the problem, it is a server query newly created, i dont know which servergroups it belongs to and it is not shown as a normal client in channels tree, so i cant select it

**Comment by Bluscream** [comment]
The serverquery is bound to the client it was created with, so if you created with your admin identity it has the same permissions as that ID

**Comment by lbenicio** [comment]
Strange, I'm the Server Admin, but when I try to change the b_virtualserver_select property of the serveradmin i got an "insufficient client permissions (failed on i_permission_modify_power)" error

**Comment by Bluscream** [comment]
That ,eans that your admin's "grant" value is below what you would need, which makes sense in case the group doesnt have the permission by default you also dont want to give them the perms to give them to theirselves. Just do it with the query admin

**Comment by lbenicio** [comment]
the problem is, the Server Admin (the main one which is created on a newly created server) group has `i_permission_modify_power` set to 75, which came by default on a newly created server. If I try to increase that value I got the same error and with the power 75 I can't change the serverquery permissions for any servergroup

**Comment by Bluscream** [comment]
Every permission has its own "..._needed_modify_power". you should look up some tutorials about teamspeak permissions, man

**Comment by lbenicio** [comment]
I know about permissions, that is why I'm getting frustrated about that, everything seems ok but is not working, i have the devs here doing such a great work.

As you can see, the permissions seems fine:
https://imgur.com/a/eVJTIAB

anyways, thank you for your time and patience.

**Comment by Bluscream** [comment]
Apperantly you do not know a lot about permissions, because to assign ![](https://placehold.it/15/30FF00/FFFFFF?text=+) you need ![](https://placehold.it/15/FF0000/FFFFFF?text=+). 

![ts3client_win64_2018-11-28_21-35-29](https://user-images.githubusercontent.com/3318223/49180663-36aae180-f34d-11e8-9ca3-0abb0aebba95.png)

**Comment by lbenicio** [comment]
Yeah, i know
![as shown here](https://i.imgur.com/QmHIuVG.png)

**Comment by Bluscream** [comment]
`i_permission_modify_power` is **not** the same as what i showed...

**Comment by Bluscream** [comment]
![2018-11-28_23-48-24](https://user-images.githubusercontent.com/3318223/49187566-ceb1c680-f35f-11e8-99a6-010e7b37690f.png)

**Comment by lbenicio** [comment]
i already gave that permissions thought server query admin to all available servergroups:

![as shown here](https://i.imgur.com/4lhF0v0.png)

**Comment by Bluscream** [comment]
Can you try to give it with YaTQA?

**Comment by lbenicio** [comment]
Seems fine in yatqa but the changes dont show up in the TS Client

![yaqta](https://i.imgur.com/0ggEK53.png)
![ts](https://i.imgur.com/etuW8wH.png)

**Comment by lbenicio** [comment]
im trying to make a web interface similar to yaqta to each of my server but i dont want to give serverquery admin password to all my servers users, i wanna them to be able to generate a new serverquery login and query the specific server, that is why i'm getting this trouble =(

sorry for the hard time
