### ISSUE TITLE
serverlist shows wrong details of server!

### ISSUE THREAD

**Issue by hamidkag** [TeaSpeak/TeaSpeak#509]
i test all versions on my VPS for u
test for report true details of server [Server Password and channel create ability]
v1.2.28-beta 2 ---> show wrong details [server password = yes! && channel create ability = No!]
v1.2.28-beta 3 ---> show wrong details [server password = yes! && channel create ability = No!]
v1.2.28-beta 4 ---> show wrong details [server password = yes! && channel create ability = No!]
v1.2.28-beta 5 ---> show wrong details [server password = yes! && channel create ability = No!]
v1.2.29-beta ---> show wrong details [server password = yes! && channel create ability = No!]
v1.2.29-beta 1 ---> show wrong details [server password = yes! && channel create ability = No!]

and i also tested my last lovely stable version 1.2.26 beta-2 ---> show true details [server password = NO - channel create ability = YES]

and now i try to test 1.2.28 beta and beta 1

**Comment by hamidkag** [comment]
v1.2.28-beta ---> show wrong details [server password = yes! && channel create ability = No!]
v1.2.28-beta 1 ---> show wrong details [server password = yes! && channel create ability = No!]

there is 2 more bug version

**Comment by hamidkag** [comment]
pleae fix 1.2.29 because ita more stabe than 1.2.26 beta-2 xD
i always test all version for u
if u want any VPS to test tell me
i have more

**Comment by WolverinDEV** [comment]
Will be fixed within the next build :)

**Comment by hamidkag** [comment]
> 
> 
> Will be fixed within the next build :)

its not fix in 1.2.30 too!

**Comment by hamidkag** [comment]
dude v1.2.26 report true details... so its for your source codes... u should look up for some wrong code 

u know? mybe You may have moved the word yes and no

there is yes for server pass and no for channel guess

**Comment by hamidkag** [comment]
[2018-11-27 04:09:26] [DEBUG]     1 | [WebList] Requesting from local address 0.0.0.0:9987:30567
[2018-11-27 04:09:27] [DEBUG]     1 | [WebList] Sending properties: flag_channel: false, flag_server: true
[2018-11-27 04:09:27] [INFO]      1 | [WebList] Status update succeeded! Scheduling next update in ten minutes.
