### ISSUE TITLE
High CPU usage (v1.0.28-beta)

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#51]
## System Information
***Operating System***: Debian 9 (**Only on debian 9? !**)
***Operating System Type***: x64
***TeaSpeak Version***: v1.0.28-beta

## Issue
***High CPU usage***:

![_2018-02-12_18-28-27](https://user-images.githubusercontent.com/15149258/36107476-d84de0f0-1022-11e8-9096-ee86524c2008.png)

**Comment by mytstools** [comment]
Operating System: Debian 9.3 Stretch (stable) (64bits)
```
uname -v
#1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
```
Operating System Type: x64
TeaSpeak Version: v1.0.29-beta
OVH Server - i7-4790K - 16GB 

![2018-02-18_21-49-10](https://user-images.githubusercontent.com/36574855/36356123-eb15b00a-14f5-11e8-8d53-778d114f7f56.png)

**Comment by lexesv** [comment]
Operating System: Debian 9.3 Stretch (stable) (64bits)
```
uname -v
#1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
```
Operating System Type: x64
TeaSpeak Version: v1.0.29-beta
OVH Server - i7-4790K - 16GB 

![2018-02-18_21-49-10](https://user-images.githubusercontent.com/15149258/36356164-7d9eb124-14f6-11e8-8e68-aba7ce11534d.png)

**Comment by lexesv** [comment]
strangely...
The CPU usage is normal after creating another virtual server

**Comment by sudosu0** [comment]
> strangely...
> The CPU usage is normal after creating one more virtual server

x2

**Comment by WolverinDEV** [comment]
Hey,
i have a little question.
Is the cpu usage only so high when zero users are on the server or even when somebody is online?

**Comment by essemX** [comment]
Issue confirmed with Debian 8.10 so its not only for debian 9 (to answer one question)
```
uname  -v
#1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19)
```

@WolverinDEV 
teaspeak uses 1 core at 100% with one user online while teamspeak uses ~3% with ~5 users

**Comment by WolverinDEV** [comment]
Basically the 100% issue is an fail. Thats just a loop which runs without breaks, and i still could not resolve why :/

**Comment by essemX** [comment]
@WolverinDEV saw it but wanted to wait until we got more information about the webclient. but i guess i can try it now

**Comment by lexesv** [comment]
@WolverinDEV  https://github.com/TeaSpeak/TeaSpeak/issues/58

**Comment by WolverinDEV** [comment]
This should be fixed :)
