### ISSUE TITLE
High Server load and drop clients

### ISSUE THREAD

**Issue by ts3cloud** [TeaSpeak/TeaSpeak#510]
**Describe the bug**
Server generate high server load (~20) on 4 cores and suddenly drop all clients.

**To Reproduce**
Steps to reproduce the behaviour:
Load server 1k+ clients

**Logs**
 logs spam only: ( how to fix it ??  this log rape disk :()  

> [2018-11-26 22:20:41] [ERROR] 19834 | Found varianzes within the server tick! (Supposed: 500ms Hold: 605ms)
> [2018-11-26 22:20:41] [ERROR] 19579 | Found varianzes within the server tick! (Supposed: 500ms Hold: 602ms)
> [2018-11-26 22:20:41] [ERROR] 21699 | Found varianzes within the server tick! (Supposed: 500ms Hold: 606ms)
> [2018-11-26 22:20:41] [ERROR] 21704 | Found varianzes within the server tick! (Supposed: 500ms Hold: 606ms)
> [2018-11-26 22:20:41] [ERROR] 19636 | Found varianzes within the server tick! (Supposed: 500ms Hold: 603ms)
> [2018-11-26 22:20:41] [ERROR] 21640 | Found varianzes within the server tick! (Supposed: 500ms Hold: 605ms)

**Environment information:**
 Operating system: Debian 8 Jessie
 TeaSpeak version: [TeaSpeak-1.2.29-beta-1]
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Are you using the optimized build?
As well I've noticed a slight hangup at the moment the license client failes

**Comment by ts3cloud** [comment]
@WolverinDEV , okay, servers updated. I will check if it will be better

**Comment by ts3cloud** [comment]
The message repeats itself, the server load is still high. (v. TeaSpeak-1.2.30).

**Comment by ts3cloud** [comment]
This time, the server crash. 

Here is dump:

[crash_dump_91da4f07-b188-4435-54d0ccbb-01ae453a.zip](https://github.com/TeaSpeak/TeaSpeak/files/2643089/crash_dump_91da4f07-b188-4435-54d0ccbb-01ae453a.zip)

**Comment by lbenicio** [comment]
This is the same problem my bot is causing... but it happens to me with only 1 client connected. this same message appear on the teaspeak logs and clients disconects with undefined error

**Comment by WolverinDEV** [comment]
Should be in general fixed (1.4.10 stable)
