### ISSUE TITLE
Subscribe bug

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#511]
**Describe the bug**
Create a guest group with subscribe powers of 1 
Create a channel "Test" with needed subscribe powers of 10

No issue, the members in guest group can't see members in "Test"

However if we move members in the guest group into channel "Test" and then back out again, they are still able to see members in "Test".

**To Reproduce**
^^ Described above

**Expected behaviour**

When members are moved out, they should be automatically unsubscribed if they don't have the subscribe powers initially

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 version 1.2.30-beta
Debian

**Additional context**

**Comment by WolverinDEV** [comment]
Fixed within next build (not build 1 but the next, overlooked your issue :D)
