### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by MadD0g25** [TeaSpeak/TeaSpeak#513]
Hey,
My server does not want to launch any more and in the end does not stop crashing.
I am attaching the various logs and a crash dump.

Link:

https://code.empreintesduweb.com/13211.html
https://code.empreintesduweb.com/13212.html

http://hebergeurfichier.com/download/f9e7f4883f76587d675a4b51c50fe3b5.html

Thank you for your answers !

**Comment by WolverinDEV** [comment]
I think I've already helped you within the forum :)

**Comment by MadD0g25** [comment]
Yes indeed you already helped me on the forum and I thank you for it!
