### ISSUE TITLE
Not working Centos 6.10

### ISSUE THREAD

**Issue by jsanahuja** [TeaSpeak/TeaSpeak#514]
**Describe the bug**
Cannot start the server.

**To Reproduce**
Steps to reproduce the behaviour:
Just try running the teastart_minimal.sh in a CentOS release 6.10 (Final)

**Expected behaviour**
The server to work

**Screenshots**
![image](https://user-images.githubusercontent.com/16489902/49311240-e2386b00-f4e0-11e8-9ee6-103d49c28d48.png)

**Logs**
# sh teastart_minimal.sh
teastart_minimal.sh: line 49: packageManagersList: bad array subscript
teastart_minimal.sh: line 49: packageManagersList: bad array subscript
teastart_minimal.sh: line 49: packageManagersList: bad array subscript
./TeaSpeakServer: error while loading shared libraries: libnice.so.10: cannot open shared object file: No such file or directory

**Environment information:**
 Operating system: [root@BanNsS2 tea]# uname -a
Linux BanNsS2 2.6.32-754.6.3.el6.x86_64 #1 SMP Tue Oct 9 17:27:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.30-beta-1]
 I am using `experimental_31`: no

**Additional context**
-

**Comment by Chazotu** [comment]
Have you installes libnice ?

**Comment by BanNsS1** [comment]
Yeah but haven't found a way to install the required version. I successfully got it to work on a  CentOS 7.5.

By the way, is there any TeaMusic guide or something?

**Comment by Chazotu** [comment]
TeaMusic ist already integrated in TeaSpeak.

https://github.com/TeaSpeak/TeaSpeak/blob/master/documentation/Music%20bot%20query%20interface.md
