### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#515]
**Describe the bug**
Server crashed, with less than 5 people on it

**To Reproduce**
Steps to reproduce the behaviour:
1. Start server
2. ??

**Expected behaviour**
Doesn't crash

**Logs**
Dump: https://transfer.sh/15kvyk/crash_dump_3655f033-5f1a-494a-095a2eb0-c49f1daf.dmp

**Environment information:**
 Operating system: Linux beta 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.2.31-beta]
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Hmm okey looks crazy.
Does this just applies since the 31?

**Comment by Sickness-chan** [comment]
I think I ran 30 before and it didn't happen. Switched to another Debian server and updated to 31, and that crash happened within 15 minutes of starting the server.

**Comment by WolverinDEV** [comment]
Hmm well very strange.
Had you tried out the 30 on the same server?

**Comment by Sickness-chan** [comment]
No

**Comment by WolverinDEV** [comment]
Could you please try?
It seems for me to be a random libmalloc crash

**Comment by Sickness-chan** [comment]
Server ran for like 2 days now and seems to have crashed again https://transfer.sh/Yz0R9/crash_dump_669f06dd-369a-4fac-5bb83aa8-6087a391.dmp

Gonna run 1.2.30-beta2 now

**Comment by Sickness-chan** [comment]
Hasn't crashed for 12 days now on 1.2.30-beta2

**Comment by WolverinDEV** [comment]
perfect :)
