### ISSUE TITLE
Server CRASH every 1h or less

### ISSUE THREAD

**Issue by ts3cloud** [TeaSpeak/TeaSpeak#519]
**To Reproduce**
Steps to reproduce the behaviour:
1. Run binary
2. Wait.. for "wind" and crash..

**Environment information:**
 Operating system: Debian 8
 TeaSpeak version: 1.2.32-beta, 1.2.31-*-beta  
 I am using `experimental_31`: yes

**Additional context**
Crash dumps form today.
[dumps24-12.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2707645/dumps24-12.tar.gz)

**Comment by WolverinDEV** [comment]
Uhh seems line the web client  does some crazy shit :)
I'll look at that :)

**Comment by WolverinDEV** [comment]
Well seems like that every crash has the same origin (the WebList client).
Have you tried to disable that and see again?
I'll also look over it again, but for me there is no plausible reason :/

**Comment by ts3cloud** [comment]
Okay, on host weblisting is masked by hosts file:
Host:
`:: ~ » cat /etc/hosts | grep web
127.0.0.1 weblist.teamspeak.com`

But function is enabled: 
`:: ~ » cat /home/tea/server/config.yml | grep allow_weblist:
  allow_weblist: 1`

I have set this option to "0".

How to read the "Crashdump: files  ?

**Comment by WolverinDEV** [comment]
Well then there shall be no crash :dagger: 

You cant really read them :)

**Comment by WolverinDEV** [comment]
It seems like its fixed :)
