### ISSUE TITLE
TeaSpeak not starting.

### ISSUE THREAD

**Issue by Apfelmus1337** [TeaSpeak/TeaSpeak#52]
## System Information
***Operating System***: Ubuntu 16.04
***Operating System Type***: x64
***TeaSpeak Version***: 1.0.29-beta

## Issue
***Reason for reporting this issue***:
TeaSpeak not starting.

***Detailed Description***:
I followed this guide : https://forum.teaspeak.de/index.php?threads/setup-linux-setting-up-teaspeak-from-0.28/ and after i executed the "teastart_minimal.sh" i could connect to the teamspeak server but as soon as i execute "teastart.sh start" the lines delete themselves from the console and nothing happens.

**Comment by WolverinDEV** [comment]
Hey,
i will this issue in a few days :)

**Comment by WolverinDEV** [comment]
Fixed in TeaSpeak-1.1.0-beta-8
