### ISSUE TITLE
Client wants handshake step 2 but we want a cookie request. Resetting client

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#520]
**Describe the bug**

> [2018-12-27 23:17:09] [DEBUG]    17 | Allocated new voice client connection at 0x7f1b0bc3e780
> [2018-12-27 23:17:09] [DEBUG]    17 | Remote address (v4) SERVER_IP destination address SERVER_IP 
> [2018-12-27 23:17:09] [DEBUG]    17 | Having new voice client. Remote address: CLIENT.IP.V4:39380
> [2018-12-27 23:17:09] [DEBUG]    17 | [CLIENT.IP.V4:39380/undefined | 0][HANDSCHAKE] Client wants handshake step 2 but we want a cookie request. Resetting client
> [2018-12-27 23:17:09] [DEBUG]    17 | [CLIENT.IP.V4:39380/undefined | 0][HANDSCHAKE] Client wants handshake step 2 but we want a cookie request. Resetting client
> [2018-12-27 23:17:09] [DEBUG]    17 | [CLIENT.IP.V4:39380/undefined | 0][HANDSCHAKE] Client wants handshake step 2 but we want a cookie request. Resetting client
> [2018-12-27 23:17:09] [DEBUG]    17 | [CLIENT.IP.V4:39380/undefined | 0][HANDSCHAKE] Client wants handshake step 2 but we want a cookie request. Resetting client
> [2018-12-27 23:17:11] [DEBUG]    14 | [Property] Changed property in db key: client_month_online_time value: 128520
> [2018-12-27 23:17:11] [DEBUG]    14 | [Property] Changed property in db key: client_total_online_time value: 128520
> [2018-12-27 23:17:11] [DEBUG]    16 | [Property] Changed property in db key: client_month_online_time value: 3960
> [2018-12-27 23:17:11] [DEBUG]    16 | [Property] Changed property in db key: client_total_online_time value: 3960
> [2018-12-27 23:17:11] [DEBUG]    17 | [CLIENT.IP.V4:39380/undefined | 0][HANDSCHAKE] Client requests a cookie. Restarting handshake from 0
> [2018-12-27 23:17:11] [DEBUG]    17 | Failed handshake for CLIENT.IP.V4 (Invalid server cookie response!)
> [2018-12-27 23:17:11] [DEBUG]    17 | [CLIENT.IP.V4:39380/undefined | 0] Closing voice client connection. (Flush: false)
> [2018-12-27 23:17:11] [INFO]     17 | Voice client 0/ (undefined) from CLIENT.IP.V4:39380 left.

Happens only for a small number of clients, are we able to skip a certain step?

**Environment information:**
 Operating system: 3.16.0-4-amd64 debian
 TeaSpeak version: 1.2.30-beta-2
 I am using `experimental_31`: yes

**Additional context**

**Comment by WolverinDEV** [comment]
Disable coocie enforcement within the config :)

**Comment by slushpuppy** [comment]
>  #The value must be a positive numeric value between 0 and 1
>   notifymute: 1
>   rsa:
>     #Description:
>     #  The amount of precomputed puzzles
>     #Warning:
>     #  Do NOT TOUCH unless you're 100% sure!
>     #The value must be a unsigned long between 1 and 65536
>     puzzle_pool_size: 128
>   handshake:
>     #Description:
>     #  The puzzle level. (A higher number will result a longer calculation time for the manager RSA puzzle)
>     #Warning:
>     #  Do NOT TOUCH unless you're 100% sure!
>     #The value must be a positive numeric value between 512 and 1048576
>     puzzle_level: 1000
>     #Description:
>     #  Enforces the cookie exchange (Low level protection against distributed denial of service attacks (DDOS attacks))
>     #Notes:
>     #  This option is highly recommended!
>     #Warning:
>     #  Do NOT TOUCH unless you're 100% sure!
>     #The value must be a positive numeric value between 0 and 1
>     enforce_cookie: 0

Still no go.

Also updated to

{build_name: "1.2.32-beta"

> [2018-12-29 07:35:19] [DEBUG]    17 | Allocated new voice client connection at 0x7f255aee1600
> [2018-12-29 07:35:19] [DEBUG]    17 | Remote address (v4) SERVER_IP destination address SERVER_IP
> [2018-12-29 07:35:19] [DEBUG]    17 | Having new voice client. Remote address: CLIENT_IP:39110
> [2018-12-29 07:35:19] [DEBUG]    17 | Failed handshake for CLIENT_IP (Invalid server cookie response!)
> [2018-12-29 07:35:19] [DEBUG]    17 | [CLIENT_IP:39110/undefined | 0] Closing voice client connection. (Flush: false)
> [2018-12-29 07:35:19] [INFO]     17 | Voice client 0/ (undefined) from CLIENT_IP:39110 left.
> [2018-12-29 07:35:19] [DEBUG]    17 | Updating server property: virtualserver_last_client_disconnect. New value: 1546086919.$
> [2018-12-29 07:35:20] [DEBUG]    17 | [CLIENT_IP:39110/undefined] Creating VoiceClient instance at 0x7f255ae42a10
> [2018-12-29 07:35:20] [DEBUG]    17 | Allocated new voice client connection at 0x7f255aee1c00
> [2018-12-29 07:35:20] [DEBUG]    17 | Remote address (v4) SERVER_IP destination address SERVER_IP
> [2018-12-29 07:35:20] [DEBUG]    17 | Having new voice client. Remote address: CLIENT_IP:39110
> [2018-12-29 07:35:20] [DEBUG]    17 | [CLIENT_IP:39110/undefined | 0][HANDSCHAKE] Client wants handshake step 2 but we wa$
> [2018-12-29 07:35:21] [DEBUG]    17 | [CLIENT_IP:39110/undefined | 0][HANDSCHAKE] Client wants handshake step 2 but we wa$
> [2018-12-29 07:35:21] [DEBUG]    17 | [CLIENT_IP:39110/undefined | 0][HANDSCHAKE] Client requests a cookie. Restarting ha$
> [2018-12-29 07:35:22] [DEBUG]    17 | [CLIENT_IP:39110/undefined | 0][HANDSCHAKE] Client requests a cookie. Restarting ha$
> [2018-12-29 07:35:22] [DEBUG]    17 | Failed handshake for CLIENT_IP (Invalid server cookie response!)
> [2018-12-29 07:35:22] [DEBUG]    17 | [CLIENT_IP:39110/undefined | 0] Closing voice client connection. (Flush: false)
> [2018-12-29 07:35:22] [INFO]     17 | Voice client 0/ (undefined) from CLIENT_IP:39110 left.

**Comment by WolverinDEV** [comment]
`Well in this case the client is behind, and the server jumps back to the client state.
Actiually this is quite rare and usually its fixed by restarting the client or waiting 20~30 seconds :)

**Comment by slushpuppy** [comment]
sorry could u describe the process? so client connects, dcs but then he or she has to wait for a whole before connecting?

this person is on satellite net

**Comment by WolverinDEV** [comment]
I think the high ping is the main issue.
But update to the 1.3.1 and may there had changed something.

**Comment by WolverinDEV** [comment]
This should
