### ISSUE TITLE
Invalid clientid / teamspeak crash for all clients

### ISSUE THREAD

**Issue by DanielAlves123** [TeaSpeak/TeaSpeak#526]
Often it kicks people for invalid clientId and hangouts whole server and sometimes it crashes teamspeak for all clients.
<16:12:05> "x" dropped (Packet resend failed)
<16:12:05> "x" dropped (Packet resend failed)
<16:12:05> "x" dropped (Packet resend failed)
<16:12:05> "x" dropped (Packet resend failed)
<16:12:05> "x" dropped (Packet resend failed)
<16:12:05> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x<3" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x.xxx]" dropped (Packet resend failed)
<16:12:06> "[X" connected to channel "[spacer6]-.-"
<16:12:06> "[x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "xx" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "[x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "xx" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)
<16:12:06> "x" dropped (Packet resend failed)

**Comment by WolverinDEV** [comment]
Should get better with 1.3.3 :)
