### ISSUE TITLE
[Bug] Channel commander stays when switching channels

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#527]
When someone has the channel commander permission in a channel and enables channel commander and then he switches to channel where he doesn't have channel commander he will keep channelcommander instead of `notifyclientupdated clid=x client_is_channel_commander=0`

**Comment by WolverinDEV** [comment]
Fixed within the next version

**Comment by Bluscream** [comment]
Thanks ♥

**Comment by Bluscream** [comment]
implemented as `clientedit clid=x client_is_channelcommander=1`
