### ISSUE TITLE
No IP-HWID logging 

### ISSUE THREAD

**Issue by Chazotu** [TeaSpeak/TeaSpeak#532]
- [x] Add an Config Option to remove IP logging from the TeaSpeak server instance.
- [x] Add the property virtualserver_log_remoteaddress

- [ ] Add an Config Option to remove HWID logging from the TeaSpeak server instance.
- [ ] Add the property virtualserver_log_hwid

**Comment by WolverinDEV** [comment]
I will not add the HWID.
This just goes directly with the IP logging under one hood :)

Implemented within the next build
