### ISSUE TITLE
Crash. No reason, no logs.

### ISSUE THREAD

**Issue by ts3cloud** [TeaSpeak/TeaSpeak#538]
**Describe the bug**
Crash. No reason, no logs.

Same problem on 2 nodes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run server,

**Environment information:**
 Operating system: Debain 8
 TeaSpeak version: 1.2.34-beta-1 
 I am using `experimental_31`: yes

**Additional context**
crashdumps:
[crash_7-January.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2734289/crash_7-January.tar.gz)

**Comment by WolverinDEV** [comment]
?
