### ISSUE TITLE
Crash, without reason.

### ISSUE THREAD

**Issue by ts3cloud** [TeaSpeak/TeaSpeak#539]
**Describe the bug**
Crash. No reason, no logs.

_Same problem on 2 nodes._

**To Reproduce**
1. Run server

**Environment information:**
Operating system: **Debain 8**
TeaSpeak version: **1.2.34-beta-1**
I am using experimental_31: **yes**

**Additional context**

[crash_7-January.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/2734292/crash_7-January.tar.gz)

**Comment by WolverinDEV** [comment]
Had you created the issue twice?
Had you tried to disable the weblist client (TeamSpeak's weblist?)

**Comment by WolverinDEV** [comment]
Does this crash still occur?

**Comment by ts3cloud** [comment]
Nope. New version work OK.
