### ISSUE TITLE
i_channel_view_power causing flood-ban

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#543]
I thought this was fixed in https://github.com/TeaSpeak/TeaSpeak/issues/148

![image](https://user-images.githubusercontent.com/3318223/50948152-a90cf680-14a1-11e9-8547-1cd380266bda.png)

**Comment by WolverinDEV** [comment]
It has been fixed, idk what your plugins are doing

**Comment by WolverinDEV** [comment]
Its not the same bug. The previous bug was that when a channel had created a flood ban.
In this case the appearing of a channel cause the ban, because you gave the user a group which allowed him to see these channels.

**Comment by WolverinDEV** [comment]
fixed within the next version :)

**Comment by Bluscream** [comment]
Still not completely fixed

```
<16:09:08> "TheRealHearts" was added to server group "Verifiziert" by "[Whisper Bot] Whisper Bot | !sub".
<16:09:09> "TheRealHearts" was moved from channel "[cspacer]◆ＶＥＲＩＦＩＺＩＥＲＵＮＧ◆" to "[cspacer]◆ＥＩＮＧＡＮＧＳＨＡＬＬＥ◆" by "[Whisper Bot] Whisper Bot | !sub" 
<16:09:14> "TheRealHearts" was banned for 10 minutes from the server by "MexoGames.de »  Mex your own GAMES!" (You're flooding too much)
```

**Comment by WolverinDEV** [comment]
How to reproduce?

**Comment by WolverinDEV** [comment]
Still relevant?

**Comment by Bluscream** [comment]
Not using teamspeak anymore, so not for now
