### ISSUE TITLE
Channel id count

### ISSUE THREAD

**Issue by batizisanya** [TeaSpeak/TeaSpeak#546]
**Describe the bug**
If I create a channel (id=2) and I delete it. And create another channel, the second channel also get channel id=2.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a channel
2. See channel id
3. Delete that channel
4. Create another channel
5. See channel id

**Expected behaviour**
Add +1 to the second channel's id, even if the prevous channel is deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/16525148/51078925-d2a26980-16bd-11e9-9bae-7ce94bf7081b.png)

**Environment information:**
 Operating system: 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
 TeaSpeak version: TeaSpeak 1.2.33-beta (2018. 12. 30. 11:42:41)
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
> Add +1 to the second channel's id, even if the prevous channel is deleted.
Why? After the channel got deleted the ID could be reused.
