### ISSUE TITLE
Cant generate new 'Privilege Key'

### ISSUE THREAD

**Issue by ts3cloud** [TeaSpeak/TeaSpeak#548]
## System Information
***Operating System***: Debian 
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.3.0b

## Issue
***Reason for reporting this issue***:

When i try generate new Privilege Key, server kick me with message: 

_<13:26:04> You were kicked from the server by the Server (Invalid argument (could not find key [token]))_

**Comment by WolverinDEV** [comment]
Known bug, will be fixed within the next version, approximated release should be around this weekend
