### ISSUE TITLE
Disconnected from server (server version is too old for command)

### ISSUE THREAD

**Issue by ae2xdnk** [TeaSpeak/TeaSpeak#549]
So you cant log in to the server if your client version is 3.2.3? 

Or did i do something wrong

**Comment by MikkelDK** [comment]
it's not a bug. ;) 

You **can't** connect to the server. **without you have buy a AAL(gamerlicense) from TeamSpeak**
And you need to edit on config.yml and updating protocol_key.txt(TeaSpeak's own version).

You can read on forum howto > [Forum](https://forum.teaspeak.de/index.php?threads/how-to-get-teaspeak-to-show-license-aal-license-from-teamspeak.702)
