### ISSUE TITLE
Move count parameter in clientdblist -count response to front

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#551]
This probably brakes compatibility with some query tools: https://github.com/Newcomer1989/TSN-Ranksystem/issues/563

And also causes a display-bug in YaTQA: 

![image](https://user-images.githubusercontent.com/3318223/51401257-98681a80-1b4a-11e9-80d0-a9fdb7718151.png)

**Comment by WolverinDEV** [comment]
Fixed within 1.3.3 :)

**Comment by Bluscream** [comment]
cool ♥

**Comment by Bluscream** [comment]
Still not fixed in 1.3.4

**Comment by WolverinDEV** [comment]
Its within the first bulk, this should work else the query parser is shit.

**Comment by nummacway** [comment]
Fixed in YaTQA 3.6.0-final.

**Comment by Bluscream** [comment]
> 
> 
> Fixed in YaTQA 3.6.0-final.

"Bypassed" in YaTQA 3.6.0-final.
