### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by tinchocba** [TeaSpeak/TeaSpeak#558]
Hi! I really don't know why this happens. 

**Log**
https://drive.google.com/file/d/12l8tznsWOcttUjiPkUB-C-W4tQqlWBts/view

**Crash dump**
https://drive.google.com/file/d/1dUNgppVNJQCd-E2LBlyNJGbwbTX77TzZ/view

**Server**
Experimental: **Yes**
Version: **1.3.3-beta-1**

Thanks in advance,
Martin.-

**Comment by WolverinDEV** [comment]
fixed :)
