### ISSUE TITLE
Change password of serveradmin

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#560]
**Describe the bug**
Can't update the serveradmin query password using the cmd : passwd in console ( it's not working anymore )

**To Reproduce**
1. go to console ( under minimal teaspeak start )
2. passwd newpass newpass

**Expected behaviour**
It's print correctly : [INFO]    GEN | Server admin successfully changed!
But the password don't change . nothing update in reality.

**Environment information:**
 Operating system: Debian
 TeaSpeak version: v1.3.4-beta [Build: 1548519988]
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Fixed within 1.3.5b

**Comment by lemignon** [comment]
it's not fixed in 1.3.5 .

**Comment by lemignon** [comment]
tested just now . nothing fixed.

**Comment by WolverinDEV** [comment]
Ahh fuck there was something... I've fixed that, and then had problems with MySQL because of that I reverted the changes and accidentally that too.

A quick fix would be to remove the serveradmin from the database within the table queries.
You'll find there two instances (one with server id 0 and the other with NULL)
Delete the NULL one :)

**Comment by lemignon** [comment]
hello , 

i dont use mysql.

**Comment by lemignon** [comment]
so how to do ?

**Comment by lemignon** [comment]
i opened with sqlite browser and in queries i have 2 result : 1 login is serveradmin and another is aNameofOneofMyadmin so i have 2 serveradmin but none with NULL.  and only 1 with login name : serveradmin , the other is another name.

**Comment by lemignon** [comment]
i deleted the second result and only have one left ( serveradmin )  . there is NULL in server . 

I tryed passwd , same no working.

**Comment by WolverinDEV** [comment]
> i opened with sqlite browser and in queries i have 2 result : 1 login is serveradmin and another is aNameofOneofMyadmin so i have 2 serveradmin but none with NULL. and only 1 with login name : serveradmin , the other is another name.

Haha yep you've deleted the "wrong" one :D

And with a clean install this dosnt happen, just with the upgrade of the database (Its actually my fault)

**Comment by WolverinDEV** [comment]
finally fixed in 1.3.6
