### ISSUE TITLE
New crashes

### ISSUE THREAD

**Issue by tinchocba** [TeaSpeak/TeaSpeak#561]
Hi @WolverinDEV how are you? I have new similar and random crashes. Could you please check it again? 

Maybe could be related to #558 

**Log** 
https://transfer.sh/N14NW/log_2019-01-28_05:00:10_general.log

**Crash dump**
https://transfer.sh/iqYgr/crash_dump_dddd3bef-3dfd-4e58-c87503b9-6dde65f0.dmp

**Server**
Experimental: **Yes**
Version: **1.3.4-beta**

Thanks!
Martin.-

**Comment by WolverinDEV** [comment]
fuck its it :(

**Comment by WolverinDEV** [comment]
You're using the debug version right?

**Comment by tinchocba** [comment]
Hum... I'll set config.yml in debug mode.

**Comment by WolverinDEV** [comment]
No i mean if you're using the optimized version or the default one :D

**Comment by tinchocba** [comment]
Sorry, I'm asleep! haha default one
