### ISSUE TITLE
insufficient client permissions (failed on i_permission_modify_power)

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#562]
**Describe the bug**
Unable to modify/add permissions/Unable to use music bot functions

**To Reproduce**
Create a new virtual server. Type .mbot create

<14:55:47> "Music Manager": Failed to create music bot. (Missing permission b_client_music_create_temporary)

Try to modify permission b_client_music_create_temporary
<14:56:16> insufficient client permissions (failed on i_permission_modify_power)

Check i_permission_modify_power(It shows 75)

**Expected behaviour**
Ability to add permission to create music bots

**Screenshots**
![image](https://user-images.githubusercontent.com/1729407/51893914-4ee8bc80-23e1-11e9-9338-ad1c03e2866f.png)

**Logs**
[2019-01-29 03:17:16] [DEBUG]     2 | [Permission] Grant test result for test type 1.
[2019-01-29 03:17:16] [DEBUG]     2 | [Permission]    Permission: b_client_music_create_temporary Required value: 1 Gained value: -2 Force required: 1 Channel: Channel 3 Result: 0

**Environment information:**
 Operating system: ubuntu
 TeaSpeak version: 1.3.4-beta
 I am using `experimental_31`: yes

**Additional context**

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/51896066-ea5f3a80-23ab-11e9-810e-bb381475c09d.png)

You need to give yourself grant power first with Admin Query or Console.

**Comment by slushpuppy** [comment]
How do I do that? serverquery I assume?

**Comment by WolverinDEV** [comment]
Hey,
first of all we recommend to use YatQA because the TS editor is buggy as fuck.

The query has the permission `` which allows him to grant every permission.
The reason why you haven't this permission is simple:
I haven't yet implemented a permission upgrade system.
As soon the first stable release comes it will be implemented :)

**Comment by slushpuppy** [comment]
@WolverinDEV That sounds good, but for this time, it appears that everytime I create a server, i have to jump on yatqa to grant permissions? is there a way to do this automatically?

**Comment by WolverinDEV** [comment]
Well for new servers you could edit the template groups :)
