### ISSUE TITLE
Assigning/removing permission for some settings changes the settings for all groups in the server

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#563]
https://streamable.com/mpm23

Brand new virtual server version 1.3.4-beta

**Comment by slushpuppy** [comment]
This seems to affect settings inside the global/virtual server group

https://i.imgur.com/RDPxiKg.png

**Comment by Bluscream** [comment]
The TeamSpeak permission editor is no longer supported. You are forced to use YaTQA or the Tea(Speak/Web) client if you don't want such bugs.

**Comment by slushpuppy** [comment]
> The TeamSpeak permission editor is no longer supported. You are forced to use YaTQA or the Tea(Speak/Web) client if you don't want such bugs.

When did this change occur?! Is there a guide for setting it on the web client?

**Comment by Chazotu** [comment]
Use YATQA or [TeaWeb/TeaClient](https://web.teaspeak.de)
