### ISSUE TITLE
Music bots still spawning even when they're disabled in config

### ISSUE THREAD

**Issue by Sickness-chan** [TeaSpeak/TeaSpeak#565]
**Describe the bug**
The music bots are still being spawned in servers, even if they're disabled in `config.yml` like this
```
music:
  #Description:
  #  Enable/disable the music bots
  #The value must be a positive numeric value between 0 and 1
  enabled: 0
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Have music bots enabled and add one to a server?
2. Disable music bots on config
3. Bot will still spawn in that server after restarts etc
***This is untested, I'm not sure how it happened, but this is my guess.***

**Expected behaviour**
The bots don't spawn anymore.

**Environment information:**
 Operating system: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
 TeaSpeak version: TeaSpeak-1.3.3-beta
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
fixed in 1.3.6
