### ISSUE TITLE
Failed to parse ip entry

### ISSUE THREAD

**Issue by tinchocba** [TeaSpeak/TeaSpeak#567]
**Describe the bug**
"[ERROR] GEN | Failed to parse ip entry at line 5 of file query_ip_whitelist.txt. Line: '79.218.0.0/16'"

The server can't start properly.

**Server**
Experimental: **Yes**
Version: **1.3.6b**

Thanks!

**Comment by Bluscream** [comment]
That file does not support ip ranges (CIDR) use normal IPs instead

**Comment by tinchocba** [comment]
> That file does not support ip ranges (CIDR) use normal IPs instead

Thanks for your answer. Wolverin told me to create this issue :)

**Comment by WolverinDEV** [comment]
Implemented in 1.3.10
