### ISSUE TITLE
SinusBot Bug

### ISSUE THREAD

**Issue by MehdiSele** [TeaSpeak/TeaSpeak#569]
hi SinusBot Bugs:
1. SinusBot Will  dropped (Packet resend failed) after some hours
2. SinusBot when you disconnect music bot from panel , didnt say in chat: leaving (Requested API)
it says: dropped (Packet resend failed)
![image](https://user-images.githubusercontent.com/43189584/52343517-8a146c80-2a2d-11e9-95d3-b6ca1d0e5d2d.png)
3. channel commander didnt work but on sinusbot is enabled. and its not permession problems
you can see on screenshot i uploaded some bots have channel commander some havent

**Comment by Bluscream** [comment]
You should modify your banner to allow unicode in names xd

**Comment by MehdiSele** [comment]
how can i do this? :D
I sent you pm in teaspeak forum

**Comment by Bluscream** [comment]
Depends on which banner youre using

**Comment by WolverinDEV** [comment]
Well I haven't yet reproduced the described issues. I'm ru Ning my bot for over 2days without any problems :/

**Comment by WolverinDEV** [comment]
fixed :)
