### ISSUE TITLE
Serverprotokoll implementieren (logview)

### ISSUE THREAD

**Issue by essemX** [TeaSpeak/TeaSpeak#57]
TeaSpeak version:
1.0.29-beta

Das Serverprotokoll als ein wichtiges Tool für die überwachung von Usern eines Teamspeak Servers wurde noch nicht implementiert. 
Hier eine kleine erinnerungsbox:

- [x] Server Protokoll implementieren

Zitat: _"nicht implementiert"_

Btw @WolverinDEV :
Hab den Server grad erst Installiert (musste die sqlite datenbank editieren um den port einzustellen was nicht umbedingt optimal ist, könnte man eventuell mit startparametern oder config regeln) und sollte ich mich entscheiden diese Serversoftware zu verwenden dann werd ich hier warscheinlich genauso aktiv sein wie bei BungeeUtil ^^

**Comment by WolverinDEV** [comment]
Hey exxemX mein alter Freund :D
Kannst du mir vil. erklären was du mit "Server Protokoll" meinst?

Du kannst Query & File-Transfare port in der `config.yml` einstellen.
Der default server startup port lautet 9987 (welchen du aber mit jedem belibigen query tool bearbeiten kannst ;)

**Comment by essemX** [comment]
ich mein das Server Protokoll im Client unter Extras -> Server Protokoll 
wenn ich es versuche zu öffnen kommt einfach nur Error und die zitierte Nachricht.
Und das mit dem query tool ist garnicht so einfach wenn der server nicht richtig startet weil der standard port belegt ist ^^ das mit query und file-transfer in der config hab ich gesehen, wäre nett wenn man da noch den standardport hinzufügen könnte

**Comment by WolverinDEV** [comment]
Sollte eig. einfach sein?
Query startet ganz normal auf port 10101.
Ob ein Server failed to start ausgiebt hat für das ganze system keinerlei bedeutung :D

Und jetzt weiß ich was du meinst du meinst die logview funktion :D

**Comment by xRedFox** [comment]
UP for logview

**Comment by WolverinDEV** [comment]
Implemented
