### ISSUE TITLE
Mute bug

### ISSUE THREAD

**Issue by rafalohaki** [TeaSpeak/TeaSpeak#571]
when user muting another user u get notify that user has unmuted u instead muted and when u get unmuted u dont get notify

**Comment by WolverinDEV** [comment]
Well I cant confirm that bug.
Had you may changed the unmute message within the config to nothing?

**Comment by rafalohaki** [comment]
https://i.imgur.com/LHMfXOg.png have a string like i had to but i only got notify of unmuting when someone muted me thats only one notify which i get from all possibilities

**Comment by WolverinDEV** [comment]
Hmm thats suspicious.
Which version are you using?

**Comment by rafalohaki** [comment]
1.3.6b for now but its from 1.3.3b or 1.3.2b iu think but im not sure

**Comment by rafalohaki** [comment]
if i am only one who has a problem u can drop this issue but i got this from updating some version and im not sure which.

**Comment by WolverinDEV** [comment]
So in the newer versions this dosnt occur anymore?

**Comment by Pdani001** [comment]
I can confirm this on 1.3.10b, but this was an issue in older versions too.

**Comment by WolverinDEV** [comment]
Hmm @Pdani001 you had the same bug as well?
I've never been able to reproduce :/

**Comment by WolverinDEV** [comment]
fixed in 1.4.0 :)
Mute and unmute message were the same
