### ISSUE TITLE
can't run TeaSpeak Server

### ISSUE THREAD

**Issue by superba02** [TeaSpeak/TeaSpeak#573]
Can't run with Cygwin64 on windows.
Please help.

$ /home/Administrator/01/teastart_minimal.sh

Your package manager is not supported!
Please report this problem to
https://github.com/TeaSpeak/TeaSpeak/issues

      2 [main] bash 22044 C:\cygwin64\bin\bash.exe: *** fatal error in forked process - error while loading shared libraries: ./libs/libjemalloc.so.2: cannot open shared object file: Exec format error
/home/Administrator/01/teastart_minimal.sh: line 65: 22044 Hangup                  ./TeaSpeakServer $@

      1 [main] bash 34344 C:\cygwin64\bin\bash.exe: *** fatal error in forked process - error while loading shared libraries: ./libs/libjemalloc.so.2: cannot open shared object file: Exec format error
/home/Administrator/01/teastart_minimal.sh: line 67: 34344 Hangup                  stty cooked echo

**Comment by WolverinDEV** [comment]
Hmm well never tried it with Cygwin, but it seems like it it cant handle the one dependency for unknown reason. May use the win subsystem for linux instead :)

**Comment by superba02** [comment]
> Hmm well never tried it with Cygwin, but it seems like it it cant handle the one dependency for unknown reason. May use the win subsystem for linux instead :)

Thank You. <3
