### ISSUE TITLE
Users cannot Speak

### ISSUE THREAD

**Issue by Schuermi7** [TeaSpeak/TeaSpeak#575]
Users are unable to speak after seemingly random timespan.
It appears spontaneously. Users are seeing the light blue dot flashing, while speaking, but the others do not and can't see the light blue dot.

**To Reproduce**
There is no definitive way of reproducing

**Expected behaviour**
Users can speak, when they want, what they want.

**Logs**
no error messages found, reviewing the logs.

**Environment information:**
 Operating system: Debian 9 Linux amd64 
 TeaSpeak version: TeaSpeak-1.3.8 beta
 I am using `experimental_31`: yes

**Comment by wasyady** [comment]
`[2019-02-24 19:50:16] [DEBUG]     2 | [176.63.25.xxx:10209/The Victator | 7] Cant decrypt packet of type Voice. Packet ID: 866, Estimated generation: 0. Dropping packet. Error: memory verify failed!

You need disable Channel voice data encrytion. Globally and channel too.


`

**Comment by Sickness-chan** [comment]
I've gotten reports about a problem that matches this description on 1.3.9-beta-1.

**Comment by Schuermi7** [comment]
We could determine, that it has to do with the encryption on the server.
What caught my eye was, that after i selected the server to deactivate the encryption globally, it occured further. I had to activate encryption channelwise and deactivate it on every channel one after another.
This may be a bug in the serversoftware, not properly setting the flag, because if I turn encryption on serverwide, every channel gets the checkbox that enables encryption. If I turn it off, it leaves the checkbox checked and greys it out whilst producing the error again

**Comment by Sickness-chan** [comment]
I was afraid that bug might exist, so I disabled it for the channel first, and then set encryption to be off globally. Thanks for the information, I've now set it to individually per channel and disabled encryption per channel.

**Comment by jonipin** [comment]
Can confirm This is the solution!  Disabling the Encryption helped for now. But this needs to be adressed!

**Comment by WolverinDEV** [comment]
Hmm well thats strange.
I'll may improve the debug output posted bellow a littlebit more.
```
[2019-02-24 19:50:16] [DEBUG] 2 | [176.63.25.xxx:10209/The Victator | 7] Cant decrypt packet of type Voice. Packet ID: 866, Estimated generation: 0. Dropping packet. Error: memory verify failed!
```

**Comment by Crosus97** [comment]
In #556 there is a temporal """""solution""""" 

In conclusion is to do downgrade  to  1.2.33 beta 2-3

**Comment by chronicals** [comment]
A downgrade never is a decent solution. It is one, but a very dirty one. We need a fix for this.

**Comment by Sickness-chan** [comment]
@WolverinDEV is this getting looked into?

**Comment by WolverinDEV** [comment]
> @WolverinDEV is this getting looked into?

Actually I've no clue whats going on there.
I've never experience such an issue at all, as well have no idea where this comes from, because it seems like command packets are still correctly encrypted, which cant be possible if the crypt key or method would be wrong.

**Comment by chronicals** [comment]
@WolverinDEV When disabling encryption for a channel it imediately works again. Using CentOS 7 as a host, if that helps. No error logs at all.

**Comment by WolverinDEV** [comment]
@chronicals Yeahr ofc its an encryption problem...
Does this error occur on opus codec based channels or on non opus based channels?

**Comment by Schuermi7** [comment]
For me I am only having issues reported for Opus set channels.

**Comment by chronicals** [comment]
I didn't notice a difference, but I'll recheck this weekend. Maybe I'll find out if there's a difference between opus and non opus codec channels.

**Comment by WolverinDEV** [comment]
Hey,
I need the logmessage again which @wasyady posted above.
It has slightly changed may may gives a little clue, does anybody has that for me?

**Comment by WolverinDEV** [comment]
fixed in 1.3.17 :)
Thanks for all of your support!

**Comment by chronicals** [comment]
On version v1.3.17-beta [Build: 1555681353] we still ran into the error. It took 2 hours for the problem to occur, first the person I talked with couldn't hear me and rejoined. 

A minute later the same occurred to me, I could hear everything from the channel but nobody could hear me. A quick reconnect _temporarily_ fixed it for me.

The only unusual message in the server log around that time was:
`[WARNING]   GEN | Timer InstanceHandler::tickInstance -> statistics tick needs more than 8509 microseconds. Max allowed was 5000 microseconds.`

**Comment by WolverinDEV** [comment]
Hmm thats strange.
Please enable debug mode and watch out for decrypt failures :)
As well how frequently does this occur?
As well dos the clients have a "high" packet loss, or packet loss in general?
