### ISSUE TITLE
Packet resend failed

### ISSUE THREAD

**Issue by Shelouw** [TeaSpeak/TeaSpeak#577]
people get kicked for "Packet resend failed"

<17:06:27> "no soy maravilla" dropped (Packet resend failed)
<17:06:27> "!                  AleksandrFP" dropped (Packet resend failed)
<17:06:27> "[Coronel Fuzzo] [L.FNC] Coronel de los Fanatic" dropped (Packet resend failed)
<17:06:28> "PauLBP" dropped (Packet resend failed)
<17:06:28> "[Tazøneta] Tazøneta" dropped (Packet resend failed)
<17:06:28> "________T_______" dropped (Packet resend failed)
<17:06:28> "!  sʀɴᴀᴢᴀ ϟ" dropped (Packet resend failed)
<17:06:28> "xd123" dropped (Packet resend failed)
<17:06:28> "MrDental" dropped (connection timeout)
<17:06:28> "L.HM MCKing" dropped (Packet resend failed)
<17:06:28> "Hystericc" dropped (Packet resend failed)
<17:06:28> "x_Jiren_x" dropped (Packet resend failed)
<17:06:28> "loonsed" dropped (Packet resend failed)
<17:06:28> "lTepho_" dropped (Packet resend failed)
<17:06:28> "[daniel] ♥   Fanáti   ♥ daniel" dropped (Packet resend failed)
<17:06:28> "[!                 SimplyStrafe] !         _Jxrdxn/$ιмρℓу$тяαfє" dropped (Packet resend failed)
<17:06:28> "YOMISMO" dropped (Packet resend failed)
<17:06:28> "DROPPING" dropped (Packet resend failed)
<17:06:28> "DrugFree" dropped (Packet resend failed)
<17:06:28> "Maximus332" dropped (Packet resend failed)
<17:06:28> "!                       zVloom" dropped (Packet resend failed)
<17:06:28> "Nielsan" dropped (Packet resend failed)
<17:06:28> Channel "adsajioaoo" was deleted by "Minecub.es"
<17:06:28> "FCFacu" dropped (Packet resend failed)
<17:06:28> "Lobezno" dropped (Packet resend failed)
<17:06:28> "bsc_" dropped (Packet resend failed)
<17:06:28> "_Kno" dropped (Packet resend failed)
<17:06:28> "L.NBD Aquapup11" dropped (Packet resend failed)
<17:06:28> "♥ EduardoGamer200 ♥" dropped (Packet resend failed)
<17:06:28> "Laniick/titi" dropped (Packet resend failed)
<17:06:28> "iRaid3rPvP" dropped (Packet resend failed)
<17:06:29> "Krozover" dropped (Packet resend failed)
<17:06:29> "Azxrd" dropped (Packet resend failed)
<17:06:29> "!              Angel" dropped (Packet resend failed)
<17:06:29> "iAutoCliker" dropped (Packet resend failed)
<17:06:29> "ｅｃｋｏ_４７" dropped (Packet resend failed)
<17:06:29> "[!Forzzamar:3] !Forzzamar:3" dropped (Packet resend failed)
<17:06:29> "Gotto" dropped (Packet resend failed)
<17:06:29> "[L.RC]xlCarlos" dropped (Packet resend failed)
<17:06:29> "[FNC]KING_REXX" dropped (Packet resend failed)
<17:06:29> "Gise♥" dropped (Packet resend failed)
<17:06:29> "daviid452" dropped (Packet resend failed)
<17:06:29> "Xx4xelxX" dropped (Packet resend failed)
<17:06:29> "[Shawty_22] Supreme" dropped (Packet resend failed)
<17:06:29> "C A Z Z U" dropped (Packet resend failed)
<17:06:29> "GrifferHD" dropped (Packet resend failed)
<17:06:29> "Anne" dropped (Packet resend failed)
<17:06:29> "santu" dropped (Packet resend failed)
<17:06:29> "[ACZ1N0] Kxvinn" dropped (Packet resend failed)
<17:06:29> "[MasedaMZ] MasedaMZ" dropped (Packet resend failed)
<17:06:29> "MrEdUu333" dropped (Packet resend failed)
<17:06:29> "!Lxs_" dropped (Packet resend failed)
<17:06:29> "jhonny1999" dropped (Packet resend failed)
<17:06:29> "Seba" dropped (Packet resend failed)
<17:06:29> "TeamSpearkUzter" dropped (Packet resend failed)
<17:06:29> "BEBE" dropped (Packet resend failed)
<17:06:29> "Elite2KYT | 㴀大夫☣" dropped (Packet resend failed)
<17:06:29> "ChileanDrops L.KI" dropped (Packet resend failed)
<17:06:29> "!                 MᴀᴛɪCʜᴇᴀᴛᴇᴇʀ" dropped (Packet resend failed)
<17:06:29> "_iGuiseppe_" dropped (Packet resend failed)
<17:06:29> "DerpHimox" dropped (Packet resend failed)
<17:06:29> "Thunder/titi/poke" dropped (Packet resend failed)
<17:06:29> "MMVXIII_" dropped (Packet resend failed)
<17:06:29> "Reboting#titi" dropped (Packet resend failed)
<17:06:29> "l2014l" dropped (Packet resend failed)
<17:06:29> "[Henry] Henry" dropped (Packet resend failed)
<17:06:29> "[MarioJaja] Mariojaja" dropped (Packet resend failed)
<17:06:29> "[MARCOSGAMER29] uSxcks" dropped (Packet resend failed)
<17:06:29> "zlFalleN" dropped (Packet resend failed)
<17:06:29> "!                     Lxis98__" dropped (Packet resend failed)
<17:06:29> "Lucas †" dropped (Packet resend failed)
<17:06:29> "[Guhan_] SLegend" dropped (Packet resend failed)
<17:06:29> "Yandel." dropped (Packet resend failed)
<17:06:29> "]ZOXRINOMASTER" dropped (Packet resend failed)
<17:06:29> "!                     
迭戈" dropped (Packet resend failed)
<17:06:29> "lStreak" dropped (Packet resend failed)
<17:06:29> "Kaysooo." dropped (Packet resend failed)
<17:06:29> "!            Vk__" dropped (Packet resend failed)
<17:06:29> "Matute." dropped (Packet resend failed)
<17:06:29> "492728" dropped (Packet resend failed)
<17:06:29> "lSayko" dropped (Packet resend failed)
<17:06:29> "Autism0-" dropped (Packet resend failed)
<17:06:29> "6ix9Tekashi NBD" dropped (Packet resend failed)
<17:06:29> "LeRev_" dropped (Packet resend failed)
<17:06:29> "╬SebaPox╬" dropped (Packet resend failed)
<17:06:29> "espectro_x" dropped (Packet resend failed)
<17:06:29> "[L.Hys]Hystericc." dropped (Packet resend failed)
<17:06:29> "xlStrqffe" dropped (Packet resend failed)
<17:06:29> "Mark Evans" dropped (Packet resend failed)
<17:06:29> "Perseve" dropped (Packet resend failed)
<17:06:29> "Darkyeon" dropped (Packet resend failed)
<17:06:29> "SW4TTING_" dropped (Packet resend failed)
<17:06:29> "EREMYXD233" dropped (Packet resend failed)
<17:06:29> "Kevstaaah_" dropped (Packet resend failed)
<17:06:29> "ImDeltaa" dropped (Packet resend failed)
<17:06:29> "!      ♥SαмυєƖ" dropped (Packet resend failed)
<17:06:29> "barrio" dropped (Packet resend failed)
<17:06:29> "ugcmerc" dropped (Packet resend failed)
<17:06:29> "KanGasKann" dropped (Packet resend failed)
<17:06:30> "CesarEspiritu369" dropped (Packet resend failed)
<17:06:30> "Neekogames" dropped (Packet resend failed)
<17:06:30> "7Bl0cks" dropped (Packet resend failed)
<17:06:30> "Gonzalo998" dropped (Packet resend failed)
<17:06:30> "Alvaroo99" dropped (Packet resend failed)
<17:06:30> "counter" dropped (Packet resend failed)
<17:06:30> "lαтeɴcyαrɢeɴтιɴe | @αƖєxαкɗмια" dropped (Packet resend failed)
<17:06:30> "W0SIT0" dropped (Packet resend failed)
<17:06:30> "Alexpeach" dropped (Packet resend failed)
<17:06:30> "нα¢єℓσqυєqυιєяαѕ" dropped (Packet resend failed)
<17:06:30> "flexxxxxxx" dropped (Packet resend failed)
<17:06:30> "Rusgato #RC" dropped (Packet resend failed)
<17:06:30> "LQRSquad" dropped (Packet resend failed)
<17:06:30> "FeRnaPrO28" dropped (Packet resend failed)
<17:06:30> "nicolas3456" dropped (Packet resend failed)
<17:06:30> "1townarg" dropped (Packet resend failed)
<17:06:30> "180000000000" dropped (Packet resend failed)
<17:06:30> "TreffWinnier_" dropped (Packet resend failed)
<17:06:30> "Train132" dropped (Packet resend failed)
<17:06:30> "♥♥♥" dropped (Packet resend failed)
<17:06:30> "Magoo" dropped (Packet resend failed)
<17:06:30> "Maicol." dropped (Packet resend failed)
<17:06:30> "sadasdasd" dropped (Packet resend failed)
<17:06:30> "Fenixx_Elite" dropped (Packet resend failed)
<17:06:30> "iTzDiorite" dropped (Packet resend failed)
<17:06:30> "zElemenTal_" dropped (Packet resend failed)
<17:06:30> "TeamSpeakUser" dropped (Packet resend failed)
<17:06:30> "[uKhaz_] uKhaz" dropped (Packet resend failed)
<17:06:30> "Combo" dropped (Packet resend failed)
<17:06:30> "!                       KOKI10" dropped (Packet resend failed)
<17:06:30> "VampeClient_" dropped (Packet resend failed)
<17:06:30> "twitch.tv/bestchile.07♿" dropped (Packet resend failed)
<17:06:30> "Rupe" dropped (Packet resend failed)
<17:06:30> "Pøℓ∂σѕку_" dropped (Packet resend failed)
<17:06:30> "Derian" dropped (Packet resend failed)
<17:06:30> "!    infinitumm" dropped (Packet resend failed)
<17:06:30> "[Charmander_PvP] xPairus_" dropped (Packet resend failed)
<17:06:30> "OsoBlacked_" dropped (Packet resend failed)
<17:06:30> "iKx_" dropped (Packet resend failed)
<17:06:30> Channel "xx" was deleted by "Minecub.es"
<17:06:30> "luquitas" dropped (Packet resend failed)
<17:06:30> "NoDat~" dropped (Packet resend failed)
<17:06:30> "_мαѕαςяє_" dropped (Packet resend failed)
<17:06:30> "OSCAR" dropped (Packet resend failed)
<17:06:30> "!ƬнεΜλϰιιƤvƤ" dropped (Packet resend failed)
<17:06:30> "HASKS_" dropped (Packet resend failed)
<17:06:30> "Alejandro" dropped (Packet resend failed)
<17:06:30> "TailsDolls" dropped (Packet resend failed)
<17:06:30> "vlMexicanDrops" dropped (Packet resend failed)

**Comment by REDOSS** [comment]
Attach the server logs and describe what version of the server you are using.

**Comment by REDOSS** [comment]
@WolverinDEV , I think this problem is no longer relevant.

**Comment by WolverinDEV** [comment]
Well yes this is the thing with the invalid channel order etc.
Ultra rare, should be improved, but first a stable version will come out, not that I'm making the server unstable again.
