### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by RealRunSpace** [TeaSpeak/TeaSpeak#578]
**Describe the bug**
The server doesn't start in 1.3.10b

**To Reproduce**
Steps to reproduce the behaviour:
1. Start it

**Expected behaviour**
The server just boots up

**Screenshots**
-

**Logs**
Not needed, as they cannot be generated

**Environment information:**
 Operating system: CentOS7 
 TeaSpeak version: 1.3.10b
 I am using `experimental_31`: yes

**Additional context**
The server won't start and gives this error: ./TeaSpeakServer: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory
1.3.9b works fine

**Comment by WolverinDEV** [comment]
Its already known, official release rolled back to 1.3.9 :)

**Comment by REDOSS** [comment]
@WolverinDEV I understand that this problem is reproduced only in the normal assembly, that is, not in the optimized one?
I use 1.3.10 optimized and I have not seen this problem.

**Comment by RealRunSpace** [comment]
sure @WolverinDEV ! I thought it was a bug because in the tea website shows 1.3.9 so I've decided to download 1.3.10b and test it out, luckily I always perform a backup of all files before updating, thanks for your work as always!

**Comment by WolverinDEV** [comment]
fixed in 1.3.10-2 or 1.3.11 :)
