### ISSUE TITLE
I cant start teaspeak client

### ISSUE THREAD

**Issue by Aventix** [TeaSpeak/TeaSpeak#581]
After i installed teaspeak successfully, the critical error message: teamspeak failed to load script <code> js/profiles/identities/NameIdentity.js </code>

**Comment by MikkelDK** [comment]
@WolverinDEV - Can you move this "issue" to [TeaWeb](https://github.com/TeaSpeak/TeaWeb)

**This is for TeaSpeak Server Issue, and TeaSpeak Client is build via web(files - aka TeaWeb)**
