### ISSUE TITLE
Same username serverquery login

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#585]
**Describe the bug**
Having the same username allows you to gain unauthorized access on other teaspeak virtual instance

**To Reproduce**
Steps to reproduce the behaviour:
1. Create 2 virtual servers, 1 then 2
2. Create a serverquery login called "test" on virtual server 1
3. Create a serverquery login called "test" on virtual server 2
4. Logging into YATQA allowed you to modify virtual server 1 using the login from virtual server 2

**Expected behaviour**

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: (`uname -a`)
 TeaSpeak version: 1.3.11-beta-2.
 I am using `experimental_31`: (yes/no)

**Additional context**

**Comment by WolverinDEV** [comment]
Are you may using the same identity?
Each server query is bound to one identity and their permissions.
If you have permissions on server A and B the you could ofc modify both servers :)

**Comment by slushpuppy** [comment]
Ah ok. Thanks for clearing it up. I'll use a unique username for each server
