### ISSUE TITLE
TeaSpeak Issue 20190329

### ISSUE THREAD

**Issue by bernardopribeiro** [TeaSpeak/TeaSpeak#586]
## System Information
***Operating System***:
Ubuntu 18.04
***Operating System Type*** (x86|x64): 
64
***TeaSpeak Version***:
Last
## Issue
***Reason for reporting this issue***:

https://i.imgur.com/undefined.png
![v5lbDDl](https://user-images.githubusercontent.com/13475010/55224616-cfbd0c80-5208-11e9-86fc-479e42bb65cf.png)

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
There is a config issue there, within the config.yml.
Fix will be out soon.

**Comment by WolverinDEV** [comment]
Fixed in 1.3.13-beta2
