### ISSUE TITLE
Empty for on Yatqa

### ISSUE THREAD

**Issue by otalportista** [TeaSpeak/TeaSpeak#587]
Hey,

I have a suggestion to you, you can add in server when room empty with the time, check print.
http://prnt.sc/n64epp

**Comment by Crosus97** [comment]
some bots use the Empy for to Delete channel in x Days, this will a good implement

**Comment by WolverinDEV** [comment]
Fixed within the next version :)

**Comment by otalportista** [comment]
Okay im waiting 👌

**Comment by Crosus97** [comment]
im still having this bug in the yatqa any help?

**Comment by Crosus97** [comment]
https://gyazo.com/1d51c34f8acdb35b61f515ce08b1052d
