### ISSUE TITLE
Max Virtual Servers Creating Variable

### ISSUE THREAD

**Issue by speedmaxro** [TeaSpeak/TeaSpeak#588]
Request Max Server in Config.yml

For hosters its a good ideea to implement max virtual servers created on a teaspeak server.

For example, we make a teaspeak server on a VPS and we give this server access full query as a reseller package to a people and he can create servers.
Now is unlimited and i request to implement a variable in config.yml with name "max-vservers: 0" or other, name its irrelevant.
Is neccesary to be in config.yml to avoid replace it if is in query access.

After this feature we can implement reseller packages as hosters with reseller plans with plans with max servers per plan.

I think is a very good ideea

Thnak You TeaTeam !

**Comment by WolverinDEV** [comment]
implemented within the next version :)
