### ISSUE TITLE
Implementing the "Average packet loss" counter in server connection info

### ISSUE THREAD

**Issue by REDOSS** [TeaSpeak/TeaSpeak#591]
**Describe the solution you'd like**
It would be nice to keep track of the average number of lost packets on a virtual server.

**Additional context**
![WzMPRto](https://user-images.githubusercontent.com/9403349/56038637-177c8180-5d3b-11e9-87e9-9a4e01d1d18d.png)

**Comment by WolverinDEV** [comment]
Implemented
May add an option for taking the client stats in account as well, but thats currently disabled because clients could easily manipulate their stats.
