### ISSUE TITLE
Сan add / remove members ignoring their permissions

### ISSUE THREAD

**Issue by REDOSS** [TeaSpeak/TeaSpeak#592]
**Describe the bug:**
After you migrate a snapshot from the TeamSpeak to TeaSpeak, can add/remove any member of the group, ignoring its maximum permissions, but with the condition that you have rights to add/remove members of in these groups.

**Steps to reproduce the behaviour:**
1. Use this server snapshot - [test.txt](https://github.com/TeaSpeak/TeaSpeak/files/3092290/test.txt)
2. After restoring the server snapshot in the "Moder" group, we get the following permissions - https://i.imgur.com/YK5NuWK.png and with these permissions we can add / remove absolutely any member in the groups "Test1", "Test2", "Test3". Even if this user has "Server Admin" or "Admin Server Query".
- or
1. You can reproduce this issue on a new TeaSpeak virtual server.
2. If set these privileges on a server group that can grant some rights, there is no problem - https://i.imgur.com/fdf2sxT.png
3. But if also assign these privileges, can immediately be able to add/remove members, ignoring their privileges - https://i.imgur.com/zaWwuvn.png
4. If remove the privileges assigned in step 3, will still be able to add/remove members to groups, although could not do so in step 2 with the same privileges.

**Expected behaviour:**
Should get the error "insufficient client permissions (failed i_client_needed_permission_modify_power)

**Comment by WolverinDEV** [comment]
`i_client_needed_permission_modify_power` has no relevance related to member add/remove actions.
Add your test groups (`Test 1`, `Test 2`, `Test 3`) have a required member add/remove power (`i_server_group_needed_member_add_power`) of 60.  

Your `Moder` groups has a member add power of 60 (`i_server_group_member_add_power`) which ofc is enough to add the groups to other people :)

**Comment by WolverinDEV** [comment]
fixed btw
