### ISSUE TITLE
"Mute" "The channel name was changed" of Specific users

### ISSUE THREAD

**Issue by Crosus97** [TeaSpeak/TeaSpeak#593]
**Is your feature request related to a problem? Please describe.**
A lot of Admins use a Bots like Sinusbot or others. I have a Sinusbot plugin that is digital clock
This plugin "disable" the General chat because the chat its "flooded" of this
![a74e922853c73ef056b173a4ebc3c035](https://user-images.githubusercontent.com/46854222/57076979-22e41c80-6ceb-11e9-8ce2-c6303939d088.png)

**Describe the solution you'd like**
There is a anyway to "mute" this messages of a Specific users (Bots Permission) in the server?

**Comment by WolverinDEV** [comment]
Hey,
I'm sorry for the delay.

In general these messages are not suppressible because they're generated by the client.
