### ISSUE TITLE
Verbindung via Webinterfaces crashen Teaspeak Server

### ISSUE THREAD

**Issue by Sephiara** [TeaSpeak/TeaSpeak#594]
**Describe the bug**
Webinterfaceaufruf nach Rücksetzung auf Version 1.3.19 am 29.05.2019 bringt TeaspeakServer zum crashen /// 2 verschiedene Webinterfaces (first-coder und das angepasste Psychokiller) haben den selben Effekt. Verbindung via Yatqa funktioniert komischerweise ohne Probleme.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://forum.teaspeak.de/index.php?threads/psychokillers-webinterface-modiffied-a-little-bit-for-teaspeak.1955/'
2. Click on 'install at your server'
3. Setting to apply 'start teaspeak server'
4. See error 'if you try to connect the webinterface, TeaspeakServer crashed'

**Expected behaviour**
-

**Screenshots**
no screens avaiable, pid killed after try to start webinterfaces

**Logs**
crash reports dont be written in the logs

**Environment information:**
 Operating system: Debian 4.9.168-1+deb9u2
 TeaSpeak version: [TeaSpeak-1.3.19-beta-]
 I am using `experimental_31`: (yes)

**Additional context**
Ich vermute, bei mir liegt es daran, der updater hat auf 1.3.19 zurückgesetzt, jedoch kein Backup von dieser Version gehabt. Irgendwas passt da nicht zusammen.

**Comment by Sephiara** [comment]
Mit Version 1.3.17 stable funktionieren die Webinterface's wieder ohne Störung.
Muss irgendwo ein Fehlercode drin sein, der beim Aufruf den TeaSpeak Server zum crashen bringt (Schleifenfehler, oder was auch immer)

**Comment by WolverinDEV** [comment]
Hey hast du mal 1.3.19-beta6 getestet?

**Comment by WolverinDEV** [comment]
Und ja habe einiges mal wieder geändert, aber desshalb gibts ja endlich stable releases xD

**Comment by Sephiara** [comment]
ok, deshalb bleibt die stable nun erstmal :)
Mag da nicht mehr weiter rum probieren. War schon schwer, heraus zu finden, woran es denn überhaupt lag. Stable 1.3.17 bleibt erstmal :)

**Comment by WolverinDEV** [comment]
Nunja wenn du jz erstmal da bleibst weiß ich nicht ob dein bug gefixt wurde :/
Kannst du vil trotzdem mal die 1.3.19-beta7 probieren?

BTW: Wenn der TS crashed sollte es einen crash_dump geben. Kannst du den bitte hochladen sofern der crash noch relevant ist?

**Comment by DWKevinos** [comment]
Same on 1.3.19-beta7, crash dump file 
[crash_dump_e7beb58f-c407-42d2-8fef0ab2-486a3db2.zip](https://github.com/TeaSpeak/TeaSpeak/files/3240914/crash_dump_e7beb58f-c407-42d2-8fef0ab2-486a3db2.zip)

**Comment by WolverinDEV** [comment]
Fixed in 1.3.19-beta8 :)
