### ISSUE TITLE
disconnected v.1.3.18b

### ISSUE THREAD

**Issue by rafalohaki** [TeaSpeak/TeaSpeak#595]
after beta update to 3.3.0 i got error to my server. 
<21:58:12> Connected to Server: "No server"
<21:58:12> convert error
<21:58:12> Disconnected from server (invalid parameter)

**Comment by DWKevinos** [comment]
Hello the bug are fixed soon. Please wait a update ;)

**Comment by MikkelDK** [comment]
It's already reported on forums! ;)

https://forum.teaspeak.de/index.php?threads/teamspeak-3-3-0-does-not-connect-to-teaspeak-server.2013/#post-13827 ^

**Comment by WolverinDEV** [comment]
Hey this has been fixed in 1.3.19-beta7
