### ISSUE TITLE
musicbotqueueadd

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#597]
Hello.
Implementation **musicbotqueueadd** for serverquery execute.

**Comment by WolverinDEV** [comment]
Its currently done via the bots playlist :)

**Comment by lexesv** [comment]
How? :)
I don`t find
https://github.com/TeaSpeak/TeaSpeak/blob/master/documentation/Music%20bot%20query%20interface.md

**Comment by WolverinDEV** [comment]
https://github.com/TeaSpeak/TeaSpeak/blob/master/default_files/commanddocs/musicbotplaylistassign.txt 
And then manage everything via playlist...
I know this is a horrible system, but I'm working on it :)

**Comment by lexesv** [comment]
OK, but how add URL to a playlist?
since, musicbotqueueadd not working

**Comment by WolverinDEV** [comment]
These commands have been removed.
//Closed
