### ISSUE TITLE
 microphone

### ISSUE THREAD

**Issue by djshylow** [TeaSpeak/TeaSpeak#598]
**Describe the bug**
Clients Randomly disable microphone after using the server for like 30-60 minz onwards. It shows the mic is On, but when you talk other clients cannot hear. It works perfectly fine after reconnect and keeps happening again. I have no idea what it causing it so I post the past-bin link. 

**Logs**
[https://pastebin.com/CYrwNCbe](url)

**Environment information:**
 Operating system: (`Linux - Debian`)
 TeaSpeak version: [TeaSpeak-1.3.17]
 I am using `experimental_31`: (no)

**Comment by MikkelDK** [comment]
Are you using 1.3.17?

Update to: **1.3.19-beta13**

**Comment by djshylow** [comment]
> Are you using 1.3.17?
> 
> Update to: **1.3.19-beta13**
> You can DL it from here: https://repo.teaspeak.de/server/linux/amd64_optimized/TeaSpeak-1.3.19-beta-13.tar.gz

I will update and see if any issues thank you

**Comment by MikkelDK** [comment]
> > Are you using 1.3.17?
> > Update to: **1.3.19-beta13**
> > You can DL it from here: https://repo.teaspeak.de/server/linux/amd64_optimized/TeaSpeak-1.3.19-beta-13.tar.gz
> 
> I will update and see if any issues thank you

No problemo! ;)

**Comment by djshylow** [comment]
OKi Done updating. Lets see if the error come back within 24 hours.

**Comment by MikkelDK** [comment]
> OKi Done updating. Lets see if the error come back within 24 hours.

Let me know if it did help! ;) 

I don't have any issues! ;)

**Comment by djshylow** [comment]
lookz good!. Ty buddy
