### ISSUE TITLE
[CRITICAL]: Client 3.3.0 problem connect server

### ISSUE THREAD

**Issue by HomeNetwork1991** [TeaSpeak/TeaSpeak#600]
**Describe the bug**

**Environment information:**
 Operating system: (Debian 9.9)
 TeaSpeak version: [TeaSpeak-1.3.17]

**Additional context**
the next problem is that with the new version of teamspeak came out and that at the time of connxion to the server it tells me

Not Implemented
Disconnected from server ( invalide rarameter )

witch the version client 3.3.0 (11/06/2019 17:02:44) [Beta]

**Comment by MikkelDK** [comment]
Download newest version. https://repo.teaspeak.de/server/linux/amd64_optimized/TeaSpeak-1.3.19-beta-13.tar.gz
