### ISSUE TITLE
server version is too old for command while connecting

### ISSUE THREAD

**Issue by panteLx** [TeaSpeak/TeaSpeak#601]
**Describe the bug**
Server refused connection with the following reason
<20:36:20> Von Server getrennt (server version is too old for command)

**To Reproduce**
Steps to reproduce the behaviour:
- 

**Expected behaviour**
Connect

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.
16.06.2019 18:36:20	SCHandler	Warning	Error while parsing packet: server version is too old for command	

**Environment information:**
 Operating system: Win 10
 TeaSpeak version: TeaSpeak-1.3.19-beta-13.tar.gz
 I am using `experimental_31`: no?

**Comment by MikkelDK** [comment]
You need a protocol_key.txt + experimental_31 needs to be yes before it works.

Go to our forum, and contact yamano! ;)
