### ISSUE TITLE
[Question]i_permission_modify_power Not working for new permission

### ISSUE THREAD

**Issue by GoRiLliAz** [TeaSpeak/TeaSpeak#602]
**Describe the bug**
Hello,
I use the teaspeak Client.
When I want to activate a new permission like (example) b_channel_ignore_join_power
This permission does not have a Granted or Value client tells me that I need permission i_permission_modify_power, while I am 75 value and 75 Granted.
This is normal?

**Expected behaviour**
I would like to enable / disable permissions via the client instead of always going through Querie

**Screenshots**

**Logs**
[2019-06-18 15:33:25] [DEBUG]     2 | failed to format message '[Permission]    Permission: b_channel_ignore_join_power Required value: 1 Gained value: -2 Force required: 1 Channel: [cspacer]*.:{Accueil }:.* Shark Result: 0': argument not found
[2019-06-18 15:33:35] [DEBUG]     2 | [Permission] Grant test result for test type 1.

**Environment information:**
 Operating system: Linux machine 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 GNU/Linux
 TeaSpeak version: [TeaSpeak-1.3.19-beta-13]
 I am using `experimental_31`: (yes)

**Additional context**

**Comment by WolverinDEV** [comment]
Do you also have the grant permission for `b_channel_ignore_join_power` itself?
Because you could only grant permission where you've a granted value.

**Comment by GoRiLliAz** [comment]
So if the permission is not activated it can only be done via queries?
On teamspeak you can activate and deactivate the permissions in a simple click.

**Comment by WolverinDEV** [comment]
Yes or you've the permission to ignore the grant power, like the admin server query has.
The thing that you cant assign the "new" permissions because of upgrading your server is manly because that I'm not upgrading the permission db... I'll have to improve that and give all server admin groups the granted permission.

**Comment by WolverinDEV** [comment]
fixed (on permission updated the new permission will be automatically granted via the auto update permission)
