### ISSUE TITLE
(Error) insufficient client permissions (failed on i_permission_modify_power)

### ISSUE THREAD

**Issue by survivalizer** [TeaSpeak/TeaSpeak#604]
**Describe the bug**
Unable to use priority speaker on TeamSpeak 3 Client

**To Reproduce**
Steps to reproduce the behaviour:
1. Right click on a user
2. Select "Priority Speaker"
3. ERROR: insufficient client permissions (failed on i_permission_modify_power)

**Expected behaviour**
Allows the use of priority speaker in a channel

**Environment information:**
 Operating system: Ubuntu 18.04
 TeaSpeak version: 1.3.19-beta-13 
 I am using `experimental_31`: yes

**Additional context**

**Comment by WolverinDEV** [comment]
It seems like you haven't enough permissions for the target client :)
Increase your `i_permission_modify_power` :)

**Comment by survivalizer** [comment]
I have adjusted the permissions accordingly to no avail. I am able to grant it through query admin. It also kind of works if I import a fresh database from a teamspeak server; however, doing that appears to break some things.

**Comment by survivalizer** [comment]
`[2019-06-21 02:16:21] [DEBUG]     1 | [Permission]    Permission: b_client_is_priority_speaker Required value: 1 Gained value: -2 Force required: 1 Channel: [cspacer04]Default Channel Result: 0`
This is the log that appears on a brand new server install

**Comment by WolverinDEV** [comment]
> `[2019-06-21 02:16:21] [DEBUG] 1 | [Permission] Permission: b_client_is_priority_speaker Required value: 1 Gained value: -2 Force required: 1 Channel: [cspacer04]Default Channel Result: 0`
> This is the log that appears on a brand new server install

Oh that should not be the case... I'll test for it

**Comment by WolverinDEV** [comment]
https://forum.teaspeak.de/index.php?threads/does-not-work-priority-speaker-1-3-21-beta1.2097/

**Comment by WolverinDEV** [comment]
Okey with 1.4.0 `b_client_is_priority_speaker` has now for server admins a grant power of one.
This means that these groups could give priority speaker from now on.
