### ISSUE TITLE
not implemented client error

### ISSUE THREAD

**Issue by zafai** [TeaSpeak/TeaSpeak#605]
**Describe the bug**
User joins the TeaSpeak server and get the error:

not implemented
or in german
nicht implementiert

**To Reproduce**
Steps to reproduce the behaviour:
1. Use client version 3.3.0
2. connect to teaspeak server
3. see error

**Expected behaviour**
No error message

**Logs**
In the teaspeak server log I can see this error
`[ERROR]     8 | Missing command 'updatemytsdata'`
**Environment information:**
 Operating system: Debian 9.9
 TeaSpeak version: [TeaSpeak-1.3.19-beta-13]
 I am using `experimental_31`: (yes)

**Comment by Riddler76** [comment]
Same here

**Comment by WolverinDEV** [comment]
Will be fixed in 1.3.20 :)

**Comment by Riddler76** [comment]
Ok nice, no temporary issue ?

**Comment by zafai** [comment]
> Will be fixed in 1.3.20 :)

Thank you for that information, is there a ETA for 1.3.20?

**Comment by WolverinDEV** [comment]
```
--
Average stage times:(Average full run time: ~8min 10s) | 3s | 3s | 19s | 3min 21s | 240ms | 2min 4s | 22s | 247ms | 4min 4s | 4min 55s | 365ms | 1min 58s | 26s | 1s | NaNy NaNd | 2min 19s | 442ms | 584ms | NaNy NaNd | 376ms | 1min 44s | NaNy NaNd
#531

```

**Comment by zafai** [comment]
@WolverinDEV I installed the Linux x64 | 1.3.19 (Stable) from teaspeak.de and the problem is still there do you know when the 1.3.20 release is ready.

Thank you in advance.

**Comment by WolverinDEV** [comment]
Use the beta channel :)
I also recommend this script to install stuff: https://github.com/TeaSpeak/TeaSpeak/blob/master/scripts/updater.sh
