### ISSUE TITLE
Reusing virtual server ids 

### ISSUE THREAD

**Issue by wendellcosta** [TeaSpeak/TeaSpeak#607]
Reusing virtual server ids after these servers have been deleted

this could be optional, could have an option to re-use ID
adding this option in the settings would be very good

**Comment by WolverinDEV** [comment]
Implemented within the next build.

Default setting is the behavior you wanted.



If you've already created some servers you may have to increase the instance property [ICODE]serverinstance_virtual_server_id_index[/ICODE] to the server id you want to start with!
