### ISSUE TITLE
Can't delete permission

### ISSUE THREAD

**Issue by DrCost** [TeaSpeak/TeaSpeak#609]
Hello,

I can not delete permissions from the File Transfer and Client: Admin sections on some groups. No blunders just pop it up automatically

**Comment by WolverinDEV** [comment]
I'm not sure what you mean, but in general:
Editing permissions with the TeamSpeak 3 client is deprecated and not supported!
Use YatQa or the TeaSpeak client!

**Comment by DrCost** [comment]
Yes, on client teamspeak permission is set, on teaspeak client permission is not set ^^, thanks for it.
Now i have new problem on connect to server: Invalid UTF-8 character at index 4

**Comment by REDMONDS** [comment]
@DrCost You did not think to upgrade to version 1.3.20 beta 1 or higher? Starting with this version this bug is fixed.

**Comment by DrCost** [comment]
oh yea, i have 1.3.19 :)

**Comment by WolverinDEV** [comment]
Closed due to inactivity.
As well there are a lot of new versions
