### ISSUE TITLE
i_channel_group_modify_power: Invalid granted permission

### ISSUE THREAD

**Issue by essemX** [TeaSpeak/TeaSpeak#61]
## System Information
***Operating System***: Debian 8.10
***Operating System Type*** (x86|x64): amd64
***TeaSpeak Version***: TeaSpeak-1.1.0-beta-11.tar.gz
## Issue

***Detailed Description***:
trying to set the i_channel_group_modify_power (which is per default not set for the Server Admin group) will result in an Error: Invalid granted permission
which effectevly prevents me to edit any channel group

```
[23:43:37] [TRACE]   1 | [IPCENSORED/essem][Client -> Server][Command] Id 'servergroupaddperm sgid='9' permid='169' permvalue='75' permnegated='0' permskip='0' return_code='1:1v'
[23:43:37] [DEBUG]     | [Permission] Test Result: Type: 2 Permission: b_client_ignore_antiflood Req Value: 1 Value: 1 Force required: 1 Target: 0x2bf6740 Result: 1
[23:43:37] [DEBUG]     | [Permission] Test Result: Type: 2 Permission: i_server_group_modify_power Req Value: 75 Value: 75 Force required: 1 Target: 0 Result: 1
[23:43:37] [TRACE]   1 | [IPCENSORED/essem]Invalid command handle of servergroupaddperm sgid=9 permid=169 permvalue=75 permnegated=0 permskip=0 return_code=1:1v
[23:43:37] [TRACE] [IPCENSORED/essem]ErrorId: 1538 Msg: invalid parameter Data: {extra_msg = Invalid granted permission}. Sending: 1 Type: 0
[23:43:37] [TRACE]     | [IPCENSORED/essem][Server -> Client][Command] Id '0/0' Command: error id=1538 msg=invalid\sparameter return_code=1:1v extra_msg=Invalid\sgranted\spermission
```

**Comment by WolverinDEV** [comment]
You could use the perm grant command view the terminal (but I would fix this)

**Comment by WolverinDEV** [comment]
Fixed in 1.1.0-beta-13

**Comment by essemX** [comment]
das beta-13 ist korrekt und sollte nicht eigentlich beta-12 heißen oder?
wenn nicht: kann die permission in beta-12 immernoch nicht setzen.

offtopic: hab mir ein kleines update script geschrieben. denkst du es besteht soweit interesse das sich ein tutorial im forum dazu lohnt?

**Comment by WolverinDEV** [comment]
Es fixed die permission nicht im nachhinein :) 
DU musst dir diese per console geben, oder den server neu aufsetzen :)

**Comment by essemX** [comment]
ah hat geklappt endlich konnte ich die permission i_icon_id für die channel-gruppe Guest löschen, der server fand das wohl nicht so optimal:
```
<22:29:12> file not exists
<22:29:27> Das Icon für die Channel Gruppe "Guest" wurde nicht gefunden.
```

**Comment by WolverinDEV** [comment]
Haha aber was hast du denn versucht zu löschen? Das standart icon?

**Comment by essemX** [comment]
das icon ist noch da, hab nur die permission entfernt, das ist ja das lustige daran. warscheinlich versucht es jetzt ein icon mit der id null zu finden oder was auch immer beim recht entfernen gemacht wird

**Comment by essemX** [comment]
bug still present in beta-17 (did a fresh setup)
- unable to set it in the permissions window (Invalid granted permission)
- unable to set it via permgrant 1 9 i_channel_group_modify_power 75 (but it tells me it was successfully and yes i made sure the other values are correct)

**Comment by essemX** [comment]
1.1.0-beta-36 where somehow able to set the permission via the permission window but not via the permgrant command

**Comment by Xavyerder** [comment]
So, in the TeaSpeak-1.1.0-beta-36, the error is fixed or not?

**Comment by WolverinDEV** [comment]
The permgrant command is just for set the grant permission, not for the actual permission value

**Comment by essemX** [comment]
ok ich glaub ich habs herausgefunden wie es funktioniert:
wenn man den befehl permgrant <ServerId> <GroupId> <Permission> <Grant> nutzt kann man anschließend die permission auf den wert setzen der bei Grant angegeben ist, aber nur auf diesen und keinen anderen ansonsten gibt es den "Invalid granted permission" error.

Example:
permgrant 1 9 i_channel_group_modify_power 75
lässt mich die permission nur auf 75 setzen aber nicht auf 70 oder was anderes
permgrant 1 9 i_channel_group_modify_power 70
lässt mich die permission nur auf 70 setzen aber nicht auf 75 oder was anderes

**Comment by WolverinDEV** [comment]
Eigendlich solltest du mit dem permgrant die grant permission auf eine belibigen Wert setzen können.
(ACHTUNG: Die Grant value ist nicht gleich der permission wert!)

**Comment by WolverinDEV** [comment]
Fixed a long time ago :)
