### ISSUE TITLE
Ban bug

### ISSUE THREAD

**Issue by DDDD5** [TeaSpeak/TeaSpeak#610]
**Describe the bug**
Bug on ban of clients with the same IP

**To Reproduce**
Steps to reproduce the behaviour:
1. Join 2 client with the same IP
2. Ban one of the client for X Time
3. The other client will be banned permanently (only visual bug)

**Expected behaviour**
Ban for the same time

**Environment information:**
 TeaSpeak version: [TeaSpeak-1.3.21B1]
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Did we test this with a one second ban?
If so I've just fixed this issue :)

**Comment by WolverinDEV** [comment]
//Closed
