### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by tinchocba** [TeaSpeak/TeaSpeak#613]
## System Information
***Operating System***: CentOS 7.6.1810 
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.3.22-beta-2

## Issue
***Reason for reporting this issue***: It's weird but sometimes I have this random crashes.

***Detailed Description***: I can't tell you how to reproduce it, because can occur anytime.

***Crash dump***: https://drive.google.com/file/d/1hN94cwHxWfLvM2YKoSfGpK3bPFI2pMY1/view
***Log***: https://drive.google.com/open?id=1rL3cuhFG62dtO9X1zD600KySEs-dxZcI

**Comment by WolverinDEV** [comment]
Update to beta 5 :)(
They're fixed there
