### ISSUE TITLE
Server crash upon login though teaspeak web

### ISSUE THREAD

**Issue by Pyr-000** [TeaSpeak/TeaSpeak#614]
**Describe the bug**
TeaSpeak Server crashes when logging in through teaspeak web. This seems to be a hard crash, there is no error in the logfiles and the process simply exits.
The error is only visible when looking at the terminal output of a running teaspeak_minimal
There appears to be no new crash dump

**To Reproduce**
1. Go to web.teaspeak.de
2. Simply click on 'connect to a server', enter the IP and hit connect.
3. The server process crashes

**Logs**
As stated above, the error is not shown in the logfiles (the last entry is simply what happened before). The logs stop before there is even a login attempt by the webclient.
Terminal output of the crash below, starting with the connection attempt (IP substituted):
<details><summary>(expand)</summary>
<pre>
[2019-07-21 14:54:11] [INFO]      1 | [Web] Got new manager from [IP]:49548
[2019-07-21 14:54:11] [INFO]      1 | [[[IP]:49548/undefined | 0]] Using encrypted basic connection.
[2019-07-21 14:54:11] [ERROR]     1 | [[IP]:49548/undefined | 0] Got ssl pipeline error (16 | Could not proceed accept! (-1|1))
[2019-07-21 14:54:11] [INFO]      1 | Voice client 0/ (undefined) from [IP]:49548 left.
[2019-07-21 14:54:11] [INFO]      1 | [Web] Got new manager from [IP]:49457
[2019-07-21 14:54:11] [INFO]      1 | [[[IP]:49457/undefined | 0]] Using encrypted basic connection.
[2019-07-21 14:54:12] [ERROR]     1 | [[IP]:49457/UnknownWebClient # | 0] Tried to pass a unknown value client_browser_engine. Please report this, if you're sure that this key should be known!
[2019-07-21 14:54:12] [INFO]      1 | [[IP]:49457/Another TeaSpeak user | 0] Client may cached a old permission list (Server is newer than the client's last join)
[2019-07-21 14:54:12] [WARNING]     1 | Command handling of command clientinit needs 21ms.
[2019-07-21 14:54:12] [INFO]      1 | Voice client 60/6UF7cBMv4L9RZjiPLSUx2twDzpo= (Another TeaSpeak user) from [IP]:49457 joined.
[2019-07-21 14:54:12] [WARNING]     1 | Command handling of command permissionlist needs 14ms.
>
(process:9883): GLib-GObject-WARNING **: 14:54:12.456: g_object_set_is_valid_property: object class 'NiceAgent' has no property named 'ice-tcp'

(process:9883): GLib-GObject-WARNING **: 14:54:12.456: g_object_set_is_valid_property: object class 'NiceAgent' has no property named 'ice-udp'

(process:9883): GLib-GObject-WARNING **: 14:54:12.469: gsignal.c:2523: signal 'new-selected-pair-full' is invalid for instance '0x7eff75057000' of type 'NiceAgent'
./TeaSpeakServer: symbol lookup error: ./libs/libDataPipes.so: undefined symbol: nice_agent_set_stream_name

</pre>
</details>

**Environment information:**
 Operating system: CentOS 7
(Linux 3.10.0-042stab139.1 Tue Jun 18 12:51:14 MSK 2019 x86_64 GNU/Linux)
TeaSpeak version:  [build_name: "1.3.19", build_version: "1.3.19", build_index: 0]
 I am using `experimental_31`: no

**Comment by MikkelDK** [comment]
Do you use 1.3.19 version?

Try update to: https://repo.teaspeak.de/server/linux/amd64_optimized/TeaSpeak-1.3.21-beta-11.tar.gz

**Comment by Pyr-000** [comment]
Just updated to the linked version, still having the same issue.
(including no info in the logs & no crash dump)
error seems unchanged:
<details><summary>(expand)</summary>
<pre>
>
(process:10569): GLib-GObject-WARNING **: 15:08:37.926: g_object_set_is_valid_property: object class 'NiceAgent' has no property named 'ice-tcp'

(process:10569): GLib-GObject-WARNING **: 15:08:37.926: g_object_set_is_valid_property: object class 'NiceAgent' has no property named 'ice-udp'

(process:10569): GLib-GObject-WARNING **: 15:08:37.953: gsignal.c:2523: signal 'new-selected-pair-full' is invalid for instance '0x7fdb54c45000' of type 'NiceAgent'
./TeaSpeakServer: symbol lookup error: ./libs/libDataPipes.so: undefined symbol: nice_agent_set_stream_name
</pre>
</details>

**Comment by Pyr-000** [comment]
I also tried running experimental_31 to see if I would get different results, the error is still unchanged.

**Comment by WolverinDEV** [comment]
You've to update your libnice version :)

**Comment by Pyr-000** [comment]
I tried to update libnice via yum earlier, it told me I already had latest according to my Centos7 repos.
Trying to get a newer version, I used the install_libnice.sh. since then I've been getting an error upon startup:
./TeaSpeakServer: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
I reinstalled libnice, libnice-devel, pcre, pcre-devel via yum - still nothing
I tried backing up my current teaspeak server and replacing everything save for my data (config, files, DB) with the files from a freshly downloaded installation tar (http://repo.teaspeak.de/server/linux/amd64_stable/TeaSpeak-1.3.19.tar.gz), but that didn't help either.
(including re-running install_libnice.sh and reinstalling libs via yum after the fresh download)

How would I go about getting a proper pcre working here?

**Comment by Pyr-000** [comment]
Managed to fix it:
I did some research and apparently libpcre.so.3 is unique to Debian.
I grabbed the libpcre.deb from debian.org (https://packages.debian.org/sid/amd64/libpcre3/download), extracted it, extracted the data.tar.xz from there and copied the libpcre.so.3* to the libs folder in teaspeak.
It now starts again (and seems to work normally), though I currently don't have time to check if logging in via web works now.
(I may update this later when I get a chance)

**Comment by WolverinDEV** [comment]
Yeahr I'm already thinking of changing there some systems because how it currently works is a bit shitty.... Specially because if this crash stuff. As well libnice is in general a huge library, thats also why I don't directly deliver it with the server.
I think I'll try to improve that as soon the new client design is out.

**Comment by WolverinDEV** [comment]
The libnice package has been fixed.
Delete the `libnice` folder and execute the script again.
Everything should work then.

I'll still keep this issue open, because I'll link libnice in near future statically directly without a need to externally install it (For some reason that was the only way one year ago)

**Comment by Pyr-000** [comment]
I just tested, the libraries now seem to be downloading completely.
(re)moving the libnice folder and executing the install_libnice script again successfully downloaded the libraries; Starting the server still works (and operation seems normal).

**Comment by WolverinDEV** [comment]
fixed :)
