### ISSUE TITLE
Failed to execute packet resend

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#620]
## System Information
***Operating System***: ubuntu
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: "1.3.20-beta-1", build_version: "1.3.20-beta"

## Issue
Seeking help to debug a packet resend issue

These are the server logs:

"Failed to execute packet resend: Failed to receive acknowledge for packet 122 of type Command"
.....
 Failed to execute packet resend: Failed to receive acknowledge for packet 1072 of type Command
...

***Detailed Description***:

Users are disconnecting from teaspeak with "Packet resend failed". These users are online however as they are connected on other mediums such as in an FPS game or on discord

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by MikkelDK** [comment]
You need to update this version: https://repo.teaspeak.de/server/linux/amd64_optimized/TeaSpeak-1.3.22-beta-10.tar.gz

**Comment by slushpuppy** [comment]
Hey @MikkelDK unfortunately the latest version has a voice issue, and this packet resend has existed for prior versions before

**Comment by MikkelDK** [comment]
@slushpuppy TeaSpeak is not 100% stable. (only BETA) - I did move to TeamSpeak until TeaSpeak did solve the problem with "**packet error** / **Packet resend failed**"

**Comment by slushpuppy** [comment]
@MikkelDK indeed, so I am wondering how I can debug this further to help this project

**Comment by WolverinDEV** [comment]
Well there are some already stable versions out there :)
I'm a bit surprised that the users seem to "randomly" timeout....

Do you have a high server lod etc?

**Comment by slushpuppy** [comment]
@WolverinDEV Serverload is quite low, perhaps 60-70 users on at a time. 3-4 virtual servers with less than <50 users per

**Comment by WolverinDEV** [comment]
Well I've fixed some packet related issue in 1.3.22-beta12, could you may try it out?
As well @MikkelDK the voice shuddering/lag should be fixed there :)

**Comment by slushpuppy** [comment]
[2019-08-03 11:47:17] [DEBUG]    18 | [ | 30] Failed to execute packet resend: Failed to receive acknowledge for packet 126 of type Command
[2019-08-03 11:47:18] [DEBUG]    18 | [ | 30] Failed to execute packet resend: Failed to receive acknowledge for packet 126 of type Command
[2019-08-03 11:47:19] [DEBUG]    18 | [ | 30] Failed to execute packet resend: Failed to receive acknowledge for packet 126 of type Command
[2019-08-03 12:00:18] [DEBUG]    18 | [ Is For | 49] Failed to execute packet resend: Failed to receive acknowledge for packet 694 of type Command
[2019-08-03 12:00:19] [DEBUG]    18 | [ Is For | 49] Failed to execute packet resend: Failed to receive acknowledge for packet 694 of type Command
[2019-08-03 12:00:20] [DEBUG]    18 | [ | 49] Failed to execute packet resend: Failed to receive acknowledge for packet 694 of type Command

Still happening on a regular basis. Is there a way I can help you debug this, like increasing verbosity of logs or something?

**Comment by slushpuppy** [comment]
Note that this occurs when the TS is online for a couple of days. Restarting it seems to fix the issue completely o.O

**Comment by WolverinDEV** [comment]
Well thats strange sure you used there 1.3.22-beta12? Because Its just 2 days old :D

**Comment by slushpuppy** [comment]
# Version: 1.3.22-beta-12
# TeaSpeak version: 1.3.22-beta
# Build version: 12

Yes, it's a bit weird. I have also flushed my firewalls too

**Comment by WolverinDEV** [comment]
But in general it got better did it?

**Comment by slushpuppy** [comment]
Not exactly, still seeing packet resend failed of users hourly

**Comment by Sickness-chan** [comment]
For me, people are still getting dropped on the latest build (1.3.22-beta-12) due to the packet resend failing.

**Comment by WolverinDEV** [comment]
@Sickness-chan 
Sometimes its nothing critical.
It  just means that a client timed out due to bad Internet (in TeamSpeak the message is `connection lost`). Its just another message within TeaSpeak :)

But in general: I've fixed there a bug and from all of my "big" servers I god positive feedback.
So I'll close this for now. If you encounter this problem havely then just open it again :)

**Comment by Sickness-chan** [comment]
@WolverinDEV you should make the message configurable in config.yml. So it is less confusing for people who are used to TeamSpeak.

**Comment by WolverinDEV** [comment]
It is already :)
