### ISSUE TITLE
(certificate invalid date)

### ISSUE THREAD

**Issue by GoRiLliAz** [TeaSpeak/TeaSpeak#621]
**Describe the bug**
today my teamspeak client say (certificate invalid date) if i try to connect, but working in teaspeak client why ?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to connect
2. (certificate invalid date)

**Expected behaviour**

**Screenshots**

**Logs**
If applicable, add logs (trace level is recommended) to help explain your problem.

**Environment information:**
 Operating system: (`uname -a`)
 TeaSpeak version: TeaSpeak-1.3.22-beta-9.tar
 I am using `experimental_31`: (yes)

**Additional context**

**Comment by Schuermi7** [comment]
There is a certificate change, that took effect 108 minutes ago.
Until the default license of Tea*Speak was extracted of the official upstream, there is no way of connecting to your TeaSpeak Server, because that has to be put in your protocol_key.txt

**Comment by GoRiLliAz** [comment]
Ok, is and of Teaspeak ? All my team 25 use only teamspeak client no teaspeak client..
And i have 4 teaspeak server on the same machine.

**Comment by Schuermi7** [comment]
It is a thing, that is induced by TeamSpeak. The license is expired and the new one will most likely be extracted in the next few days.
Your 4 teaspeak servers will be incompatible with TeamSpeak-Client as long as there is no new protocol_key to use. 
You may switch to TeaSpeak Client or wait for the new protocol_key. 
I am very sorry for your inconvenience, but i am facing the same issues.

**Comment by lexesv** [comment]
https://teaspeaklicense.tk/

**Comment by GoRiLliAz** [comment]
THANKS YOU !

**Comment by Sephiara** [comment]
Sorry, but you posted a link to analyze protocol.key. What should i do with this? Please help me, cant connect with ts3client

**Comment by GoRiLliAz** [comment]
click on right button  "32 Slots License (1 Jan 2019 - 31 Jan 2020)" and copy/past 5 last line in protocal_key.txt , before stop server

**Comment by JoxyS** [comment]
@Schuermi7 where can I find the new protocol key?

**Comment by Schuermi7** [comment]
Hey @JoxyS. Follow the link mentioned above and click on the right button. 
It will show you the new key, that will work with your TeaSpeak instance. 
Sincerely,
Lukas

**Comment by JoxyS** [comment]
@Schuermi7 is this? https://teaspeaklicense.tk/

**Comment by Schuermi7** [comment]
Yes. 
The rightmost button

**Comment by JoxyS** [comment]
@Schuermi7 doesn't work it say this "Connection lost because server license can not be validated"

**Comment by Schuermi7** [comment]
Try removing the space after „version: 0“ 
There is a trailing Space.

**Comment by JoxyS** [comment]
Nop doesn't works. Some ideas @Schuermi7

**Comment by MikkelDK** [comment]
Set slots to 32. ;) 
+ "Invalid UTF-8 character at index 4" < You need to update teaspeak server. and adding this on config.yml:  strict_ut8_mode: 0 and done! =)

Please use the Forum! :D

**Comment by Schuermi7** [comment]
It worked for me by deleting the protocol_key.txt and recreating it with the last four lines of the new license key. 
You didn‘t copy alle the lines, didn‘t you? Because online the cryptic last ones are used

**Comment by JoxyS** [comment]
@MikkelDK where i add it?

**Comment by MikkelDK** [comment]
> @MikkelDK where i add it?
> at the end of the config?

As an example, yeah! =)

**Comment by JoxyS** [comment]
nop doesn't work @MikkelDK

**Comment by MikkelDK** [comment]
> nop doesn't work @MikkelDK

What version are you using? check buildversion.txt

**Comment by JoxyS** [comment]
now i have updated to 1.3.20-beta but now send me this "Disconnected from server (server version is too old for command)" @MikkelDK

**Comment by JoxyS** [comment]
ok @MikkelDK i have solved thanks so much if it hadn't been for you I wouldn't have solved it

**Comment by MikkelDK** [comment]
> ok @MikkelDK i have solved thanks so much if it hadn't been for you I wouldn't have solved it

or you can update to this version; https://repo.teaspeak.de/server/linux/amd64_optimized/TeaSpeak-1.3.22-beta-12.tar.gz
