### ISSUE TITLE
kicked becouse Resource deadlock avoided

### ISSUE THREAD

**Issue by McGamerComunity** [TeaSpeak/TeaSpeak#623]
**Describe the bug**
ich werd vom server gekickt

**To Reproduce**
Steps to reproduce the behaviour:
ich hatte die channelguppe channel admin
dann bin ich auf rechte gegangen channelgruppen und hab
der channelgruppe channeladmin im standart rechte system(nicht erweitert)
die serverkickpower von niemand auf serveradmin gesetzt

**Expected behaviour**
das das was da is gefixt wird

**Screenshots**
https://neoncraft.net/view.php?type=image&file=ts3client_win64_cWd653jMMs.png

**Logs**
<23:00:18> "KILLDIEKRECKER [Dosentelefon]" wurde von "Killlprecker.net" vom Server gekickt (Error while command handling (Resource deadlock avoided)!)

**Environment information:**
 Operating system: Windows 64bit
 tea*speak: 3.3.0
 I am using `experimental_31`: 1

**Additional context**
nee eig nichts

**Comment by WolverinDEV** [comment]
Well I'm sorry, but I cant reproduce this behavior.
We may should talk later, may its already fixed :D

**Comment by REDMONDS** [comment]
> Well I'm sorry, but I cant reproduce this behavior.
> We may should talk later, may its already fixed :D

It seems to me or this bug is fixed in version 1.4.0, there are familiar words, namely the reason?
