### ISSUE TITLE
Empty  for on Yatqa

### ISSUE THREAD

**Issue by Crosus97** [TeaSpeak/TeaSpeak#625]
Same has #587 

**Screenshots GIF**
https://gyazo.com/1d51c34f8acdb35b61f515ce08b1052d

**Environment information:**
 Operating system: Ubuntu 19.04
 TeaSpeak version: TeaSpeak-1.3.22
 I am using `experimental_31`: Yes

**Comment by WolverinDEV** [comment]
Your screen shot which you're posted is empty.
For me it works fine:
![](https://img.did.science/Screenshot_18-01-28.png)
![](https://img.did.science/Screenshot_18-01-58.png)

**Comment by Crosus97** [comment]
maybe you know the reason of why this can happend ?

**Comment by WolverinDEV** [comment]
Well not really, but may the channel is just not empty?
Thats then def a plausible reason :dagger:

**Comment by Crosus97** [comment]
Is empty I'm sure, maybe my db version is to old? IDK? I don't know if that can affect or can be a reason ... (?

**Comment by WolverinDEV** [comment]
Well it might be if nobody after then ever join the channel.
So may join and then leave the channel :)

**Comment by WolverinDEV** [comment]
fixed in the next version (it was only a thing in the channel list, not on channel info)
