### ISSUE TITLE
./teastart_minimal.sh throws a error 

### ISSUE THREAD

**Issue by RasmonT** [TeaSpeak/TeaSpeak#626]
Hello,

I followed this guide https://r4p3.net/resources/mirror-teaspeak-server.291/ .

But when im in the step of using the teastart minimal script im stucked and it throws a error instead...

    ./teastart_minimal.sh
    ./teastart_minimal.sh: line 65: ./TeaSpeakServer: No such file or directory
    ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (wrong 
    ELF class: ELFCLASS32): ignored.

downloaded: wget -O TeaSpeak.tar.gz https://repo.teaspeak.de/server/linux/amd64/TeaSpeak-$(curl -k https://repo.teaspeak.de/server/linux/amd64/latest).tar.gz;

Is this bug of latest version ? 

Ubuntu 16.04

**Comment by WolverinDEV** [comment]
Hey,
it seems like you're trying to use a x64 binary on a x86 host system.
Get the latest version here: https://repo.teaspeak.de/server/linux/x86_stable/

**Comment by RasmonT** [comment]
I will take a look into it this evening! Thank you for fast respond.

**Comment by RasmonT** [comment]
Unfortunately same results .. after i downloaded the teaspeak from your link .

    ./teastart_minimal.sh
    ./teastart_minimal.sh: line 65: ./TeaSpeakServer: No such file or directory
    ERROR: ld.so: object './libs/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (wrong ELF 
    class: ELFCLASS32): ignored.

**Comment by RasmonT** [comment]
Nevermind this one is working for me . 
https://repo.teaspeak.de/server/linux/amd64_stable/

**Comment by WolverinDEV** [comment]
top :)

**Comment by xchuky35** [comment]
> Önemli değil, bu benim işime yarıyor. https://repo.teaspeak.de/server/linux/amd64_stable/

This link installed and no error. thx bro :)
