### ISSUE TITLE
TeaMusic Server has been shut down: Application crashed

### ISSUE THREAD

**Issue by essemX** [TeaSpeak/TeaSpeak#63]
## System Information
***Operating System***: Debian 8.10
***Operating System Type*** (x86|x64): amd64
***TeaSpeak Version***: 1.1.0-beta-17

## Issue
***Detailed Description***:
crash after using .mbot yt <link> command:
[crashlog_02-03-2018 09-32-56.txt](https://github.com/TeaSpeak/TeaSpeak/files/1774261/crashlog_02-03-2018.09-32-56.txt)

**Comment by WolverinDEV** [comment]
Sorry,
i was to lazy to research your issue.
Did it still happens or did it just get disappeared?

**Comment by essemX** [comment]
did not happen again since late 1.1.0 but im not sure if it won't happen again
