### ISSUE TITLE
Add OpenWRT version for TeaSpeak

### ISSUE THREAD

**Issue by kyoto44** [TeaSpeak/TeaSpeak#630]
It would be very good if we can host teaspeak server on Openwrt-based router. Like umurmur for mumble.

**Comment by WolverinDEV** [comment]
Hey,
I'm not seeing any use case for running TeaSpeak on a router.
But correct me if I'm not mistaken :)

**Comment by kyoto44** [comment]
To host a server for a small group of people and use router for it so there's no need to get individual server for teaspeak host .

**Comment by WolverinDEV** [comment]
Well in that cause I recommand to use an Raspberry :)
This is much more likely than using a router.

**Comment by kyoto44** [comment]
It is not rational to spend money on a purchase raspberry pi just for teaspeak. And for you job is only in compiling to needed platform.

**Comment by WolverinDEV** [comment]
Well 20 bucks for a small really handy device is definitely that much.
And its not so easy to "just" compile for another platform as well.

But even with compiling for another platform there is still the task of maintaining another platform.
To round it up,  I'll close this here, but of cause if you've some other good reasons we could reconsider it.
