### ISSUE TITLE
<21:31:55> Desconectado del servidor (certificate invalid date)

### ISSUE THREAD

**Issue by eniorJR** [TeaSpeak/TeaSpeak#631]
**Is your feature request related to a problem? Please describe.**
when I join the server I get the error = esconectado del servidor (certificate invalid date)

**Describe the solution you'd like**
Let me access my server and put +32 slots

**Describe alternatives you've considered**
IDK

**Additional context**
https://gyazo.com/37f1a8c2110ef3a370c787897d52fd76

**Comment by MikkelDK** [comment]
Use the Forum! ;)

You need to buy new protocol_key.txt
Close this! ;)
