### ISSUE TITLE
Incorrect channel subscription behavior

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#633]
Video: https://youtu.be/Y-xUjqJzuRU

**Environment information:**
 Operating system: Debian 9.3
 TeaSpeak version: TeaSpeak-1.3.25-beta-6
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Do you have a trace log for me?
I'm not encounter this issue :/

**Comment by REDMONDS** [comment]
> Do you have a trace log for me?
> I'm not encounter this issue :/

In the evening I will provide.

**Comment by REDMONDS** [comment]
> Do you have a trace log for me?
> I'm not encounter this issue :/

I think we found a bug that will be fixed in 1.4.0-beta-2?

**Comment by WolverinDEV** [comment]
Fixed in TeaSpeak-1.4.0-beta-2.tar.gz :)
Thanks for the report
