### ISSUE TITLE
ftdeletefile

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#634]
**Describe the bug**

```
ftdeletefile cid=0 cpw name=\/icons\/icon_83503142
error id=2 msg=not\simplemented
```

**Environment information:**
 Operating system: Debian 9 x64
 TeaSpeak version: TeaSpeak-1.3.24-beta
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
The name is invalid.
Correct usage:
```
ftdeletefile cid=0 cpw name=\/icon_83503142
```

**Comment by lexesv** [comment]
Thanks!

Do you know what's wrong with that?:
```
ftinitupload clientftfid=34862 name=\/tmp\/phpoKgjan cid=0 cpw size=712 overwrite=1 resume=0 proto=0
error id=2 msg=not\simplemented
```

**Comment by WolverinDEV** [comment]
`path` is missing :)

**Comment by lexesv** [comment]
https://github.com/Dh0mp5eur/TeamSpeak3-Server/blob/master/i386/opt/teamspeak3-server_linux-x86/serverquerydocs/ftinitupload.txt

Which path?
