### ISSUE TITLE
The music bot does not save the last channel

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#635]
After the server reboots, the music bot does not connect to the last channel in which it was located; it connects to the default channel.

**Version:** TeaSpeak-1.4.0-beta-2

**Comment by WolverinDEV** [comment]
![](https://img.did.science/Screenshot_11-56-27.png)
Hmm ;)

**Comment by WolverinDEV** [comment]
Fixed in beta 3 (1.4.0)

**Comment by REDMONDS** [comment]
Fixed, but it only seems to work when you drag the bot into a channel and the channel is saved as the last one.
If you have just created a bot and did not drag it through the channels, then the bot after reboot will fall into the default channel, which is installed on the server.
