### ISSUE TITLE
Server hangs after creating a music bot

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#636]
**Describe the bug**
The server hangs if I send a command to create a music bot in the chat channel in which I am. If I send a command to create a music bot in the general chat, then everything works correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to server.
2. Write a command to create a music bot in the chat channel in which you are.
3. Congratulations you are stuck and can not go to other channels etc

**Expected behaviour**
The server should create a music bot or just not respond to the command.

**Logs**
https://pastebin.com/Qi72qE6Z

**Environment information:**
 Operating system: Debian 10.1
 TeaSpeak version: TeaSpeak-1.4.0-beta-2
 I am using `experimental_31`: yes

**Additional context**
TeamSpeak 3 Client (version 3.3.2)

**Comment by WolverinDEV** [comment]
Confirmed, fixed in beta 3 :)
