### ISSUE TITLE
The bot loaded the processor

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#638]
There is a test server (one virtual server and several channels). The server is empty, just for testing, only I know the address. I created one radio bot that broadcasts music, and after a while, namely after 19 hours the bot loaded the processor and there is no sound. The bot successfully responds to the commands to start the stream, but there is no sound.

![123456](https://user-images.githubusercontent.com/6460267/67227769-949e5700-f440-11e9-8bc3-0a181910f14f.png)

**Environment information:**
 Operating system: Debian 9.3
 TeaSpeak version: [TeaSpeak-1.4.0-beta-3]
 I am using `experimental_31`: yes

**Additional context**
A similar problem was sometimes encountered in earlier versions.

**Comment by WolverinDEV** [comment]
Does this still occur?

**Comment by REDMONDS** [comment]
> Does this still occur?

This problem seems to be fixed... but unfortunately, I'm not sure, because the bot has other problems that you already know about. :- ) If there was no new problem, I would have already been able to check the bot more deeply.
