### ISSUE TITLE
German locales bug

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [TeaSpeak/TeaSpeak#639]
umlauts and special characters are not displayed correctly in the server groups
http://vvcap.com/AcoBCH2gU

 Operating system: Debian 8
 TeaSpeak version: 1.3.25-2
 I am using `experimental_31`:  yes

**Comment by WolverinDEV** [comment]
Well cant confirm that (even with restart):
![](https://img.did.science/Screenshot_19-21-01.png)

**Comment by BIOS-THE-ORIGINAL** [comment]
yep on other servers same problem...

try´ed to solve with restarts multiple times
reconfigured locales
reinstalled server

**Comment by WolverinDEV** [comment]
A bit crazy...
Could you come later TS maybe to solve this issue?

**Comment by WolverinDEV** [comment]
Are you using SQLITE or MySQL?

**Comment by BIOS-THE-ORIGINAL** [comment]
i currently using MariaDB

i want to switch to influxDB when it will be supportet

**Comment by WolverinDEV** [comment]
Ahh thats an important thing to know.
Because with SQLITE it works like expected :)

**Comment by WolverinDEV** [comment]
Update:
The UTF-8 character issue also affects channel names :/

**Comment by WolverinDEV** [comment]
Fixed in 1.4.1-beta1 :)
