### ISSUE TITLE
After creating the bot, it does not have a default country

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#640]
**Describe the bug**
After creating the bot, it does not have a default country. Perhaps the bot has a default country, but for some reason is not displayed after the create command. If you use the command to specify a country, everything works correctly, shows the assigned country.

**To Reproduce**
1. Send a command to the server `.mbot create`
2. Look at the country of the bot after its creation.

**Expected behaviour**
After creating a bot, it must have a country. For example DE.

**Screenshots**

![Screenshot_2](https://user-images.githubusercontent.com/6460267/68051342-4159bd80-fcf8-11e9-9688-65cc66dad924.png)

**Environment information:**
 Operating system: Debian 10.3
 TeaSpeak version: TeaSpeak-1.4.1-beta
 I am using `experimental_31`: yes

**Additional context**
If it is not implemented, then I suggest to implement : -) I Think it is not difficult.

**Comment by WolverinDEV** [comment]
Well I think that the current status "I do not have a country" is the default behaviour.
A might usefull thing would be to use the fallback country within the config.

**Comment by WolverinDEV** [comment]
Implemented within the next beta
