### ISSUE TITLE
Client privileges are not removed

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#641]
**Describe the bug**
I will not describe anything, just duplicate the link to the forum where this problem is described - https://forum.teaspeak.de/index.php?threads/2313/

**Environment information:**
 Operating system: Debian 9.3
 TeaSpeak version: TeaSpeak-1.3.26-beta-1
 I am using `experimental_31`: yes/no

**Comment by REDMONDS** [comment]
@WolverinDEV _Small addition:_
The above problem is also relevant on version 1.4.1.
If necessary, I can provide a copy of the server for testing.

**Comment by WolverinDEV** [comment]
fixed in 1.4.1
