### ISSUE TITLE
Connection lost because server license can not be validated

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#644]
Perhaps I will duplicate this problem here, so that it is not lost and has been fixed.

https://forum.teaspeak.de/index.php?threads/2319/#post-16384

**Comment by WolverinDEV** [comment]
fixed in 1.4.3

**Comment by REDMONDS** [comment]
@WolverinDEV I confirm that the problem is solved 👍 
Everything works correctly and users are not disconnected from the server.
`Connection failed because the server reached its maximum amount of clients.`

**Comment by WolverinDEV** [comment]
Yes, but 1.4.3-beta has some issues with the web client and is not yet ready to use (Added libnice to the server itself, but currently has some linking issues :))

**Comment by REDMONDS** [comment]
> Yes, but 1.4.3-beta has some issues with the web client and is not yet ready to use (Added libnice to the server itself, but currently has some linking issues :))

I have seen these changes : -) I am not using the web client on my servers yet, but I am studying it and following the development.
