### ISSUE TITLE
Option to allow only TeaClient & TeaWeb to connect to the server

### ISSUE THREAD

**Issue by WolverinDEV** [TeaSpeak/TeaSpeak#647]
Title says everything

**Comment by Vafin84** [comment]
Hi! Have you made any headway?

**Comment by WolverinDEV** [comment]
Not yet :)

**Comment by WolverinDEV** [comment]
Implemented within the next release

**Comment by REDMONDS** [comment]
> Implemented within the next release

How do I use it? What is the default value?

**Comment by WolverinDEV** [comment]
Within the config.yml is a setting. By default everything is enabled. This value is also re-loadable.

**Comment by Vafin84** [comment]
Which setting is responsible for this?
