### ISSUE TITLE
Bugs after restart

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#648]
**Describe the bug**
After restarting the TeaSpeak server,  the settings of the music bot and channels privileges are reset (for some servers)

**Environment information:**
 Operating system: Debian 9
 TeaSpeak version:  1.3.25-2
 I am using `experimental_31`: yes

**Comment by WolverinDEV** [comment]
Is this reproducible for a fresh created server? Because I'm unable to :/

**Comment by lexesv** [comment]
Not. The server has been working for over a year and is being updated by files replacement.

**Comment by WolverinDEV** [comment]
Well yes I guess its manly because of the so long chipped database.
It may be a bit messed up :D

**Comment by WolverinDEV** [comment]
Well is this still a thing in 1.4.X?
