### ISSUE TITLE
Server Snapshot from Tea*mspeak too TeaSpeak

### ISSUE THREAD

**Issue by Herobr1ne** [TeaSpeak/TeaSpeak#650]
**Describe the bug**
Make a Snapshot with YaTQa from Tea*mspeak and try to use it on a TeaSpeak Server

**To Reproduce**
Steps to reproduce the behaviour:
1. Tea*mspeak Version 1.11.0 (1.10.0 too)
2. Teaspeak Version 1.4.8-beta-9

**Screenshots**
https://prnt.sc/r42dqb

**Environment information:**
 Operating system: Debian 9.4
 TeaSpeak version: 1.4.8-beta-9
 I am using `experimental_31`: yes

I try it with YaTQa 3.9.8.3b and 3.9.8.2
And with the [TS3 Manager](https://www.ts3.app)

**Comment by WolverinDEV** [comment]
The new "compressed" snapshots are not yet supported.

**Comment by Herobr1ne** [comment]
When will it be possible?

**Comment by Herobr1ne** [comment]
Or is it possible to downgrade a Tea*speak Server?
