### ISSUE TITLE
mbot bug 1.4.10-beta 

### ISSUE THREAD

**Issue by xlenonz** [TeaSpeak/TeaSpeak#651]
1.4.10-beta bugged music bot play
because of change

Removed the obsolete commands musicbotqueuelist, musicbotqueueadd, musicbotqueuereorder and musicbotqueueremove

if these files not in commanddocs .mbot not play music
musicbotqueueadd.txt	
musicbotqueuelist.txt	
musicbotqueueremove.txt	
musicbotqueuereorder.txt

**Comment by WolverinDEV** [comment]
I'm not sure what the bug here is.

**Comment by xlenonz** [comment]
sorry now i recheck this problem.

if setup teaserver first from 1.4.10-beta , music bot not working.

if setup first teaserver stable or TeaSpeak-1.4.8-beta-11 and after close and update files to 1.4.10-beta  music bot still work

**Comment by xlenonz** [comment]
i think the problem only happening first setup 1.4.10-beta and some settings are missing in database?

now i try like this ;
first setup with 1.4.10-beta then snapshotdeploy from 1.3.25 stable backup and after that music bot working.

**Comment by WolverinDEV** [comment]
Try 1.4.10-beta 1 :)

**Comment by WolverinDEV** [comment]
fixed
