### ISSUE TITLE
Missing privileges for the groups of templates

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#657]
After a new server instance is deployed, template groups do not have these privileges. I think these privileges should be added.

[T] **Server Admin**
`i_playlist_song_move_power` value 75, grant `75`

[Q] **Admin Server Query**
`i_playlist_song_move_power` value `100`, grant  `100`
`i_playlist_song_needed_move_power` value `100`, grant `100`

**Comment by WolverinDEV** [comment]
Fixed with the next update (Seems like in some beta its slipped throu)
