### ISSUE TITLE
Server Ports

### ISSUE THREAD

**Issue by otalportista** [TeaSpeak/TeaSpeak#658]
Hey,

Add a detector to check if port in use create server in avaible port 

Best regards

**Comment by REDMONDS** [comment]
Yes, you can't create a new virtual server in TeamSpeak 3 if this port is already in use, but in TeaSpeak this is possible. I suggest making this parameter configurable (enable/disable)

![Screenshot_9](https://user-images.githubusercontent.com/6460267/78502190-71eec900-7768-11ea-969e-a64091ae1c8c.png)

**Comment by otalportista** [comment]
@REDMONDS exactly and in teamspeak it don't create in port in use and create in avaible port

**Comment by WolverinDEV** [comment]
Will be implemented within the next version
