### ISSUE TITLE
Invalid channel flags

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#660]
I'll duplicate this problem here just in case.

If we create a new permanent channel and try to edit it after creation, assign it as the default channel, we will get the error "invalid channel flags", but for channels and separators that were created long time ago or moved from the default server (template), we can assign property "default channel".

**_Version:_** 1.4.11-beta-8

**Comment by REDMONDS** [comment]
Will this be fixed in some of the beta version 1.4.12?

**Comment by WolverinDEV** [comment]
Yep
