### ISSUE TITLE
MOTD / Welcome message does not match regular TS3 server

### ISSUE THREAD

**Issue by rogermb** [TeaSpeak/TeaSpeak#661]
Hi!

**Describe the bug**
The MOTD that the server sends when connecting to the Server Query interface (only raw/telnet tested) does not match the MOTD that a regular TS3 server would send.

In particular, the main problem for API / library writers is that the number of lines does not match.

Where a regular TS3 server returns these 4 lines (tested on Windows and Linux - I haven't found anyone crazy enough to run a TS3 server on MacOS)
```
TS3

Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.

```
TeaSpeak only returns 2:
```
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.
```

This likely relates to #522 and [this forum post](https://forum.teaspeak.de/index.php?threads/teaspeak-api.2586/).

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to a server using the query interface
2. Read the MOTD

**Environment information:**
I am reporting this based on an issue of a user of [our TS3 API](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API), who is using a hosting provider. As such, no detailed OS information is available. The TeaSpeak version string was gathered using the query interface.
 Operating system: Linux-based
 TeaSpeak version: [version=1.4.11-beta build_count=0 build=1585161947 platform=Linux]
 I am using `experimental_31`: no (?)

**Comment by otalportista** [comment]
Use this
motd: "TS3\r\n\nWelcome to the TeamSpeak 3 ServerQuery interface, type \"help\" for a list of commands and \"help <command>\" for information on a specific command.\r\n"

**Comment by WolverinDEV** [comment]
This is configurable within the `config.yml` ;)
https://github.com/TeaSpeak/TeaSpeak/blob/master/default_files/config.yml#L96

If you want to have multiple lines just insert a bunch more `\n`s.
It seems a bit like TS3 is also sending `\r`s before `\n` so may add some `\r\n`.

**Comment by otalportista** [comment]
@rogermb you're wrong, motd are correct, but if you want space you can use this motd.
motd: "TS3\r\n\nWelcome to the TeamSpeak 3 ServerQuery interface, type \"help\" for a list of commands and \"help <command>\" for information on a specific command.\r\n"

**Comment by rogermb** [comment]
@WolverinDEV Ah, interesting! It looks like the MOTD we observed was not even TeaSpeak's default MOTD, but possibly an MOTD set by the hosting provider. Thanks for the quick reply!

But while we're at it - the default MOTD mentioned in the comment 2 lines above:
https://github.com/TeaSpeak/TeaSpeak/blob/master/default_files/config.yml#L94
doesn't match, and I think this one probably should match.

Either way, thanks for the help! Cheers 😄

**Comment by WolverinDEV** [comment]
Comment has been changed appropriately in 1.4.14-beta6

**Comment by WolverinDEV** [comment]
Out of the ChangeLog:
```
Changed default query new line characters to the de facto standard of `\n`.
Previously `\n\r` has been used which miss matched *every* known standard.
```
  
But I don't think Java should have issues at all.  
 `java.io.BufferedReader.readline()` does not bother the line feed. It only looks for at least one of `\r` or `n`.
