### ISSUE TITLE
ts3 version is too old

### ISSUE THREAD

**Issue by GFOXI** [TeaSpeak/TeaSpeak#664]
How can i update the version of teaspeak?
Im downloading the latest version from here: https://teaspeak.de/
When i try join i have that message (server version is too old for command)

**Comment by MikkelDK** [comment]
Use forum! =)

1) You need **protocol_key**
2) Newest version: https://repo.teaspeak.de/server/linux/amd64_optimized/TeaSpeak-1.4.14-beta-2.tar.gz
