### ISSUE TITLE
Incorrect statistics of the virtual server

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#665]
I'll just leave this screenshot of the virtual server statistics.

![Без названия](https://user-images.githubusercontent.com/6460267/80427293-1be8ed80-88f0-11ea-86a0-578116f01cb7.png)

Also pay attention to the average statistics for the entire instance (data, packets, files) from the very beginning of the instance, it is also incorrect, this was written on the forum... It's possible that these bugs are related, but I'm not sure.

**TeaSpeak version:** TeaSpeak-1.4.14-beta-2

**Comment by WolverinDEV** [comment]
Fixed in beta 3.
The 16,00 EiB isn't a TeaSpeak bug. YatQa just can't handle a value of 0.

**Comment by REDMONDS** [comment]
@WolverinDEV so TeaSpeak doesn't count file traffic sent and received in the virtual server statistics in the counter since the virtual server was started?

**Comment by REDMONDS** [comment]
Here's how this is displayed in TS3. At the moment, I created a server and, without connecting to it, loaded icons using YaTQA.
![1234](https://user-images.githubusercontent.com/6460267/80516151-bb0ef300-898b-11ea-8879-3f9fb0bc10a2.png)

**Comment by REDMONDS** [comment]
file traffic is also ignored in TeaSpeak when loading icons via YaTQA)) but this is probably normal, although the same TS3 takes this traffic into account (see the screenshot above).
![Screenshot_13](https://user-images.githubusercontent.com/6460267/80518524-3920c900-898f-11ea-908f-23fb4e3378a6.png)

but now I was loading icons using the TS3 interface, the file traffic counts, but still one of them is zero. I suspect that it is not implemented or does not work correctly.
![Screenshot_14](https://user-images.githubusercontent.com/6460267/80518767-99b00600-898f-11ea-9fc3-410229d2658e.png)

**Comment by WolverinDEV** [comment]
Seems like the server only received data, but never send any^^
Thats normal.

YatQA icon downloads are taken (in general) in account as well.
But that highly depends on the current server you're on

**Comment by REDMONDS** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/6460267/80520324-ef85ad80-8991-11ea-8d59-dcd5f34b4d7f.png)
I uploaded the icons to the server, as well as one file via a file browser.... then I downloaded this file)) this counter still shows zero.

**Comment by WolverinDEV** [comment]
hmm, but the total traffic increased?

**Comment by WolverinDEV** [comment]
Fixed, these properties have not been transferred. Will be fixed in next build

**Comment by REDMONDS** [comment]
> Fixed, these properties have not been transferred. Will be fixed in next build

I will be waiting for 1.4.14-beta-4 with improved virtual server statistics, but also you will pay attention to the statistics of the entire instance. I reproduced a case where some of the transmitted statistics were lost,  however this happened in 1.4.14-beta-2
