### ISSUE TITLE
channel max client reached before it have to

### ISSUE THREAD

**Issue by TheDiversity** [TeaSpeak/TeaSpeak#666]
Bug in version Beta 1.4.14 (maybe already solved?)

Join in a chanel with a maximum clients result in an error "channel maxclient reached" one client before the maximum reach. I test this also with 1.4.12 (Stable) here the things work as intented.

**Environment information:**
 Operating system: Ubuntu 18.04.4 LTS
 TeaSpeak version: Beta 1.4.14
 I am using `experimental_31`: yes

**Comment by MikkelDK** [comment]
Do you use 1.4.14 or 1.4.14-b2?

**Comment by TheDiversity** [comment]
Thank you for the Quick response. I had test this with 1.4.14-b3. Same error.

**Comment by REDMONDS** [comment]
> Thank you for the Quick response. I had test this with 1.4.14-b3. Same error.

I feel like this is a child's mistake)) @WolverinDEV (Markus) probably forgot to put the "=" sign when checking how many clients are in the channel and how many are allowed)

**Comment by TheDiversity** [comment]
Be careful caused of the b_channel_join_ignore_maxclients permision is a client count over max client not a invalid case.

**Comment by WolverinDEV** [comment]
> > Thank you for the Quick response. I had test this with 1.4.14-b3. Same error.
> 
> I feel like this is a child's mistake)) @WolverinDEV (Markus) probably forgot to put the "=" sign when checking how many clients are in the channel and how many are allowed)
You'll laugh, but the exact opposite happened...
![image](https://user-images.githubusercontent.com/11856882/80575938-9f93fe80-8a04-11ea-82d1-216b7b052eea.png)
I put in one `=` too much.

Fixed in b4

**Comment by REDMONDS** [comment]
@WolverinDEV just checked, it's fixed.
