### ISSUE TITLE
Virtual server statistics

### ISSUE THREAD

**Issue by REDMONDS** [TeaSpeak/TeaSpeak#672]
**Describe the bug**
Statistics for virtual servers are displayed incorrectly after a while.

**To Reproduce**
![12345678](https://user-images.githubusercontent.com/6460267/82147845-568fd700-9859-11ea-81f0-5e3576d51ce5.png)

**Additional context**
A similar problem has been fixed in instance statistics, now everything is fine there, but I strongly recommend checking all statistics counters (data, packets, files)

**Environment information:**
 Version: TeaSpeak-1.4.14-beta-12

**Comment by WolverinDEV** [comment]
Will be fixed in the next build
