### ISSUE TITLE
Buffer Underflow while connecting to my Server

### ISSUE THREAD

**Issue by slin2510** [TeaSpeak/TeaSpeak#674]
## System Information
***Operating System***: Ubuntu Linux 16.04.6
***Operating System Type***: x64
***TeaSpeak Version***: 1.4.14
## Issue
***Reason for reporting this issue***:
Nobody can connect to my TeaSpeak Server. Everybody gets this Error in their client "Failed to connect to server".

***Detailed Description***:
Every Time i try to connect to my Teaspeak Server i get this error in my logfile (log level: DEBUG).
"Dropping command packet because command assembly buffer has an underflow (32|2|1)" 

I've uploaded the whole logfile so it's easier for you to help me.

[log_2020-07-03_17%3A26%3A08_general.log](https://github.com/TeaSpeak/TeaSpeak/files/4870447/log_2020-07-03_17.3A26.3A08_general.log)

**Comment by MikkelDK** [comment]
Do you have enabled this:

"`experimental_31: 1`" on config.yml?
If it's 0 > need to be enabled! =)
