### ISSUE TITLE
Cannot join to TeaSpeak server using TeamSpeak 3 Client

### ISSUE THREAD

**Issue by norelock** [TeaSpeak/TeaSpeak#675]
**Describe the bug**
When you're trying to join server by TeamSpeak 3 Client he can't join.

**Screenshots**
![image](https://user-images.githubusercontent.com/45716916/87561765-6727c680-c6bd-11ea-8808-90b556509bf7.png)

**Comment by MikkelDK** [comment]
We don't support ts3 client. :)

**Comment by Bluscream** [comment]
You need experimental_3_1 setting + a generated key for teamspeak to work

**Comment by waiodijowgerpo** [comment]
> You need experimental_3_1 setting + a generated key for teamspeak to work

What do you mean "generated key"?
