### ISSUE TITLE
[request] VServer Logs Splitted

### ISSUE THREAD

**Issue by JonathanNet** [TeaSpeak/TeaSpeak#68]
Server logs splitted in log by vserver as teamspeak server does, eks:

ts3server_2017-05-14__23_15_09.010926_0
ts3server_2017-05-14__23_15_09.010926_1

Etc. So the last number is the virtual server id.

**Comment by essemX** [comment]
i would suggest to put the number between ts3_server and the date so every vServer is grouped together if its sorted by name

**Comment by WolverinDEV** [comment]
~ Implemented in 1.1.2-beta

**Comment by Bluscream** [comment]
It's also possible to group the logs in folders as @WolverinDEV pointed out [here](https://forum.teaspeak.de/index.php?threads/de-allgemeine-vorschl%C3%A4ge.105/post-591)
