### ISSUE TITLE
Bug when creating channel using ts3phpframework

### ISSUE THREAD

**Issue by otalportista** [TeaSpeak/TeaSpeak#680]
Hello,

I think i found a bug when i try create channel using ts3phpframework it just create without password.

$ts3->channelCreate(array(
                "channel_name" => $_POST['name'],
                "channel_password" => $_POST['password'],
                "channel_codec" => TeamSpeak3::CODEC_OPUS_VOICE,
                "channel_codec_quality" => 0x08,
                "channel_flag_permanent" => true,
));

Best regards.

**Comment by WolverinDEV** [comment]
Hey,
you're missing the `channel_flag_password => true` parameter.

**Comment by otalportista** [comment]
Yep, sorry im wrong now works. Thanks 👍
