### ISSUE TITLE
It is not possible to edit the text notification "client type is not allowed to join the server"

### ISSUE THREAD

**Issue by Vafin84** [TeaSpeak/TeaSpeak#681]
**Is your feature request related to a problem? Please describe.**
I would like to change the text notification "client type is not allowed to join the server" when forcibly disabling the TS3 client, but this is not possible at the moment.

**Describe the solution you'd like**
Add the ability to change the "client type is not allowed to join the server" text notification in the config.yml file

**Comment by Vafin84** [comment]
@WolverinDEV , when will you add this feature?

**Comment by cyberlimbo** [comment]
I hope yes.
It is really important so we can inform our clients that they can download teaspeak client and connect ;)

**Comment by WolverinDEV** [comment]
Will most likely come with 1.5.0, hopefully I don't forget about it.

**Comment by WolverinDEV** [comment]
Okey will come in 1.5.0

**Comment by cyberlimbo** [comment]
Is this added to the new build v1.5.0 nightly?

**Comment by WolverinDEV** [comment]
`not_allowed_message` ;)

**Comment by cyberlimbo** [comment]
Nice :P

**Comment by Vafin84** [comment]
Everything works fine for me too, thank you!
