### ISSUE TITLE
We need teaspeak server arm version,to deploy on Rpi4

### ISSUE THREAD

**Issue by samondlee** [TeaSpeak/TeaSpeak#685]
We need teaspeak server arm version,to deploy on Rpi4

**Comment by MikkelDK** [comment]
https://repo.teaspeak.de/server/linux/arm32v7_optimized/ - Here.

**Comment by samondlee** [comment]
> https://repo.teaspeak.de/server/linux/arm32v7_optimized/ - Here.

ohhh thanks,does it work with teamspeak 3.12 client or only teaspeak client......

**Comment by samondlee** [comment]
i get it
