### ISSUE TITLE
Permissions not getting updated after using token

### ISSUE THREAD

**Issue by dudztroyer** [TeaSpeak/TeaSpeak#689]
When using a privillege key the user doesn't trigger update channel list, which won't show the channels that were out of view via the view power permission... Also, the user order change in the channel wont trigger for any of the connected clients, implying that the clients doesn't get the talk_power permission update aswell.

Steps to reproduce:

1-Join with a new user ID, without any permissions, only the default group (without any special permissions aswell, you can even make sure he doesn't see any channel via the VIEW_POWER permission just so you can see the effect more drastically).
2-Create a token for the SA group, which has view power needed to see all the channels and then use the token on the new user ID.
3-The user wont be able to see the channels neither change to any other since his permissions didn't get updated.

https://i.imgur.com/Gr8KRh6.gif

**Comment by WolverinDEV** [comment]
fixed :)
