### ISSUE TITLE
Serverpassword not working

### ISSUE THREAD

**Issue by JonathanNet** [TeaSpeak/TeaSpeak#69]
I trying to set the server password, and its not working, I dont know if its a bug, or not yet implanted, but its not working then I try to connect with a new client, without enter the server password I set.

Using TeaSpeak-1.1.3-beta-2

**Comment by essemX** [comment]
can confirm this behavior. everyone can connect regardless of what is typed in the password field.

**Comment by WolverinDEV** [comment]
This issue not exists (you may had the permission `b_virtualserver_join_ignore_password`)
