### ISSUE TITLE
Resource deadlock avoided

### ISSUE THREAD

**Issue by almir101** [TeaSpeak/TeaSpeak#692]
**Describe the bug**

You were kicked from the server by the Server (Error while command handling (Resource deadlock avoided)!)
When I try to edit needed talk power on the channel I got kicked every single time, even tried with clean server.

**To Reproduce**
Modify needed talk power on any room and click apply

**Environment information:**
 Operating system:  debian 10 buster, i7-7700K, 64GB DDR4, OVH Game. Run as teaspeak user (not root)
 TeaSpeak version: TeaSpeak 1.5.0-beta [Build: 1607801091]
 I am using `experimental_31`:yes

**Comment by WolverinDEV** [comment]
Yes this is a thing but only occurs when people are within the channel.
This is more a logic error which isn't easy to fix. But I'll improve on that soonly.

**Comment by WolverinDEV** [comment]
fixed

**Comment by alishmax** [comment]
1.4.21-b3 now while editing talk power on channel group

![Image](https://github.com/user-attachments/assets/8db1da9a-04d5-4bea-a62d-cfa46b080bd8)
