### ISSUE TITLE
random rash

### ISSUE THREAD

**Issue by Panda260** [TeaSpeak/TeaSpeak#693]
**Describe the bug**
der TeaSpeak ist einfach ge krasht

**To Reproduce**
Steps to reproduce the behaviour:
3. Setting to apply '....'

**Expected behaviour**

**Screenshots**
https://img.neverstopgaming.net/Panda260/MobaXterm_cgANLTaP70.png

**Logs**
https://img.NeverStopGaming.net/Panda260/crash_dump_371ee12b-8bc7-40f3-4dee19a0-eda62e18.dmp

**Environment information:**
 Operating system: (`uname -a`)
 TeaSpeak version: [TeaSpeak-1.1.40-beta-1]
 I am using `experimental_31`: (yes/no)

**Additional context**

**Comment by WolverinDEV** [comment]
Update to 1.5.0 ;)
