### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#694]
**Environment information:**
 Operating system: Linux 
 4.9.0-14-amd64 #1 SMP Debian 4.9.240-2 (2020-10-30) x86_64 GNU/Linux
 TeaSpeak version: TeaSpeak-1.4.20
 I am using `experimental_31`: yes

[crash_dumps.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/5851731/crash_dumps.tar.gz)

**Comment by WolverinDEV** [comment]
This version is'nt supported.
I'd recommend using the latest 1.5.0-beta version.

**Comment by lexesv** [comment]
Why beta, not stable version (TeaSpeak-1.4.22)?

**Comment by WolverinDEV** [comment]
Well since some crashes of 1.4.22 have been fixed in 1.5.0 ;)
It's also the next release candidate for stable.
https://forum.teaspeak.de/index.php?threads/1-5-0-crash-collection.3154/
