### ISSUE TITLE
Crash dumps

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#695]
Environment information:
Operating system: Linux 4.9.0-14-amd64 SMP Debian 4.9.240-2 (2020-10-30) x86_64 GNU/Linux
TeaSpeak version:  TeaSpeak-1.5.0-beta-7
I am using experimental_31: yes

[crash_dumps.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/5875364/crash_dumps.tar.gz)

**Comment by REDMONDS** [comment]
Thanks. Сan you also test your server with the trace log enabled?
You can enable it in the configuration of your instance (config.yml)
![Screenshot_14](https://user-images.githubusercontent.com/6460267/105914355-4c0c1b00-603f-11eb-864d-0bbb41766b7e.png)

After testing, also attach a crash dump if it appears.

**Comment by REDMONDS** [comment]
https://forum.teaspeak.de/index.php?threads/1-5-0-crash-collection.3154/#post-22399

Also, a very big request to test your server on this version and provide the requested information.

**Comment by lexesv** [comment]
Unfortunately, I cannot run tests. This is a production server.

After the update to 1.4.22 (as well as to 1.5.0), something strange began to happen.
Server crashes every half hour. On virtual servers, the privileges of groups, channels, chat, etc. have disappeared. Some of the important privileges have been lost for the "ServerAdmin" groups.

I cannot allow this on a production server with 200+ clients. I rolled back the server to the previous version (1.4.20) and restored the database from backups.

**Comment by WolverinDEV** [comment]
Can you upload the logs for the crash dumps as well (must be at least debug).
Do you use the query on a regular basis?

**Comment by lexesv** [comment]
> Do you use the query on a regular basis?

Yes.

[logs.tar.gz](https://github.com/TeaSpeak/TeaSpeak/files/5882193/logs.tar.gz)

**Comment by WolverinDEV** [comment]
most likely fixed in the new 1.5.4-beta7
