### ISSUE TITLE
Install Server Error "libjemalloc.so.2"

### ISSUE THREAD

**Issue by PainFlowZz** [TeaSpeak/TeaSpeak#696]
**Describe the bug**
I'm trying to install TeaSpeak on my Root Server. A lot of Errors say something about the lib: "libjemalloc.so.2"

**To Reproduce**
Steps to reproduce the behaviour:
1. Create Teaspeak user
2. Move aioinstall.sh in root directory
3. Apply 777 permissions to script
4. run script
5. select option 1) Install TeaSpeak Server
6. ./teastart_minimal.sh
7. Errors Errors Errors

**Screenshot**
https://prnt.sc/yh2nwl

**Log**
https://workupload.com/archive/EsB27NCa

**Environment information:**
Debian 9

**Comment by MikkelDK** [comment]
Try to remove the file. =)

**Comment by WolverinDEV** [comment]
`libjemalloc.so.2` is currently not shipped (See https://forum.teaspeak.de/index.php?threads/1-5-0-crash-collection.3154/#post-22399)
It's nothing critical but thanks for pointing out

**Comment by WolverinDEV** [comment]
fixed
