### ISSUE TITLE
libssl.so.1.1 missing

### ISSUE THREAD

**Issue by DieNrSieben** [TeaSpeak/TeaSpeak#70]
## System Information
***Operating System***: Ubuntu-16.04.4-server-amd64
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.4-beta

## Issue
***Reason for reporting this issue***:
The Server didn't started after the Update to 1.1.4-beta and even if I create a fresh instance it didn't start

***Detailed Description***:
When I'm start the TeaSpeak Server with the minimal startscript I get the following error:
./TeaSpeakServer: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

I already installed libssl-dev via apt but it didn't helped

The OS is running in a clean VM and is fresh installed.

**Comment by WolverinDEV** [comment]
Haha fuck,
that was a point that i forgot to check...
I have to link the lib static or provide it under libs.
You could easily  fix this issue by installing libssl :)

**Comment by DieNrSieben** [comment]
Fixed since 1.1.5-beta
