### ISSUE TITLE
Forum account banned for spam

### ISSUE THREAD

**Issue by jeantmsantos** [TeaSpeak/TeaSpeak#706]
It's not an application problem, it's a teaspeak forum account.

Today when I went to renew my license my account took longer than usual to log in, as soon as I logged in there was information that I had been banned for spam and to contact the administrator, it is not possible through the forum to do this type of action. Well, it's been a while since I have access to my forum account, it has 2 active factors and the login is always done through github and whenever there is access I am notified by email, there has been no access to it for 5 months. This account is exclusive to teaspeak access, it doesn't exist in other forums, as well as the password is very specific for this forum.

My license will expire in the next few days, more precisely in 10 days how to proceed from here?

@WolverinDEV

**Comment by jeantmsantos** [comment]
@WolverinDEV

Para facilitar, meu nome no fórum é **Pamonha**

**Comment by jeantmsantos** [comment]
@WolverinDEV
To make it easier, my name on the forum is **Pamonha**

**Comment by mrc4tt** [comment]
You should **had** fix your account. - You're banned because your account is hacked =)

**Comment by cyberlimbo** [comment]
yeah, i just informed BIOS that some forum users accounts got hacked because they're using
really easy passwords, you're one of the persons.
So please login your account and edit the password to a secure one mate ;)

**Comment by jeantmsantos** [comment]
The strange thing about all this is that the password had all the factors for its security, capital letters, lowercase letters, special characters and etc. But when accessing the account monitoring system by Google, there was a notice for my account here on gitbub really , I changed all credentials and improved the security of the specific account by enabling two factors.

Thanks for the alert, I even sent a notification to Google, as normally the account monitoring system should have warned me on the day the identification was made, which happened more than 30 days ago and nothing had arrived in the application.
