### ISSUE TITLE
Connection to server from webclient fails

### ISSUE THREAD

**Issue by zocker-160** [TeaSpeak/TeaSpeak#708]
**Describe the bug**
I setup a TeaSpeak server using the Docker container. When connecting using the TeaSpeak Client everything works, but when I try to connect using the webclient, it fails.

I tried it both with my own self hosted one and with https://web.teaspeak.de/.

**To Reproduce**
Steps to reproduce the behaviour:
- Setup TeaSpeak server using https://github.com/TeaSpeak/TeaDocker/blob/master/server/debian.Dockerfile
- go to https://web.teaspeak.de/ and try to connect

**Expected behaviour**
It should connect just like with the TeaClient.

**Logs**
During the connection attempt, on the server I get the following log:
```
> [2021-11-10 15:01:21] [INFO ]     1 | [Web] Got new client from 84.149.240.243:57226
> [2021-11-10 15:01:21] [INFO ]     1 | [[84.149.240.243:57226/undefined | 0]] Using encrypted basic connection.
> [2021-11-10 15:01:21] [ERROR]     1 | [84.149.240.243:57226/undefined | 0] Got ssl pipeline error (16 | error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate)
> [2021-11-10 15:01:21] [CRITICAL]   GEN | Soft assertion @/root/server/TeaSpeak/server/src/TS3ServerClientManager.cpp:106 'client->state == ConnectionState::DISCONNECTED' failed! This could cause fatal fails!
> [2021-11-10 15:01:21] [INFO ]     1 | Voice client 0/ (undefined) from 84.149.240.243:57226 left.
> [2021-11-10 15:01:22] [INFO ]     1 | [Web] Got new client from 84.149.240.243:57234
> [2021-11-10 15:01:22] [INFO ]     1 | [[84.149.240.243:57234/undefined | 0]] Using encrypted basic connection.
> [2021-11-10 15:01:22] [ERROR]     1 | [84.149.240.243:57234/undefined | 0] Got ssl pipeline error (16 | error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired)
> [2021-11-10 15:01:22] [CRITICAL]   GEN | Soft assertion @/root/server/TeaSpeak/server/src/TS3ServerClientManager.cpp:106 'client->state == ConnectionState::DISCONNECTED' failed! This could cause fatal fails!
> [2021-11-10 15:01:22] [INFO ]     1 | Voice client 0/ (undefined) from 84.149.240.243:57234 left.
```

**Environment information:**
 Operating system: `Linux Tea-Server 4.19.0 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 GNU/Linux`
 TeaSpeak version: 1.5.6
 I am using `experimental_31`: no

**Additional context**
Interestingly enough even connecting to the official testserver (ts.teaspeak.de)) fails when using the webclient.

I tested with both Firefox and Chromium.

**Comment by WolverinDEV** [comment]
fixed (needed to update the `con-gate.work` certificate.

**Comment by zocker-160** [comment]
can confirm it works now, thank you!
