### ISSUE TITLE
Implement private channels

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#71]
Could you please implement private channels? They're already partly implemented as you see with the `b_channel_create_private` permission.

**I think** the concept is as follows:

- Private channels are invisible for people that don't have enough `i_channel_needed_view_power` (create this perm) to view it
- Private channels can be created with plugins using the `CHANNEL_FLAG_PRIVATE` (see https://pytson.4qt.de/ts3defines.ChannelPropertiesRare-class.html) or query (http://yat.qa/ressourcen/server-query-kommentare/#channelcreateprivate)
- When a user enters the server and he get's the channel list the perms are being compared and only those where the client's `i_channel_view_power` > `i_channel_needed_view_power` get listed.
- When a client gets a `i_channel_view_power` greater then one of the channels `i_channel_needed_view_power` that channel will become visible by a `notifychannelcreated` event so he can join it.
- Also when a user want's to move someone in such a channel the server should first send a `notifychannelcreated` before the `notifyclientmoved` and after he's moved out again the server should send a `notifychanneldeleted` for that channel

**Comment by WolverinDEV** [comment]
Well good concept, but still not shure if i can delete a channel without a reason and a invoker.
Need some research, may I'll will implement this

**Comment by Bluscream** [comment]
Use the server as invoker (clientID 0) and as reason an empty string maybe or "channel is private"

**Comment by WolverinDEV** [comment]
Implemented within the next build :)

**Comment by Bluscream** [comment]
Ohh thats pretty cool :+1:
