### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by srkhost** [TeaSpeak/TeaSpeak#72]
## System Information
***Operating System Ubuntu 14.04:
***Operating System Type x64 (x86|x64):
***TeaSpeak Version 1.1.9:

## Issue
When I upload one or more icon and change the directory or the group icon it changes but after i reopen it disappear.

***Detailed Description***:
http://prntscr.com/ixyqu0

**Comment by WolverinDEV** [comment]
Seems like the icon wasn't uploaded successfully. 
I'll try to reproduce that

**Comment by WolverinDEV** [comment]
This issue corespondent with https://github.com/TeaSpeak/TeaSpeak/issues/78

**Comment by WolverinDEV** [comment]
Should be fixed.
Could you test it?
