### ISSUE TITLE
Group Icon Bug!

### ISSUE THREAD

**Issue by CraftenMedia** [TeaSpeak/TeaSpeak#74]
**System Information:**

***Operating System Ubuntu 16.04.4 LTS:
***Operating System Type x64 (x86|x64):
***TeaSpeak Version 1.1.9-beta-4

**Issue:**

When i join whit my freshly installed TeamSpeak 3 Client (3.1.8) on Windows and my freshly installed TeaSpeak Server on Version TeaSpeak-1.1.9-beta-4. I get some error for the icons on the Server!

**Detailed Description:**
https://gyazo.com/25835d2feed4941e947f8d8f0384f785

**Comment by WolverinDEV** [comment]
Fixed in 1.1.11-beta-1 :)
