### ISSUE TITLE
Icon file not found after removing permission

### ISSUE THREAD

**Issue by essemX** [TeaSpeak/TeaSpeak#76]
## System Information
***Operating System***: Debian 8.10
***TeaSpeak Version***: 1.1.11-beta-4

## Issue
***Detailed Description***:
When you delete the permission i_icon_id in the advanced permission display (same with the standard (simple) display) from an default-group like the Guest channelgroup then you will get this error on join (in the server-chat):
```
<20:55:59> file not exists
<20:56:14> The icon for channel group "Guest" was not found.
```
Note: this bug is present since ~ <1.1.0

**Comment by WolverinDEV** [comment]
Still preset?
Should be fixed

**Comment by essemX** [comment]
when i set and remove an icon its temporarily fixed while the server is running (even after reconnecting), but after a server-restart it comes back

**Comment by WolverinDEV** [comment]
Fixed (now testing on server restart all icons)
TeaSpeak - 1.1.20

**Comment by essemX** [comment]
updated to 1.1.20-beta-1 but can't even connect...
`<15:23:08> Disconnected from server (convert error)`
btw ip of my testserver is quixcast.de:25580

**Comment by WolverinDEV** [comment]
Fixed,
but thanks for the detailed report.
