### ISSUE TITLE
Show name in tree

### ISSUE THREAD

**Issue by srkhost** [TeaSpeak/TeaSpeak#77]
## System Information
***Operating System***: Ubuntu 14.04
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.11.1

## Issue
***Reason for reporting this issue***:
Can't change i_group_show_name_in_tree
Invalid granted permission

and i can't grant it.

***Detailed Description***:
http://prntscr.com/j05fje

**Comment by WolverinDEV** [comment]
Fixed in 1.1.12-beta
