### ISSUE TITLE
Can't upload files to channel

### ISSUE THREAD

**Issue by srkhost** [TeaSpeak/TeaSpeak#78]
## System Information
***Operating System***: Ubuntu 14.04
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.11.1

## Issue
***Reason for reporting this issue***:
When I want to upload a picture or a simple file I can't, because it's get uploading but at 37%-50% it's write error.
Transfer "vps_hosting_bg1.jpg" reports: (lost file transfer connection)

***Detailed Description***:
http://prntscr.com/j05h99
http://prntscr.com/j05hcy

**Comment by WolverinDEV** [comment]
This is a general file upload issue, when you're trying to upload a bunch of files

**Comment by WolverinDEV** [comment]
should be fixed in 1.1.20 :)
