### ISSUE TITLE
Fix typo in tags

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#81]
one of your github tags is `teamsepak` instead of `teamspeak`

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WolverinDEV** [comment]
Hmm where?
I dont file it.
![](http://img.mcgalaxy.de/Screenshot-11-54-00.png)

**Comment by Bluscream** [comment]
@WolverinDEV second last on your screenshot

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bluscream** [comment]
Also `communication` :3
