### ISSUE TITLE
Implementation of VPN and Proxy Checker

### ISSUE THREAD

**Issue by Sporesirius** [TeaSpeak/TeaSpeak#85]
**Implementation of VPN and Proxy Checker**

**Forum**
https://forum.teaspeak.de/index.php?threads/vpn-blocker.129/

**Function**
Checks if a user is using a VPN or a proxy.

**Command suggestion**
b_client_vpncheck_bypass

**Service**
https://vpnblocker.net/

**Comment by Bluscream** [comment]
If at all it's `b_client_vpncheck_bypass` since it's a boolean.

Also there are plenty of bots out there that already have vpn checking

- vpn checker by gzpro
- sprummlbot
- ispvalidator plugin for pytson and ts3audiobot

**Comment by WolverinDEV** [comment]
If cause it just could check VPN providers.
It's nearly impossible to detect **all** vpn's

**Comment by Bluscream** [comment]
Yeah the only real way would be a well maintained list of IP ranges owned by legit home ISP's and AFAIK that's not a thing yet

**Comment by schoerg** [comment]
What for anyway? if people are circumventing bans, increase the security level.

**Comment by Bluscream** [comment]
@schoerg thats no longer effective, there are tools that allow malicious users ti increase their security level up to 800% faster than legit users.

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WolverinDEV** [comment]
I think its not necessary to implement someones vpn api (which is may even wrong)
I think the max clone limits for ip and hwid do a really great job :)

**Comment by Ghostium** [comment]
As an alternative you could use this IP range list of datacenters: https://github.com/client9/ipcat/blob/master/datacenters.csv.

It is licensed under GPLv3 and would make the integration loosely coupled in comparison to an API. It may be not as good as a professional VPN detection API nor does it have complete coverage but I think it is good enough for most cases.

**Comment by WolverinDEV** [comment]
Implemented within the next version :)
