### ISSUE TITLE
WebClient not working with Firefox browser

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#87]
## System Information
***Operating System***: Debian 9
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: WebClient (Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0)

## Issue
Not working.

**Comment by WolverinDEV** [comment]
Please provide the terminal output (Console)
![](http://img.mcgalaxy.de/Screenshot-19-18-17.png)

**Comment by WolverinDEV** [comment]
BTW: Wrong repro :)
