### ISSUE TITLE
Uptime

### ISSUE THREAD

**Issue by srkhost** [TeaSpeak/TeaSpeak#88]
## System Information
***Operating System***: Ubuntu 17.04
***Operating System Type*** (x86|x64): x64 
***TeaSpeak Version***: newest

## Issue
***Reason for reporting this issue***:
http://prntscr.com/j54jek

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by Bluscream** [comment]
`serverlist`'s `virtualserver_uptime`

**Comment by WolverinDEV** [comment]
Should be fixed :)

**Comment by WolverinDEV** [comment]
Should be fixed too
