### ISSUE TITLE
perm b_group_is_permanent not working

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#89]
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64): 64
***TeaSpeak Version***: last

## Issue
***Reason for reporting this issue***:
The permission is not working

***Detailed Description***:

b_group_is_permanent is not working , it should remove the users if they left the server .

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Will be fixed :)

**Comment by WolverinDEV** [comment]
Implemented :)
