### ISSUE TITLE
Retreiving IP / Number of connections.

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#90]
## System Information
***Operating System***: debian
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.16-beta-7

## Issue
***Reason for reporting this issue***:
No ability to retreive client ip and number of clients connection with Query ? 

***Detailed Description***:

I wanted to know how to retreive client connection ip and clients total connections with query? 
Is there another name for thoses values are them implemented yet ?

connection_client_ip
client_totalconnections

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Should be fixed :)
