### ISSUE TITLE
Crash on serverSnapshotDeploy

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaSpeak#91]
## System Information
***Operating System***: Linux
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: v1.1.16-beta-9

## Issue

[crash_dump_40d12727-e446-4d8a-82472abc-fec4a002.dmp.gz](https://github.com/TeaSpeak/TeaSpeak/files/1916523/crash_dump_40d12727-e446-4d8a-82472abc-fec4a002.dmp.gz)

**Comment by lexesv** [comment]
[crash_dump_e0c21efd-b885-4ae4-895a1ea7-3011bd92.dmp.gz](https://github.com/TeaSpeak/TeaSpeak/files/1925365/crash_dump_e0c21efd-b885-4ae4-895a1ea7-3011bd92.dmp.gz)

**Comment by WolverinDEV** [comment]
:( xD I still don't had the time to resolve it :/)

**Comment by WolverinDEV** [comment]
Found the issue :)
Resolved and fixed now :)
