### ISSUE TITLE
clientEnterview

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#92]
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64):
***TeaSpeak Version***: 1.1.17

## Issue
***Reason for reporting this issue***:
i think there is a problem with an event.

***Detailed Description***:
I will try to explain . 

If you connect a bot using ts3 php framework. There is 2 cases : 

Player already connected when the bot start
If one of thoses player switch channel there is a ClientEnterView calling . It should not have since the player is already connected on the teaspeak and it's not a new player connection . teamspeak work like this it seems or the ts3phpframework is doing a cache somewhere and working for teamspeak3 it seems . . I don't know if the issue is from ts3 php framework or no  about caching the currents player ? or from teaspeak .

in fact a clientEnterview is called if a player is already connected but doing an event like switching channel.

Player who come after the bot started : 
In this case everything is correct a new player join the teaspeak server and then the clientEnterView is called . 

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by lemignon** [comment]
yes

**Comment by lemignon** [comment]
sorry my bad . it's ok .

**Comment by lemignon** [comment]
i tryed to explain the problem , maybe it's not a problem from teaspeak but i don't know

**Comment by Bluscream** [comment]
I can't test it so we wait for @WolverinDEV to confirm/void it

**Comment by WolverinDEV** [comment]
Well the system behind is easy.
All `notify` events are just state changing events.
If you don't register, that you want to be notified, you don't get these events.
If youre already on a server, you wont get a all events that you have already passed while you're not subscribed to them, like join events and all others.
When you start subscribing the server thinks that you already know these persons (cause the query subscribes all channels by default)

**Comment by lemignon** [comment]
i confirm that there seems to be a bug . 

Once the query enable notify he should only receive new clientEnterview on player joining server anywhere ( channel id dn't care ) but the connected player should not triger CliententerView if they switch channel ( they are not new player ) .

**Comment by WolverinDEV** [comment]
Yes you're right and I thought it would be so?
You only get an enter view when somebody joined from the invisible to the visible.
I'll look at this this evening, but if somebody would help me he can may post the terminal output for TeamSpeak in comprehension with TeaSpeak

**Comment by WolverinDEV** [comment]
Well are you sure, that you subscribed to all channels?
`channesubscribeall`. If not of cause you'll get enter view on every client move you see :)

**Comment by lemignon** [comment]
yes everything seems fine on my side . 

To reproduce 

connect 1 or more clients to your server ( very important ) , then go in telnet : 

login serveradmin xxxxx
use 1
channelsubscribeall
servernotifyregister event=server

then connect a new client ( you will have the cliententerview ) = NORMAL , 

then switch an actual previously connected client ( you will also have the cliententerview ??? ) only 1 time of course . after if you switch the same client you will not have the cliententerview  = not ok . 

so how damn a previously connected client can trigger this event even if it's only called 1 time , it should simply never be called 1 time for previously connected client ... ?

**Comment by lemignon** [comment]
so let's imagine , you made a welcome bot , and start your bot when 50 clients already online 

thoses 50 clients will trigger an event 1 time only ofc , but 1 time . so if one of thoses client switch channel they will got the welcome message . but they were already connected so they are not supposed to get a welcome message ...

**Comment by WolverinDEV** [comment]
Okey I'll test and fix it :)

**Comment by WolverinDEV** [comment]
fixed :)

**Comment by lemignon** [comment]
yes it's now working like it should be . ty
