### ISSUE TITLE
b_serverinstance_permission_list

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#93]
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.17

## Issue
***Reason for reporting this issue***:
permissionlist is not working or not working properly

***Detailed Description***:

in my bot : 
2018-04-16 22:59:47	PERMISSION_CACHE	Warning: Unable to receive permission list! If wanted, set permission b_serverinstance_permission_list.
2018-04-16 22:59:47	PERMISSION_CACHE	ServerQuery Error 1024 @ getList(): invalid serverID - invalid bounded server

Related to permissionlist ( in Query ) .

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Resolved the issue.
Was the missing permission for that (also destroyed the ts client)

**Comment by Bluscream** [comment]
What do you mean by "destroyed"?

**Comment by WolverinDEV** [comment]
Just download 1.1.17-beta 3 and try to do anithink what has some think to do with permissions
