### ISSUE TITLE
clientinfo clid=

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#94]
## System Information
***Operating System***: Debian 
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.17

## Issue
***Reason for reporting this issue***:
clientinfo clid= seems to be incomplete .

***Detailed Description***:

clientinfo clid= 
seems to miss client_platform and client_version

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by lemignon** [comment]
teaspeak : 

client_channel_group_id 14
client_output_muted 0
client_nickname xxx
client_teaforum_id 0
client_is_channel_commander 0
client_type 0
client_unique_identifier xxx
client_flag_avatar
client_description I don't have a description
client_database_id 4
client_output_hardware 1
client_nickname_phonetic
client_talk_request 0
client_outputonly_muted 0
client_icon_id 0
client_badges overwolf=0
client_totalconnections 22
client_is_talker 0
client_talk_request_msg
client_meta_data
clid 2
client_talk_power 25
client_input_muted 0
client_is_recording 0
client_is_priority_speaker 0
client_channel_group_inherited_channel_id 0
client_input_hardware 1
client_teaforum_name
client_country FR
client_away_message
client_servergroups 2,49,51,53
client_unread_messages 0
client_needed_serverquery_view_power 0
client_away 0

teamspeak : 

client_channel_group_id 12
client_security_hash
client_nickname xxx
client_platform Windows
client_type 0
client_output_hardware 1
client_nickname_phonetic
connection_filetransfer_bandwidth_received 0
connection_bytes_received_total 966
client_badges overwolf=0
client_login_name
client_totalconnections 1744
client_talk_request_msg
client_meta_data
client_idle_time 45
connection_packets_received_total 10
connection_connected_time 203
client_month_bytes_uploaded 0
connection_client_ip xxx
client_input_muted 0
client_is_recording 0
connection_bytes_sent_total 5233
client_input_hardware 0
client_servergroups 2,380,511,516
client_default_token
client_needed_serverquery_view_power 100
cid 15992
client_base64HashClientUID xxx
client_output_muted 1
client_is_channel_commander 0
client_version_sign xxx
client_unique_identifier xxx
client_flag_avatar
client_total_bytes_downloaded 944860791
client_description
client_database_id 64488
client_talk_request 0
client_outputonly_muted 0
client_version 3.1.8 [Build: 1516614607]
client_icon_id 0
connection_packets_sent_total 19
client_is_talker 0
connection_bandwidth_sent_last_minute_total 0
client_created 1452696228
client_default_channel /15992
client_talk_power 99999
connection_filetransfer_bandwidth_sent 0
client_total_bytes_uploaded 581534205
client_is_priority_speaker 0
client_lastconnected 1523914020
client_channel_group_inherited_channel_id 15992
connection_bandwidth_received_last_minute_total 0
client_country FR
client_away_message
connection_bandwidth_sent_last_second_total 0
connection_bandwidth_received_last_second_total 0
client_away 0
client_month_bytes_downloaded 15082

**Comment by lemignon** [comment]
client_platform and client_version was usefull in clientinfo clid= because  it's basic informations.

**Comment by WolverinDEV** [comment]
Fixed in TeaSpeak-1.1.17-beta.tar.gz

**Comment by lemignon** [comment]
i missed very important value : connection_client_ip
