### ISSUE TITLE
send own commands

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#95]
It would be nice to have a test version that is shown as such (no ability to change the version/platform in the config and a hardcoded hostmessage like `this is a test server. interesting stuff can happen here`) which allows sending own commands to individual/all clients from the console like `raw <clid> notifyclientupdated clid=21 client_nickname=i\sdidnt\srename\smyself` xD

**Comment by WolverinDEV** [comment]
Enchantment denied
Reason: It's to risky due the mass of "bad" attack possibilities like crash a client
