### ISSUE TITLE
Cant resolve target channel high channels ID

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#96]
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.17

## Issue
***Reason for reporting this issue***:
Can't join channel 
error : Cant resolve target channel

***Detailed Description***:

I can't join some channel after i restore my teamspeak. All channels ID > 65535 or high ID don't know the exact limit ...

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Fixed in TeaSpeak-1.1.17-beta.tar.gz
