### ISSUE TITLE
block empty/invalid clientupdate

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaSpeak#97]
Currently clientupdate is handled like this:
```
[OUT] clientupdate
[IN ] notifyclientupdated clid=5
```
TeaSpeak should not allow empty clientupdates to prevent anti-afk scripts like [this one](https://github.com/Bluscream/pyTSon_plugins/blob/master/scripts/antiAFK/__init__.py#L55) or some musicbots use.

To add an extra layer of "abuse prevention" the server could also check if the new (updated) variable is the same as it was before. Example:
```
[OUT] clientupdate client_input_muted=0
[IN ] notifyclientupdated clid=5 client_input_muted=0
[OUT] clientupdate client_input_muted=0
[IN ] notifyclientupdated clid=5 client_input_muted=0
[OUT] clientupdate client_input_muted=0
[IN ] notifyclientupdated clid=5 client_input_muted=0
[OUT] clientupdate client_input_muted=0
[IN ] notifyclientupdated clid=5 client_input_muted=0
```

**Comment by WolverinDEV** [comment]
Hmm good idea after first review, but need a more complex revision

**Comment by WolverinDEV** [comment]
Implemented within the new version
