### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by WolverinDEV** [TeaSpeak/TeaSpeak#98]
> Also i think the help stuff should be implemented i know it's not required but it helps new people getting into query and gives a quick syntax on how stuff can be used. it can work the same as in Teamspeak so just giving out the content of the serverquerydocs/ subdir. Example:
help = teaspeak/serverquerydocs/help.txt
help clientinfo = teaspeak/serverquerydocs/clientinfo.txt
we can copy their docs folder and just add the stuff we added to it.

[original post](https://github.com/TeaSpeak/TeaSpeak/issues/17#issuecomment-381928859)

**Comment by jamefane** [comment]
“we can copy their docs folder and just add the stuff we added to it.“ :D

**Comment by WolverinDEV** [comment]
Implemented in 1.1.27b

**Comment by Bluscream** [comment]
When will 1.1.27 be available?

**Comment by WolverinDEV** [comment]
This evening
