### ISSUE TITLE
missed propriety / values

### ISSUE THREAD

**Issue by lemignon** [TeaSpeak/TeaSpeak#99]
## System Information
***Operating System***: Debian
***Operating System Type*** (x86|x64): x64
***TeaSpeak Version***: 1.1.17-beta-1

## Issue
***Reason for reporting this issue***:

clientinfo need also connection_client_ip
channellist miss channel_icon_id

***Detailed Description***:

clientinfo need also connection_client_ip
channellist miss channel_icon_id

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
`channel_icon_id` requires the `-icon` parameter
The oder property is fixed within the next build
